(** Tiling.Bew - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.

From Tiling Require Import Syntax.
From Tiling Require Import Provable.
From Tiling Require Import Polymodal.


(*============================================================================*)
(*  Concretely-encoded provability predicate [Bew_n] over [T_n].              *)
(*                                                                            *)
(*  A concrete recursive axiomatisation [T_n] given by an axiom-set predicate *)
(*  [T_axiom n], a derivability predicate [Bew n] inductively closed under    *)
(*  axioms, MP, and Necessitation at any level [k < n].  The                  *)
(*  Hilbert-Bernays-Loeb conditions (K-axiom, Loeb-axiom, Nec rule, Box4)     *)
(*  hold as theorems of [Bew n] without being postulated on the calculus      *)
(*  side.  [Bew_to_Provable] shows every Bew-derivation is a Provable         *)
(*  derivation; [Bew_cumulative] shows the tower                              *)
(*  [T_0 ⊆ T_1 ⊆ T_2 ⊆ ...] is a true cumulative chain.                       *)
(*                                                                            *)
(*  This is the structural [Bew], not the arithmetic Sigma_1 [Bew]            *)
(*  predicate inside PA — the latter would require Goedel encoding of         *)
(*  formulas and proofs as natural numbers, which the present [Form]          *)
(*  language does not carry.                                                  *)
(*============================================================================*)

Inductive T_axiom (n : nat) : Form -> Prop :=
  | TAx_K : forall phi psi,
      T_axiom n (Impl phi (Impl psi phi))
  | TAx_S : forall phi psi chi,
      T_axiom n (Impl (Impl phi (Impl psi chi))
                      (Impl (Impl phi psi) (Impl phi chi)))
  | TAx_DN : forall phi,
      T_axiom n (Impl (Neg (Neg phi)) phi)
  | TAx_BoxK : forall k phi psi, k < n ->
      T_axiom n (Impl (Box k (Impl phi psi)) (Impl (Box k phi) (Box k psi)))
  | TAx_Loeb : forall k phi, k < n ->
      T_axiom n (Impl (Box k (Impl (Box k phi) phi)) (Box k phi))
  | TAx_Box4 : forall k phi, k < n ->
      T_axiom n (Impl (Box k phi) (Box k (Box k phi)))
  | TAx_Mon : forall k phi, S k < n ->
      T_axiom n (Impl (Box k phi) (Box (S k) phi))
  | TAx_NextCon : forall k, S k < n ->
      T_axiom n (Box (S k) (Neg (Box k Bot))).


Inductive Bew (n : nat) : Form -> Prop :=
  | Bew_ax  : forall phi, T_axiom n phi -> Bew n phi
  | Bew_MP  : forall phi psi, Bew n (Impl phi psi) -> Bew n phi -> Bew n psi
  | Bew_Nec : forall k phi, k < n -> Bew n phi -> Bew n (Box k phi).


(** *** HBL Condition K (axiom): K-axiom for Bew at every level k < n. *)
Theorem Bew_HBL_K : forall n k phi psi, k < n ->
  Bew n (Impl (Box k (Impl phi psi)) (Impl (Box k phi) (Box k psi))).
Proof. intros n k phi psi Hk. apply Bew_ax. apply TAx_BoxK; assumption. Qed.


(** *** HBL Condition Loeb (axiom): internal Loeb at every level k < n. *)
Theorem Bew_HBL_Loeb : forall n k phi, k < n ->
  Bew n (Impl (Box k (Impl (Box k phi) phi)) (Box k phi)).
Proof. intros n k phi Hk. apply Bew_ax. apply TAx_Loeb; assumption. Qed.


(** *** HBL Condition Box4 (axiom): internal Box4 at every level k < n. *)
Theorem Bew_HBL_Box4 : forall n k phi, k < n ->
  Bew n (Impl (Box k phi) (Box k (Box k phi))).
Proof. intros n k phi Hk. apply Bew_ax. apply TAx_Box4; assumption. Qed.


(** *** HBL Condition Necessitation (rule). *)
Theorem Bew_HBL_Nec : forall n k phi, k < n ->
  Bew n phi -> Bew n (Box k phi).
Proof. intros n k phi Hk H. exact (Bew_Nec n k phi Hk H). Qed.


(** *** HBL Condition MP (rule). *)
Theorem Bew_HBL_MP : forall n phi psi,
  Bew n (Impl phi psi) -> Bew n phi -> Bew n psi.
Proof. exact Bew_MP. Qed.


(** *** Cumulativity of the tower: T_n axioms are T_(n+1) axioms. *)
Theorem T_axiom_cumulative : forall n phi,
  T_axiom n phi -> T_axiom (S n) phi.
Proof.
  intros n phi H. induction H.
  - apply TAx_K.
  - apply TAx_S.
  - apply TAx_DN.
  - apply TAx_BoxK; lia.
  - apply TAx_Loeb; lia.
  - apply TAx_Box4; lia.
  - apply TAx_Mon; lia.
  - apply TAx_NextCon; lia.
Qed.


Theorem Bew_cumulative : forall n phi,
  Bew n phi -> Bew (S n) phi.
Proof.
  intros n phi H. induction H as [phi Hax | phi psi _ IH1 _ IH2 | k phi Hk _ IH].
  - apply Bew_ax. exact (T_axiom_cumulative n phi Hax).
  - exact (Bew_MP _ _ _ IH1 IH2).
  - apply Bew_Nec; [lia|exact IH].
Qed.


(** *** Connection lemma: every Bew-derivation lifts to a Provable derivation. *)
Theorem Bew_to_Provable : forall n phi, Bew n phi -> |- phi.
Proof.
  intros n phi H. induction H as [phi Hax | phi psi _ IH1 _ IH2 | k phi Hk _ IH].
  - induction Hax.
    + apply Ax_K.
    + apply Ax_S.
    + apply Ax_DN.
    + apply Ax_BoxK.
    + apply Ax_Loeb.
    + apply Ax_Box4.
    + apply Ax_Mon.
    + apply Ax_NextCon.
  - exact (MP _ _ IH1 IH2).
  - exact (Nec _ _ IH).
Qed.


(** *** The HBL package as a single theorem. *)
Theorem Bew_HBL_conditions : forall n,
  (forall k phi psi, k < n ->
    Bew n (Impl (Box k (Impl phi psi)) (Impl (Box k phi) (Box k psi)))) /\
  (forall k phi, k < n ->
    Bew n (Impl (Box k (Impl (Box k phi) phi)) (Box k phi))) /\
  (forall k phi, k < n ->
    Bew n (Impl (Box k phi) (Box k (Box k phi)))) /\
  (forall k phi, k < n ->
    Bew n phi -> Bew n (Box k phi)) /\
  (forall phi psi, Bew n (Impl phi psi) -> Bew n phi -> Bew n psi).
Proof.
  intro n. split; [|split; [|split; [|split]]].
  - intros k phi psi Hk. exact (Bew_HBL_K n k phi psi Hk).
  - intros k phi Hk. exact (Bew_HBL_Loeb n k phi Hk).
  - intros k phi Hk. exact (Bew_HBL_Box4 n k phi Hk).
  - intros k phi Hk. exact (Bew_HBL_Nec n k phi Hk).
  - intros phi psi. exact (Bew_HBL_MP n phi psi).
Qed.


(** *** Bew_n is consistent for every n (via Bew_to_Provable + meta_consistency). *)
Theorem Bew_consistent : forall n, ~ Bew n Bot.
Proof. intros n H. exact (meta_consistency_system (Bew_to_Provable n Bot H)). Qed.


(** *** Loeb metatheorem internal to Bew_n. *)
Theorem Bew_loeb_metatheorem : forall n k phi, k < n ->
  Bew n (Impl (Box k phi) phi) -> Bew n phi.
Proof.
  intros n k phi Hk Hsound.
  pose proof (Bew_HBL_Nec n k _ Hk Hsound) as Hnec.
  pose proof (Bew_HBL_Loeb n k phi Hk) as HLoeb.
  pose proof (Bew_MP _ _ _ HLoeb Hnec) as Hbox.
  exact (Bew_MP _ _ _ Hsound Hbox).
Qed.


(** *** Loebian obstacle internal to Bew_n: a level-k uniform soundness
    schema is impossible inside T_n. *)
Theorem Bew_loebian_obstacle : forall n k, k < n ->
  (forall phi, Bew n (Impl (Box k phi) phi)) -> Bew n Bot.
Proof.
  intros n k Hk Hall.
  exact (Bew_loeb_metatheorem n k Bot Hk (Hall Bot)).
Qed.


(*============================================================================*)
(*  Explicit first-order tower [T_0] ⊆ [T_1] ⊆ [T_2] ⊆ ...                    *)
(*                                                                            *)
(*  [T_n] is the theory whose axioms are [T_axiom n].  Cumulativity is        *)
(*  [Bew_cumulative].  The tower is strictly ordered (each step adds new      *)
(*  axioms when [n] grows), and the consistency-of-the-predecessor formula    *)
(*  [Con(T_n) := Neg (Box n Bot)] is internally affirmed by [T_{n+2}]         *)
(*  (the witness is the [Box (S n)]-prefixed [NextCon] axiom; [T_n] cannot    *)
(*  itself prove [Con(T_n)] by Loeb).  The recovered version of [Ax_NextCon]  *)
(*  is [Bew_recovers_NextCon].                                                *)
(*                                                                            *)
(*  This is the structural, modal-level tower; a full arithmetic encoding     *)
(*  (formulas/proofs as numerals, Sigma_1 [Bew] predicate as a PA-formula)    *)
(*  would require a separate Goedel-encoding layer over PA.                   *)
(*============================================================================*)

Definition Con (n : nat) : Form := Neg (Box n Bot).


(** Inside our calculus, Con(T_n) at level (S n) is provable via NextCon. *)
Theorem T_Con_box_at_next_level : forall n,
  |- Box (S n) (Con n).
Proof. intro n. unfold Con. exact (Ax_NextCon n). Qed.


(** Inside Bew (S (S n)), the witness Box (S n) (Con n) is an axiom.  This is
    the modal counterpart of "T_{n+2} contains Con(T_n) as an internalised
    fact"; the strictly-arithmetic statement T_{n+1} ⊢ Con(T_n) corresponds
    to having Neg (Box n Bot) at the level-(n+1) extension, which would
    make our Bew (S n) inconsistent (Loeb at level n inside Bew (S n)
    derives Bot from |- Con n). *)

Theorem Bew_recovers_NextCon : forall n,
  S (S n) <= S (S n) -> Bew (S (S n)) (Box (S n) (Con n)).
Proof.
  intros n _. unfold Con. apply Bew_ax. apply TAx_NextCon. lia.
Qed.


(** Strict inclusion: T_(n+2) has a strictly-bigger axiom set than T_n. *)
Theorem T_axiom_strict_inclusion : forall n,
  exists phi, T_axiom (S (S n)) phi /\ ~ T_axiom n phi.
Proof.
  intro n. exists (Box (S n) (Neg (Box n Bot))).
  split.
  - apply TAx_NextCon. lia.
  - intro H. inversion H; subst.
    + lia.
Qed.


Lemma T_axiom_outer_bound : forall n phi,
  T_axiom n phi -> outer_box_level phi <= n.
Proof.
  intros n phi H. induction H; simpl; try lia.
Qed.


(** *** Cumulativity at every step. *)
Theorem T_axiom_cumulative_iter : forall n m phi,
  n <= m -> T_axiom n phi -> T_axiom m phi.
Proof.
  intros n m phi Hle H.
  induction Hle.
  - exact H.
  - exact (T_axiom_cumulative _ _ IHHle).
Qed.


Theorem Bew_cumulative_iter : forall n m phi,
  n <= m -> Bew n phi -> Bew m phi.
Proof.
  intros n m phi Hle H.
  induction Hle.
  - exact H.
  - exact (Bew_cumulative _ _ IHHle).
Qed.


(** *** The tower has a non-trivial extension at every level. *)
Theorem T_tower_nontrivial_extension : forall n,
  exists phi, T_axiom (S (S n)) phi /\ ~ T_axiom n phi.
Proof.
  intro n. exists (Box (S n) (Neg (Box n Bot))).
  split.
  - apply TAx_NextCon. lia.
  - intro H. inversion H; subst.
    + lia.
Qed.


(*============================================================================*)
(*  Relative consistency: [Con(T_0)] → [Con(T_n)].                            *)
(*                                                                            *)
(*  Meta-level statement: if [T_0] is consistent ([~ |- Bot]), then [T_n]     *)
(*  is consistent at every level [n].  Proof via [Bew_to_Provable]: any       *)
(*  [T_n]-derivation of [Bot] lifts to a Provable derivation of [Bot],        *)
(*  which contradicts [meta_consistency_system].  Since the calculus has      *)
(*  [meta_consistency_system] unconditionally, the antecedent [Con(T_0)]      *)
(*  is automatically discharged.                                              *)
(*============================================================================*)

Definition T_consistent (n : nat) : Prop := ~ Bew n Bot.


Theorem T0_consistent : T_consistent 0.
Proof.
  unfold T_consistent. intro H.
  exact (meta_consistency_system (Bew_to_Provable 0 Bot H)).
Qed.


Theorem T_relative_consistency : forall n,
  T_consistent 0 -> T_consistent 0 /\ T_consistent n.
Proof.
  intros n Hcon0. split.
  - exact Hcon0.
  - unfold T_consistent. intro H.
    exact (meta_consistency_system (Bew_to_Provable n Bot H)).
Qed.


Theorem T_consistency_chain : forall n, T_consistent n.
Proof.
  intro n.
  exact (proj2 (T_relative_consistency n T0_consistent)).
Qed.


(** *** The Con-witness at level (S n) is genuinely informative: T_(S (S n))
    proves the modal consistency-statement [Box (S n) (Con n)] internally. *)
Theorem T_internal_witness_of_predecessor_consistency : forall n,
  Bew (S (S n)) (Box (S n) (Con n)).
Proof.
  intro n. unfold Con. apply Bew_ax. apply TAx_NextCon. lia.
Qed.


(** *** No theory in the tower proves its OWN consistency (Goedel II). *)
Theorem T_no_self_consistency : forall n, ~ Bew n (Con n).
Proof.
  intros n H.
  unfold Con in H.
  pose proof (Bew_to_Provable n _ H) as Hprov.
  pose proof (Nec n _ Hprov) as Hnec.
  pose proof (Ax_Loeb n Bot) as HLoeb.
  pose proof (MP _ _ HLoeb Hnec) as Hbox.
  pose proof (MP _ _ Hprov Hbox) as Hbot.
  exact (meta_consistency_system Hbot).
Qed.


Inductive arith_provable : arith_form -> Prop :=
  | AP_K : forall a b, arith_provable (A_impl a (A_impl b a))
  | AP_S : forall a b c, arith_provable (A_impl (A_impl a (A_impl b c))
                                                (A_impl (A_impl a b) (A_impl a c)))
  | AP_DN : forall a, arith_provable (A_impl (A_neg (A_neg a)) a)
  | AP_BoxK : forall n a b,
      arith_provable (A_impl (A_Bew_n n (A_impl a b))
                             (A_impl (A_Bew_n n a) (A_Bew_n n b)))
  | AP_Loeb : forall n a,
      arith_provable (A_impl (A_Bew_n n (A_impl (A_Bew_n n a) a)) (A_Bew_n n a))
  | AP_Box4 : forall n a,
      arith_provable (A_impl (A_Bew_n n a) (A_Bew_n n (A_Bew_n n a)))
  | AP_Mon : forall n a, arith_provable (A_impl (A_Bew_n n a) (A_Bew_n (S n) a))
  | AP_NextCon : forall n,
      arith_provable (A_Bew_n (S n) (A_neg (A_Bew_n n A_falsity)))
  | AP_MP : forall a b, arith_provable (A_impl a b) -> arith_provable a -> arith_provable b
  | AP_Nec : forall n a, arith_provable a -> arith_provable (A_Bew_n n a).


Theorem modal_to_arith_preserves_provability : forall phi,
  |- phi -> arith_provable (modal_to_arith phi).
Proof.
  intros phi H. induction H; simpl.
  - apply AP_K.
  - apply AP_S.
  - apply AP_DN.
  - apply AP_BoxK.
  - apply AP_Loeb.
  - apply AP_Box4.
  - apply AP_Mon.
  - apply AP_NextCon.
  - apply AP_MP with (a := modal_to_arith phi); assumption.
  - apply AP_Nec. assumption.
Qed.



Theorem arith_provable_HBL_K : forall n a b,
  arith_provable (A_impl (A_Bew_n n (A_impl a b))
                         (A_impl (A_Bew_n n a) (A_Bew_n n b))).
Proof. exact AP_BoxK. Qed.


Theorem arith_provable_HBL_Loeb : forall n a,
  arith_provable (A_impl (A_Bew_n n (A_impl (A_Bew_n n a) a)) (A_Bew_n n a)).
Proof. exact AP_Loeb. Qed.


Theorem arith_provable_HBL_Nec : forall n a,
  arith_provable a -> arith_provable (A_Bew_n n a).
Proof. exact AP_Nec. Qed.


Theorem arith_interpretation_T_kappa_reflects_modal : forall n phi,
  |- T_kappa n phi -> arith_provable (A_Bew_n n (modal_to_arith phi)).
Proof.
  intros n phi H. unfold T_kappa in H.
  pose proof (modal_to_arith_preserves_provability _ H) as Hap.
  simpl in Hap. exact Hap.
Qed.


Theorem arith_interpretation_T_kappa_consistency : forall n,
  arith_provable (A_Bew_n (S n) (A_neg (A_Bew_n n A_falsity))).
Proof. intro n. exact (AP_NextCon n). Qed.

