(** Tiling.Encoding - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.

From Tiling Require Import Syntax.
From Tiling Require Import Provable.


Fixpoint to_triangle (n : nat) : nat :=
  match n with
  | O => 0
  | S k => S k + to_triangle k
  end.


Definition cpair (a b : nat) : nat := to_triangle (a + b) + b.


Fixpoint find_root (n bound : nat) : nat :=
  match bound with
  | O => 0
  | S b => let prev := find_root n b in
           if Nat.leb (to_triangle (S prev)) n then S prev else prev
  end.


Definition cunpair (n : nat) : nat * nat :=
  let k := find_root n n in
  let b := n - to_triangle k in
  (k - b, b).


Lemma to_triangle_mono : forall a b, a <= b -> to_triangle a <= to_triangle b.
Proof.
  intros a b. induction 1; simpl; lia.
Qed.


Lemma find_root_le : forall n b, find_root n b <= b.
Proof.
  intros n b. induction b as [|b' IH].
  - apply Nat.le_refl.
  - cbn [find_root].
    destruct (Nat.leb (to_triangle (S (find_root n b'))) n).
    + apply le_n_S. exact IH.
    + apply Nat.le_le_succ_r. exact IH.
Qed.


Lemma find_root_correct : forall n b,
  to_triangle (find_root n b) <= n.
Proof.
  intros n b. induction b as [|b' IH].
  - apply Nat.le_0_l.
  - cbn [find_root].
    destruct (Nat.leb (to_triangle (S (find_root n b'))) n) eqn:Heq.
    + apply Nat.leb_le in Heq. exact Heq.
    + exact IH.
Qed.


Lemma to_triangle_strict_mono : forall a b, a < b -> to_triangle a < to_triangle b.
Proof.
  intros a b H. induction H.
  - cbn. lia.
  - cbn. lia.
Qed.


Lemma to_triangle_pos_for_pos : forall n, 0 < n -> 0 < to_triangle n.
Proof.
  intros n H. destruct n; [lia|]. cbn. lia.
Qed.


Lemma find_root_max : forall n bound k,
  to_triangle k <= n ->
  k <= bound ->
  k <= find_root n bound.
Proof.
  intros n bound. induction bound as [|b IH]; intros k Hle Hkb.
  - assert (k = 0) by lia. subst k. cbn. lia.
  - cbn [find_root].
    destruct (Nat.leb (to_triangle (S (find_root n b))) n) eqn:Hcase.
    + (* find_root n (S b) = S (find_root n b) *)
      destruct (Nat.eq_dec k (S b)) as [Heq|Hne].
      * subst k. apply le_n_S.
        apply IH; [|lia].
        apply Nat.leb_le in Hcase.
        assert (Hmono : to_triangle b < to_triangle (S b)).
        { apply to_triangle_strict_mono. lia. }
        lia.
      * assert (k <= b) by lia.
        assert (k <= find_root n b) by exact (IH k Hle H).
        lia.
    + (* find_root n (S b) = find_root n b *)
      destruct (Nat.eq_dec k (S b)) as [Heq|Hne].
      * subst k. apply Nat.leb_nle in Hcase.
        exfalso. apply Hcase.
        assert (Hmono : to_triangle (S (find_root n b)) <= to_triangle (S b)).
        { apply to_triangle_mono. pose proof (find_root_le n b). lia. }
        lia.
      * assert (k <= b) by lia.
        exact (IH k Hle H).
Qed.


Lemma find_root_eq_when_bounds : forall n a,
  to_triangle a <= n ->
  to_triangle (S a) > n ->
  a <= n ->
  find_root n n = a.
Proof.
  intros n a Hle Hgt Han.
  pose proof (find_root_correct n n) as Hroot_le.
  pose proof (find_root_max n n a Hle Han) as Hmax.
  destruct (le_lt_dec (find_root n n) a) as [HleR|HltR].
  - lia.
  - exfalso.
    assert (to_triangle (S a) <= to_triangle (find_root n n)).
    { apply to_triangle_mono. lia. }
    lia.
Qed.


Lemma cpair_bound : forall a b, a + b <= cpair a b.
Proof.
  intros a b. unfold cpair.
  assert (a + b <= to_triangle (a + b)).
  { destruct (a + b) as [|m] eqn:E.
    - lia.
    - cbn. lia. }
  lia.
Qed.


Theorem cunpair_cpair : forall a b, cunpair (cpair a b) = (a, b).
Proof.
  intros a b. unfold cunpair.
  set (n := cpair a b).
  assert (Hroot : find_root n n = a + b).
  { apply find_root_eq_when_bounds.
    - unfold n, cpair. lia.
    - unfold n, cpair. cbn. lia.
    - apply cpair_bound. }
  rewrite Hroot.
  unfold n, cpair.
  replace (to_triangle (a + b) + b - to_triangle (a + b)) with b by lia.
  replace (a + b - b) with a by lia.
  reflexivity.
Qed.


Lemma triangle_bounded_below : forall k, k <= to_triangle k.
Proof. induction k; cbn; lia. Qed.


Lemma find_root_succ_exceeds : forall n,
  to_triangle (S (find_root n n)) > n.
Proof.
  intro n.
  destruct (le_lt_dec (to_triangle (S (find_root n n))) n) as [Hle | Hgt]; [|exact Hgt].
  exfalso.
  pose proof (triangle_bounded_below (S (find_root n n))) as Hbound.
  assert (HSk_le_n : S (find_root n n) <= n) by lia.
  pose proof (find_root_max n n (S (find_root n n)) Hle HSk_le_n) as Hmax.
  lia.
Qed.


Theorem cpair_cunpair : forall n,
  cpair (fst (cunpair n)) (snd (cunpair n)) = n.
Proof.
  intro n. unfold cunpair, cpair. cbn.
  set (k := find_root n n).
  set (b := n - to_triangle k).
  pose proof (find_root_correct n n) as Hcor.
  pose proof (find_root_succ_exceeds n) as Hexc.
  fold k in Hcor, Hexc.
  assert (Hbk : b <= k).
  { unfold b. cbn in Hexc. lia. }
  replace (k - b + b) with k by lia.
  unfold b. lia.
Qed.


(** [find_root n n] is the genuine root of the triangle inequality:
    the unique [k] satisfying [to_triangle k <= n < to_triangle (S k)]. *)

Theorem find_root_genuine_root : forall n,
  to_triangle (find_root n n) <= n /\
  to_triangle (S (find_root n n)) > n.
Proof.
  intro n. split.
  - exact (find_root_correct n n).
  - exact (find_root_succ_exceeds n).
Qed.


Theorem find_root_unique : forall n k,
  to_triangle k <= n ->
  to_triangle (S k) > n ->
  k = find_root n n.
Proof.
  intros n k Hle Hgt.
  pose proof (find_root_correct n n) as Hr_le.
  pose proof (find_root_succ_exceeds n) as Hr_gt.
  pose proof (triangle_bounded_below k) as Hk_n.
  assert (Hk_le_n : k <= n) by lia.
  pose proof (find_root_max n n k Hle Hk_le_n) as Hk_le_root.
  destruct (Nat.lt_total k (find_root n n)) as [Hlt | [Heq | Hgt']].
  - exfalso.
    assert (Hmono : to_triangle (S k) <= to_triangle (find_root n n)).
    { apply to_triangle_mono. lia. }
    lia.
  - exact Heq.
  - lia.
Qed.


Fixpoint encode_form (phi : Form) : nat :=
  match phi with
  | Bot => 0
  | Var p => 1 + cpair 0 p
  | Impl X Y => 1 + cpair 1 (cpair (encode_form X) (encode_form Y))
  | Box k psi => 1 + cpair 2 (cpair k (encode_form psi))
  end.


Fixpoint decode_form_bounded (depth n : nat) : Form :=
  match depth with
  | O => Bot
  | S d =>
    match n with
    | O => Bot
    | S n' =>
      let p := cunpair n' in
      let tag := fst p in
      let payload := snd p in
      match tag with
      | 0 => Var payload
      | 1 =>
        let q := cunpair payload in
        Impl (decode_form_bounded d (fst q)) (decode_form_bounded d (snd q))
      | 2 =>
        let q := cunpair payload in
        Box (fst q) (decode_form_bounded d (snd q))
      | _ => Bot
      end
    end
  end.


Definition decode_form (n : nat) : Form := decode_form_bounded (S n) n.


Lemma encode_Impl_bound_left : forall X Y,
  encode_form X < encode_form (Impl X Y).
Proof.
  intros X Y. cbn. unfold cpair.
  pose proof (triangle_bounded_below (encode_form X + encode_form Y)) as H1.
  pose proof (triangle_bounded_below
    (1 + (to_triangle (encode_form X + encode_form Y) + encode_form Y))) as H2.
  lia.
Qed.


Lemma encode_Impl_bound_right : forall X Y,
  encode_form Y < encode_form (Impl X Y).
Proof.
  intros X Y. cbn. unfold cpair.
  pose proof (triangle_bounded_below (encode_form X + encode_form Y)) as H1.
  pose proof (triangle_bounded_below
    (1 + (to_triangle (encode_form X + encode_form Y) + encode_form Y))) as H2.
  lia.
Qed.


Lemma encode_Box_bound : forall k psi,
  encode_form psi < encode_form (Box k psi).
Proof.
  intros k psi. cbn. unfold cpair.
  pose proof (triangle_bounded_below (k + encode_form psi)) as H1.
  pose proof (triangle_bounded_below
    (1 + (to_triangle (k + encode_form psi) + encode_form psi))) as H2.
  lia.
Qed.


Lemma decode_step_var : forall p d',
  decode_form_bounded (S d') (S (cpair 0 p)) = Var p.
Proof.
  intros p d'.
  cbn [decode_form_bounded].
  rewrite cunpair_cpair. cbn [fst snd]. reflexivity.
Qed.


Lemma decode_step_impl : forall a b d',
  decode_form_bounded (S d') (S (cpair 1 (cpair a b))) =
    Impl (decode_form_bounded d' a) (decode_form_bounded d' b).
Proof.
  intros a b d'.
  cbn [decode_form_bounded].
  rewrite cunpair_cpair. cbn [fst snd].
  rewrite cunpair_cpair. cbn [fst snd].
  reflexivity.
Qed.


Lemma decode_step_box : forall k a d',
  decode_form_bounded (S d') (S (cpair 2 (cpair k a))) =
    Box k (decode_form_bounded d' a).
Proof.
  intros k a d'.
  cbn [decode_form_bounded].
  rewrite cunpair_cpair. cbn [fst snd].
  rewrite cunpair_cpair. cbn [fst snd].
  reflexivity.
Qed.


Lemma decode_encode_with_depth : forall phi d,
  encode_form phi < d ->
  decode_form_bounded d (encode_form phi) = phi.
Proof.
  induction phi as [p | | X IHX Y IHY | k psi IHpsi]; intros d Hd.
  - destruct d as [|d']; [lia|].
    change (encode_form (Var p)) with (S (cpair 0 p)).
    apply decode_step_var.
  - destruct d as [|d']; [lia|]. cbn. reflexivity.
  - destruct d as [|d']; [lia|].
    change (encode_form (Impl X Y))
      with (S (cpair 1 (cpair (encode_form X) (encode_form Y)))).
    rewrite decode_step_impl.
    pose proof (encode_Impl_bound_left X Y) as HX.
    pose proof (encode_Impl_bound_right X Y) as HY.
    rewrite IHX by lia.
    rewrite IHY by lia.
    reflexivity.
  - destruct d as [|d']; [lia|].
    change (encode_form (Box k psi))
      with (S (cpair 2 (cpair k (encode_form psi)))).
    rewrite decode_step_box.
    pose proof (encode_Box_bound k psi) as HB.
    rewrite IHpsi by lia.
    reflexivity.
Qed.


Theorem decode_encode : forall phi,
  decode_form (encode_form phi) = phi.
Proof.
  intro phi. unfold decode_form.
  apply decode_encode_with_depth. lia.
Qed.


Definition enum_form (n : nat) : Form := decode_form n.


Definition Form_seq : nat -> Form := enum_form.


Lemma Form_seq_encode : forall phi, Form_seq (encode_form phi) = phi.
Proof.
  intros phi. unfold Form_seq, enum_form. apply decode_encode.
Qed.

