(** Tiling.Interpolation - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.

From Tiling Require Import Syntax.
From Tiling Require Import Provable.
From Tiling Require Import Propositional.


(** [craig_interpolation_phi_subset] / [_psi_subset]: when one side's
    free variables are already contained in the other's, the obvious
    interpolant works.  Substantive only as degenerate corollaries of
    the genuine theorem [craig_interpolation_box_free]; kept here only
    in their containment-hypothesis form. *)

Theorem craig_interpolation_phi_subset : forall phi psi,
  (forall v, In v (free_vars phi) -> In v (free_vars psi)) ->
  |- Impl phi psi ->
  exists chi,
    |- Impl phi chi /\ |- Impl chi psi /\
    (forall v, In v (free_vars chi) ->
       In v (free_vars phi) /\ In v (free_vars psi)).
Proof.
  intros phi psi Hsub Himpl. exists phi.
  split; [|split].
  - exact (prov_id phi).
  - exact Himpl.
  - intros v Hv. split; [exact Hv | exact (Hsub v Hv)].
Qed.


Theorem craig_interpolation_psi_subset : forall phi psi,
  (forall v, In v (free_vars psi) -> In v (free_vars phi)) ->
  |- Impl phi psi ->
  exists chi,
    |- Impl phi chi /\ |- Impl chi psi /\
    (forall v, In v (free_vars chi) ->
       In v (free_vars phi) /\ In v (free_vars psi)).
Proof.
  intros phi psi Hsub Himpl. exists psi.
  split; [|split].
  - exact Himpl.
  - exact (prov_id psi).
  - intros v Hv. split; [exact (Hsub v Hv) | exact Hv].
Qed.


Theorem craig_interpolation_top_when_psi_provable : forall phi psi,
  |- psi ->
  exists chi,
    |- Impl phi chi /\ |- Impl chi psi /\
    free_vars chi = [].
Proof.
  intros phi psi Hpsi. exists Top.
  split; [|split].
  - exact (prov_weaken Top phi (prov_id Bot)).
  - exact (prov_weaken psi Top Hpsi).
  - reflexivity.
Qed.


Theorem craig_interpolation_bot_when_phi_unsat : forall phi psi,
  |- Impl phi Bot ->
  exists chi,
    |- Impl phi chi /\ |- Impl chi psi /\
    free_vars chi = [].
Proof.
  intros phi psi Hunsat. exists Bot.
  split; [|split].
  - exact Hunsat.
  - exact (prov_explosion psi).
  - reflexivity.
Qed.


(** [beth_definability_from_craig] (alias of [craig_interpolation_phi_subset])
    and [beth_implicit_to_explicit] (with witness [def := psi]) were trivial
    placeholders.  The substantive box-free Beth theorem is
    [beth_explicit_definability_box_free], proved alongside the genuine
    Craig theorem at the end of the file. *)

Theorem beth_uniqueness_via_craig : forall phi1 phi2 psi,
  (forall v, In v (free_vars phi1) -> In v (free_vars psi)) ->
  (forall v, In v (free_vars phi2) -> In v (free_vars psi)) ->
  |- Impl phi1 psi -> |- Impl psi phi1 ->
  |- Impl phi2 psi -> |- Impl psi phi2 ->
  |- Iff phi1 phi2.
Proof.
  intros phi1 phi2 psi _ _ Hf1 Hb1 Hf2 Hb2.
  apply prov_and_intro_meta.
  - exact (prov_compose _ _ _ Hf1 Hb2).
  - exact (prov_compose _ _ _ Hf2 Hb1).
Qed.


(** [lyndon_interpolation_via_craig_subset] (witness [chi = phi]) and
    [lyndon_polarity_preserved_when_identical_interpolant] (same witness)
    were trivial placeholders.  Lyndon interpolation requires polarity
    tracking that the proof-term reduction system has not yet been
    extended to support; see todo item 18. *)

Theorem uniform_interpolation_no_occurrence : forall phi p,
  ~ In p (free_vars phi) ->
  exists phi_p, ~ In p (free_vars phi_p) /\
    forall psi, ~ In p (free_vars psi) ->
      (|- Impl phi psi <-> |- Impl phi_p psi).
Proof.
  intros phi p Hp_notin. exists phi.
  split; [exact Hp_notin|].
  intros psi _. tauto.
Qed.


Theorem uniform_interpolation_top_for_unrefuteable : forall phi p,
  |- phi ->
  exists phi_p, ~ In p (free_vars phi_p) /\
    forall psi, ~ In p (free_vars psi) ->
      (|- Impl phi psi -> |- Impl phi_p psi).
Proof.
  intros phi p Hphi. exists Top.
  split.
  - intro H. simpl in H. unfold Top in H. simpl in H. exact H.
  - intros psi _ Himpl.
    pose proof (MP _ _ Himpl Hphi) as Hpsi.
    exact (prov_weaken psi Top Hpsi).
Qed.


Theorem craig_interpolation_when_psi_tautology : forall phi psi,
  box_free psi ->
  |- psi ->
  exists chi, free_vars chi = [] /\ box_free psi /\
              |- Impl phi chi /\ |- Impl chi psi.
Proof.
  intros phi psi Hbfpsi Hpsi_provable.
  exists Top. split; [reflexivity | split; [|split]].
  + exact Hbfpsi.
  + exact (prov_weaken _ phi (prov_id Bot)).
  + exact (prov_weaken _ Top Hpsi_provable).
Qed.


Theorem craig_interpolation_when_phi_unsat : forall phi psi,
  |- Impl phi Bot ->
  exists chi, free_vars chi = [] /\ |- Impl phi chi /\ |- Impl chi psi.
Proof.
  intros phi psi Hphi_unsat.
  exists Bot. split; [reflexivity | split].
  + exact Hphi_unsat.
  + exact (prov_explosion psi).
Qed.


Theorem craig_interpolation_via_shared_variable : forall p q r,
  p <> q -> q <> r -> p <> r ->
  |- Impl (And (Var p) (Var q)) (Or (Var q) (Var r)).
Proof.
  intros p q r _ _ _.
  pose proof (prov_and_elim_r (Var p) (Var q)) as Hand_r.
  pose proof (prov_or_intro_l (Var q) (Var r)) as Hor_l.
  exact (prov_compose _ _ _ Hand_r Hor_l).
Qed.


Theorem craig_interpolation_extracts_shared : forall p q r,
  p <> q -> q <> r -> p <> r ->
  exists chi, |- Impl (And (Var p) (Var q)) chi /\
              |- Impl chi (Or (Var q) (Var r)) /\
              free_vars chi = [q].
Proof.
  intros p q r Hpq Hqr Hpr.
  exists (Var q). split; [|split].
  - exact (prov_and_elim_r _ _).
  - exact (prov_or_intro_l _ _).
  - reflexivity.
Qed.


Theorem craig_interpolation_chi_strictly_smaller : forall p q r,
  p <> q -> q <> r -> p <> r ->
  exists chi, |- Impl (And (Var p) (Var q)) chi /\
              |- Impl chi (Or (Var q) (Var r)) /\
              (forall v, In v (free_vars chi) ->
                In v (free_vars (And (Var p) (Var q))) /\
                In v (free_vars (Or (Var q) (Var r)))).
Proof.
  intros p q r Hpq Hqr Hpr.
  exists (Var q). split; [|split].
  - exact (prov_and_elim_r _ _).
  - exact (prov_or_intro_l _ _).
  - intros v Hv. simpl in Hv. destruct Hv as [<-|[]].
    split.
    + simpl. unfold And. simpl. unfold Neg. simpl.
      right. left. reflexivity.
    + simpl. unfold Or. simpl. unfold Neg. simpl.
      left. reflexivity.
Qed.


Definition forget_var (p : nat) (phi : Form) : Form :=
  Or (Subst p Top phi) (Subst p Bot phi).


Lemma box_free_forget_var : forall p phi,
  box_free phi -> box_free (forget_var p phi).
Proof.
  intros p phi Hbf. unfold forget_var, Or, Neg.
  cbn. split.
  - split; [apply box_free_Subst; [exact Hbf|exact box_free_Top] | exact I].
  - apply box_free_Subst; [exact Hbf|exact box_free_Bot].
Qed.


Lemma eval_forget_var_intro : forall val p phi,
  box_free phi ->
  eval val phi = true ->
  eval val (forget_var p phi) = true.
Proof.
  intros val p phi Hbf Hev. unfold forget_var.
  rewrite eval_Or.
  rewrite (eval_Subst_box_free val p Top phi Hbf).
  rewrite (eval_Subst_box_free val p Bot phi Hbf).
  rewrite eval_Top_true, eval_Bot_false.
  destruct (val p) eqn:Vp.
  - assert (Hxt : eval (update_val val p true) phi = eval val phi).
    { apply eval_ext_on_free_vars. intros q _.
      unfold update_val. destruct (Nat.eqb q p) eqn:E.
      - apply Nat.eqb_eq in E. subst q. symmetry. exact Vp.
      - reflexivity. }
    rewrite Hxt, Hev. reflexivity.
  - assert (Hxf : eval (update_val val p false) phi = eval val phi).
    { apply eval_ext_on_free_vars. intros q _.
      unfold update_val. destruct (Nat.eqb q p) eqn:E.
      - apply Nat.eqb_eq in E. subst q. symmetry. exact Vp.
      - reflexivity. }
    rewrite Hxf, Hev.
    destruct (eval (update_val val p true) phi); reflexivity.
Qed.


Lemma eval_forget_var_elim : forall val p phi psi,
  box_free phi -> box_free psi ->
  ~ In p (free_vars psi) ->
  (forall val', eval val' (Impl phi psi) = true) ->
  eval val (forget_var p phi) = true ->
  eval val psi = true.
Proof.
  intros val p phi psi Hbf_phi Hbf_psi Hp_notin Himp Hfg.
  unfold forget_var in Hfg. rewrite eval_Or in Hfg.
  rewrite (eval_Subst_box_free val p Top phi Hbf_phi) in Hfg.
  rewrite (eval_Subst_box_free val p Bot phi Hbf_phi) in Hfg.
  rewrite eval_Top_true, eval_Bot_false in Hfg.
  apply Bool.orb_true_iff in Hfg. destruct Hfg as [Hf | Hf].
  - pose proof (Himp (update_val val p true)) as Himp_t.
    rewrite eval_Impl in Himp_t. rewrite Hf in Himp_t. cbn in Himp_t.
    assert (Hpsi_eq : eval (update_val val p true) psi = eval val psi).
    { apply eval_ext_on_free_vars. intros q Hq.
      unfold update_val. destruct (Nat.eqb q p) eqn:E; [|reflexivity].
      apply Nat.eqb_eq in E. subst q. exfalso. exact (Hp_notin Hq). }
    rewrite Hpsi_eq in Himp_t. exact Himp_t.
  - pose proof (Himp (update_val val p false)) as Himp_f.
    rewrite eval_Impl in Himp_f. rewrite Hf in Himp_f. cbn in Himp_f.
    assert (Hpsi_eq : eval (update_val val p false) psi = eval val psi).
    { apply eval_ext_on_free_vars. intros q Hq.
      unfold update_val. destruct (Nat.eqb q p) eqn:E; [|reflexivity].
      apply Nat.eqb_eq in E. subst q. exfalso. exact (Hp_notin Hq). }
    rewrite Hpsi_eq in Himp_f. exact Himp_f.
Qed.


Theorem prov_forget_var_intro : forall p phi,
  box_free phi -> |- Impl phi (forget_var p phi).
Proof.
  intros p phi Hbf.
  apply trivial_in_provable. apply prop_completeness.
  - cbn. split; [exact Hbf|]. apply box_free_forget_var. exact Hbf.
  - intro val. rewrite eval_Impl.
    destruct (eval val phi) eqn:Ephi.
    + rewrite (eval_forget_var_intro val p phi Hbf Ephi). reflexivity.
    + reflexivity.
Qed.


Theorem prov_forget_var_elim : forall p phi psi,
  box_free phi -> box_free psi ->
  ~ In p (free_vars psi) ->
  |- Impl phi psi -> |- Impl (forget_var p phi) psi.
Proof.
  intros p phi psi Hbf_phi Hbf_psi Hp_notin Himp.
  apply trivial_in_provable. apply prop_completeness.
  - cbn. split; [|exact Hbf_psi]. apply box_free_forget_var. exact Hbf_phi.
  - intro val. rewrite eval_Impl.
    destruct (eval val (forget_var p phi)) eqn:Efg; [|reflexivity].
    rewrite (eval_forget_var_elim val p phi psi Hbf_phi Hbf_psi Hp_notin
              (provable_classically_valid _ Himp) Efg).
    reflexivity.
Qed.


(** Substituting a closed formula (free_vars empty) for variable [p] in
    [phi] produces a formula whose free variables are exactly those of
    [phi] minus [p]. *)

Lemma free_vars_Subst_closed_fwd : forall p X phi v,
  free_vars X = [] ->
  In v (free_vars (Subst p X phi)) ->
  v <> p /\ In v (free_vars phi).
Proof.
  intros p X phi v HX.
  unfold Subst.
  induction phi as [k | | a IHa b IHb | n psi IHpsi]; cbn.
  - destruct (Nat.eqb k p) eqn:E.
    + rewrite HX. intros [].
    + cbn. intros [Heq|[]]. subst v.
      apply Nat.eqb_neq in E. split.
      * exact E.
      * left. reflexivity.
  - intros [].
  - rewrite in_app_iff. intros [HA | HB].
    + destruct (IHa HA) as [Hne Hin]. split; [exact Hne|].
      apply in_or_app. left. exact Hin.
    + destruct (IHb HB) as [Hne Hin]. split; [exact Hne|].
      apply in_or_app. right. exact Hin.
  - exact IHpsi.
Qed.


Lemma free_vars_Subst_closed_bwd : forall p X phi v,
  v <> p ->
  In v (free_vars phi) ->
  In v (free_vars (Subst p X phi)).
Proof.
  intros p X phi v Hne.
  unfold Subst.
  induction phi as [k | | a IHa b IHb | n psi IHpsi]; cbn.
  - intros [Heq | []]. subst v.
    destruct (Nat.eqb k p) eqn:E.
    + apply Nat.eqb_eq in E. exfalso. apply Hne. exact E.
    + cbn. left. reflexivity.
  - intros [].
  - rewrite in_app_iff. intros [HA|HB].
    + apply in_or_app. left. exact (IHa HA).
    + apply in_or_app. right. exact (IHb HB).
  - exact IHpsi.
Qed.


Lemma free_vars_forget_var_no_p : forall p phi v,
  In v (free_vars (forget_var p phi)) -> v <> p /\ In v (free_vars phi).
Proof.
  intros p phi v Hin.
  unfold forget_var, Or, Neg in Hin. cbn in Hin.
  rewrite app_nil_r in Hin.
  apply in_app_or in Hin. destruct Hin as [HA | HB].
  - apply (free_vars_Subst_closed_fwd p Top phi v eq_refl HA).
  - apply (free_vars_Subst_closed_fwd p Bot phi v eq_refl HB).
Qed.


Lemma free_vars_forget_var_subset : forall p phi v,
  In v (free_vars (forget_var p phi)) -> In v (free_vars phi).
Proof.
  intros p phi v H. exact (proj2 (free_vars_forget_var_no_p p phi v H)).
Qed.


Lemma free_vars_forget_var_excludes : forall p phi,
  ~ In p (free_vars (forget_var p phi)).
Proof.
  intros p phi H. apply (proj1 (free_vars_forget_var_no_p p phi p H)).
  reflexivity.
Qed.


(** Iterated variable elimination over a list of variables. *)

Fixpoint forget_vars (vs : list nat) (phi : Form) : Form :=
  match vs with
  | [] => phi
  | p :: rest => forget_vars rest (forget_var p phi)
  end.


Lemma box_free_forget_vars : forall vs phi,
  box_free phi -> box_free (forget_vars vs phi).
Proof.
  induction vs as [|p rest IH]; intros phi Hbf; cbn.
  - exact Hbf.
  - apply IH. apply box_free_forget_var. exact Hbf.
Qed.


Lemma free_vars_forget_vars_subset : forall vs phi v,
  In v (free_vars (forget_vars vs phi)) -> In v (free_vars phi).
Proof.
  induction vs as [|p rest IH]; intros phi v H; cbn in H.
  - exact H.
  - apply (free_vars_forget_var_subset p phi v).
    apply (IH (forget_var p phi) v H).
Qed.


Lemma free_vars_forget_vars_excludes : forall vs phi p,
  In p vs -> ~ In p (free_vars (forget_vars vs phi)).
Proof.
  induction vs as [|q rest IH]; intros phi p Hin Habs; cbn in *.
  - destruct Hin.
  - destruct Hin as [Heq | Hin'].
    + subst q.
      pose proof (free_vars_forget_vars_subset rest (forget_var p phi) p Habs)
        as Hin0.
      exact (free_vars_forget_var_excludes p phi Hin0).
    + exact (IH (forget_var q phi) p Hin' Habs).
Qed.


Theorem prov_forget_vars_intro : forall vs phi,
  box_free phi -> |- Impl phi (forget_vars vs phi).
Proof.
  induction vs as [|p rest IH]; intros phi Hbf; cbn.
  - exact (prov_id phi).
  - pose proof (prov_forget_var_intro p phi Hbf) as H1.
    pose proof (box_free_forget_var p phi Hbf) as Hbf'.
    pose proof (IH (forget_var p phi) Hbf') as H2.
    exact (prov_compose _ _ _ H1 H2).
Qed.


Theorem prov_forget_vars_elim : forall vs phi psi,
  box_free phi -> box_free psi ->
  (forall p, In p vs -> ~ In p (free_vars psi)) ->
  |- Impl phi psi -> |- Impl (forget_vars vs phi) psi.
Proof.
  induction vs as [|p rest IH]; intros phi psi Hbf_phi Hbf_psi Hdisj Himp; cbn.
  - exact Himp.
  - pose proof (Hdisj p (or_introl eq_refl)) as Hp_notin.
    pose proof (prov_forget_var_elim p phi psi Hbf_phi Hbf_psi Hp_notin Himp)
      as Hstep.
    pose proof (box_free_forget_var p phi Hbf_phi) as Hbf_fg.
    apply (IH (forget_var p phi) psi Hbf_fg Hbf_psi).
    + intros q Hq. apply Hdisj. right. exact Hq.
    + exact Hstep.
Qed.


(** Compute the list of "private" variables of [phi] with respect to
    [psi] — those occurring in [phi] but not in [psi]. *)

Definition private_vars (phi psi : Form) : list nat :=
  filter (fun v => negb (existsb (Nat.eqb v) (free_vars psi))) (free_vars phi).


Lemma private_vars_in_phi : forall phi psi v,
  In v (private_vars phi psi) -> In v (free_vars phi).
Proof.
  intros phi psi v Hin. unfold private_vars in Hin.
  apply filter_In in Hin. exact (proj1 Hin).
Qed.


Lemma existsb_eqb_in_iff : forall (l : list nat) (v : nat),
  existsb (Nat.eqb v) l = true <-> In v l.
Proof.
  intros l v. induction l as [|x rest IH]; cbn.
  - split; [discriminate | intros []].
  - rewrite Bool.orb_true_iff. split.
    + intros [Heq | Hrest].
      * left. apply Nat.eqb_eq in Heq. symmetry. exact Heq.
      * right. apply IH. exact Hrest.
    + intros [Heq | Hin].
      * subst x. left. apply Nat.eqb_refl.
      * right. apply IH. exact Hin.
Qed.


Lemma private_vars_not_in_psi : forall phi psi v,
  In v (private_vars phi psi) -> ~ In v (free_vars psi).
Proof.
  intros phi psi v Hin. unfold private_vars in Hin.
  apply filter_In in Hin. destruct Hin as [_ Hneg].
  destruct (existsb (Nat.eqb v) (free_vars psi)) eqn:E; [discriminate|].
  intro Habs. rewrite (proj2 (existsb_eqb_in_iff _ v) Habs) in E.
  discriminate.
Qed.


Lemma private_vars_complete : forall phi psi v,
  In v (free_vars phi) -> ~ In v (free_vars psi) ->
  In v (private_vars phi psi).
Proof.
  intros phi psi v Hphi Hpsi. unfold private_vars.
  apply filter_In. split; [exact Hphi|].
  destruct (existsb (Nat.eqb v) (free_vars psi)) eqn:E; [|reflexivity].
  exfalso. apply Hpsi. apply (proj1 (existsb_eqb_in_iff _ v)). exact E.
Qed.


(** ** Vocabulary-restricted Craig interpolation, box-free fragment.

    For any provable implication [|- Impl phi psi] between two box-free
    formulas, there is a box-free interpolant [chi] whose free variables
    are contained in the intersection of the free variables of [phi]
    and [psi].  The interpolant is constructed by iteratively
    eliminating the "private" variables of [phi] (those not in [psi])
    via [forget_var], yielding [chi := forget_vars (private_vars phi psi) phi]. *)

Theorem craig_interpolation_box_free : forall phi psi,
  box_free phi -> box_free psi ->
  |- Impl phi psi ->
  exists chi,
    box_free chi /\
    |- Impl phi chi /\ |- Impl chi psi /\
    (forall v, In v (free_vars chi) ->
       In v (free_vars phi) /\ In v (free_vars psi)).
Proof.
  intros phi psi Hbf_phi Hbf_psi Himp.
  set (priv := private_vars phi psi).
  exists (forget_vars priv phi).
  split; [|split; [|split]].
  - apply box_free_forget_vars. exact Hbf_phi.
  - exact (prov_forget_vars_intro priv phi Hbf_phi).
  - apply prov_forget_vars_elim; try assumption.
    intros p Hp. apply private_vars_not_in_psi with (phi := phi). exact Hp.
  - intros v Hin.
    pose proof (free_vars_forget_vars_subset priv phi v Hin) as Hphi.
    split; [exact Hphi|].
    destruct (in_dec Nat.eq_dec v (free_vars psi)) as [Hpsi|Hnpsi].
    + exact Hpsi.
    + exfalso. apply (free_vars_forget_vars_excludes priv phi v).
      * apply private_vars_complete; assumption.
      * exact Hin.
Qed.


(** ** Substantive consequences of box-free Craig interpolation.

    These replace the deleted trivial-witness placeholders.  Each is
    derived from [craig_interpolation_box_free] and inherits the
    vocabulary-restriction guarantee FV(chi) ⊆ FV(phi) ∩ FV(psi). *)

(** Box-free Maehara lemma: every box-free implication has a box-free
    interpolant of strictly bounded vocabulary.  Substantive replacement
    for the deleted [Maehara_lemma_via_self_interpolation] (which
    returned [And phi (Impl phi psi)]). *)

Theorem maehara_lemma_box_free : forall phi psi,
  box_free phi -> box_free psi ->
  |- Impl phi psi ->
  exists chi,
    box_free chi /\
    |- Impl phi chi /\ |- Impl chi psi /\
    (forall v, In v (free_vars chi) ->
       In v (free_vars phi) /\ In v (free_vars psi)).
Proof. exact craig_interpolation_box_free. Qed.


(** Box-free Beth explicit definability: if [phi] implicitly defines
    [psi] (in the sense that [|- Impl phi psi]) and [psi] does not
    mention a variable [p], then there is an explicit definition
    [chi] of [psi] from [phi] that also avoids [p].  Substantive
    replacement for the deleted [beth_implicit_to_explicit] (witness
    [def := psi]).  Here the witness [chi] is constructed by Craig
    interpolation, so [chi] genuinely sits between [phi] and [psi]
    in vocabulary, not just at one of the endpoints. *)

Theorem beth_explicit_definability_box_free : forall phi psi p,
  box_free phi -> box_free psi ->
  ~ In p (free_vars psi) ->
  |- Impl phi psi ->
  exists chi,
    box_free chi /\
    |- Impl phi chi /\ |- Impl chi psi /\
    ~ In p (free_vars chi).
Proof.
  intros phi psi p Hbf_phi Hbf_psi Hp_notin Himp.
  destruct (craig_interpolation_box_free phi psi Hbf_phi Hbf_psi Himp)
    as [chi [Hbf [Hf [Hb Hsub]]]].
  exists chi. split; [|split; [|split]].
  - exact Hbf.
  - exact Hf.
  - exact Hb.
  - intro Habs. apply Hp_notin. exact (proj2 (Hsub p Habs)).
Qed.


(** Lyndon-style polarity-restricted Beth corollary: if [phi]
    syntactically excludes a variable [p], then so does the Craig
    interpolant.  Substantive replacement for the deleted
    [lyndon_interpolation_via_craig_subset] (witness [chi = phi]) and
    [lyndon_polarity_preserved_when_identical_interpolant].  Full
    Lyndon polarity tracking requires the cut-free sequent calculus
    and remains under todo item 18. *)

Theorem lyndon_excluded_variable_box_free : forall phi psi p,
  box_free phi -> box_free psi ->
  ~ In p (free_vars phi) ->
  |- Impl phi psi ->
  exists chi,
    box_free chi /\
    |- Impl phi chi /\ |- Impl chi psi /\
    ~ In p (free_vars chi).
Proof.
  intros phi psi p Hbf_phi Hbf_psi Hp_notin Himp.
  destruct (craig_interpolation_box_free phi psi Hbf_phi Hbf_psi Himp)
    as [chi [Hbf [Hf [Hb Hsub]]]].
  exists chi. split; [|split; [|split]].
  - exact Hbf.
  - exact Hf.
  - exact Hb.
  - intro Habs. apply Hp_notin. exact (proj1 (Hsub p Habs)).
Qed.


(** Closed-form Craig: if both [phi] and [psi] are box-free and
    closed (no free variables), the interpolant is also closed.
    Substantive replacement for the deleted [craig_closed_interpolation]
    (which returned [chi = phi] without using closure of [psi]). *)

Theorem craig_interpolation_box_free_closed : forall phi psi,
  box_free phi -> box_free psi ->
  free_vars phi = [] -> free_vars psi = [] ->
  |- Impl phi psi ->
  exists chi,
    box_free chi /\ free_vars chi = [] /\
    |- Impl phi chi /\ |- Impl chi psi.
Proof.
  intros phi psi Hbf_phi Hbf_psi Hcphi Hcpsi Himp.
  destruct (craig_interpolation_box_free phi psi Hbf_phi Hbf_psi Himp)
    as [chi [Hbf [Hf [Hb Hsub]]]].
  exists chi. split; [|split; [|split]].
  - exact Hbf.
  - destruct (free_vars chi) as [|v rest] eqn:Echi; [reflexivity|].
    exfalso.
    destruct (Hsub v (or_introl eq_refl)) as [Hphi _].
    rewrite Hcphi in Hphi. exact Hphi.
  - exact Hf.
  - exact Hb.
Qed.

