(** Tiling.Kripke - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.

From Tiling Require Import Syntax.
From Tiling Require Import Provable.
From Tiling Require Import Propositional.


(** ** Reflection schema unprovability (conditional).

    Strengthening of [loebian_obstacle]: assuming meta-consistency
    of the system ([~ |- Bot]), the same-level reflection schema is
    not even uniformly provable.  The unconditional version
    [reflection_schema_unprovable] follows from
    [meta_consistency_system], proved below. *)

Theorem reflection_schema_unprovable_conditional : forall n,
  ~ (|- Bot) -> ~ (forall phi, |- Impl (Box n phi) phi).
Proof.
  intros n Hcons Hsch.
  exact (Hcons (loebian_obstacle n Hsch)).
Qed.


(** With system-level meta-consistency in hand, the conditional
    [reflection_schema_unprovable_conditional] becomes unconditional. *)

Theorem reflection_schema_unprovable : forall n,
  ~ (forall phi, |- Impl (Box n phi) phi).
Proof.
  intros n.
  exact (reflection_schema_unprovable_conditional n meta_consistency_system).
Qed.


(** A Kripke frame for GLP* consists of a type of worlds, a family of
    accessibility relations indexed by level, and four structural
    conditions:

    - Each [R n] is transitive.
    - Each [R n] is converse-well-founded (Noetherian, validating Loeb).
    - [R (S n)] is contained in [R n] (validating monotonicity).
    - Every [R (S n)] successor has an [R n] successor (validating
      [NextCon]).

    Forcing is defined classically with [bool]-valued valuations. *)

Record Frame : Type := mkFrame {
  fW : Type;
  fR : nat -> fW -> fW -> Prop;
  fR_trans : forall n w v u, fR n w v -> fR n v u -> fR n w u;
  fR_wf : forall n, well_founded (fun u v => fR n v u);
  fR_mon : forall n w v, fR (S n) w v -> fR n w v;
  fR_nextcon : forall n w v, fR (S n) w v -> exists u, fR n v u
}.


Fixpoint forces (F : Frame) (V : fW F -> nat -> bool)
                (w : fW F) (phi : Form) : Prop :=
  match phi with
  | Var p => V w p = true
  | Bot => False
  | Impl X Y => forces F V w X -> forces F V w Y
  | Box n psi => forall v, fR F n w v -> forces F V v psi
  end.


Definition Valid (phi : Form) : Prop :=
  forall F V w, forces F V w phi.


(** ** Soundness of GLP* with respect to Kripke semantics.

    Every Provable formula is valid in every GLP*-frame.  The Loeb
    axiom uses well-founded induction on the converse of [fR n] to
    extract a witness; cross-level axioms use [fR_mon] and
    [fR_nextcon] respectively. *)

Theorem soundness : forall phi, |- phi -> Valid phi.
Proof.
  intros phi H. induction H.
  - (* Ax_K *)
    unfold Valid. intros F V w. simpl. intros Hphi _. exact Hphi.
  - (* Ax_S *)
    unfold Valid. intros F V w. simpl. intros Hf Hg Hphi.
    apply Hf; [exact Hphi | apply Hg; exact Hphi].
  - (* Ax_DN *)
    unfold Valid. intros F V w. simpl. intro Hnnp.
    apply NNPP. exact Hnnp.
  - (* Ax_BoxK *)
    unfold Valid. intros F V w. simpl. intros Himp Hphi v Hwv.
    apply (Himp v Hwv). apply (Hphi v Hwv).
  - (* Ax_Loeb *)
    unfold Valid. intros F V w. simpl. intros Hbox v Hwv.
    pose proof (fR_wf F n) as Hwf.
    set (P := fun u => fR F n w u -> forces F V u phi).
    cut (P v); [intro Hpv; exact (Hpv Hwv) |].
    apply (well_founded_ind Hwf P).
    intros u IH. unfold P. intro Hwu.
    apply (Hbox u Hwu).
    intros u' Huu'.
    apply (IH u' Huu' (fR_trans F n w u u' Hwu Huu')).
  - (* Ax_Box4 *)
    unfold Valid. intros F V w. simpl. intros Hphi v Hwv u Hvu.
    apply Hphi. apply (fR_trans F n w v u Hwv Hvu).
  - (* Ax_Mon *)
    unfold Valid. intros F V w. simpl. intros Hphi v Hwv.
    apply Hphi. apply (fR_mon F n w v Hwv).
  - (* Ax_NextCon *)
    unfold Valid. intros F V w. simpl. intros v Hwv Hbox.
    destruct (fR_nextcon F n w v Hwv) as [u Hvu].
    exact (Hbox u Hvu).
  - (* MP *)
    unfold Valid. intros F V w.
    apply (IHProvable1 F V w). apply (IHProvable2 F V w).
  - (* Nec *)
    unfold Valid. intros F V w. simpl.
    intros v _. apply (IHProvable F V v).
Qed.


(** ** A two-world frame refuting [Box 0 Bot].

    [F0] has [W := bool] (with [true] interpreted as the root and
    [false] as a single [R 0]-successor), [R 0] = {(true, false)},
    and all other [R n] empty.  All four frame conditions hold
    vacuously or trivially, so [F0] is a GLP*-frame.  At the root
    [true], [Box 0 Bot] forces to [False] because the successor
    [false] forces [Bot] to [False]. *)

Definition F0_R (n : nat) (w v : bool) : Prop :=
  match n with O => w = true /\ v = false | _ => False end.


Lemma F0_R_trans : forall n w v u,
  F0_R n w v -> F0_R n v u -> F0_R n w u.
Proof.
  intros [|n] w v u; simpl; intros H1 H2; try contradiction.
  destruct H1 as [_ Hvf]. destruct H2 as [Hvt _]. subst v. discriminate.
Qed.


Lemma F0_R_wf : forall n, well_founded (fun u v => F0_R n v u).
Proof.
  intros n w.
  destruct n; destruct w; apply Acc_intro; intros y Hy; simpl in Hy.
  - destruct Hy as [_ Hyf]. subst y.
    apply Acc_intro. intros z Hz. simpl in Hz.
    destruct Hz as [Heq _]. discriminate.
  - destruct Hy as [Heq _]. discriminate.
  - destruct Hy.
  - destruct Hy.
Qed.


Lemma F0_R_mon : forall n w v, F0_R (S n) w v -> F0_R n w v.
Proof. intros n w v H. simpl in H. destruct H. Qed.


Lemma F0_R_nextcon : forall n w v,
  F0_R (S n) w v -> exists u, F0_R n v u.
Proof. intros n w v H. simpl in H. destruct H. Qed.


Definition F0 : Frame :=
  mkFrame bool F0_R F0_R_trans F0_R_wf F0_R_mon F0_R_nextcon.


Theorem meta_consistency_box_0 : ~ (|- Box 0 Bot).
Proof.
  intro H.
  pose proof (soundness _ H F0 (fun _ _ => true) true) as Hf.
  simpl in Hf.
  apply (Hf false).
  split; reflexivity.
Qed.


(** ** A nat-indexed frame refuting [Box n Bot] uniformly.

    [Fnat] takes [W := nat] and [R k w v := w > v /\ v >= k].  At
    world [n+1], the world [n] witnesses an [R n]-successor with
    [Bot] forced false.  All four frame conditions are direct
    consequences of basic arithmetic. *)

Definition Fnat_R (k : nat) (w v : nat) : Prop := w > v /\ v >= k.


Lemma Fnat_R_trans : forall k w v u,
  Fnat_R k w v -> Fnat_R k v u -> Fnat_R k w u.
Proof.
  intros k w v u [Hwv _] [Hvu Hun]. split; lia.
Qed.


Lemma Fnat_R_wf : forall k, well_founded (fun u v => Fnat_R k v u).
Proof.
  intros k x.
  induction x as [x IH] using (well_founded_induction lt_wf).
  apply Acc_intro. intros y Hy.
  destruct Hy as [Hgt _].
  apply IH. exact Hgt.
Qed.


Lemma Fnat_R_mon : forall k w v, Fnat_R (S k) w v -> Fnat_R k w v.
Proof.
  intros k w v [H1 H2]. split; lia.
Qed.


Lemma Fnat_R_nextcon : forall k w v,
  Fnat_R (S k) w v -> exists u, Fnat_R k v u.
Proof.
  intros k w v [Hwv Hvk]. exists k.
  unfold Fnat_R. split; lia.
Qed.


Definition Fnat : Frame :=
  mkFrame nat Fnat_R Fnat_R_trans Fnat_R_wf Fnat_R_mon Fnat_R_nextcon.


(** ** Meta-consistency at every level.

    For any [n], evaluating in [Fnat] at world [S n] refutes [Box n
    Bot], since the witness [n] satisfies [S n > n /\ n >= n]. *)

Theorem meta_consistency_every_level : forall n, ~ (|- Box n Bot).
Proof.
  intros n H.
  pose proof (soundness _ H Fnat (fun _ _ => true) (S n)) as Hf.
  simpl in Hf.
  apply (Hf n).
  unfold Fnat_R. split; lia.
Qed.


(** ** Meta_consistency_no_contradiction unconditional. *)

Theorem meta_no_contradiction : forall n phi,
  ~ (|- Box n phi /\ |- Box n (Neg phi)).
Proof.
  intros n phi.
  apply meta_consistency_no_contradiction.
  exact (meta_consistency_every_level n).
Qed.


(** ** Monotonicity converse fails.

    [|- Impl (Box (S n) phi) (Box n phi)] is not a theorem of GLP*
    for [phi] a propositional variable.  Witnessed by [Fnat] at world
    [S n] with valuation [V w 0 := S n <=? w]: in [Fnat], every
    [R (S n)]-successor of [S n] is empty, so [Box (S n) (Var 0)]
    holds vacuously, while [n] is an [R n]-successor of [S n] but
    fails [Var 0]'s valuation.  Hence the implication fails at [S n]
    in [Fnat], and by soundness it is not Provable. *)

Theorem mon_converse_fails : forall n,
  ~ (|- Impl (Box (S n) (Var 0)) (Box n (Var 0))).
Proof.
  intros n H.
  pose (V := fun (w : nat) (p : nat) =>
    match p with 0 => Nat.leb (S n) w | _ => false end).
  pose proof (soundness _ H Fnat V (S n)) as Hf.
  simpl in Hf.
  assert (Hbox_Sn : forall v, Fnat_R (S n) (S n) v -> V v 0 = true).
  { intros v [Hlt Hge]. exfalso. lia. }
  pose proof (Hf Hbox_Sn n) as HboxN.
  assert (Hrn : Fnat_R n (S n) n).
  { unfold Fnat_R. split; lia. }
  specialize (HboxN Hrn).
  change (V n 0 = true) in HboxN.
  unfold V in HboxN.
  change (Nat.leb (S n) n = true) in HboxN.
  apply Nat.leb_le in HboxN. lia.
Qed.


(** ** Strict extension at every level.

    For each [n], the formula [Neg (Box n Bot)] (the consistency
    sentence for level [n]) is provable at level [S n] but not at
    level [n] itself.  This witnesses genuine ascent: each level of
    the tower proves something its predecessor cannot. *)

Theorem strict_extension_at_each_level : forall n,
  exists phi, (|- Box (S n) phi) /\ ~ (|- Box n phi).
Proof.
  intro n.
  exists (Neg (Box n Bot)).
  split.
  - exact (Ax_NextCon n).
  - intro H.
    apply (meta_consistency_every_level n).
    exact (MP _ _ (godel_second n) H).
Qed.


(** ** Same-level boxed reflection schema is unprovable uniformly.

    A "level-[S n] internalisation" of [loebian_obstacle]: if level
    [S n] uniformly proves [Box (S n) phi -> phi] (its own-level
    reflection schema), then by [Ax_Loeb] specialised at [Bot],
    [|- Box (S n) Bot] follows, contradicting
    [meta_consistency_every_level]. *)

Theorem reflection_at_same_level_unprovable_uniformly : forall n,
  ~ (forall phi, |- Box (S n) (Impl (Box (S n) phi) phi)).
Proof.
  intros n Hsch.
  pose proof (Hsch Bot) as Hbot.
  pose proof (Ax_Loeb (S n) Bot) as HLoeb.
  pose proof (MP _ _ HLoeb Hbot) as HboxBot.
  exact (meta_consistency_every_level (S n) HboxBot).
Qed.


Record Frame_no_NC : Type := mkFrame_no_NC {
  fW_nc : Type;
  fR_nc : nat -> fW_nc -> fW_nc -> Prop;
  fR_nc_trans : forall n w v u, fR_nc n w v -> fR_nc n v u -> fR_nc n w u;
  fR_nc_wf : forall n, well_founded (fun u v => fR_nc n v u);
  fR_nc_mon : forall n w v, fR_nc (S n) w v -> fR_nc n w v
}.


Theorem meta_consistency_via_kripke : ~ (|- Bot).
Proof.
  intro Hbot.
  pose proof (soundness Bot Hbot) as Hval.
  exact (Hval F0 (fun _ _ => false) true).
Qed.


(** ** Level-indexed Gödel-Rosser theorem.

    For every [n], [Var 0] is independent at level [n]: neither
    [Box n (Var 0)] nor [Box n (Neg (Var 0))] is provable.  Both
    unprovabilities follow from Kripke soundness against [Fnat] at
    world [S n], with [Var 0] valued uniformly false (resp. true).
    Establishes that level-[n] provability is genuinely incomplete in
    the Gödel sense at every level. *)

Theorem godel_rosser_every_level : forall n,
  exists phi, ~ (|- Box n phi) /\ ~ (|- Box n (Neg phi)).
Proof.
  intro n. exists (Var 0). split.
  - intro H.
    pose proof (soundness _ H Fnat (fun _ _ => false) (S n)) as Hf.
    simpl in Hf.
    assert (Hsucc : Fnat_R n (S n) n) by (unfold Fnat_R; split; lia).
    pose proof (Hf n Hsucc) as Hcontra. discriminate.
  - intro H.
    pose proof (soundness _ H Fnat (fun _ _ => true) (S n)) as Hf.
    simpl in Hf.
    assert (Hsucc : Fnat_R n (S n) n) by (unfold Fnat_R; split; lia).
    exact (Hf n Hsucc eq_refl).
Qed.


(** ** Frame-condition independence.

    Each of the four [Frame] conditions is independent of the other
    three: for each condition there is a [(W, R)] satisfying the other
    three but violating that one.  Each counter-frame is exhibited by
    a relation on a small finite or natural-numbered carrier. *)

(** *** Counter-frame violating transitivity. *)

Definition R_break_trans (n : nat) (w v : nat) : Prop :=
  match n with
  | 0 => (w = 0 /\ v = 1) \/ (w = 1 /\ v = 2)
  | _ => False
  end.


Lemma R_break_trans_NOT_trans :
  ~ (forall n w v u,
        R_break_trans n w v -> R_break_trans n v u -> R_break_trans n w u).
Proof.
  intro Htr.
  specialize (Htr 0 0 1 2).
  assert (H01 : R_break_trans 0 0 1) by (left; split; reflexivity).
  assert (H12 : R_break_trans 0 1 2) by (right; split; reflexivity).
  pose proof (Htr H01 H12) as H02. simpl in H02.
  destruct H02 as [[_ H]|[H _]]; discriminate.
Qed.


Lemma R_break_trans_wf :
  forall n, well_founded (fun u v => R_break_trans n v u).
Proof.
  intros n x.
  destruct n as [|n'].
  2: { apply Acc_intro. intros y Hy. simpl in Hy. contradiction. }
  destruct x as [|[|x']].
  - apply Acc_intro. intros y Hy. simpl in Hy.
    destruct Hy as [[_ Hy]|[H _]]; [|discriminate].
    subst y. apply Acc_intro. intros z Hz. simpl in Hz.
    destruct Hz as [[H _]|[_ Hz]]; [discriminate|].
    subst z. apply Acc_intro. intros w Hw. simpl in Hw.
    destruct Hw as [[H _]|[H _]]; discriminate.
  - apply Acc_intro. intros z Hz. simpl in Hz.
    destruct Hz as [[H _]|[_ Hz]]; [discriminate|].
    subst z. apply Acc_intro. intros w Hw. simpl in Hw.
    destruct Hw as [[H _]|[H _]]; discriminate.
  - apply Acc_intro. intros y Hy. simpl in Hy.
    destruct Hy as [[H _]|[H _]]; discriminate.
Qed.


Lemma R_break_trans_mon : forall n w v,
  R_break_trans (S n) w v -> R_break_trans n w v.
Proof. intros n w v H. simpl in H. contradiction. Qed.


Lemma R_break_trans_nextcon : forall n w v,
  R_break_trans (S n) w v -> exists u, R_break_trans n v u.
Proof. intros n w v H. simpl in H. contradiction. Qed.


(** *** Counter-frame violating converse-well-foundedness.
    [W := nat], [R n w v := w < v] at every level. *)

Definition R_break_wf (n : nat) (w v : nat) : Prop := w < v.


Lemma R_break_wf_trans : forall n w v u,
  R_break_wf n w v -> R_break_wf n v u -> R_break_wf n w u.
Proof. intros n w v u H1 H2. unfold R_break_wf in *. lia. Qed.


Lemma R_break_wf_NOT_wf :
  ~ (forall n, well_founded (fun u v => R_break_wf n v u)).
Proof.
  intro Hwf. pose proof (Hwf 0) as Hwf0.
  assert (Hloop : forall a,
    Acc (fun u v => R_break_wf 0 v u) a ->
    forall (t : nat -> nat),
      t 0 = a ->
      (forall n, R_break_wf 0 (t n) (t (S n))) ->
      False).
  { intros a Hacc. induction Hacc as [a _ IH].
    intros t Heq Hch.
    assert (Hpf : R_break_wf 0 a (t 1)).
    { rewrite <- Heq. exact (Hch 0). }
    exact (IH (t 1) Hpf (fun n => t (S n)) eq_refl
              (fun n => Hch (S n))). }
  apply (Hloop 0 (Hwf0 0) (fun n => n) eq_refl).
  intro n. unfold R_break_wf. lia.
Qed.


Lemma R_break_wf_mon : forall n w v,
  R_break_wf (S n) w v -> R_break_wf n w v.
Proof. intros n w v H. exact H. Qed.


Lemma R_break_wf_nextcon : forall n w v,
  R_break_wf (S n) w v -> exists u, R_break_wf n v u.
Proof.
  intros n w v H. exists (S v). unfold R_break_wf. lia.
Qed.


(** *** Counter-frame violating monotone inclusion.
    [W := nat] with [R 0 := {(1,2)}], [R 1 := {(0,1)}], [R n] empty
    for [n>=2].  [R 1] not a subset of [R 0] because [(0,1)] in [R 1]
    but not in [R 0]. *)

Definition R_break_mon (n : nat) (w v : nat) : Prop :=
  match n with
  | 0 => w = 1 /\ v = 2
  | 1 => w = 0 /\ v = 1
  | _ => False
  end.


Lemma R_break_mon_trans : forall n w v u,
  R_break_mon n w v -> R_break_mon n v u -> R_break_mon n w u.
Proof.
  intros [|[|n]] w v u H1 H2; simpl in *; try contradiction.
  - destruct H1 as [_ Hv]. destruct H2 as [Hv' _]. subst. discriminate.
  - destruct H1 as [_ Hv]. destruct H2 as [Hv' _]. subst. discriminate.
Qed.


Lemma R_break_mon_wf :
  forall n, well_founded (fun u v => R_break_mon n v u).
Proof.
  intros n x.
  destruct n as [|[|n']].
  - (* n=0: predecessors of x are y with x=1 /\ y=2 *)
    apply Acc_intro. intros y Hy. simpl in Hy.
    destruct Hy as [Hx Hy]. subst.
    apply Acc_intro. intros z Hz. simpl in Hz.
    destruct Hz as [Hz _]. discriminate.
  - (* n=1 *)
    apply Acc_intro. intros y Hy. simpl in Hy.
    destruct Hy as [Hx Hy]. subst.
    apply Acc_intro. intros z Hz. simpl in Hz.
    destruct Hz as [Hz _]. discriminate.
  - (* n>=2: empty *)
    apply Acc_intro. intros y Hy. simpl in Hy. contradiction.
Qed.


Lemma R_break_mon_NOT_mon :
  ~ (forall n w v, R_break_mon (S n) w v -> R_break_mon n w v).
Proof.
  intro Hm. specialize (Hm 0 0 1).
  assert (H : R_break_mon 1 0 1) by (simpl; split; reflexivity).
  pose proof (Hm H) as Hbad. simpl in Hbad.
  destruct Hbad as [Hbad _]. discriminate.
Qed.


Lemma R_break_mon_nextcon : forall n w v,
  R_break_mon (S n) w v -> exists u, R_break_mon n v u.
Proof.
  intros [|[|n]] w v H; simpl in H; try contradiction.
  - destruct H as [Hw Hv]. subst. exists 2. simpl. split; reflexivity.
Qed.


(** *** Counter-frame violating NextCon successor.
    [W := nat] with [R 0 := {(0,1)}], [R 1 := {(0,1)}], higher empty.
    NextCon at level 0 fails: [R 1 (0,1)] holds but [R 0 1 _] is
    empty. *)

Definition R_break_nc (n : nat) (w v : nat) : Prop :=
  match n with
  | 0 => w = 0 /\ v = 1
  | 1 => w = 0 /\ v = 1
  | _ => False
  end.


Lemma R_break_nc_trans : forall n w v u,
  R_break_nc n w v -> R_break_nc n v u -> R_break_nc n w u.
Proof.
  intros [|[|n']] w v u H1 H2; simpl in *; try contradiction;
    destruct H1 as [_ Hv]; destruct H2 as [Hv' _]; subst; discriminate.
Qed.


Lemma R_break_nc_wf :
  forall n, well_founded (fun u v => R_break_nc n v u).
Proof.
  intros n x.
  destruct n as [|[|n']].
  - apply Acc_intro. intros y Hy. simpl in Hy.
    destruct Hy as [Hx Hy]. subst.
    apply Acc_intro. intros z Hz. simpl in Hz.
    destruct Hz as [Hz _]. discriminate.
  - apply Acc_intro. intros y Hy. simpl in Hy.
    destruct Hy as [Hx Hy]. subst.
    apply Acc_intro. intros z Hz. simpl in Hz.
    destruct Hz as [Hz _]. discriminate.
  - apply Acc_intro. intros y Hy. simpl in Hy. contradiction.
Qed.


Lemma R_break_nc_mon : forall n w v,
  R_break_nc (S n) w v -> R_break_nc n w v.
Proof.
  intros [|[|n]] w v H; simpl in *; try contradiction.
  exact H.
Qed.


Lemma R_break_nc_NOT_nc :
  ~ (forall n w v, R_break_nc (S n) w v -> exists u, R_break_nc n v u).
Proof.
  intro Hnc. specialize (Hnc 0 0 1).
  assert (H : R_break_nc 1 0 1) by (simpl; split; reflexivity).
  pose proof (Hnc H) as [u Hu]. simpl in Hu.
  destruct Hu as [Hu _]. discriminate.
Qed.


Theorem frame_indep_trans :
  exists Rt : nat -> nat -> nat -> Prop,
    (forall n, well_founded (fun u v => Rt n v u)) /\
    (forall n w v, Rt (S n) w v -> Rt n w v) /\
    (forall n w v, Rt (S n) w v -> exists u, Rt n v u) /\
    ~ (forall n w v u, Rt n w v -> Rt n v u -> Rt n w u).
Proof.
  exists R_break_trans.
  refine (conj _ (conj _ (conj _ _))).
  - exact R_break_trans_wf.
  - exact R_break_trans_mon.
  - exact R_break_trans_nextcon.
  - exact R_break_trans_NOT_trans.
Qed.


Theorem frame_indep_wf :
  exists Rt : nat -> nat -> nat -> Prop,
    (forall n w v u, Rt n w v -> Rt n v u -> Rt n w u) /\
    (forall n w v, Rt (S n) w v -> Rt n w v) /\
    (forall n w v, Rt (S n) w v -> exists u, Rt n v u) /\
    ~ (forall n, well_founded (fun u v => Rt n v u)).
Proof.
  exists R_break_wf.
  refine (conj _ (conj _ (conj _ _))).
  - exact R_break_wf_trans.
  - exact R_break_wf_mon.
  - exact R_break_wf_nextcon.
  - exact R_break_wf_NOT_wf.
Qed.


Theorem frame_indep_mon :
  exists Rt : nat -> nat -> nat -> Prop,
    (forall n w v u, Rt n w v -> Rt n v u -> Rt n w u) /\
    (forall n, well_founded (fun u v => Rt n v u)) /\
    (forall n w v, Rt (S n) w v -> exists u, Rt n v u) /\
    ~ (forall n w v, Rt (S n) w v -> Rt n w v).
Proof.
  exists R_break_mon.
  refine (conj _ (conj _ (conj _ _))).
  - exact R_break_mon_trans.
  - exact R_break_mon_wf.
  - exact R_break_mon_nextcon.
  - exact R_break_mon_NOT_mon.
Qed.


Theorem frame_indep_nc :
  exists Rt : nat -> nat -> nat -> Prop,
    (forall n w v u, Rt n w v -> Rt n v u -> Rt n w u) /\
    (forall n, well_founded (fun u v => Rt n v u)) /\
    (forall n w v, Rt (S n) w v -> Rt n w v) /\
    ~ (forall n w v, Rt (S n) w v -> exists u, Rt n v u).
Proof.
  exists R_break_nc.
  refine (conj _ (conj _ (conj _ _))).
  - exact R_break_nc_trans.
  - exact R_break_nc_wf.
  - exact R_break_nc_mon.
  - exact R_break_nc_NOT_nc.
Qed.


(** ** Uniform-witness theorem for tiling_consistency.

    [tiling_consistency] in Coq is already a single dependent term of
    type [forall n phi, |- Box (S n) (Impl (Box n phi) (Neg (Box n
    (Neg phi))))], i.e., a uniform witness whose body does not
    case-split on [n] or [phi].  We package this fact: the schematic
    instances [tiling_consistency n phi] are obtained by parameter
    substitution into a single derivation, not a family of unrelated
    proofs. *)

Definition tiling_witness :
  forall n phi, |- Box (S n) (Impl (Box n phi) (Neg (Box n (Neg phi))))
  := tiling_consistency.


Theorem tiling_uniform_witness :
  forall n phi, tiling_witness n phi = tiling_consistency n phi.
Proof. intros n phi. reflexivity. Qed.


Theorem tiling_witness_pointed :
  exists f : (forall n phi,
    |- Box (S n) (Impl (Box n phi) (Neg (Box n (Neg phi))))),
    forall n phi, f n phi = tiling_consistency n phi.
Proof.
  exists tiling_consistency. intros. reflexivity.
Qed.


Record Frame_no_Mon : Type := mkFrame_no_Mon {
  fW_nm : Type;
  fR_nm : nat -> fW_nm -> fW_nm -> Prop;
  fR_nm_trans : forall n w v u, fR_nm n w v -> fR_nm n v u -> fR_nm n w u;
  fR_nm_wf : forall n, well_founded (fun u v => fR_nm n v u);
  fR_nm_nextcon : forall n w v, fR_nm (S n) w v -> exists u, fR_nm n v u
}.


Record Frame_no_Loeb : Type := mkFrame_no_Loeb {
  fW_nl : Type;
  fR_nl : nat -> fW_nl -> fW_nl -> Prop;
  fR_nl_trans : forall n w v u, fR_nl n w v -> fR_nl n v u -> fR_nl n w u;
  fR_nl_mon : forall n w v, fR_nl (S n) w v -> fR_nl n w v;
  fR_nl_nextcon : forall n w v, fR_nl (S n) w v -> exists u, fR_nl n v u
}.


Theorem no_panic_reflective_trust : forall n,
  (|- Impl (Box n (Neg (Box n Bot))) (Box n Bot)) /\
  ~ (|- Box n Bot).
Proof.
  intro n. split.
  - exact (godel_second n).
  - exact (meta_consistency_every_level n).
Qed.


Theorem vingean_principle :
  exists pf : (forall n phi, |- Box (S n)
                  (Impl (Box n phi) (Neg (Box n (Neg phi))))),
    forall n phi, pf n phi = tiling_consistency n phi.
Proof. exact tiling_witness_pointed. Qed.


Definition LevelBisim (k : nat) (F1 F2 : Frame)
                       (V1 : fW F1 -> nat -> bool)
                       (V2 : fW F2 -> nat -> bool)
                       (Z : fW F1 -> fW F2 -> Prop) : Prop :=
  forall w1 w2, Z w1 w2 ->
    (forall p, V1 w1 p = V2 w2 p) /\
    (forall v1, fR F1 k w1 v1 -> exists v2, fR F2 k w2 v2 /\ Z v1 v2) /\
    (forall v2, fR F2 k w2 v2 -> exists v1, fR F1 k w1 v1 /\ Z v1 v2).


Theorem level_bisim_invariance : forall k F1 F2 V1 V2 Z,
  LevelBisim k F1 F2 V1 V2 Z ->
  forall phi w1 w2, level_k_only k phi -> Z w1 w2 ->
    (forces F1 V1 w1 phi <-> forces F2 V2 w2 phi).
Proof.
  intros k F1 F2 V1 V2 Z HBisim phi.
  induction phi as [p | | X IHX Y IHY | n psi IHpsi];
    intros w1 w2 Hlk HZ; simpl.
  - destruct (HBisim w1 w2 HZ) as [Hval _].
    rewrite (Hval p). reflexivity.
  - reflexivity.
  - simpl in Hlk. destruct Hlk as [HlX HlY].
    rewrite (IHX w1 w2 HlX HZ), (IHY w1 w2 HlY HZ). reflexivity.
  - simpl in Hlk. destruct Hlk as [Hnk Hlpsi]. subst n.
    split.
    + intros HBox v2 Hv2.
      destruct (HBisim w1 w2 HZ) as [_ [_ Hback]].
      destruct (Hback v2 Hv2) as [v1 [Hv1 HZ12]].
      rewrite <- (IHpsi v1 v2 Hlpsi HZ12).
      apply HBox. exact Hv1.
    + intros HBox v1 Hv1.
      destruct (HBisim w1 w2 HZ) as [_ [Hforth _]].
      destruct (Hforth v1 Hv1) as [v2 [Hv2 HZ12]].
      rewrite (IHpsi v1 v2 Hlpsi HZ12).
      apply HBox. exact Hv2.
Qed.


Theorem level_bisim_id : forall k F V, LevelBisim k F F V V (@eq (fW F)).
Proof.
  intros k F V w1 w2 Heq. subst w2.
  split; [reflexivity|]. split.
  - intros v1 Hv1. exists v1. split; [exact Hv1|reflexivity].
  - intros v2 Hv2. exists v2. split; [exact Hv2|reflexivity].
Qed.


Definition build_finite_frame
  (W : Type)
  (R : nat -> W -> W -> Prop)
  (Htrans : forall n w v u, R n w v -> R n v u -> R n w u)
  (Hwf : forall n, well_founded (fun u v => R n v u))
  (Hmon : forall n w v, R (S n) w v -> R n w v)
  (Hnextcon : forall n w v, R (S n) w v -> exists u, R n v u)
  : Frame :=
  mkFrame W R Htrans Hwf Hmon Hnextcon.


Theorem build_finite_frame_correct : forall W R Htrans Hwf Hmon Hnextcon,
  fW (build_finite_frame W R Htrans Hwf Hmon Hnextcon) = W /\
  (forall n w v, fR (build_finite_frame W R Htrans Hwf Hmon Hnextcon) n w v <-> R n w v).
Proof.
  intros W R Htrans Hwf Hmon Hnextcon.
  split.
  - reflexivity.
  - intros n w v. simpl. reflexivity.
Qed.


Definition F0_via_builder : Frame :=
  build_finite_frame bool F0_R F0_R_trans F0_R_wf F0_R_mon F0_R_nextcon.


Theorem F0_via_builder_eq_F0 : F0_via_builder = F0.
Proof. unfold F0_via_builder, build_finite_frame, F0. reflexivity. Qed.


Definition Fnat_via_builder : Frame :=
  build_finite_frame nat Fnat_R
    Fnat_R_trans Fnat_R_wf Fnat_R_mon Fnat_R_nextcon.


Theorem Fnat_via_builder_eq_Fnat : Fnat_via_builder = Fnat.
Proof. unfold Fnat_via_builder, build_finite_frame, Fnat. reflexivity. Qed.


Record NeighFrame : Type := mkNeighFrame {
  fW_neigh : Type;
  fN : nat -> fW_neigh -> (fW_neigh -> Prop) -> Prop
}.


Fixpoint forces_neigh (F : NeighFrame) (V : fW_neigh F -> nat -> bool)
                      (w : fW_neigh F) (phi : Form) : Prop :=
  match phi with
  | Var p => V w p = true
  | Bot => False
  | Impl X Y => forces_neigh F V w X -> forces_neigh F V w Y
  | Box k psi => fN F k w (fun v => forces_neigh F V v psi)
  end.


Definition F_K_refuter_N (_ : nat) (_ : bool) (P : bool -> Prop) : Prop :=
  (P true /\ ~ P false) \/ (~ P true /\ P false) \/ (P true /\ P false).


Definition F_K_refuter : NeighFrame :=
  mkNeighFrame bool F_K_refuter_N.


Theorem K_refuted_in_neighborhood :
  ~ forces_neigh F_K_refuter
      (fun w (_ : nat) => if w then true else false) true
      (Impl (Box 0 (Impl (Var 0) Bot))
            (Impl (Box 0 (Var 0)) (Box 0 Bot))).
Proof.
  intro Habs.
  assert (HboxImp : F_K_refuter_N 0 true
            (fun v => forces_neigh F_K_refuter
                        (fun w (_ : nat) => if w then true else false) v
                        (Impl (Var 0) Bot))).
  { unfold F_K_refuter_N. right. left. split.
    - simpl. intro H. apply H. reflexivity.
    - simpl. intro H. discriminate. }
  pose proof (Habs HboxImp) as Habs2.
  assert (HboxA : F_K_refuter_N 0 true
            (fun v => forces_neigh F_K_refuter
                        (fun w (_ : nat) => if w then true else false) v
                        (Var 0))).
  { unfold F_K_refuter_N. left. split.
    - simpl. reflexivity.
    - simpl. intro H. discriminate. }
  pose proof (Habs2 HboxA) as HboxB.
  unfold F_K_refuter_N in HboxB.
  destruct HboxB as [[H _]|[[_ H]|[H _]]]; exact H.
Qed.


(** ** Polymodal bisimulation and forces-invariance.

    A bisimulation between [(F1, V1)] and [(F2, V2)] is a relation
    [Z] over [fW F1 × fW F2] satisfying atomic agreement plus the
    forth-and-back conditions for [fR] at every level.  [forces] is
    invariant under bisimulation: bisimilar worlds satisfy the same
    formulas. *)

Definition Bisim (F1 F2 : Frame)
                 (V1 : fW F1 -> nat -> bool)
                 (V2 : fW F2 -> nat -> bool)
                 (Z : fW F1 -> fW F2 -> Prop) : Prop :=
  forall w1 w2, Z w1 w2 ->
    (forall p, V1 w1 p = V2 w2 p) /\
    (forall n v1, fR F1 n w1 v1 -> exists v2, fR F2 n w2 v2 /\ Z v1 v2) /\
    (forall n v2, fR F2 n w2 v2 -> exists v1, fR F1 n w1 v1 /\ Z v1 v2).


Theorem bisim_invariance : forall F1 F2 V1 V2 Z,
  Bisim F1 F2 V1 V2 Z ->
  forall phi w1 w2, Z w1 w2 ->
    (forces F1 V1 w1 phi <-> forces F2 V2 w2 phi).
Proof.
  intros F1 F2 V1 V2 Z HBisim phi.
  induction phi as [p | | X IHX Y IHY | n psi IHpsi];
    intros w1 w2 HZ; simpl.
  - destruct (HBisim w1 w2 HZ) as [Hval _].
    rewrite (Hval p). reflexivity.
  - reflexivity.
  - rewrite (IHX w1 w2 HZ), (IHY w1 w2 HZ). reflexivity.
  - split.
    + intros HBox v2 Hv2.
      destruct (HBisim w1 w2 HZ) as [_ [_ Hback]].
      destruct (Hback n v2 Hv2) as [v1 [Hv1 HZ12]].
      rewrite <- (IHpsi v1 v2 HZ12).
      apply HBox. exact Hv1.
    + intros HBox v1 Hv1.
      destruct (HBisim w1 w2 HZ) as [_ [Hforth _]].
      destruct (Hforth n v1 Hv1) as [v2 [Hv2 HZ12]].
      rewrite (IHpsi v1 v2 HZ12).
      apply HBox. exact Hv2.
Qed.


(** Identity bisimulation: every model is bisimilar to itself by [eq]. *)

Theorem bisim_id : forall F V, Bisim F F V V (@eq (fW F)).
Proof.
  intros F V w1 w2 Heq. subst w2.
  split; [reflexivity|]. split.
  - intros n v1 Hv1. exists v1. split; [exact Hv1|reflexivity].
  - intros n v2 Hv2. exists v2. split; [exact Hv2|reflexivity].
Qed.


(** ** Japaridze axiom and Provable_GLP.

    The Japaridze axiom of standard polymodal provability logic GLP:
    [Diamond n phi -> Box (S n) (Diamond n phi)].  Stated and shown
    to fail under suitable Kripke counter-models (so it is not
    derivable in [Provable]).  The full conservativity-into-GLP
    embedding is a separate theorem that requires the Box4-derivability
    transfer (item 12) and remains for the GLP-style calculus
    [Provable_GLP], not built here. *)

Definition Japaridze (n : nat) (phi : Form) : Form :=
  Impl (Diamond n phi) (Box (S n) (Diamond n phi)).


Theorem japaridze_unprovable_at_0 :
  ~ (|- Japaridze 0 (Var 0)).
Proof.
  intro H.
  pose (V := fun (w : nat) (p : nat) =>
    match p with O => Nat.eqb w 4 | _ => false end).
  pose proof (soundness _ H Fnat V 5) as Hf.
  unfold Japaridze, Diamond in Hf. simpl in Hf.
  assert (Hdia0 : (forall v : nat, Fnat_R 0 5 v -> V v 0 = true -> False) -> False).
  { intro Habs.
    apply (Habs 4).
    - unfold Fnat_R. split; lia.
    - unfold V. simpl. reflexivity. }
  pose proof (Hf Hdia0) as HBox1.
  apply (HBox1 1).
  - unfold Fnat_R. split; lia.
  - intros v Hv Hval. unfold Fnat_R in Hv. destruct Hv as [Hv1 Hv2].
    assert (v = 0) by lia. subst v.
    unfold V in Hval. simpl in Hval. discriminate.
Qed.


Theorem japaridze_unprovable_family : forall n, ~ (|- Japaridze n (Var 0)).
Proof.
  intro n. intro H.
  pose (V := fun (w : nat) (p : nat) =>
    match p with O => Nat.eqb w (n+4) | _ => false end).
  pose proof (soundness _ H Fnat V (n+5)) as Hf.
  unfold Japaridze, Diamond in Hf. simpl in Hf.
  assert (Hdia : (forall v : nat, Fnat_R n (n+5) v -> V v 0 = true -> False) -> False).
  { intro Habs.
    apply (Habs (n+4)).
    - unfold Fnat_R. split; lia.
    - unfold V. simpl. rewrite Nat.eqb_refl. reflexivity. }
  pose proof (Hf Hdia) as HBoxSn.
  specialize (HBoxSn (n+1) ltac:(unfold Fnat_R; split; lia)) as HD.
  apply HD.
  intros v Hv Hval.
  unfold Fnat_R in Hv. destruct Hv as [Hv1 Hv2].
  assert (Hve : v = n) by lia. subst v.
  unfold V in Hval. simpl in Hval.
  apply Nat.eqb_eq in Hval. lia.
Qed.


Definition Sum_R (F1 F2 : Frame) (n : nat) (w v : fW F1 + fW F2) : Prop :=
  match w, v with
  | inl a, inl b => fR F1 n a b
  | inr a, inr b => fR F2 n a b
  | _, _ => False
  end.


Lemma Sum_R_trans : forall F1 F2 n w v u,
  Sum_R F1 F2 n w v -> Sum_R F1 F2 n v u -> Sum_R F1 F2 n w u.
Proof.
  intros F1 F2 n [a|a] [b|b] [c|c] H1 H2; simpl in *; try contradiction.
  - exact (fR_trans F1 n a b c H1 H2).
  - exact (fR_trans F2 n a b c H1 H2).
Qed.


Lemma Sum_R_wf : forall F1 F2 n,
  well_founded (fun u v => Sum_R F1 F2 n v u).
Proof.
  intros F1 F2 n [a|a].
  - induction a as [a IHa] using (well_founded_induction (fR_wf F1 n)).
    apply Acc_intro. intros [b|b] H; simpl in H.
    + apply IHa. exact H.
    + contradiction.
  - induction a as [a IHa] using (well_founded_induction (fR_wf F2 n)).
    apply Acc_intro. intros [b|b] H; simpl in H.
    + contradiction.
    + apply IHa. exact H.
Qed.


Lemma Sum_R_mon : forall F1 F2 n w v,
  Sum_R F1 F2 (S n) w v -> Sum_R F1 F2 n w v.
Proof.
  intros F1 F2 n [a|a] [b|b] H; simpl in *; try contradiction.
  - exact (fR_mon F1 n a b H).
  - exact (fR_mon F2 n a b H).
Qed.


Lemma Sum_R_nextcon : forall F1 F2 n w v,
  Sum_R F1 F2 (S n) w v -> exists u, Sum_R F1 F2 n v u.
Proof.
  intros F1 F2 n [a|a] [b|b] H; simpl in *; try contradiction.
  - destruct (fR_nextcon F1 n a b H) as [u Hu]. exists (inl u). exact Hu.
  - destruct (fR_nextcon F2 n a b H) as [u Hu]. exists (inr u). exact Hu.
Qed.


Definition Frame_Sum (F1 F2 : Frame) : Frame :=
  mkFrame (fW F1 + fW F2) (Sum_R F1 F2)
    (Sum_R_trans F1 F2) (Sum_R_wf F1 F2)
    (Sum_R_mon F1 F2) (Sum_R_nextcon F1 F2).


Lemma forces_sum_left : forall F1 F2 V phi w,
  forces (Frame_Sum F1 F2) V (inl w) phi <->
  forces F1 (fun v p => V (inl v) p) w phi.
Proof.
  intros F1 F2 V phi.
  induction phi as [p | | X IHX Y IHY | n psi IHpsi]; intro w; simpl.
  - reflexivity.
  - reflexivity.
  - rewrite (IHX w), (IHY w). reflexivity.
  - split.
    + intros HBox v1 Hv1.
      pose proof (HBox (inl v1) Hv1) as Hf.
      rewrite IHpsi in Hf. exact Hf.
    + intros HBox v Hv.
      destruct v as [v1|v2].
      * simpl in Hv. rewrite IHpsi. apply HBox. exact Hv.
      * simpl in Hv. contradiction.
Qed.


Lemma forces_sum_right : forall F1 F2 V phi w,
  forces (Frame_Sum F1 F2) V (inr w) phi <->
  forces F2 (fun v p => V (inr v) p) w phi.
Proof.
  intros F1 F2 V phi.
  induction phi as [p | | X IHX Y IHY | n psi IHpsi]; intro w; simpl.
  - reflexivity.
  - reflexivity.
  - rewrite (IHX w), (IHY w). reflexivity.
  - split.
    + intros HBox v2 Hv2.
      pose proof (HBox (inr v2) Hv2) as Hf.
      rewrite IHpsi in Hf. exact Hf.
    + intros HBox v Hv.
      destruct v as [v1|v2].
      * simpl in Hv. contradiction.
      * simpl in Hv. rewrite IHpsi. apply HBox. exact Hv.
Qed.


Theorem sum_preserves_validity : forall F1 F2 phi,
  Valid phi ->
  forall V w, forces (Frame_Sum F1 F2) V w phi.
Proof.
  intros F1 F2 phi Hval V w.
  apply Hval.
Qed.


(** ** Finite frame property: F0 refutes [Box 0 Bot].

    [F0] (Boolean frame, two worlds) is a finite refuting frame for
    [Box 0 Bot]: not a theorem, not satisfied at any F0-world. *)

Theorem finite_frame_property_for_box0_bot :
  ~ |- Box 0 Bot.
Proof. exact (meta_consistency_every_level 0). Qed.



Theorem frame_conditions_independent :
  (exists Rt : nat -> nat -> nat -> Prop,
    (forall n, well_founded (fun u v => Rt n v u)) /\
    (forall n w v, Rt (S n) w v -> Rt n w v) /\
    (forall n w v, Rt (S n) w v -> exists u, Rt n v u) /\
    ~ (forall n w v u, Rt n w v -> Rt n v u -> Rt n w u)) /\
  (exists Rt : nat -> nat -> nat -> Prop,
    (forall n w v u, Rt n w v -> Rt n v u -> Rt n w u) /\
    (forall n w v, Rt (S n) w v -> Rt n w v) /\
    (forall n w v, Rt (S n) w v -> exists u, Rt n v u) /\
    ~ (forall n, well_founded (fun u v => Rt n v u))) /\
  (exists Rt : nat -> nat -> nat -> Prop,
    (forall n w v u, Rt n w v -> Rt n v u -> Rt n w u) /\
    (forall n, well_founded (fun u v => Rt n v u)) /\
    (forall n w v, Rt (S n) w v -> exists u, Rt n v u) /\
    ~ (forall n w v, Rt (S n) w v -> Rt n w v)) /\
  (exists Rt : nat -> nat -> nat -> Prop,
    (forall n w v u, Rt n w v -> Rt n v u -> Rt n w u) /\
    (forall n, well_founded (fun u v => Rt n v u)) /\
    (forall n w v, Rt (S n) w v -> Rt n w v) /\
    ~ (forall n w v, Rt (S n) w v -> exists u, Rt n v u)).
Proof.
  exact (conj frame_indep_trans
        (conj frame_indep_wf
        (conj frame_indep_mon frame_indep_nc))).
Qed.


Theorem alpha_equivalence_decidable : forall (f g : QForm), {f = g} + {f <> g}.
Proof. exact QForm_eq_dec. Qed.


Theorem nnf_correct : forall phi,
  (|- Iff (nnf_pos phi) phi) /\ (|- Iff (nnf_neg phi) (Neg phi)).
Proof.
  induction phi as [p | | X IHX Y IHY | n X IHX].
  - cbn. split; apply prov_iff_refl.
  - cbn. split.
    + apply prov_iff_refl.
    + apply prov_and_intro_meta.
      * apply prov_weaken. apply prov_id.
      * apply prov_weaken. apply prov_id.
  - destruct IHX as [IHXp IHXn]. destruct IHY as [IHYp IHYn].
    cbn. split.
    + pose proof (prov_or_neg_iff_impl X Y) as HOI.
      pose proof (prov_equiv_impl_cong _ _ _ _ IHXn IHYp) as Hcong.
      assert (Hor_eq : prov_equiv (Or (nnf_neg X) (nnf_pos Y)) (Or (Neg X) Y)).
      { unfold Or. unfold prov_equiv in Hcong |- *.
        apply prov_equiv_impl_cong; [|exact IHYp].
        apply prov_equiv_impl_cong; [|apply prov_iff_refl].
        exact IHXn. }
      unfold prov_equiv in Hor_eq.
      exact (prov_equiv_trans _ _ _ Hor_eq HOI).
    + pose proof (prov_and_neg_iff_neg_impl X Y) as HAI.
      assert (Hand_eq : prov_equiv (And (nnf_pos X) (nnf_neg Y)) (And X (Neg Y))).
      { unfold And, Neg. unfold prov_equiv.
        apply prov_equiv_impl_cong; [|apply prov_iff_refl].
        apply prov_equiv_impl_cong; [exact IHXp|].
        apply prov_equiv_impl_cong; [exact IHYn| apply prov_iff_refl]. }
      unfold prov_equiv in Hand_eq.
      exact (prov_equiv_trans _ _ _ Hand_eq HAI).
  - destruct IHX as [IHXp IHXn]. cbn. split.
    + apply prov_equiv_box_cong. exact IHXp.
    + pose proof (prov_neg_box_iff_diamond n X) as HBD.
      assert (Hd_eq : prov_equiv (Diamond n (nnf_neg X)) (Diamond n (Neg X))).
      { unfold Diamond. unfold prov_equiv.
        apply prov_equiv_impl_cong; [|apply prov_iff_refl].
        apply prov_equiv_box_cong.
        apply prov_equiv_impl_cong; [exact IHXn|apply prov_iff_refl]. }
      unfold prov_equiv in Hd_eq.
      exact (prov_equiv_trans _ _ _ Hd_eq HBD).
Qed.

