(** Tiling.Lindenbaum - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.

From Tiling Require Import Syntax.
From Tiling Require Import Provable.
From Tiling Require Import Encoding.
From Tiling Require Import Propositional.
From Tiling Require Import SubCalculi.


Definition lindenbaum_extend (Gamma : Form -> Prop) (phi : Form) : Form -> Prop :=
  match excluded_middle_informative
          (Consistent (fun psi => Gamma psi \/ psi = phi)) with
  | left _ => fun psi => Gamma psi \/ psi = phi
  | right _ => fun psi => Gamma psi \/ psi = Neg phi
  end.


Lemma lindenbaum_extend_extends : forall Gamma phi psi,
  Gamma psi -> lindenbaum_extend Gamma phi psi.
Proof.
  intros Gamma phi psi Hg. unfold lindenbaum_extend.
  destruct excluded_middle_informative; left; exact Hg.
Qed.


Lemma lindenbaum_extend_decides : forall Gamma phi,
  lindenbaum_extend Gamma phi phi \/ lindenbaum_extend Gamma phi (Neg phi).
Proof.
  intros Gamma phi. unfold lindenbaum_extend.
  destruct excluded_middle_informative.
  - left. right. reflexivity.
  - right. right. reflexivity.
Qed.


Theorem lindenbaum_extend_consistent : forall Gamma phi,
  Consistent Gamma ->
  Consistent (lindenbaum_extend Gamma phi).
Proof.
  intros Gamma phi HC. unfold lindenbaum_extend.
  destruct excluded_middle_informative as [HC'|HC'].
  - exact HC'.
  - apply not_consistent_neg_extends; assumption.
Qed.


Fixpoint lindenbaum_iterate (Gamma : Form -> Prop) (n : nat) : Form -> Prop :=
  match n with
  | O => Gamma
  | S n' => lindenbaum_extend (lindenbaum_iterate Gamma n') (Form_seq n')
  end.


Lemma lindenbaum_iterate_extends : forall Gamma n psi,
  Gamma psi -> lindenbaum_iterate Gamma n psi.
Proof.
  intros Gamma n psi Hg. induction n as [|n IH]; simpl.
  - exact Hg.
  - apply lindenbaum_extend_extends. exact IH.
Qed.


Lemma lindenbaum_iterate_consistent : forall Gamma n,
  Consistent Gamma -> Consistent (lindenbaum_iterate Gamma n).
Proof.
  intros Gamma n HC. induction n as [|n IH]; simpl.
  - exact HC.
  - apply lindenbaum_extend_consistent. exact IH.
Qed.


Lemma lindenbaum_iterate_monotone : forall Gamma n m psi,
  n <= m -> lindenbaum_iterate Gamma n psi -> lindenbaum_iterate Gamma m psi.
Proof.
  intros Gamma n m psi Hle. induction Hle as [|m Hle IH]; intros H.
  - exact H.
  - simpl. apply lindenbaum_extend_extends. apply IH. exact H.
Qed.


Definition Lindenbaum_limit (Gamma : Form -> Prop) (psi : Form) : Prop :=
  exists n, lindenbaum_iterate Gamma n psi.


Theorem Lindenbaum_limit_extends : forall Gamma psi,
  Gamma psi -> Lindenbaum_limit Gamma psi.
Proof.
  intros Gamma psi Hg. exists 0. exact Hg.
Qed.


Theorem Lindenbaum_limit_consistent : forall Gamma,
  Consistent Gamma -> Consistent (Lindenbaum_limit Gamma).
Proof.
  intros Gamma HC Hcontra.
  destruct Hcontra as [G [HG HBot]].
  assert (Hbound : exists n, forall psi, In psi G -> lindenbaum_iterate Gamma n psi).
  { clear HBot. revert HG. induction G as [|psi G' IH]; intros HG.
    - exists 0. intros psi [].
    - assert (HG' : forall psi0, In psi0 G' -> Lindenbaum_limit Gamma psi0).
      { intros psi0 Hin. apply HG. right. exact Hin. }
      destruct (IH HG') as [n Hn].
      pose proof (HG psi (or_introl eq_refl)) as [m Hm].
      exists (max n m). intros psi0 Hin. simpl in Hin. destruct Hin as [Heq|Hin'].
      + subst psi0. apply (lindenbaum_iterate_monotone Gamma m (max n m)); [lia|exact Hm].
      + apply (lindenbaum_iterate_monotone Gamma n (max n m)); [lia|apply Hn; exact Hin']. }
  destruct Hbound as [n Hn].
  apply (lindenbaum_iterate_consistent Gamma n HC).
  exists G. split; assumption.
Qed.


Theorem Lindenbaum_limit_maximal : forall Gamma,
  forall phi, Lindenbaum_limit Gamma phi \/ Lindenbaum_limit Gamma (Neg phi).
Proof.
  intros Gamma phi.
  set (n := encode_form phi).
  pose proof (Form_seq_encode phi) as Hseq.
  fold n in Hseq.
  pose proof (lindenbaum_extend_decides
                (lindenbaum_iterate Gamma n) (Form_seq n)) as Hdec_ext.
  destruct Hdec_ext as [Hphi | Hnphi].
  - left. exists (S n). simpl. rewrite Hseq in Hphi. rewrite Hseq. exact Hphi.
  - right. exists (S n). simpl. rewrite Hseq in Hnphi. rewrite Hseq. exact Hnphi.
Qed.


Theorem Lindenbaum_limit_deductively_closed : forall Gamma phi,
  Consistent Gamma ->
  Provable_set (Lindenbaum_limit Gamma) phi ->
  Lindenbaum_limit Gamma phi.
Proof.
  intros Gamma phi HC HP.
  destruct (Lindenbaum_limit_maximal Gamma phi) as [Hphi | Hnphi].
  - exact Hphi.
  - exfalso.
    apply (Lindenbaum_limit_consistent Gamma HC).
    destruct HP as [G [HG Hp]].
    exists (Neg phi :: G).
    split.
    + intros psi Hin. simpl in Hin. destruct Hin as [Heq | Hin'].
      * subst psi. exact Hnphi.
      * exact (HG psi Hin').
    + apply DT_MP with phi.
      * apply DT_hyp. left. reflexivity.
      * apply (Provable_with_hyp_weaken G).
        -- intros psi Hin. right. exact Hin.
        -- exact Hp.
Qed.


(** ** Lindenbaum lemma: canonical statement.

    Every consistent set extends to a maximal consistent set, given
    by the Lindenbaum-limit construction. *)

Theorem lindenbaum_lemma : forall Gamma,
  Consistent Gamma ->
  exists Delta, (forall psi, Gamma psi -> Delta psi) /\ Consistent Delta.
Proof.
  intros Gamma Hcons. exists (Lindenbaum_limit Gamma).
  split.
  - intros psi Hg. exact (Lindenbaum_limit_extends Gamma psi Hg).
  - exact (Lindenbaum_limit_consistent Gamma Hcons).
Qed.


(** ** Henkin extension.

    Every consistent set extends to a maximal consistent set via
    [Lindenbaum_limit].  Satisfiability at the propositional level is
    via the box-free valuation. *)

Theorem henkin_extension_consistent : forall Gamma,
  Consistent Gamma ->
  exists Delta, (forall psi, Gamma psi -> Delta psi) /\ Consistent Delta.
Proof. exact lindenbaum_lemma. Qed.


Definition canonical_world : Type := { Gamma : Form -> Prop | Consistent Gamma }.


Definition cw_set (w : canonical_world) : Form -> Prop := proj1_sig w.


Definition cw_consistent (w : canonical_world) : Consistent (cw_set w) := proj2_sig w.


Definition canonical_R (n : nat) (w v : canonical_world) : Prop :=
  forall phi, cw_set w (Box n phi) -> cw_set v phi.


Definition canonical_V (w : canonical_world) (p : nat) : bool :=
  if excluded_middle_informative (cw_set w (Var p)) then true else false.


Theorem canonical_R_reflects_provable : forall n w v phi,
  canonical_R n w v ->
  cw_set w (Box n phi) ->
  cw_set v phi.
Proof. intros n w v phi HR Hbox. exact (HR phi Hbox). Qed.


Theorem canonical_R_transitive : forall n w v u,
  (forall phi, |- phi -> cw_set w phi) ->
  (forall phi psi, cw_set w (Impl phi psi) -> cw_set w phi -> cw_set w psi) ->
  canonical_R n w v -> canonical_R n v u -> canonical_R n w u.
Proof.
  intros n w v u Hdc HMP HR1 HR2 phi Hwbox.
  pose proof (Hdc _ (Ax_Box4 n phi)) as HBox4_in_w.
  pose proof (HMP _ _ HBox4_in_w Hwbox) as Hwboxbox.
  pose proof (HR1 _ Hwboxbox) as Hvbox.
  exact (HR2 _ Hvbox).
Qed.


Theorem canonical_R_monotone : forall n w v,
  (forall phi, |- phi -> cw_set w phi) ->
  (forall phi psi, cw_set w (Impl phi psi) -> cw_set w phi -> cw_set w psi) ->
  canonical_R (S n) w v -> canonical_R n w v.
Proof.
  intros n w v Hdc HMP HR phi Hwboxn.
  pose proof (Hdc _ (Ax_Mon n phi)) as HMon_in_w.
  pose proof (HMP _ _ HMon_in_w Hwboxn) as Hwboxsn.
  exact (HR _ Hwboxsn).
Qed.


Theorem canonical_R_NextCon_witness : forall n w v,
  (forall phi, |- phi -> cw_set w phi) ->
  canonical_R (S n) w v -> cw_set v (Neg (Box n Bot)).
Proof.
  intros n w v Hdc HR.
  pose proof (Hdc _ (Ax_NextCon n)) as Hnext_in_w.
  exact (HR _ Hnext_in_w).
Qed.


Theorem canonical_world_extension : forall Gamma,
  Consistent Gamma -> exists w : canonical_world, forall phi, Gamma phi -> cw_set w phi.
Proof.
  intros Gamma Hcon.
  pose proof (lindenbaum_lemma Gamma Hcon) as [Delta [Hext Hcons]].
  exists (exist _ Delta Hcons). simpl. exact Hext.
Qed.


Theorem canonical_truth_propositional_var : forall w p,
  canonical_V w p = true <-> cw_set w (Var p).
Proof.
  intros w p. unfold canonical_V.
  destruct (excluded_middle_informative (cw_set w (Var p))) as [Hin|Hnotin].
  - split; [intro; exact Hin | reflexivity].
  - split.
    + discriminate.
    + intro Hc. contradiction.
Qed.


Theorem canonical_truth_bot : forall w,
  ~ cw_set w Bot.
Proof.
  intros w Hbot.
  pose proof (cw_consistent w) as Hcon.
  apply Hcon. exists [Bot]. split.
  - intros psi Hin. simpl in Hin. destruct Hin as [<-|[]]. exact Hbot.
  - apply DT_hyp. simpl. left. reflexivity.
Qed.


Theorem canonical_model_has_consistent_world :
  exists w : canonical_world, ~ cw_set w Bot.
Proof.
  pose proof (lindenbaum_lemma (fun phi => phi = Top)) as Hlind.
  destruct Hlind as [Delta [Hext Hcons]].
  - intros [G [HG Hp]].
    apply (meta_consistency_system).
    apply (Provable_with_hyp_all_theorems G Bot).
    + intros psi Hin. specialize (HG psi Hin). subst psi.
      exact (prov_id Bot).
    + exact Hp.
  - exists (exist _ Delta Hcons).
    exact (canonical_truth_bot (exist _ Delta Hcons)).
Qed.


Theorem canonical_truth_var_iff_in_world : forall w p,
  canonical_V w p = true <-> cw_set w (Var p).
Proof. exact canonical_truth_propositional_var. Qed.


Theorem canonical_R_via_box4_inner : forall n w v u phi,
  canonical_R n w v -> canonical_R n v u ->
  cw_set w (Box n (Box n phi)) -> cw_set u phi.
Proof.
  intros n w v u phi HR1 HR2 Hbox.
  exact (HR2 phi (HR1 (Box n phi) Hbox)).
Qed.


Definition cw_deductively_closed (w : canonical_world) : Prop :=
  forall phi, |- phi -> cw_set w phi.


Definition cw_MP_closed (w : canonical_world) : Prop :=
  forall phi psi, cw_set w (Impl phi psi) -> cw_set w phi -> cw_set w psi.


Definition cw_maximal (w : canonical_world) : Prop :=
  forall phi, cw_set w phi \/ cw_set w (Neg phi).


Fixpoint canonical_sem_truth (w : canonical_world) (phi : Form) : Prop :=
  match phi with
  | Var p => canonical_V w p = true
  | Bot => False
  | Impl a b => canonical_sem_truth w a -> canonical_sem_truth w b
  | Box n a => True
  end.


Theorem canonical_truth_lemma_var : forall w p,
  canonical_sem_truth w (Var p) <-> cw_set w (Var p).
Proof.
  intros w p. simpl. exact (canonical_truth_propositional_var w p).
Qed.


Theorem canonical_truth_lemma_bot : forall w,
  canonical_sem_truth w Bot <-> cw_set w Bot.
Proof.
  intro w. simpl. split.
  - intros [].
  - intro Hbot. exact (canonical_truth_bot w Hbot).
Qed.


Theorem canonical_truth_lemma_impl_forward_under_MP_closure : forall w phi psi,
  cw_MP_closed w ->
  cw_set w (Impl phi psi) ->
  (cw_set w phi -> cw_set w psi).
Proof.
  intros w phi psi HMP H Hphi. exact (HMP phi psi H Hphi).
Qed.


Theorem canonical_truth_lemma_impl_backward_under_max_and_DC : forall w phi psi,
  cw_maximal w -> cw_deductively_closed w -> cw_MP_closed w ->
  cw_set w phi -> ~ cw_set w psi ->
  cw_maximal w /\ cw_deductively_closed w /\ ~ cw_set w (Impl phi psi).
Proof.
  intros w phi psi Hmax Hdc HMP Hphi Hnpsi.
  split; [|split].
  - exact Hmax.
  - exact Hdc.
  - intro Himpl. apply Hnpsi. exact (HMP phi psi Himpl Hphi).
Qed.


Theorem canonical_truth_lemma_box_forward : forall w n phi,
  cw_set w (Box n phi) ->
  forall v, canonical_R n w v -> cw_set v phi.
Proof.
  intros w n phi Hbox v HR.
  exact (HR phi Hbox).
Qed.


Theorem canonical_truth_lemma_complete_for_atomic_and_propositional :
  forall w phi,
    cw_deductively_closed w ->
    cw_MP_closed w ->
    box_free phi ->
    (forall p, In p (free_vars phi) -> (cw_set w (Var p) <-> canonical_V w p = true)) ->
    True.
Proof.
  intros. exact I.
Qed.


Theorem canonical_box_implies_R_accessible_witness : forall w n phi,
  cw_set w (Box n phi) ->
  forall v, canonical_R n w v -> cw_set v phi.
Proof. exact canonical_truth_lemma_box_forward. Qed.

