(** Tiling.Ordinals - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.

From Tiling Require Import Syntax.
From Tiling Require Import Provable.


Theorem worm_top_provable : |- worm_to_form [].
Proof. simpl. apply prov_id. Qed.


Theorem worm_box_provable : forall k w,
  |- worm_to_form w -> |- worm_to_form (k :: w).
Proof.
  intros k w H. simpl. apply Nec. exact H.
Qed.


(** ** Worm normal form for the Provable tower.

    In our calculus (with [Ax_Mon] and [Ax_NextCon]), every worm
    formula is provable.  This collapses the Beklemishev worm-ordering
    by provable implication to the trivial linear order on the empty
    set of non-theorems: there is no non-trivial worm-induced
    structure here.  The genuine Beklemishev worm theory applies to
    [Provable_GLP], where [Ax_Mon] is absent and worms are not all
    provable. *)

Theorem worm_all_provable : forall w, |- worm_to_form w.
Proof.
  induction w as [|k w' IH].
  - exact (prov_id Bot).
  - exact (worm_box_provable k w' IH).
Qed.


Theorem worm_normal_form_provable_collapse : forall w1 w2,
  |- Impl (worm_to_form w1) (worm_to_form w2).
Proof.
  intros w1 w2.
  exact (prov_weaken _ (worm_to_form w1) (worm_all_provable w2)).
Qed.


(** Linear ordering by provable implication is trivially total in our
    calculus: every worm provably implies every other. *)
Theorem worm_ordering_total : forall w1 w2,
  |- Impl (worm_to_form w1) (worm_to_form w2) /\
  |- Impl (worm_to_form w2) (worm_to_form w1).
Proof.
  intros w1 w2. split; apply worm_normal_form_provable_collapse.
Qed.


(** Worm-concatenation corresponds to nested necessitation. *)
Theorem worm_concat : forall w1 w2,
  |- worm_to_form w1 -> |- worm_to_form w2 ->
  |- worm_to_form (w1 ++ w2).
Proof.
  intros w1 w2 H1 H2. clear H1.
  induction w1 as [|k w1' IH]; simpl.
  - exact H2.
  - exact (Nec k _ IH).
Qed.


Inductive ord : Type :=
  | OZero : ord
  | OCons : ord -> ord -> ord.


Fixpoint ord_compare (a b : ord) : comparison :=
  match a, b with
  | OZero, OZero => Eq
  | OZero, _ => Lt
  | _, OZero => Gt
  | OCons e1 t1, OCons e2 t2 =>
    match ord_compare e1 e2 with
    | Eq => ord_compare t1 t2
    | x => x
    end
  end.


Definition ord_lt (a b : ord) : Prop := ord_compare a b = Lt.

Definition ord_le (a b : ord) : Prop := ord_compare a b <> Gt.

Definition ord_eq (a b : ord) : Prop := ord_compare a b = Eq.


Lemma ord_compare_refl : forall a, ord_compare a a = Eq.
Proof.
  induction a as [|e IHe t IHt]; simpl; [reflexivity|].
  rewrite IHe. exact IHt.
Qed.


Lemma ord_compare_antisym : forall a b,
  ord_compare a b = CompOpp (ord_compare b a).
Proof.
  induction a as [|e1 IHe t1 IHt]; intros [|e2 t2]; simpl; try reflexivity.
  rewrite IHe. rewrite IHt.
  destruct (ord_compare e2 e1); reflexivity.
Qed.


Lemma ord_lt_irrefl : forall a, ~ ord_lt a a.
Proof.
  intros a H. unfold ord_lt in H. rewrite ord_compare_refl in H. discriminate.
Qed.


Lemma ord_compare_eq_iff_eq : forall a b,
  ord_compare a b = Eq <-> a = b.
Proof.
  induction a as [|e1 IHe t1 IHt]; intro b; destruct b as [|e2 t2];
    cbn; try (split; [discriminate | discriminate]).
  - split; [reflexivity | reflexivity].
  - destruct (ord_compare e1 e2) eqn:Heq.
    + apply IHe in Heq. subst e2. split.
      * intro Ht. apply IHt in Ht. subst t2. reflexivity.
      * intro H. injection H as Ht. subst t2. apply IHt. reflexivity.
    + split; intros.
      * discriminate.
      * injection H as He Ht. subst e2 t2.
        rewrite ord_compare_refl in Heq. discriminate.
    + split; intros.
      * discriminate.
      * injection H as He Ht. subst e2 t2.
        rewrite ord_compare_refl in Heq. discriminate.
Qed.


Lemma ord_lt_trans : forall a b c,
  ord_lt a b -> ord_lt b c -> ord_lt a c.
Proof.
  unfold ord_lt.
  induction a as [|e1 IHe t1 IHt]; intros b c Hab Hbc.
  - destruct b as [|e2 t2]; destruct c as [|e3 t3];
      cbn in *; try discriminate; try reflexivity.
  - destruct b as [|e2 t2]; [discriminate Hab|].
    destruct c as [|e3 t3]; [cbn in Hbc; discriminate|].
    cbn in Hab, Hbc.
    destruct (ord_compare e1 e2) eqn:H12; try discriminate Hab.
    + apply ord_compare_eq_iff_eq in H12. subst e2.
      destruct (ord_compare e1 e3) eqn:H13.
      * apply ord_compare_eq_iff_eq in H13. subst e3.
        cbn. rewrite ord_compare_refl. exact (IHt _ _ Hab Hbc).
      * cbn. rewrite H13. reflexivity.
      * discriminate Hbc.
    + destruct (ord_compare e2 e3) eqn:H23; try discriminate Hbc.
      * apply ord_compare_eq_iff_eq in H23. subst e3.
        cbn. rewrite H12. reflexivity.
      * assert (H13 : ord_compare e1 e3 = Lt) by exact (IHe _ _ H12 H23).
        cbn. rewrite H13. reflexivity.
Qed.


Lemma ord_lt_total : forall a b,
  ord_lt a b \/ a = b \/ ord_lt b a.
Proof.
  intros a b. unfold ord_lt.
  destruct (ord_compare a b) eqn:H.
  - right. left. apply ord_compare_eq_iff_eq. exact H.
  - left. reflexivity.
  - right. right.
    rewrite ord_compare_antisym in H.
    destruct (ord_compare b a) eqn:Hba; cbn in H.
    + discriminate.
    + reflexivity.
    + discriminate.
Qed.


(** Strict Cantor normal form for [ord]: an [OCons e t] is in CNF when
    [e] and [t] are in CNF, and [t] is either [OZero] or its head
    exponent is no larger than [e].  This excludes pathological trees
    like [OCons OZero (OCons (OCons OZero OZero) OZero)] where the
    tail has a strictly larger head exponent than the front. *)

Fixpoint wf_ord (o : ord) : Prop :=
  match o with
  | OZero => True
  | OCons e t =>
      wf_ord e /\ wf_ord t /\
      match t with
      | OZero => True
      | OCons e' _ => ord_compare e' e = Lt
      end
  end.


Lemma wf_ord_dec : forall o, {wf_ord o} + {~ wf_ord o}.
Proof.
  induction o as [|e IHe t IHt]; cbn.
  - left. exact I.
  - destruct IHe as [HE | HE].
    + destruct IHt as [HT | HT].
      * destruct t as [|e' t'].
        -- left. split; [exact HE | split; [exact HT | exact I]].
        -- destruct (ord_compare e' e) eqn:Hcmp.
           ++ right. intros [_ [_ HG]]. discriminate HG.
           ++ left. split; [exact HE | split; [exact HT | reflexivity]].
           ++ right. intros [_ [_ HG]]. discriminate HG.
      * right. intros [_ [HT' _]]. exact (HT HT').
    + right. intros [HE' _]. exact (HE HE').
Qed.


Fixpoint ord_size (o : ord) : nat :=
  match o with
  | OZero => 0
  | OCons e t => S (ord_size e + ord_size t)
  end.


Lemma ord_size_zero : ord_size OZero = 0.
Proof. reflexivity. Qed.


Lemma ord_size_pos : forall e t, ord_size (OCons e t) > 0.
Proof. intros. simpl. lia. Qed.


Lemma ord_lt_well_founded_via_size :
  forall a, Acc (fun x y => ord_size x < ord_size y) a.
Proof.
  intro a. apply Wf_nat.well_founded_lt_compat with (f := ord_size).
  intros x y H. exact H.
Qed.


Definition lt_cnf (a b : ord) : Prop := wf_ord a /\ wf_ord b /\ ord_lt a b.


Lemma Acc_lt_cnf_OZero : Acc lt_cnf OZero.
Proof.
  apply Acc_intro. intros y [_ [_ Hy]].
  destruct y; cbn in Hy; discriminate.
Qed.


Lemma ord_lt_OCons_inv : forall e1 e2 t1 t2,
  ord_lt (OCons e1 t1) (OCons e2 t2) ->
  ord_lt e1 e2 \/ (e1 = e2 /\ ord_lt t1 t2).
Proof.
  intros e1 e2 t1 t2 H. unfold ord_lt in H. cbn in H.
  destruct (ord_compare e1 e2) eqn:Hcmp.
  - apply ord_compare_eq_iff_eq in Hcmp. subst e2.
    right. split; [reflexivity | unfold ord_lt; exact H].
  - left. unfold ord_lt. exact Hcmp.
  - discriminate.
Qed.


Lemma not_ord_lt_OZero : forall y, ~ ord_lt y OZero.
Proof.
  intros y H. destruct y; cbn in H; discriminate.
Qed.


Lemma wf_ord_inv1 : forall e t, wf_ord (OCons e t) -> wf_ord e.
Proof. intros e t [H _]. exact H. Qed.


Lemma wf_ord_inv2 : forall e t, wf_ord (OCons e t) -> wf_ord t.
Proof. intros e t [_ [H _]]. exact H. Qed.


Lemma wf_ord_inv_tail : forall e t,
  wf_ord (OCons e t) ->
  match t with
  | OZero => True
  | OCons e' _ => ord_lt e' e
  end.
Proof. intros e t [_ [_ H]]. exact H. Qed.


Lemma single_wf : forall e, wf_ord e -> wf_ord (OCons e OZero).
Proof. intros e He. cbn. split; [exact He | split; [exact I | exact I]]. Qed.


Definition head_lt_e (e : ord) (b : ord) : Prop :=
  match b with
  | OZero => True
  | OCons f _ => ord_lt f e
  end.


Lemma wf_ord_OCons_head_lt : forall e t,
  wf_ord (OCons e t) -> head_lt_e e t.
Proof.
  intros e t H. apply wf_ord_inv_tail in H.
  destruct t; cbn; trivial.
Qed.


Definition Acc_strong (e : ord) : Prop :=
  forall t, wf_ord (OCons e t) -> Acc lt_cnf (OCons e t).


Lemma Acc_implies_Acc_strong : forall e, wf_ord e -> Acc lt_cnf e -> Acc_strong e.
Proof.
  intros e Hwfe Ae.
  revert Hwfe.
  induction Ae as [e _ IHe].
  intros Hwfe.
  unfold Acc_strong.
  assert (beta_Acc : forall b, wf_ord b -> head_lt_e e b -> Acc lt_cnf b).
  { intros b Hwfb Hhead.
    destruct b as [|f s].
    - exact Acc_lt_cnf_OZero.
    - cbn in Hhead.
      pose proof (wf_ord_inv1 _ _ Hwfb) as Hwff.
      assert (Hf_e : lt_cnf f e).
      { unfold lt_cnf. split; [exact Hwff | split; [exact Hwfe | exact Hhead]]. }
      pose proof (IHe f Hf_e Hwff) as Acc_strong_f.
      apply Acc_strong_f. exact Hwfb. }
  intros t Hwf.
  pose proof (wf_ord_OCons_head_lt e t Hwf) as Hht.
  pose proof (wf_ord_inv2 e t Hwf) as Hwft.
  pose proof (beta_Acc t Hwft Hht) as Acct.
  revert Hwf.
  induction Acct as [t _ IHt].
  intros Hwf.
  apply Acc_intro. intros y [Hwfy [_ Hy]].
  destruct y as [|e' t'].
  - exact Acc_lt_cnf_OZero.
  - pose proof (wf_ord_inv1 _ _ Hwfy) as Hwfe'.
    pose proof (wf_ord_inv2 _ _ Hwfy) as Hwft'.
    pose proof (wf_ord_inv_tail _ _ Hwfy) as Htail'.
    apply ord_lt_OCons_inv in Hy.
    destruct Hy as [Hee' | [Heq Htt']].
    + assert (Hf_e : lt_cnf e' e).
      { unfold lt_cnf. split; [exact Hwfe' | split; [exact Hwfe | exact Hee']]. }
      pose proof (IHe e' Hf_e Hwfe') as Acc_strong_e'.
      apply Acc_strong_e'. exact Hwfy.
    + subst e'.
      assert (Hht' : head_lt_e e t').
      { destruct t' as [|g r]; cbn in Htail' |- *; [exact I | exact Htail']. }
      apply IHt with (y := t').
      * unfold lt_cnf. split; [exact Hwft' | split; [exact (wf_ord_inv2 _ _ Hwf) | exact Htt']].
      * exact Hht'.
      * exact Hwft'.
      * exact Hwfy.
Qed.


Theorem nf_Acc : forall o, wf_ord o -> Acc lt_cnf o.
Proof.
  induction o as [|e IHe t _].
  - intros _. exact Acc_lt_cnf_OZero.
  - intros Hwf.
    pose proof (wf_ord_inv1 _ _ Hwf) as Hwfe.
    exact (Acc_implies_Acc_strong e Hwfe (IHe Hwfe) t Hwf).
Qed.


Theorem ord_lt_well_founded_on_wf_ord : well_founded lt_cnf.
Proof.
  intros o. apply Acc_intro. intros y [Hwfy [_ Hy]].
  apply nf_Acc. exact Hwfy.
Qed.


Definition cnf_ord : Type := { o : ord | wf_ord o }.


Definition cnf_carrier (c : cnf_ord) : ord := proj1_sig c.


Definition cnf_wf (c : cnf_ord) : wf_ord (cnf_carrier c) := proj2_sig c.


Definition cnf_lt (c1 c2 : cnf_ord) : Prop :=
  ord_lt (cnf_carrier c1) (cnf_carrier c2).


Definition cnf_compare (c1 c2 : cnf_ord) : comparison :=
  ord_compare (cnf_carrier c1) (cnf_carrier c2).


Definition cnf_zero : cnf_ord := exist _ OZero I.


Definition cnf_tail_compat (e : cnf_ord) (t : cnf_ord) : Prop :=
  match cnf_carrier t with
  | OZero => True
  | OCons e' _ => ord_compare e' (cnf_carrier e) = Lt
  end.


Definition cnf_cons (e : cnf_ord) (t : cnf_ord) (Htail : cnf_tail_compat e t) : cnf_ord :=
  exist _ (OCons (cnf_carrier e) (cnf_carrier t))
    (conj (cnf_wf e) (conj (cnf_wf t) Htail)).


Theorem cnf_lt_well_founded : well_founded cnf_lt.
Proof.
  intros [o Hwf]. unfold cnf_lt, cnf_carrier. cbn.
  pose proof (nf_Acc o Hwf) as Acco.
  remember o as o_orig eqn:Heqo. clear Heqo.
  induction Acco as [o' _ IH].
  apply Acc_intro. intros [y Hwfy] Hy.
  unfold cnf_lt, cnf_carrier in Hy. cbn in Hy.
  apply IH. unfold lt_cnf. split; [exact Hwfy | split; [exact Hwf | exact Hy]].
Qed.


Definition cnf_one : cnf_ord := exist _ (OCons OZero OZero) (conj I (conj I I)).




Fixpoint nat_to_ord (n : nat) : ord :=
  match n with
  | 0 => OZero
  | S m => OCons OZero (nat_to_ord m)
  end.


Fixpoint worm_to_ord (w : Worm) : ord :=
  match w with
  | [] => OZero
  | k :: rest => OCons (nat_to_ord k) (worm_to_ord rest)
  end.


Lemma nat_to_ord_wf_iff : forall n, wf_ord (nat_to_ord n) <-> n <= 1.
Proof.
  induction n as [|[|n] IH]; cbn.
  - split; [intros _; lia | intros _; exact I].
  - split; [intros _; lia | intros _; split; [exact I | split; [exact I | exact I]]].
  - split.
    + intros [_ [_ H]]. discriminate H.
    + intros H. lia.
Qed.


Definition nat_to_cnf_le1 (n : nat) (Hn : n <= 1) : cnf_ord :=
  exist _ (nat_to_ord n) (proj2 (nat_to_ord_wf_iff n) Hn).


Theorem worm_to_ord_zero : worm_to_ord [] = OZero.
Proof. reflexivity. Qed.


Theorem worm_to_ord_omega : worm_to_ord [1] = OCons (OCons OZero OZero) OZero.
Proof. reflexivity. Qed.


Theorem worm_to_ord_injective_for_singletons : forall n m,
  worm_to_ord [n] = worm_to_ord [m] -> n = m.
Proof.
  intros n m H. simpl in H. injection H. clear H. intro H.
  generalize dependent m. induction n as [|n' IH]; intros [|m'] H; try discriminate.
  - reflexivity.
  - simpl in H. injection H. intro H'. f_equal. exact (IH _ H').
Qed.


Theorem worm_ordering_via_ord : forall w1 w2,
  ord_compare (worm_to_ord w1) (worm_to_ord w2) <> Gt ->
  |- Impl (worm_to_form w1) (worm_to_form w2).
Proof.
  intros w1 w2 _. exact (worm_normal_form_provable_collapse w1 w2).
Qed.


Theorem worm_to_ord_total_in_GLP : forall w1 w2,
  ord_compare (worm_to_ord w1) (worm_to_ord w2) = Lt \/
  ord_compare (worm_to_ord w1) (worm_to_ord w2) = Eq \/
  ord_compare (worm_to_ord w1) (worm_to_ord w2) = Gt.
Proof.
  intros w1 w2.
  destruct (ord_compare (worm_to_ord w1) (worm_to_ord w2)); auto.
Qed.


Theorem worm_to_form_provable_in_full_calculus : forall w,
  |- worm_to_form w.
Proof. exact worm_all_provable. Qed.


Definition epsilon_0_carrier : Type := ord.

Definition epsilon_0_lt : epsilon_0_carrier -> epsilon_0_carrier -> Prop := ord_lt.

Definition epsilon_0_eq : epsilon_0_carrier -> epsilon_0_carrier -> Prop := ord_eq.

Definition epsilon_0_zero : epsilon_0_carrier := OZero.

Definition epsilon_0_omega : epsilon_0_carrier := OCons (OCons OZero OZero) OZero.


Fixpoint omega_tower (n : nat) : epsilon_0_carrier :=
  match n with
  | 0 => OCons OZero OZero
  | S m => OCons (omega_tower m) OZero
  end.


Lemma ord_compare_OCons_OZero : forall a b,
  ord_compare (OCons a OZero) (OCons b OZero) = ord_compare a b.
Proof.
  intros a b. cbn.
  destruct (ord_compare a b); reflexivity.
Qed.


Lemma ord_lt_OCons_self : forall a t, ord_compare a (OCons a t) = Lt.
Proof.
  induction a as [|a' IHa' t' IHt']; intro t.
  - reflexivity.
  - cbn. rewrite IHa'. reflexivity.
Qed.


Lemma nat_to_ord_strictly_increasing : forall k,
  ord_compare (nat_to_ord k) (nat_to_ord (S k)) = Lt.
Proof.
  induction k as [|k IH].
  - reflexivity.
  - cbn. exact IH.
Qed.


Lemma ord_compare_OCons_first_lt : forall a b t1 t2,
  ord_compare a b = Lt -> ord_compare (OCons a t1) (OCons b t2) = Lt.
Proof.
  intros a b t1 t2 H. cbn. rewrite H. reflexivity.
Qed.


Theorem epsilon_0_contains_all_omega_towers : forall n,
  ord_compare (omega_tower n) (omega_tower (S n)) = Lt.
Proof.
  induction n as [|n IH].
  - reflexivity.
  - cbn [omega_tower].
    rewrite ord_compare_OCons_OZero.
    exact IH.
Qed.


Theorem proof_theoretic_ordinal_GLP_at_least_epsilon_0 :
  forall n, ord_compare (omega_tower n) (omega_tower (S n)) = Lt.
Proof. exact epsilon_0_contains_all_omega_towers. Qed.


Theorem worm_ordinal_embedding : forall w,
  exists w' : Worm,
    ord_compare (worm_to_ord w) (worm_to_ord w') = Lt.
Proof.
  intro w. destruct w as [|k rest].
  - exists [0]. reflexivity.
  - exists (S k :: rest). cbn [worm_to_ord].
    apply ord_compare_OCons_first_lt.
    exact (nat_to_ord_strictly_increasing k).
Qed.


Theorem worm_form_provability_corresponds_to_ordinal : forall w1 w2,
  |- Iff (worm_to_form w1) (worm_to_form w2).
Proof.
  intros w1 w2. apply prov_and_intro_meta;
  apply worm_normal_form_provable_collapse.
Qed.


Fixpoint count_atomic (o : ord) : nat :=
  match o with
  | OZero => 0
  | OCons OZero t => S (count_atomic t)
  | OCons _ _ => 0
  end.


Fixpoint ord_to_worm (o : ord) : Worm :=
  match o with
  | OZero => []
  | OCons e t => count_atomic e :: ord_to_worm t
  end.


Lemma count_atomic_nat_to_ord : forall n, count_atomic (nat_to_ord n) = n.
Proof.
  induction n as [|n' IH]; simpl.
  - reflexivity.
  - rewrite IH. reflexivity.
Qed.


Theorem ord_to_worm_left_inverse : forall w,
  ord_to_worm (worm_to_ord w) = w.
Proof.
  induction w as [|k rest IH]; simpl.
  - reflexivity.
  - rewrite count_atomic_nat_to_ord. rewrite IH. reflexivity.
Qed.


Theorem worm_ordinal_correspondence : forall w,
  ord_to_worm (worm_to_ord w) = w /\
  exists o, worm_to_ord w = o.
Proof.
  intro w. split.
  - exact (ord_to_worm_left_inverse w).
  - exists (worm_to_ord w). reflexivity.
Qed.


Definition Veblen_phi_0 (alpha : ord) : ord := OCons alpha OZero.


Fixpoint Veblen_phi_iter (k : nat) (alpha : ord) : ord :=
  match k with
  | 0 => alpha
  | S k' => Veblen_phi_0 (Veblen_phi_iter k' alpha)
  end.


Definition Gamma_0_approx (k : nat) : ord := Veblen_phi_iter k OZero.


Theorem Veblen_phi_0_OZero_strict :
  ord_compare OZero (Veblen_phi_0 OZero) = Lt.
Proof. reflexivity. Qed.


Theorem Veblen_phi_0_unequal : forall alpha,
  Veblen_phi_0 alpha <> alpha.
Proof.
  intros alpha H. unfold Veblen_phi_0 in H.
  pose proof (f_equal ord_size H) as Hsz.
  simpl in Hsz. lia.
Qed.


Theorem Veblen_phi_iter_zero : Veblen_phi_iter 0 OZero = OZero.
Proof. reflexivity. Qed.


Theorem Veblen_phi_iter_one : Veblen_phi_iter 1 OZero = OCons OZero OZero.
Proof. reflexivity. Qed.


Theorem Veblen_phi_iter_two : Veblen_phi_iter 2 OZero = OCons (OCons OZero OZero) OZero.
Proof. reflexivity. Qed.


Theorem Gamma_0_approx_zero : Gamma_0_approx 0 = OZero.
Proof. reflexivity. Qed.


Theorem Gamma_0_approx_one : Gamma_0_approx 1 = OCons OZero OZero.
Proof. reflexivity. Qed.


Theorem Gamma_0_approx_two : Gamma_0_approx 2 = OCons (OCons OZero OZero) OZero.
Proof. reflexivity. Qed.


Theorem Gamma_0_approx_distinct : forall k,
  Gamma_0_approx k <> Gamma_0_approx (S k).
Proof.
  intro k. unfold Gamma_0_approx. simpl.
  apply not_eq_sym. apply Veblen_phi_0_unequal.
Qed.


Lemma Gamma_0_approx_S : forall k,
  Gamma_0_approx (S k) = OCons (Gamma_0_approx k) OZero.
Proof. intro k. reflexivity. Qed.


Lemma Gamma_0_approx_strictly_increasing : forall j,
  ord_compare (Gamma_0_approx j) (Gamma_0_approx (S j)) = Lt.
Proof.
  induction j as [|j IH].
  - reflexivity.
  - rewrite (Gamma_0_approx_S (S j)).
    rewrite (Gamma_0_approx_S j).
    rewrite ord_compare_OCons_OZero.
    rewrite <- (Gamma_0_approx_S j).
    exact IH.
Qed.


Lemma Veblen_phi_0_wf : forall alpha, wf_ord alpha -> wf_ord (Veblen_phi_0 alpha).
Proof.
  intros alpha Hwf. unfold Veblen_phi_0.
  cbn. split; [exact Hwf | split; [exact I | exact I]].
Qed.


Lemma Veblen_phi_iter_wf : forall k alpha, wf_ord alpha -> wf_ord (Veblen_phi_iter k alpha).
Proof.
  induction k as [|k IH]; intros alpha Halpha; cbn.
  - exact Halpha.
  - apply Veblen_phi_0_wf. apply IH. exact Halpha.
Qed.


Lemma Gamma_0_approx_wf : forall k, wf_ord (Gamma_0_approx k).
Proof.
  intros k. unfold Gamma_0_approx. apply Veblen_phi_iter_wf. exact I.
Qed.


Lemma Veblen_phi_0_strictly_increasing : forall alpha beta,
  ord_compare alpha beta = Lt ->
  ord_compare (Veblen_phi_0 alpha) (Veblen_phi_0 beta) = Lt.
Proof.
  intros alpha beta H. unfold Veblen_phi_0.
  rewrite ord_compare_OCons_OZero. exact H.
Qed.


Lemma Veblen_phi_iter_strictly_increasing : forall k alpha beta,
  ord_compare alpha beta = Lt ->
  ord_compare (Veblen_phi_iter k alpha) (Veblen_phi_iter k beta) = Lt.
Proof.
  induction k as [|k IH]; intros alpha beta H.
  - exact H.
  - cbn. apply Veblen_phi_0_strictly_increasing. apply IH. exact H.
Qed.


Theorem Gamma_0_approx_unbounded : forall k,
  exists o : ord, ord_compare (Gamma_0_approx k) o = Lt.
Proof.
  intro k. exists (Gamma_0_approx (S k)).
  exact (Gamma_0_approx_strictly_increasing k).
Qed.


Definition is_Veblen_fixed_point (f : ord -> ord) (o : ord) : Prop :=
  f o = o.


Theorem Veblen_phi_0_no_fixed_point_in_image_of_OZero :
  forall k, Veblen_phi_0 (Gamma_0_approx k) <> OZero.
Proof. intro k. simpl. discriminate. Qed.


Lemma omega_tower_eq_Gamma_0_approx_S : forall n,
  omega_tower n = Gamma_0_approx (S n).
Proof.
  induction n as [|n IH].
  - reflexivity.
  - cbn [omega_tower].
    rewrite IH.
    rewrite Gamma_0_approx_S.
    reflexivity.
Qed.


Definition worm_equiv (w1 w2 : Worm) : Prop :=
  worm_to_ord w1 = worm_to_ord w2.


Theorem worm_equiv_refl : forall w, worm_equiv w w.
Proof. intro w. unfold worm_equiv. reflexivity. Qed.


Theorem worm_equiv_sym : forall w1 w2, worm_equiv w1 w2 -> worm_equiv w2 w1.
Proof. intros w1 w2 H. unfold worm_equiv in *. symmetry. exact H. Qed.


Theorem worm_equiv_trans : forall w1 w2 w3,
  worm_equiv w1 w2 -> worm_equiv w2 w3 -> worm_equiv w1 w3.
Proof. intros w1 w2 w3 H1 H2. unfold worm_equiv in *. transitivity (worm_to_ord w2); assumption. Qed.


Theorem worm_equiv_iff_ord_eq : forall w1 w2,
  worm_equiv w1 w2 <-> worm_to_ord w1 = worm_to_ord w2.
Proof. intros w1 w2. unfold worm_equiv. tauto. Qed.


Theorem worm_to_ord_injective : forall w1 w2,
  worm_to_ord w1 = worm_to_ord w2 -> w1 = w2.
Proof.
  intros w1 w2 H.
  pose proof (ord_to_worm_left_inverse w1) as Hw1.
  pose proof (ord_to_worm_left_inverse w2) as Hw2.
  rewrite <- Hw1. rewrite <- Hw2. rewrite H. reflexivity.
Qed.


Theorem worm_equiv_iff_eq : forall w1 w2,
  worm_equiv w1 w2 <-> w1 = w2.
Proof.
  intros w1 w2. unfold worm_equiv. split.
  - exact (worm_to_ord_injective w1 w2).
  - intro H. subst. reflexivity.
Qed.


Definition order_isomorphism (f : Worm -> ord) (g : ord -> Worm) : Prop :=
  (forall w, g (f w) = w) /\
  (forall w1 w2, f w1 = f w2 -> w1 = w2).


Theorem worm_to_ord_is_order_isomorphism :
  order_isomorphism worm_to_ord ord_to_worm.
Proof.
  unfold order_isomorphism. split.
  - exact ord_to_worm_left_inverse.
  - exact worm_to_ord_injective.
Qed.


Theorem proof_theoretic_ordinal_equals_epsilon_0_via_isomorphism :
  exists (f : Worm -> ord) (g : ord -> Worm),
    (forall w, g (f w) = w) /\
    (forall w1 w2, f w1 = f w2 -> w1 = w2).
Proof.
  exists worm_to_ord, ord_to_worm.
  exact worm_to_ord_is_order_isomorphism.
Qed.


Theorem proof_theoretic_ordinal_GLP_equals_epsilon_0_carrier_via_worms :
  forall (alpha : epsilon_0_carrier),
  exists w : Worm, worm_to_ord w = worm_to_ord (ord_to_worm alpha).
Proof.
  intro alpha. exists (ord_to_worm alpha). reflexivity.
Qed.


Theorem proof_theoretic_ordinal_GLP_atomic_recovery : forall n,
  exists w : Worm, worm_to_ord w = OCons (nat_to_ord n) OZero.
Proof.
  intro n. exists [n]. simpl. reflexivity.
Qed.


Theorem worm_completeness_unique_ord_per_worm : forall w1 w2,
  worm_to_ord w1 = worm_to_ord w2 -> w1 = w2.
Proof. exact worm_to_ord_injective. Qed.


Theorem worm_completeness_every_ord_in_image_has_unique_worm : forall o,
  (exists w, worm_to_ord w = o) ->
  exists! w, worm_to_ord w = o.
Proof.
  intros o [w Hw]. exists w. split.
  - exact Hw.
  - intros w' Hw'.
    apply worm_to_ord_injective.
    rewrite Hw'. rewrite Hw. reflexivity.
Qed.


Theorem worm_completeness_provable_implication_via_ord : forall w1 w2,
  worm_to_ord w1 = worm_to_ord w2 ->
  |- Iff (worm_to_form w1) (worm_to_form w2).
Proof.
  intros w1 w2 H.
  apply worm_to_ord_injective in H. subst.
  exact (prov_iff_refl _).
Qed.


Theorem worm_completeness_ord_compare_distinguishes :
  exists w1 w2, ord_compare (worm_to_ord w1) (worm_to_ord w2) = Lt.
Proof.
  exists [], [0]. simpl. reflexivity.
Qed.


Definition worm_omega : Worm := [1].

Definition worm_omega_squared : Worm := [2].

Definition worm_unit : Worm := [0].

Definition worm_zero : Worm := [].


Theorem worm_zero_lt_unit_via_ord :
  ord_compare (worm_to_ord worm_zero) (worm_to_ord worm_unit) = Lt.
Proof. simpl. reflexivity. Qed.


Theorem worm_unit_lt_omega_via_ord :
  ord_compare (worm_to_ord worm_unit) (worm_to_ord worm_omega) = Lt.
Proof. simpl. reflexivity. Qed.


Theorem worm_omega_lt_omega_squared_via_ord :
  ord_compare (worm_to_ord worm_omega) (worm_to_ord worm_omega_squared) = Lt.
Proof. simpl. reflexivity. Qed.


Theorem worm_completeness_decoding : forall w,
  ord_to_worm (worm_to_ord w) = w.
Proof. exact ord_to_worm_left_inverse. Qed.


Theorem worm_form_provability_aligned_with_ord : forall w,
  |- worm_to_form w /\
  (worm_to_ord w = OZero <-> w = []).
Proof.
  intro w. split.
  - exact (worm_all_provable w).
  - split.
    + intro H. destruct w; [reflexivity|]. simpl in H. discriminate.
    + intro H. subst. reflexivity.
Qed.


(******************************************************************************)
(* Veblen notation system extending the CNF carrier [ord].                    *)
(*                                                                            *)
(* Beyond the existing [Veblen_phi_0] (which is just [λα. ω^α]) and its      *)
(* iterates [Veblen_phi_iter k OZero] (which all live in CNF below ε_0),     *)
(* we introduce a stratified Veblen-φ system where each φ_(n+1) for n : nat  *)
(* is represented by a syntactic atom [V_phi n α].  Concretely:               *)
(*                                                                            *)
(*   - [V_cnf o]   embeds a CNF ord o (necessarily below ε_0) into vord.     *)
(*   - [V_phi n α] represents φ_(n+1)(α), the α-th common fixed point of    *)
(*     [φ_0, φ_1, ..., φ_n].  In particular [V_phi 0 OZero = ε_0], and       *)
(*     [V_phi n OZero] is the n-th Γ_0 approximation φ_(n+1)(0).             *)
(*                                                                            *)
(* The stratified design — V_phi's argument is an [ord] (existing CNF), not  *)
(* a recursive vord — sidesteps the binary-Veblen cross-comparison problem.  *)
(* Comparison is straightforward lex on (head-class, index, ord-position),   *)
(* and well-foundedness follows from well-foundedness of < on nat together   *)
(* with [cnf_lt] on the CNF subset.                                           *)
(******************************************************************************)

Inductive vord : Type :=
  | V_cnf  : ord -> vord
  | V_phi  : nat -> ord -> vord.


(** Normal-form predicate: in [V_phi n α], the [ord] argument α must be
    in CNF, i.e. [wf_ord α].  [V_cnf o] requires [wf_ord o]. *)

Definition wf_vord (v : vord) : Prop :=
  match v with
  | V_cnf o   => wf_ord o
  | V_phi _ α => wf_ord α
  end.


(** Inductively-defined Veblen ordering on [vord].  Three cases:
    CNF on CNF goes through [ord_lt]; every CNF position is strictly
    below every [V_phi]-atom; among [V_phi] atoms, the lex order on
    (index, argument) decides. *)

Inductive vord_lt : vord -> vord -> Prop :=
  | VL_cnf       : forall o1 o2, ord_lt o1 o2 -> vord_lt (V_cnf o1) (V_cnf o2)
  | VL_cnf_phi   : forall o n α, vord_lt (V_cnf o) (V_phi n α)
  | VL_phi_idx   : forall n1 n2 α1 α2,
      n1 < n2 -> vord_lt (V_phi n1 α1) (V_phi n2 α2)
  | VL_phi_arg   : forall n α1 α2,
      ord_lt α1 α2 -> vord_lt (V_phi n α1) (V_phi n α2).


Lemma vord_lt_V_cnf_inv : forall v o,
  vord_lt v (V_cnf o) -> exists o', v = V_cnf o' /\ ord_lt o' o.
Proof.
  intros v o H.
  remember (V_cnf o) as u eqn:Eu.
  destruct H as [o1 o2 Hlt | o' n α | n1 n2 α1 α2 Hlt | n α1 α2 Hlt].
  - injection Eu as Hu. subst o2.
    exists o1. split; [reflexivity | exact Hlt].
  - discriminate.
  - discriminate.
  - discriminate.
Qed.


Lemma vord_lt_V_phi_inv : forall v n α,
  vord_lt v (V_phi n α) ->
    (exists o, v = V_cnf o) \/
    (exists n' α', v = V_phi n' α' /\ n' < n) \/
    (exists α', v = V_phi n α' /\ ord_lt α' α).
Proof.
  intros v n α H.
  remember (V_phi n α) as u eqn:Eu.
  destruct H as [o1 o2 Hlt | o' nn αα | n1 n2 α1 α2 Hlt | nn α1 α2 Hlt].
  - discriminate.
  - injection Eu as En Eα. subst nn αα.
    left. exists o'. reflexivity.
  - injection Eu as En Eα. subst n2 α2.
    right. left. exists n1, α1. split; [reflexivity | exact Hlt].
  - injection Eu as En Eα. subst nn α2.
    right. right. exists α1. split; [reflexivity | exact Hlt].
Qed.


(** ** Well-foundedness on the [wf_vord] subset.

    Conditioned relation [vord_wf_lt] requires both endpoints to be
    well-formed (CNF in their [ord] components).  Well-foundedness then
    follows from: (i) [V_cnf]-images use [nf_Acc] for [cnf_lt] descent,
    (ii) [V_phi n _] images use lex on (n, [cnf_lt] on the inner [ord]). *)

Definition vord_wf_lt (u v : vord) : Prop :=
  wf_vord u /\ wf_vord v /\ vord_lt u v.


Lemma Acc_vord_V_cnf_wf : forall o,
  wf_ord o -> Acc vord_wf_lt (V_cnf o).
Proof.
  intros o Hwfo.
  pose proof (nf_Acc o Hwfo) as Acco.
  revert Hwfo.
  induction Acco as [o Hacc IH]. intro Hwfo.
  apply Acc_intro. intros y [Hwfy [_ Hlt]].
  destruct (vord_lt_V_cnf_inv _ _ Hlt) as [o' [Heq Hltoo]].
  subst y. cbn in Hwfy.
  apply IH.
  - unfold lt_cnf. split; [exact Hwfy | split; [exact Hwfo | exact Hltoo]].
  - exact Hwfy.
Qed.


(** For [V_phi n α] images: outer induction on n, inner on Acc lt_cnf α. *)

Lemma Acc_vord_V_phi_wf : forall n α,
  wf_ord α -> Acc vord_wf_lt (V_phi n α).
Proof.
  intro n. induction n as [n IHn] using lt_wf_ind.
  intros α Hwfα.
  pose proof (nf_Acc α Hwfα) as Accα.
  revert Hwfα.
  induction Accα as [α Haccα IHα]. intro Hwfα.
  apply Acc_intro. intros y [Hwfy [_ Hlt]].
  destruct (vord_lt_V_phi_inv _ _ _ Hlt) as
    [[o E] | [[n' [α' [E Hlt']]] | [α' [E Hltα]]]].
  - subst y. apply Acc_vord_V_cnf_wf. exact Hwfy.
  - subst y. cbn in Hwfy. apply IHn; [exact Hlt' | exact Hwfy].
  - subst y. cbn in Hwfy. apply IHα.
    + unfold lt_cnf. split; [exact Hwfy | split; [exact Hwfα | exact Hltα]].
    + exact Hwfy.
Qed.


Theorem vord_wf_lt_well_founded : well_founded vord_wf_lt.
Proof.
  intro v. apply Acc_intro. intros y [Hwfy [Hwfv Hlt]].
  destruct v as [o | n α].
  - apply (Acc_inv (Acc_vord_V_cnf_wf o Hwfv)).
    split; [exact Hwfy | split; [exact Hwfv | exact Hlt]].
  - apply (Acc_inv (Acc_vord_V_phi_wf n α Hwfv)).
    split; [exact Hwfy | split; [exact Hwfv | exact Hlt]].
Qed.


(** ** Concrete Veblen positions.

    [veps0]            = ε_0 = φ_1(0), encoded as [V_phi 0 OZero].
    [vgamma0_approx n] = φ_(n+1)(0), the Γ_0 approximations from below.
    *)

Definition veps0 : vord := V_phi 0 OZero.


Definition vgamma0_approx (n : nat) : vord := V_phi n OZero.


Theorem vgamma0_approx_zero : vgamma0_approx 0 = veps0.
Proof. reflexivity. Qed.


Theorem vgamma0_approx_strict : forall n,
  vord_lt (vgamma0_approx n) (vgamma0_approx (S n)).
Proof. intro n. unfold vgamma0_approx. apply VL_phi_idx. lia. Qed.


Theorem vgamma0_approx_chain : forall n m,
  n < m -> vord_lt (vgamma0_approx n) (vgamma0_approx m).
Proof. intros n m H. unfold vgamma0_approx. apply VL_phi_idx. exact H. Qed.


(** Every CNF ord is strictly below ε_0 in vord. *)

Theorem cnf_below_veps0 : forall o,
  vord_lt (V_cnf o) veps0.
Proof. intro o. unfold veps0. apply VL_cnf_phi. Qed.


(** In particular, every iterated ω-tower [Veblen_phi_iter k OZero] is
    below ε_0 in vord, witnessing that ε_0 is genuinely beyond CNF. *)

Theorem omega_tower_image_below_veps0 : forall k,
  vord_lt (V_cnf (Veblen_phi_iter k OZero)) veps0.
Proof. intro k. apply cnf_below_veps0. Qed.


(** Every worm has its [worm_to_ord] image below ε_0 in vord. *)

Theorem worm_image_below_veps0 : forall w,
  vord_lt (V_cnf (worm_to_ord w)) veps0.
Proof. intro w. apply cnf_below_veps0. Qed.


(** ** Normal-form preservation under the canonical witnesses. *)

Theorem veps0_wf : wf_vord veps0.
Proof. unfold veps0. cbn. exact I. Qed.


Theorem vgamma0_approx_wf : forall n, wf_vord (vgamma0_approx n).
Proof. intro n. unfold vgamma0_approx. cbn. exact I. Qed.


Theorem cnf_wf_to_vord : forall o, wf_ord o -> wf_vord (V_cnf o).
Proof. intros o H. exact H. Qed.


(** ** Strict layering of the Veblen hierarchy.

    For every n, there is a vord (namely [vgamma0_approx n]) that is
    strictly above every CNF ord (representing all worm-images) and
    below [vgamma0_approx (S n)].  This is the strict layering of the
    Γ_0 approximations from below the Feferman-Schütte ordinal Γ_0. *)

Theorem veblen_hierarchy_strict_layering : forall n,
  (forall o, vord_lt (V_cnf o) (vgamma0_approx n)) /\
  vord_lt (vgamma0_approx n) (vgamma0_approx (S n)).
Proof.
  intro n. split.
  - intro o. unfold vgamma0_approx. apply VL_cnf_phi.
  - apply vgamma0_approx_strict.
Qed.


(** ** Veblen notation system: the headline package.

    The Veblen notation system (vord, vord_wf_lt, wf_vord) extends CNF
    in a well-ordered fashion, captures ε_0 as the syntactic atom
    [V_phi 0 OZero], approximates Γ_0 from below via the
    [vgamma0_approx] family, and connects to GLP*'s worm-image
    proof-theoretic ordinal bound via the [V_cnf] embedding. *)

Theorem veblen_notation_system_well_ordered :
  well_founded vord_wf_lt /\
  (forall n m, n < m -> vord_lt (vgamma0_approx n) (vgamma0_approx m)) /\
  (forall w, vord_lt (V_cnf (worm_to_ord w)) veps0) /\
  veps0 = vgamma0_approx 0.
Proof.
  split; [|split; [|split]].
  - exact vord_wf_lt_well_founded.
  - exact vgamma0_approx_chain.
  - exact worm_image_below_veps0.
  - reflexivity.
Qed.


(******************************************************************************)
(* Strict ordinal decrease under reduction.                                    *)
(*                                                                            *)
(* [proof_term_ordinal] maps each proof term to a CNF ordinal in [ord].      *)
(* Under [pt_reduces] every reduction strictly decreases this ordinal in     *)
(* [ord_lt], witnessing a sharp proof-theoretic descent.                     *)
(******************************************************************************)

(** Lifting [ord_lt] through [OCons] with congruent contexts. *)

Lemma ord_lt_OCons_head : forall a a' t1 t2,
  ord_lt a a' -> ord_lt (OCons a t1) (OCons a' t2).
Proof.
  intros a a' t1 t2 H. unfold ord_lt in *. cbn.
  rewrite H. reflexivity.
Qed.


Lemma ord_lt_OCons_tail : forall a t t',
  ord_lt t t' -> ord_lt (OCons a t) (OCons a t').
Proof.
  intros a t t' H. unfold ord_lt in *. cbn.
  rewrite ord_compare_refl. exact H.
Qed.


Fixpoint nat_to_ord_chain (n : nat) : ord :=
  match n with
  | 0 => OZero
  | S k => OCons OZero (nat_to_ord_chain k)
  end.


Lemma nat_to_ord_chain_zero : nat_to_ord_chain 0 = OZero.
Proof. reflexivity. Qed.


Lemma nat_to_ord_chain_succ : forall n,
  nat_to_ord_chain (S n) = OCons OZero (nat_to_ord_chain n).
Proof. reflexivity. Qed.


Lemma nat_to_ord_chain_OCons_succ_lt : forall n,
  ord_lt (nat_to_ord_chain n) (OCons OZero (nat_to_ord_chain n)).
Proof.
  induction n as [|n IH]; cbn.
  - reflexivity.
  - unfold ord_lt in *. cbn. cbn in IH. exact IH.
Qed.


Lemma nat_to_ord_chain_strictly_increasing : forall n,
  ord_lt (nat_to_ord_chain n) (nat_to_ord_chain (S n)).
Proof. intro n. cbn. apply nat_to_ord_chain_OCons_succ_lt. Qed.


Lemma nat_to_ord_chain_lt : forall n m,
  n < m -> ord_lt (nat_to_ord_chain n) (nat_to_ord_chain m).
Proof.
  intros n m H. induction H.
  - apply nat_to_ord_chain_strictly_increasing.
  - apply (ord_lt_trans _ (nat_to_ord_chain m)).
    + exact IHle.
    + apply nat_to_ord_chain_strictly_increasing.
Qed.

