(** Tiling.ProofTerms - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.

From Tiling Require Import Syntax.
From Tiling Require Import Provable.
From Tiling Require Import Ordinals.
From Tiling Require Import Encoding.


Inductive proof_term : Type :=
  | PT_K : Form -> Form -> proof_term
  | PT_S : Form -> Form -> Form -> proof_term
  | PT_DN : Form -> proof_term
  | PT_BoxK : nat -> Form -> Form -> proof_term
  | PT_Loeb : nat -> Form -> proof_term
  | PT_Box4 : nat -> Form -> proof_term
  | PT_Mon : nat -> Form -> proof_term
  | PT_NextCon : nat -> proof_term
  | PT_MP : proof_term -> proof_term -> proof_term
  | PT_Nec : nat -> proof_term -> proof_term.


Fixpoint proof_term_size (pt : proof_term) : nat :=
  match pt with
  | PT_MP p1 p2 => S (proof_term_size p1 + proof_term_size p2)
  | PT_Nec _ p => S (proof_term_size p)
  | _ => 1
  end.


Fixpoint proof_term_ordinal (pt : proof_term) : ord :=
  match pt with
  | PT_MP p1 p2 => OCons (proof_term_ordinal p1) (proof_term_ordinal p2)
  | PT_Nec _ p => OCons OZero (proof_term_ordinal p)
  | _ => OZero
  end.


Theorem proof_term_strong_normalisation : forall p,
  Acc (fun a b => proof_term_size a < proof_term_size b) p.
Proof.
  intro p. apply Wf_nat.well_founded_lt_compat with (f := proof_term_size).
  intros x y H. exact H.
Qed.


Theorem proof_term_ordinal_in_epsilon_0 : forall pt,
  ord_size (proof_term_ordinal pt) <= proof_term_size pt.
Proof.
  induction pt; cbn; lia.
Qed.


Fixpoint denote_proof_term (pt : proof_term) : option Form :=
  match pt with
  | PT_K phi psi => Some (Impl phi (Impl psi phi))
  | PT_S phi psi chi => Some (Impl (Impl phi (Impl psi chi)) (Impl (Impl phi psi) (Impl phi chi)))
  | PT_DN phi => Some (Impl (Neg (Neg phi)) phi)
  | PT_BoxK n phi psi => Some (Impl (Box n (Impl phi psi)) (Impl (Box n phi) (Box n psi)))
  | PT_Loeb n phi => Some (Impl (Box n (Impl (Box n phi) phi)) (Box n phi))
  | PT_Box4 n phi => Some (Impl (Box n phi) (Box n (Box n phi)))
  | PT_Mon n phi => Some (Impl (Box n phi) (Box (S n) phi))
  | PT_NextCon n => Some (Box (S n) (Neg (Box n Bot)))
  | PT_MP p1 p2 =>
    match denote_proof_term p1, denote_proof_term p2 with
    | Some (Impl a b), Some a' => if Form_eqb a a' then Some b else None
    | _, _ => None
    end
  | PT_Nec n p =>
    match denote_proof_term p with
    | Some phi => Some (Box n phi)
    | None => None
    end
  end.



Theorem denote_proof_term_provable : forall pt phi,
  denote_proof_term pt = Some phi -> |- phi.
Proof.
  induction pt as [| | | | | | | | p1 IH1 p2 IH2 | n p IH]; intros phi Hd; simpl in Hd.
  - injection Hd. intro He. subst. apply Ax_K.
  - injection Hd. intro He. subst. apply Ax_S.
  - injection Hd. intro He. subst. apply Ax_DN.
  - injection Hd. intro He. subst. apply Ax_BoxK.
  - injection Hd. intro He. subst. apply Ax_Loeb.
  - injection Hd. intro He. subst. apply Ax_Box4.
  - injection Hd. intro He. subst. apply Ax_Mon.
  - injection Hd. intro He. subst. apply Ax_NextCon.
  - destruct (denote_proof_term p1) as [f|]; [|discriminate].
    destruct f as [v | | f1 f2 | k psi]; try discriminate.
    destruct (denote_proof_term p2) as [a'|]; [|discriminate].
    destruct (Form_eqb f1 a') eqn:Eq; [|discriminate].
    apply Form_eqb_eq in Eq. subst a'.
    injection Hd. intro He. subst phi.
    pose proof (IH1 (Impl f1 f2) eq_refl) as H1.
    pose proof (IH2 f1 eq_refl) as H2.
    exact (MP _ _ H1 H2).
  - destruct (denote_proof_term p) as [phi'|]; [|discriminate].
    injection Hd. intro He. subst phi.
    pose proof (IH phi' eq_refl) as H.
    exact (Nec _ _ H).
Qed.


Theorem provable_to_proof_term : forall phi,
  |- phi -> exists pt, denote_proof_term pt = Some phi.
Proof.
  intros phi H. induction H.
  - exists (PT_K phi psi). reflexivity.
  - exists (PT_S phi psi chi). reflexivity.
  - exists (PT_DN phi). reflexivity.
  - exists (PT_BoxK n phi psi). reflexivity.
  - exists (PT_Loeb n phi). reflexivity.
  - exists (PT_Box4 n phi). reflexivity.
  - exists (PT_Mon n phi). reflexivity.
  - exists (PT_NextCon n). reflexivity.
  - destruct IHProvable1 as [pt1 H1]. destruct IHProvable2 as [pt2 H2].
    exists (PT_MP pt1 pt2). simpl. rewrite H1, H2.
    rewrite Form_eqb_refl. reflexivity.
  - destruct IHProvable as [pt H']. exists (PT_Nec n pt). simpl. rewrite H'. reflexivity.
Qed.


Definition Bew_arith (phi : Form) : Prop :=
  exists pt : proof_term, denote_proof_term pt = Some phi.


Theorem Bew_arith_iff_provable : forall phi,
  Bew_arith phi <-> |- phi.
Proof.
  intro phi. split.
  - intros [pt Hd]. exact (denote_proof_term_provable pt phi Hd).
  - exact (provable_to_proof_term phi).
Qed.


Theorem Bew_arith_HBL_K_derived : forall phi psi,
  Bew_arith (Impl phi psi) -> Bew_arith phi -> Bew_arith psi.
Proof.
  intros phi psi [pt1 H1] [pt2 H2].
  exists (PT_MP pt1 pt2). simpl. rewrite H1, H2.
  rewrite Form_eqb_refl. reflexivity.
Qed.


Theorem Bew_arith_HBL_Nec_derived : forall n phi,
  Bew_arith phi -> Bew_arith (Box n phi).
Proof.
  intros n phi [pt H]. exists (PT_Nec n pt). simpl. rewrite H. reflexivity.
Qed.


Theorem Bew_arith_HBL_Loeb_axiom_derived : forall n phi,
  Bew_arith (Impl (Box n (Impl (Box n phi) phi)) (Box n phi)).
Proof. intros n phi. exists (PT_Loeb n phi). reflexivity. Qed.


Theorem Bew_arith_HBL_K_axiom_derived : forall n phi psi,
  Bew_arith (Impl (Box n (Impl phi psi)) (Impl (Box n phi) (Box n psi))).
Proof. intros n phi psi. exists (PT_BoxK n phi psi). reflexivity. Qed.


Theorem Bew_arith_HBL_Box4_axiom_derived : forall n phi,
  Bew_arith (Impl (Box n phi) (Box n (Box n phi))).
Proof. intros n phi. exists (PT_Box4 n phi). reflexivity. Qed.


Theorem Bew_arith_HBL_complete_package : forall (n : nat) (phi : Form),
  Bew_arith (Impl (Box n (Impl (Box n phi) phi)) (Box n phi)) /\
  (forall psi, Bew_arith (Impl (Box n (Impl phi psi)) (Impl (Box n phi) (Box n psi)))) /\
  (Bew_arith phi -> Bew_arith (Box n phi)) /\
  (forall psi, Bew_arith (Impl phi psi) -> Bew_arith phi -> Bew_arith psi).
Proof.
  intros n phi. split; [|split; [|split]].
  - exact (Bew_arith_HBL_Loeb_axiom_derived n phi).
  - intros psi. exact (Bew_arith_HBL_K_axiom_derived n phi psi).
  - exact (Bew_arith_HBL_Nec_derived n phi).
  - intros psi. exact (Bew_arith_HBL_K_derived phi psi).
Qed.


Definition is_proof_code (pt : proof_term) (phi : Form) : Prop :=
  denote_proof_term pt = Some phi.


Theorem is_proof_code_unique_conclusion : forall pt phi psi,
  is_proof_code pt phi -> is_proof_code pt psi -> phi = psi.
Proof.
  intros pt phi psi H1 H2. unfold is_proof_code in *.
  rewrite H1 in H2. injection H2. intro He. exact He.
Qed.


Theorem Bew_arith_consistent : ~ Bew_arith Bot.
Proof.
  intros [pt Hd].
  pose proof (denote_proof_term_provable pt Bot Hd) as Hbot.
  exact (meta_consistency_system Hbot).
Qed.


Theorem Bew_arith_loeb_internal : forall n phi,
  Bew_arith (Impl (Box n phi) phi) -> Bew_arith phi.
Proof.
  intros n phi [pt Hd].
  pose proof (denote_proof_term_provable pt _ Hd) as Hsound.
  pose proof (loeb_metatheorem n phi Hsound) as Hphi.
  exact (provable_to_proof_term phi Hphi).
Qed.


Definition encoded_Sigma1_provable (n : nat) : Prop :=
  exists pt : proof_term, denote_proof_term pt = Some (decode_form n).


Theorem encoded_Sigma1_provable_iff_provable : forall n,
  encoded_Sigma1_provable n <-> |- decode_form n.
Proof. intro n. unfold encoded_Sigma1_provable. exact (Bew_arith_iff_provable _). Qed.


Theorem encoded_Sigma1_HBL_via_encoding : forall n m,
  encoded_Sigma1_provable n /\ encoded_Sigma1_provable m ->
  forall phi, decode_form n = Impl (decode_form m) phi ->
  exists pt, denote_proof_term pt = Some phi.
Proof.
  intros n m [Hn Hm] phi Hd.
  destruct Hn as [ptn Hptn]. destruct Hm as [ptm Hptm].
  exists (PT_MP ptn ptm). simpl. rewrite Hptn, Hptm. rewrite Hd.
  rewrite Form_eqb_refl. reflexivity.
Qed.


Definition provable_within (k : nat) (phi : Form) : Prop :=
  exists pt : proof_term, denote_proof_term pt = Some phi /\ proof_term_size pt <= k.


Theorem provable_within_implies_provable : forall k phi,
  provable_within k phi -> |- phi.
Proof.
  intros k phi [pt [Hd _]]. exact (denote_proof_term_provable pt phi Hd).
Qed.


Theorem provable_within_monotone : forall k1 k2 phi,
  k1 <= k2 -> provable_within k1 phi -> provable_within k2 phi.
Proof.
  intros k1 k2 phi Hle [pt [Hd Hsz]].
  exists pt. split; [exact Hd | lia].
Qed.


Theorem provable_within_K_axiom : forall k n phi psi,
  k >= 1 ->
  provable_within k (Impl (Box n (Impl phi psi)) (Impl (Box n phi) (Box n psi))).
Proof.
  intros k n phi psi Hk.
  exists (PT_BoxK n phi psi). split.
  - reflexivity.
  - simpl. lia.
Qed.


Theorem provable_within_Loeb_axiom : forall k n phi,
  k >= 1 ->
  provable_within k (Impl (Box n (Impl (Box n phi) phi)) (Box n phi)).
Proof.
  intros k n phi Hk.
  exists (PT_Loeb n phi). split.
  - reflexivity.
  - simpl. lia.
Qed.


Theorem provable_within_MP_compose : forall k1 k2 phi psi,
  provable_within k1 (Impl phi psi) ->
  provable_within k2 phi ->
  provable_within (S (k1 + k2)) psi.
Proof.
  intros k1 k2 phi psi [pt1 [Hd1 Hs1]] [pt2 [Hd2 Hs2]].
  exists (PT_MP pt1 pt2). split.
  - simpl. rewrite Hd1, Hd2. rewrite Form_eqb_refl. reflexivity.
  - simpl. lia.
Qed.


Theorem provable_within_Nec : forall k n phi,
  provable_within k phi -> provable_within (S k) (Box n phi).
Proof.
  intros k n phi [pt [Hd Hs]].
  exists (PT_Nec n pt). split.
  - simpl. rewrite Hd. reflexivity.
  - simpl. lia.
Qed.


Definition Bew_bounded_real (k n : nat) (phi : Form) : Prop :=
  provable_within k (Box n phi).


Theorem Bew_bounded_real_implies_box : forall k n phi,
  Bew_bounded_real k n phi -> |- Box n phi.
Proof.
  intros k n phi H. unfold Bew_bounded_real in H.
  exact (provable_within_implies_provable k _ H).
Qed.


Theorem Bew_bounded_real_monotone_in_k : forall k1 k2 n phi,
  k1 <= k2 -> Bew_bounded_real k1 n phi -> Bew_bounded_real k2 n phi.
Proof.
  intros k1 k2 n phi Hle H.
  unfold Bew_bounded_real in *. exact (provable_within_monotone k1 k2 _ Hle H).
Qed.


Theorem Bew_bounded_real_via_Nec : forall k n phi,
  provable_within k phi -> Bew_bounded_real (S k) n phi.
Proof.
  intros k n phi H. unfold Bew_bounded_real.
  exact (provable_within_Nec k n phi H).
Qed.


Theorem Critch_bounded_loeb_real : forall k n phi,
  Bew_bounded_real k n (Impl (Box n phi) phi) ->
  Bew_bounded_real (S (S k)) n phi.
Proof.
  intros k n phi [pt [Hd Hs]].
  unfold Bew_bounded_real, provable_within.
  exists (PT_MP (PT_Loeb n phi) pt). split.
  - simpl. rewrite Hd. rewrite Form_eqb_refl. reflexivity.
  - simpl. lia.
Qed.


Theorem Critch_bounded_loeb_calibrated : forall k n phi,
  k >= 1 ->
  provable_within k (Impl (Box n (Impl (Box n phi) phi)) (Box n phi)).
Proof.
  intros k n phi Hk.
  exists (PT_Loeb n phi). split.
  - reflexivity.
  - simpl. lia.
Qed.


Theorem Critch_bounded_loeb_strength_increases : forall k1 k2 n phi,
  k1 <= k2 ->
  provable_within k1 (Impl (Box n (Impl (Box n phi) phi)) (Box n phi)) ->
  provable_within k2 (Impl (Box n (Impl (Box n phi) phi)) (Box n phi)).
Proof. intros. exact (provable_within_monotone _ _ _ H H0). Qed.


Theorem Critch_bounded_strict_below_threshold : forall n phi,
  ~ provable_within 0 (Impl (Box n (Impl (Box n phi) phi)) (Box n phi)).
Proof.
  intros n phi [pt [Hd Hs]].
  destruct pt; simpl in Hs; try lia.
Qed.

