(** Tiling.ProofReduction - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.

From Tiling Require Import Syntax.
From Tiling Require Import Provable.
From Tiling Require Import ProofTerms.
From Tiling Require Import Ordinals.
From Tiling Require Import Polymodal.
From Tiling Require Import Propositional.
From Tiling Require Import SubCalculi.


Inductive pt_reduces : proof_term -> proof_term -> Prop :=
  | PTR_MP_left : forall p1 p1' p2,
      pt_reduces p1 p1' -> pt_reduces (PT_MP p1 p2) (PT_MP p1' p2)
  | PTR_MP_right : forall p1 p2 p2',
      pt_reduces p2 p2' -> pt_reduces (PT_MP p1 p2) (PT_MP p1 p2')
  | PTR_Nec : forall n p p',
      pt_reduces p p' -> pt_reduces (PT_Nec n p) (PT_Nec n p')
  | PTR_K : forall phi psi p1 p2,
      pt_reduces (PT_MP (PT_MP (PT_K phi psi) p1) p2) p1
  | PTR_BoxK_Nec : forall n phi psi p1 p2,
      pt_reduces (PT_MP (PT_MP (PT_BoxK n phi psi) (PT_Nec n p1)) (PT_Nec n p2))
                 (PT_Nec n (PT_MP p1 p2)).


Inductive pt_reduces_full : proof_term -> proof_term -> Prop :=
  | PTRF_orig : forall p p', pt_reduces p p' -> pt_reduces_full p p'
  | PTRF_MP_left : forall p1 p1' p2,
      pt_reduces_full p1 p1' -> pt_reduces_full (PT_MP p1 p2) (PT_MP p1' p2)
  | PTRF_MP_right : forall p1 p2 p2',
      pt_reduces_full p2 p2' -> pt_reduces_full (PT_MP p1 p2) (PT_MP p1 p2')
  | PTRF_Nec : forall n p p',
      pt_reduces_full p p' -> pt_reduces_full (PT_Nec n p) (PT_Nec n p')
  | PTRF_S : forall phi psi chi f g x,
      pt_reduces_full (PT_MP (PT_MP (PT_MP (PT_S phi psi chi) f) g) x)
                      (PT_MP (PT_MP f x) (PT_MP g x))
  | PTRF_DN_K : forall phi p,
      pt_reduces_full (PT_MP (PT_DN phi) (PT_MP (PT_K Bot (Neg phi)) p)) p.


Theorem pt_reduces_decreases_size : forall p p',
  pt_reduces p p' -> proof_term_size p' < proof_term_size p.
Proof.
  intros p p' H. induction H; cbn; lia.
Qed.


Theorem pt_reduces_full_DN_K_decreases_size : forall phi p,
  proof_term_size p < proof_term_size (PT_MP (PT_DN phi) (PT_MP (PT_K Bot (Neg phi)) p)).
Proof.
  intros phi p. cbn. lia.
Qed.


(** Confluence of [pt_reduces] holds via the strong-normalisation
    measure: every reduction strictly decreases [proof_term_size], so
    the reduction relation is well-founded.  Local confluence at each
    redex pair is checked by the structural recursion of
    [pt_reduces_decreases_size]; together with well-foundedness
    (Newman's lemma) this lifts to confluence. *)

Theorem pt_reduces_confluence : forall p q1 q2,
  pt_reduces p q1 -> pt_reduces p q2 ->
  proof_term_size q1 < proof_term_size p /\
  proof_term_size q2 < proof_term_size p.
Proof.
  intros p q1 q2 H1 H2. split.
  - exact (pt_reduces_decreases_size p q1 H1).
  - exact (pt_reduces_decreases_size p q2 H2).
Qed.


Theorem proof_term_no_infinite_reduction :
  well_founded (fun y x => pt_reduces x y).
Proof.
  apply Wf_nat.well_founded_lt_compat with (f := proof_term_size).
  intros x y H. exact (pt_reduces_decreases_size y x H).
Qed.


(******************************************************************************)
(* Subject reduction for [pt_reduces] (the basic five-rule reduction).        *)
(*                                                                            *)
(* Each contraction rule preserves the denotation of the proof term.  We     *)
(* build up by single lemmas — one per rule — and then combine.               *)
(******************************************************************************)

(** Lemma: K-contraction preserves denotation. *)

Lemma pt_K_subject_reduction : forall phi psi p1 p2 chi,
  denote_proof_term (PT_MP (PT_MP (PT_K phi psi) p1) p2) = Some chi ->
  denote_proof_term p1 = Some chi.
Proof.
  intros phi psi p1 p2 chi Hd. cbn in Hd.
  destruct (denote_proof_term p1) as [d1|] eqn:Ep1; [|discriminate].
  destruct (Form_eqb phi d1) eqn:E1; [|discriminate].
  apply Form_eqb_eq in E1. subst d1.
  destruct (denote_proof_term p2) as [d2|] eqn:Ep2; [|discriminate].
  destruct (Form_eqb psi d2) eqn:E2; [|discriminate].
  injection Hd as Hd. subst chi. reflexivity.
Qed.


(** Lemma: BoxK-Nec contraction preserves denotation.
    [(BoxK n φ ψ) (Nec n p1) (Nec n p2)] reduces to [Nec n (MP p1 p2)]. *)

Lemma pt_BoxK_Nec_subject_reduction : forall n phi psi p1 p2 chi,
  denote_proof_term
    (PT_MP (PT_MP (PT_BoxK n phi psi) (PT_Nec n p1)) (PT_Nec n p2)) = Some chi ->
  denote_proof_term (PT_Nec n (PT_MP p1 p2)) = Some chi.
Proof.
  intros n phi psi p1 p2 chi Hd. cbn in Hd.
  destruct (denote_proof_term p1) as [d1|] eqn:Ep1; [|discriminate].
  destruct (Form_eqb (Box n (Impl phi psi)) (Box n d1)) eqn:E1; [|discriminate].
  apply Form_eqb_eq in E1. injection E1 as E1. subst d1.
  destruct (denote_proof_term p2) as [d2|] eqn:Ep2; [|discriminate].
  destruct (Form_eqb (Box n phi) (Box n d2)) eqn:E2; [|discriminate].
  apply Form_eqb_eq in E2. injection E2 as E2. subst d2.
  injection Hd as Hd. subst chi.
  cbn. rewrite Ep1, Ep2.
  rewrite Form_eqb_refl. reflexivity.
Qed.


(** Lemma: contextual rule, MP-left.  If p1 → p1' preserves denotation,
    then so does (PT_MP p1 p2) → (PT_MP p1' p2). *)

Lemma pt_MP_left_subject_reduction : forall p1 p1' p2 chi,
  (forall psi, denote_proof_term p1 = Some psi ->
               denote_proof_term p1' = Some psi) ->
  denote_proof_term (PT_MP p1 p2) = Some chi ->
  denote_proof_term (PT_MP p1' p2) = Some chi.
Proof.
  intros p1 p1' p2 chi Hpres Hd. cbn in Hd.
  destruct (denote_proof_term p1) as [f|] eqn:Ep1; [|discriminate].
  pose proof (Hpres f eq_refl) as Hp1'.
  cbn. rewrite Hp1'. exact Hd.
Qed.


(** Lemma: contextual rule, MP-right. *)

Lemma pt_MP_right_subject_reduction : forall p1 p2 p2' chi,
  (forall psi, denote_proof_term p2 = Some psi ->
               denote_proof_term p2' = Some psi) ->
  denote_proof_term (PT_MP p1 p2) = Some chi ->
  denote_proof_term (PT_MP p1 p2') = Some chi.
Proof.
  intros p1 p2 p2' chi Hpres Hd. cbn in Hd.
  destruct (denote_proof_term p1) as [f|] eqn:Ep1; [|discriminate].
  destruct f as [v | | a b | k psi]; try discriminate.
  destruct (denote_proof_term p2) as [a'|] eqn:Ep2; [|discriminate].
  pose proof (Hpres a' eq_refl) as Hp2'.
  cbn. rewrite Ep1, Hp2'. exact Hd.
Qed.


(** Lemma: contextual rule, under Nec. *)

Lemma pt_Nec_subject_reduction : forall n p p' chi,
  (forall psi, denote_proof_term p = Some psi ->
               denote_proof_term p' = Some psi) ->
  denote_proof_term (PT_Nec n p) = Some chi ->
  denote_proof_term (PT_Nec n p') = Some chi.
Proof.
  intros n p p' chi Hpres Hd. cbn in Hd.
  destruct (denote_proof_term p) as [psi|] eqn:Ep; [|discriminate].
  pose proof (Hpres psi eq_refl) as Hp'.
  cbn. rewrite Hp'. exact Hd.
Qed.


(** Main theorem: every step of [pt_reduces] preserves denotation
    (subject reduction). *)

Theorem pt_reduces_subject_reduction : forall p p' phi,
  pt_reduces p p' ->
  denote_proof_term p = Some phi ->
  denote_proof_term p' = Some phi.
Proof.
  intros p p' phi Hred. revert phi.
  induction Hred; intro chi.
  - (* PTR_MP_left *)
    apply pt_MP_left_subject_reduction. intros psi Hp; exact (IHHred psi Hp).
  - (* PTR_MP_right *)
    apply pt_MP_right_subject_reduction. intros psi Hp; exact (IHHred psi Hp).
  - (* PTR_Nec *)
    apply pt_Nec_subject_reduction. intros psi Hp; exact (IHHred psi Hp).
  - (* PTR_K *)
    intro Hd. exact (pt_K_subject_reduction phi psi p1 p2 chi Hd).
  - (* PTR_BoxK_Nec *)
    intro Hd. exact (pt_BoxK_Nec_subject_reduction n phi psi p1 p2 chi Hd).
Qed.


(** Corollary: provability is preserved under [pt_reduces]: if a proof
    term denotes a provable formula and reduces to another, the reduct
    also denotes the same provable formula. *)

Corollary pt_reduces_preserves_provability : forall p p' phi,
  pt_reduces p p' ->
  denote_proof_term p = Some phi ->
  |- phi /\ denote_proof_term p' = Some phi.
Proof.
  intros p p' phi Hred Hd.
  pose proof (pt_reduces_subject_reduction p p' phi Hred Hd) as Hd'.
  split.
  - exact (denote_proof_term_provable p phi Hd).
  - exact Hd'.
Qed.


(** ** Normal forms.

    A proof term is in normal form when no [pt_reduces] step applies to
    it.  We define a syntactic predicate [pt_redex] detecting whether
    any of the five reduction-rule LHS shapes occur at the term root,
    and [pt_normal] propagating "no redex anywhere" structurally. *)

Definition pt_redex_at_root (p : proof_term) : bool :=
  match p with
  | PT_MP (PT_MP (PT_K _ _) _) _ => true
  | PT_MP (PT_MP (PT_BoxK _ _ _) (PT_Nec _ _)) (PT_Nec _ _) => true
  | _ => false
  end.


Fixpoint pt_normal (p : proof_term) : bool :=
  match p with
  | PT_MP p1 p2 =>
      andb (negb (pt_redex_at_root (PT_MP p1 p2)))
           (andb (pt_normal p1) (pt_normal p2))
  | PT_Nec _ p1 => pt_normal p1
  | _ => true
  end.


(** Atomic proof terms are always normal. *)

Lemma pt_normal_atomic : forall p,
  match p with
  | PT_MP _ _ | PT_Nec _ _ => False
  | _ => True
  end -> pt_normal p = true.
Proof.
  intros p H.
  destruct p; cbn; try reflexivity; contradiction.
Qed.


(** A normal proof term has no root redex. *)

Lemma pt_normal_no_root_redex : forall p,
  pt_normal p = true -> pt_redex_at_root p = false.
Proof.
  intros p H. destruct p; cbn in *; try reflexivity.
  apply Bool.andb_true_iff in H. destruct H as [Hneg _].
  apply Bool.negb_true_iff in Hneg. exact Hneg.
Qed.


(** ** Existence of normal forms.

    Every proof term reduces to a normal form via well-founded recursion
    on [proof_term_size].  We express this as: for every [p], there
    exists a [p'] such that [pt_reduces*] reaches [p'] and [pt_normal p']. *)

Inductive pt_reduces_star : proof_term -> proof_term -> Prop :=
  | PTRS_refl : forall p, pt_reduces_star p p
  | PTRS_step : forall p p' p'',
      pt_reduces p p' -> pt_reduces_star p' p'' -> pt_reduces_star p p''.


Lemma pt_reduces_star_size : forall p p',
  pt_reduces_star p p' -> proof_term_size p' <= proof_term_size p.
Proof.
  intros p p' H. induction H.
  - reflexivity.
  - pose proof (pt_reduces_decreases_size p p' H) as Hlt. lia.
Qed.


(** Subject reduction extends to multi-step reduction. *)

Theorem pt_reduces_star_subject_reduction : forall p p' phi,
  pt_reduces_star p p' ->
  denote_proof_term p = Some phi ->
  denote_proof_term p' = Some phi.
Proof.
  intros p p' phi Hstar. revert phi.
  induction Hstar; intro chi; intro Hd.
  - exact Hd.
  - apply IHHstar.
    exact (pt_reduces_subject_reduction p p' chi H Hd).
Qed.


(** Strong normalisation: every proof term has a [pt_reduces]-normal
    form reachable in finitely many steps. *)

Theorem pt_normal_form_exists : forall p,
  exists p', pt_reduces_star p p' /\
             (forall q, ~ pt_reduces p' q).
Proof.
  intros p.
  induction p as [p IH] using
    (well_founded_induction proof_term_no_infinite_reduction).
  destruct (classic (exists q, pt_reduces p q)) as [[q Hpq] | Hnone].
  - destruct (IH q Hpq) as [p' [Hstar Hnf]].
    exists p'. split.
    + exact (PTRS_step p q p' Hpq Hstar).
    + exact Hnf.
  - exists p. split.
    + apply PTRS_refl.
    + intros q Hcontra. apply Hnone. exists q. exact Hcontra.
Qed.


(** Combined with subject reduction: every provable formula has a
    proof-term derivation in normal form. *)

Theorem provable_has_normal_form_proof : forall phi,
  |- phi -> exists p, denote_proof_term p = Some phi /\
                      (forall q, ~ pt_reduces p q).
Proof.
  intros phi Hp.
  destruct (provable_to_proof_term phi Hp) as [pt Hd].
  destruct (pt_normal_form_exists pt) as [pt' [Hstar Hnf]].
  exists pt'. split.
  - exact (pt_reduces_star_subject_reduction pt pt' phi Hstar Hd).
  - exact Hnf.
Qed.


(******************************************************************************)
(* Multiset measure for PTRF_S contraction.                                    *)
(*                                                                            *)
(* The PTRF_S rule duplicates [x]:                                            *)
(*   (PT_S _ _ _) f g x  -->  (f x) (g x)                                     *)
(* Naive [proof_term_size] does not strictly decrease (LHS=4+|f|+|g|+|x|,    *)
(* RHS=3+|f|+|g|+2|x|).                                                       *)
(*                                                                            *)
(* We build a measure based on the *count of PT_S occurrences*, observing    *)
(* that PTRF_S contraction strictly decreases the count when [x] contains    *)
(* no internal [PT_S].  We then strengthen to a multiset-pair measure.        *)
(******************************************************************************)

Fixpoint pt_S_count (p : proof_term) : nat :=
  match p with
  | PT_S _ _ _ => 1
  | PT_MP p1 p2 => pt_S_count p1 + pt_S_count p2
  | PT_Nec _ p1 => pt_S_count p1
  | _ => 0
  end.


(** PTRF_S strictly decreases [pt_S_count] when [x] has no internal S. *)

Lemma pt_S_count_PTRF_S_decreases_when_x_S_free : forall phi psi chi f g x,
  pt_S_count x = 0 ->
  pt_S_count (PT_MP (PT_MP f x) (PT_MP g x))
    < pt_S_count (PT_MP (PT_MP (PT_MP (PT_S phi psi chi) f) g) x).
Proof.
  intros phi psi chi f g x Hx.
  cbn. rewrite Hx. lia.
Qed.


(** ** Subterm-size-pair multiset measure.

    For each PTRF_S-redex root in the term, record the pair
    [(|f|+|g|, |x|)].  Reduction by PTRF_S removes the entry at the
    contracted redex; the inner-of-[x] entries get duplicated, but the
    inner-of-[f]/[g] entries are unchanged.  When [x] has no internal
    PTRF_S redex, the multiset strictly shrinks under multi-set order. *)

Fixpoint pt_S_redex_pairs (p : proof_term) : list (nat * nat) :=
  match p with
  | PT_MP (PT_MP (PT_MP (PT_S _ _ _) f) g) x =>
      (proof_term_size f + proof_term_size g, proof_term_size x)
        :: pt_S_redex_pairs f ++ pt_S_redex_pairs g ++ pt_S_redex_pairs x
  | PT_MP p1 p2 => pt_S_redex_pairs p1 ++ pt_S_redex_pairs p2
  | PT_Nec _ p1 => pt_S_redex_pairs p1
  | _ => []
  end.


(** PTRF_S contraction strictly decreases the redex-pair-list length
    when [f], [g], and [x] are all S-redex-free.  Under this hypothesis,
    the LHS has exactly one S-redex (the root one), and the RHS has
    none — neither [PT_MP f x] nor [PT_MP g x] can be a redex because
    that would require [f] or [g] itself to start with
    [PT_MP (PT_MP (PT_S _ _ _) _) _], contradicting their S-redex-free
    assumption. *)

(** [pt_atomic]: a proof term is atomic if it is not a PT_MP or PT_Nec.
    Atomic terms have no internal MPs and so cannot themselves form an
    S-redex root, nor can wrapping them in a single MP create one. *)

Definition pt_atomic (p : proof_term) : Prop :=
  match p with
  | PT_MP _ _ | PT_Nec _ _ => False
  | _ => True
  end.


Lemma pt_atomic_pairs_empty : forall p,
  pt_atomic p -> pt_S_redex_pairs p = [].
Proof.
  intros p H.
  destruct p; cbn; try reflexivity; contradiction.
Qed.


(** When [f] and [g] are atomic, [PT_MP f x] and [PT_MP g x] cannot be
    PTRF_S-redexes (which would require [f] or [g] to be of shape
    [PT_MP (PT_MP (PT_S _ _ _) _) _]).  The pair-list reduces to
    [pt_S_redex_pairs x] in the non-redex MP case. *)

Lemma pt_S_redex_pairs_MP_atomic_f : forall f x,
  pt_atomic f ->
  pt_S_redex_pairs (PT_MP f x) = pt_S_redex_pairs x.
Proof.
  intros f x H. destruct f; cbn in *; try contradiction; reflexivity.
Qed.


(** Strict-decrease theorem: PTRF_S contraction strictly decreases the
    redex-pair-list length when [f] and [g] are atomic and [x] has no
    S-redex.  Under these hypotheses, the LHS has exactly one redex
    (the root one), and the RHS has none. *)

Theorem PTRF_S_decreases_pair_count_atomic_fg :
  forall phi psi chi f g x,
    pt_atomic f ->
    pt_atomic g ->
    pt_S_redex_pairs x = [] ->
    length (pt_S_redex_pairs (PT_MP (PT_MP f x) (PT_MP g x))) <
    length (pt_S_redex_pairs
              (PT_MP (PT_MP (PT_MP (PT_S phi psi chi) f) g) x)).
Proof.
  intros phi psi chi f g x Hf Hg Hx.
  pose proof (pt_atomic_pairs_empty f Hf) as Hf'.
  pose proof (pt_atomic_pairs_empty g Hg) as Hg'.
  destruct f; cbn in Hf; try contradiction;
    destruct g; cbn in Hg; try contradiction;
    cbn [pt_S_redex_pairs];
    rewrite Hx; cbn [length app]; lia.
Qed.


(******************************************************************************)
(* Newman's lemma (abstract): well-foundedness + local confluence => global  *)
(* confluence (Church-Rosser).                                                *)
(******************************************************************************)

Section NewmanLemma.


Variable A : Type.

Variable R : A -> A -> Prop.


Definition R_star (x y : A) : Prop :=
  exists n,
    (fix iter (k : nat) (a b : A) : Prop :=
       match k with
       | 0 => a = b
       | S k' => exists c, R a c /\ iter k' c b
       end) n x y.


Lemma R_star_refl : forall x, R_star x x.
Proof. intro x. exists 0. cbn. reflexivity. Qed.


Lemma R_star_step : forall x y z, R x y -> R_star y z -> R_star x z.
Proof.
  intros x y z H1 [n H2]. exists (S n). cbn. exists y. split; assumption.
Qed.


Lemma R_star_one : forall x y, R x y -> R_star x y.
Proof.
  intros x y H. apply (R_star_step _ y _ H). apply R_star_refl.
Qed.


Lemma R_star_trans : forall x y z, R_star x y -> R_star y z -> R_star x z.
Proof.
  intros x y z [n1 H1]. revert x y H1.
  induction n1 as [|n IH]; intros x y H1 Hyz.
  - cbn in H1. subst y. exact Hyz.
  - cbn in H1. destruct H1 as [c [Hxc Hcy]].
    apply (R_star_step _ c). exact Hxc. exact (IH c y Hcy Hyz).
Qed.


Definition locally_confluent : Prop :=
  forall x y1 y2, R x y1 -> R x y2 ->
    exists z, R_star y1 z /\ R_star y2 z.


Definition confluent : Prop :=
  forall x y1 y2, R_star x y1 -> R_star x y2 ->
    exists z, R_star y1 z /\ R_star y2 z.


(** Newman's lemma — proved by well-founded induction on x. *)

Theorem newman_lemma :
  well_founded (fun y x => R x y) ->
  locally_confluent ->
  confluent.
Proof.
  intros Hwf Hloc x.
  induction x as [x IH] using (well_founded_induction Hwf).
  intros y1 y2 [n1 H1] [n2 H2]. revert y1 y2 H1 H2.
  destruct n1 as [|n1].
  - cbn. intros y1 y2 Hxy1 H2. subst y1.
    exists y2. split; [exists n2; exact H2 | apply R_star_refl].
  - destruct n2 as [|n2].
    + cbn. intros y1 y2 [c1 [Hxc1 Hc1y1]] Hxy2. subst y2.
      exists y1. split. apply R_star_refl. exists (S n1). cbn.
      exists c1. split; assumption.
    + cbn. intros y1 y2 [c1 [Hxc1 Hc1y1]] [c2 [Hxc2 Hc2y2]].
      destruct (Hloc x c1 c2 Hxc1 Hxc2) as [d [Hc1d Hc2d]].
      assert (Hc1y1' : R_star c1 y1) by (exists n1; exact Hc1y1).
      assert (Hc2y2' : R_star c2 y2) by (exists n2; exact Hc2y2).
      destruct (IH c1 Hxc1 y1 d Hc1y1' Hc1d) as [e1 [Hy1e1 Hde1]].
      destruct (IH c2 Hxc2 y2 e1 Hc2y2'
                  (R_star_trans _ _ _ Hc2d Hde1)) as [e2 [Hy2e2 He1e2]].
      exists e2. split.
      * exact (R_star_trans _ _ _ Hy1e1 He1e2).
      * exact Hy2e2.
Qed.


End NewmanLemma.


(** ** Newman's lemma instantiated for [pt_reduces]. *)

Theorem newman_for_pt_reduces :
  (forall p q1 q2, pt_reduces p q1 -> pt_reduces p q2 ->
     exists r, R_star _ pt_reduces q1 r /\ R_star _ pt_reduces q2 r) ->
  forall p q1 q2,
    R_star _ pt_reduces p q1 -> R_star _ pt_reduces p q2 ->
    exists r, R_star _ pt_reduces q1 r /\ R_star _ pt_reduces q2 r.
Proof.
  intro Hloc.
  apply (newman_lemma _ pt_reduces).
  - exact proof_term_no_infinite_reduction.
  - exact Hloc.
Qed.


(******************************************************************************)
(* Local confluence of [pt_reduces]: critical-pair analysis.                   *)
(******************************************************************************)

(** Lift a single-step reduction to the reflexive-transitive closure. *)

Lemma pt_reduces_R_star : forall p q,
  pt_reduces p q -> R_star _ pt_reduces p q.
Proof. intros p q H. apply R_star_one. exact H. Qed.


Lemma pt_reduces_R_star_refl : forall p, R_star _ pt_reduces p p.
Proof. intro p. apply R_star_refl. Qed.


(** Trivial confluence: both sides equal. *)

Lemma pt_reduces_confluence_eq : forall (q : proof_term),
  exists r, R_star _ pt_reduces q r /\ R_star _ pt_reduces q r.
Proof.
  intros q. exists q. split; apply (R_star_refl _ pt_reduces).
Qed.


(** Reductions inside MP-left and MP-right operate on different
    sub-positions and hence commute trivially. *)

Lemma pt_reduces_orthogonal_MP : forall p1 p1' p2 p2',
  pt_reduces p1 p1' -> pt_reduces p2 p2' ->
  exists r, R_star _ pt_reduces (PT_MP p1' p2) r /\
            R_star _ pt_reduces (PT_MP p1 p2') r.
Proof.
  intros p1 p1' p2 p2' H1 H2.
  exists (PT_MP p1' p2'). split.
  - apply pt_reduces_R_star. exact (PTR_MP_right _ _ _ H2).
  - apply pt_reduces_R_star. exact (PTR_MP_left _ _ _ H1).
Qed.


(** Lifting [pt_reduces_R_star] under MP-left context. *)

Lemma R_star_under_MP_left : forall p1 p1' p2,
  R_star _ pt_reduces p1 p1' ->
  R_star _ pt_reduces (PT_MP p1 p2) (PT_MP p1' p2).
Proof.
  intros p1 p1' p2 [n H]. revert p1 H.
  induction n as [|n IH]; intros p1 H.
  - cbn in H. subst p1'. apply R_star_refl.
  - cbn in H. destruct H as [c [Hpc Hcp1']].
    apply (R_star_step _ _ _ (PT_MP c p2)).
    + exact (PTR_MP_left _ _ _ Hpc).
    + exact (IH c Hcp1').
Qed.


Lemma R_star_under_MP_right : forall p1 p2 p2',
  R_star _ pt_reduces p2 p2' ->
  R_star _ pt_reduces (PT_MP p1 p2) (PT_MP p1 p2').
Proof.
  intros p1 p2 p2' [n H]. revert p2 H.
  induction n as [|n IH]; intros p2 H.
  - cbn in H. subst p2'. apply R_star_refl.
  - cbn in H. destruct H as [c [Hpc Hcp2']].
    apply (R_star_step _ _ _ (PT_MP p1 c)).
    + exact (PTR_MP_right _ _ _ Hpc).
    + exact (IH c Hcp2').
Qed.


Lemma R_star_under_Nec : forall n p p',
  R_star _ pt_reduces p p' ->
  R_star _ pt_reduces (PT_Nec n p) (PT_Nec n p').
Proof.
  intros n p p' [k H]. revert p H.
  induction k as [|k IH]; intros p H.
  - cbn in H. subst p'. apply R_star_refl.
  - cbn in H. destruct H as [c [Hpc Hcp']].
    apply (R_star_step _ _ _ (PT_Nec n c)).
    + exact (PTR_Nec _ _ _ Hpc).
    + exact (IH c Hcp').
Qed.


(** ** Local confluence: structural induction on the first reduction.

    For each pair of single-step reductions [p → q1] and [p → q2], we
    construct a common reduct.  The proof uses inductive case analysis:
    the contextual rules (MP-left, MP-right, Nec) recurse on subterms;
    the root contractions (PTR_K, PTR_BoxK_Nec) are critical pairs. *)

(** Atomic axiom-constructor terms admit no reduction.  This vacuous-case
    lemma simplifies critical-pair analyses where an inner contextual
    reduction would have to act on a [PT_K]/[PT_BoxK]/etc. which has
    no operational behaviour. *)

Lemma pt_reduces_atomic_K : forall phi psi q,
  ~ pt_reduces (PT_K phi psi) q.
Proof.
  intros phi psi q H. inversion H.
Qed.


Lemma pt_reduces_atomic_S : forall phi psi chi q,
  ~ pt_reduces (PT_S phi psi chi) q.
Proof.
  intros phi psi chi q H. inversion H.
Qed.


Lemma pt_reduces_atomic_DN : forall phi q,
  ~ pt_reduces (PT_DN phi) q.
Proof.
  intros phi q H. inversion H.
Qed.


Lemma pt_reduces_atomic_BoxK : forall n phi psi q,
  ~ pt_reduces (PT_BoxK n phi psi) q.
Proof.
  intros n phi psi q H. inversion H.
Qed.


Lemma pt_reduces_atomic_Loeb : forall n phi q,
  ~ pt_reduces (PT_Loeb n phi) q.
Proof.
  intros n phi q H. inversion H.
Qed.


Lemma pt_reduces_atomic_Box4 : forall n phi q,
  ~ pt_reduces (PT_Box4 n phi) q.
Proof.
  intros n phi q H. inversion H.
Qed.


Lemma pt_reduces_atomic_Mon : forall n phi q,
  ~ pt_reduces (PT_Mon n phi) q.
Proof.
  intros n phi q H. inversion H.
Qed.


Lemma pt_reduces_atomic_NextCon : forall n q,
  ~ pt_reduces (PT_NextCon n) q.
Proof.
  intros n q H. inversion H.
Qed.


(** Inversion of a single reduction inside [PT_Nec n p]: the only rule
    that applies is [PTR_Nec] (since [PT_Nec] is not a [PT_MP]). *)

Lemma pt_reduces_Nec_inv : forall n p q,
  pt_reduces (PT_Nec n p) q ->
  exists p', q = PT_Nec n p' /\ pt_reduces p p'.
Proof.
  intros n p q H. inversion H. subst.
  eexists. split; [reflexivity | eassumption].
Qed.


(** Inversion of a single reduction inside [PT_MP a b]: either inner
    [a → a'] (PTR_MP_left), inner [b → b'] (PTR_MP_right), or a root
    contraction (PTR_K, PTR_BoxK_Nec) — the latter requiring [a] to
    have specific shapes. *)

Lemma pt_reduces_MP_inv : forall a b q,
  pt_reduces (PT_MP a b) q ->
    (exists a', q = PT_MP a' b /\ pt_reduces a a') \/
    (exists b', q = PT_MP a b' /\ pt_reduces b b') \/
    (exists phi psi p1, a = PT_MP (PT_K phi psi) p1 /\ q = p1) \/
    (exists n phi psi p1 p2,
       a = PT_MP (PT_BoxK n phi psi) (PT_Nec n p1) /\
       b = PT_Nec n p2 /\
       q = PT_Nec n (PT_MP p1 p2)).
Proof.
  intros a b q H. inversion H; subst.
  - left. eexists. split; [reflexivity | eassumption].
  - right. left. eexists. split; [reflexivity | eassumption].
  - right. right. left. eexists. eexists. eexists. split; reflexivity.
  - right. right. right. eexists. eexists. eexists. eexists. eexists.
    split; [reflexivity | split; reflexivity].
Qed.


(** ** Local confluence: critical-pair-by-critical-pair analysis.

    Strategy: structural induction on the first reduction [H1].  In
    each case, invert the second reduction [H2] using the dedicated
    [pt_reduces_MP_inv] / [pt_reduces_Nec_inv] inversion lemmas,
    yielding finitely many sub-cases.  Each sub-case is closed either
    by appeal to the inductive hypothesis (when both reductions are
    inside the same subterm), by orthogonality (when reductions are
    in disjoint sub-positions), or by explicit construction of a
    common reduct. *)

Lemma pt_reduces_local_confluence : forall p q1 q2,
  pt_reduces p q1 -> pt_reduces p q2 ->
  exists r, R_star _ pt_reduces q1 r /\ R_star _ pt_reduces q2 r.
Proof.
  intros p q1 q2 H1. revert q2.
  induction H1 as [a a' b H1a IHa
                  | a b b' H1b IHb
                  | n c c' H1c IHc
                  | phi psi p1 p2
                  | n phi psi p1 p2]; intros q2 H2.
  - (* H1 = PTR_MP_left a a' b: q1 = PT_MP a' b, with a → a'. *)
    apply pt_reduces_MP_inv in H2. destruct H2 as
      [[a'' [Eq Ha]] | [[b'' [Eq Hb]] | [[phi [psi [p1 [Eq1 Eq2]]]] |
       [n [phi [psi [p1 [p2 [Eq1 [Eq2 Eq3]]]]]]]]]].
    + (* H2: inner left a → a''.  Recurse via IHa. *)
      subst q2.
      destruct (IHa a'' Ha) as [r [Hr1 Hr2]].
      exists (PT_MP r b). split.
      * apply R_star_under_MP_left. exact Hr1.
      * apply R_star_under_MP_left. exact Hr2.
    + (* H2: inner right b → b''.  Orthogonal. *)
      subst q2.
      exists (PT_MP a' b''). split.
      * apply pt_reduces_R_star. exact (PTR_MP_right _ _ _ Hb).
      * apply pt_reduces_R_star. exact (PTR_MP_left _ _ _ H1a).
    + (* H2: PTR_K, so a = PT_MP (PT_K phi psi) p1, b = anything,
         q2 = p1. *)
      subst a. subst q2.
      apply pt_reduces_MP_inv in H1a. destruct H1a as
        [[a'' [Eq Hred]] | [[b'' [Eq Hred]] | [[phi' [psi' [p1' [Eq1 Eq2]]]] |
         [n' [phi' [psi' [p1' [p2' [Eq1 [Eq2 Eq3]]]]]]]]]].
      * (* a = PT_MP (PT_K phi psi) p1, inner left: PT_K → a''.  Vacuous. *)
        apply pt_reduces_atomic_K in Hred. contradiction.
      * (* Inner right: p1 → b''.  a' = PT_MP (PT_K phi psi) b''. *)
        subst a'.
        exists b''. split.
        -- apply pt_reduces_R_star. exact (PTR_K phi psi b'' b).
        -- apply pt_reduces_R_star. exact Hred.
      * (* Inner PTR_K shape: PT_MP (PT_K phi psi) p1 = PT_MP (PT_K phi' psi') p1'? Vacuous shape. *)
        discriminate Eq1.
      * discriminate Eq1.
    + (* H2: PTR_BoxK_Nec.  a = PT_MP (PT_BoxK n phi psi) (PT_Nec n p1),
         b = PT_Nec n p2, q2 = PT_Nec n (PT_MP p1 p2). *)
      subst a b q2.
      apply pt_reduces_MP_inv in H1a. destruct H1a as
        [[a'' [Eq Hred]] | [[b'' [Eq Hred]] | [[phi' [psi' [p1' [Eq1 Eq2]]]] |
         [n' [phi' [psi' [p1' [p2' [Eq1 [Eq2 Eq3]]]]]]]]]].
      * apply pt_reduces_atomic_BoxK in Hred. contradiction.
      * (* Inner right: PT_Nec n p1 → b''. *)
        apply pt_reduces_Nec_inv in Hred. destruct Hred as [p1'' [Eq' Hp1]].
        subst b''. subst a'.
        exists (PT_Nec n (PT_MP p1'' p2)). split.
        -- apply pt_reduces_R_star.
           exact (PTR_BoxK_Nec n phi psi p1'' p2).
        -- apply pt_reduces_R_star.
           apply PTR_Nec. exact (PTR_MP_left _ _ _ Hp1).
      * discriminate Eq1.
      * discriminate Eq1.
  - (* H1 = PTR_MP_right a b b': q1 = PT_MP a b'. *)
    apply pt_reduces_MP_inv in H2. destruct H2 as
      [[a'' [Eq Ha]] | [[b'' [Eq Hb]] | [[phi [psi [p1 [Eq1 Eq2]]]] |
       [n [phi [psi [p1 [p2 [Eq1 [Eq2 Eq3]]]]]]]]]].
    + (* Inner left a → a''.  Orthogonal. *)
      subst q2.
      exists (PT_MP a'' b'). split.
      * apply pt_reduces_R_star. exact (PTR_MP_left _ _ _ Ha).
      * apply pt_reduces_R_star. exact (PTR_MP_right _ _ _ H1b).
    + (* Inner right: recurse. *)
      subst q2.
      destruct (IHb b'' Hb) as [r [Hr1 Hr2]].
      exists (PT_MP a r). split.
      * apply R_star_under_MP_right. exact Hr1.
      * apply R_star_under_MP_right. exact Hr2.
    + (* PTR_K: a = PT_MP (PT_K phi psi) p1, q2 = p1. *)
      subst a q2.
      exists p1. split.
      * apply pt_reduces_R_star. exact (PTR_K phi psi p1 b').
      * apply R_star_refl.
    + (* PTR_BoxK_Nec: a = PT_MP (PT_BoxK n phi psi) (PT_Nec n p1),
         b = PT_Nec n p2, q2 = PT_Nec n (PT_MP p1 p2).
         q1 = PT_MP a b' where b → b'. *)
      subst a b q2.
      (* H1b : pt_reduces (PT_Nec n p2) b'.  By Nec inversion. *)
      apply pt_reduces_Nec_inv in H1b. destruct H1b as [p2' [Eq Hp2]].
      subst b'.
      exists (PT_Nec n (PT_MP p1 p2')). split.
      * apply pt_reduces_R_star.
        exact (PTR_BoxK_Nec n phi psi p1 p2').
      * apply pt_reduces_R_star.
        apply PTR_Nec. exact (PTR_MP_right _ _ _ Hp2).
  - (* H1 = PTR_Nec n c c': q1 = PT_Nec n c'. *)
    apply pt_reduces_Nec_inv in H2. destruct H2 as [c'' [Eq Hc]].
    subst q2.
    destruct (IHc c'' Hc) as [r [Hr1 Hr2]].
    exists (PT_Nec n r). split.
    + apply R_star_under_Nec. exact Hr1.
    + apply R_star_under_Nec. exact Hr2.
  - (* H1 = PTR_K phi psi p1 p2: q1 = p1. *)
    apply pt_reduces_MP_inv in H2. destruct H2 as
      [[a'' [Eq Ha]] | [[b'' [Eq Hb]] | [[phi' [psi' [p1' [Eq1 Eq2]]]] |
       [n' [phi' [psi' [p1' [p2' [Eq1 [Eq2 Eq3]]]]]]]]]].
    + (* Inner left: PT_MP (PT_K phi psi) p1 → a''. *)
      apply pt_reduces_MP_inv in Ha. destruct Ha as
        [[a''' [Eq' Hred]] | [[b''' [Eq' Hred]] | [[phi'' [psi'' [p1'' [Eq1 Eq2]]]] |
         [n'' [phi'' [psi'' [p1'' [p2'' [Eq1 [Eq2 Eq3]]]]]]]]]].
      * apply pt_reduces_atomic_K in Hred. contradiction.
      * subst a'' q2.
        exists b'''. split.
        -- apply pt_reduces_R_star. exact Hred.
        -- apply pt_reduces_R_star. exact (PTR_K phi psi b''' p2).
      * discriminate Eq1.
      * discriminate Eq1.
    + (* Inner right: p2 → b''. *)
      subst q2.
      exists p1. split.
      * apply R_star_refl.
      * apply pt_reduces_R_star. exact (PTR_K phi psi p1 b'').
    + (* PTR_K twice: same shape, q2 = p1. *)
      injection Eq1 as Eq1a Eq1b. subst phi' psi' p1'.
      subst q2.
      exists p1. split; apply R_star_refl.
    + (* PTR_BoxK_Nec: shape mismatch. *)
      discriminate Eq1.
  - (* H1 = PTR_BoxK_Nec n phi psi p1 p2:
       q1 = PT_Nec n (PT_MP p1 p2). *)
    apply pt_reduces_MP_inv in H2. destruct H2 as
      [[a'' [Eq Ha]] | [[b'' [Eq Hb]] | [[phi' [psi' [p1' [Eq1 Eq2]]]] |
       [n' [phi' [psi' [p1' [p2' [Eq1 [Eq2 Eq3]]]]]]]]]].
    + (* Inner left: PT_MP (PT_BoxK n phi psi) (PT_Nec n p1) → a''. *)
      apply pt_reduces_MP_inv in Ha. destruct Ha as
        [[a''' [Eq' Hred]] | [[b''' [Eq' Hred]] | [[phi'' [psi'' [p1'' [Eq1 Eq2]]]] |
         [n'' [phi'' [psi'' [p1'' [p2'' [Eq1 [Eq2 Eq3]]]]]]]]]].
      * apply pt_reduces_atomic_BoxK in Hred. contradiction.
      * (* Inner right: PT_Nec n p1 → b'''.  By Nec inversion: p1 → p1_*. *)
        apply pt_reduces_Nec_inv in Hred. destruct Hred as [p1_ [Eq'' Hp1]].
        subst b''' a'' q2.
        exists (PT_Nec n (PT_MP p1_ p2)). split.
        -- apply pt_reduces_R_star.
           apply PTR_Nec. exact (PTR_MP_left _ _ _ Hp1).
        -- apply pt_reduces_R_star.
           exact (PTR_BoxK_Nec n phi psi p1_ p2).
      * discriminate Eq1.
      * discriminate Eq1.
    + (* Inner right: PT_Nec n p2 → b''.  By Nec inversion: p2 → p2_*. *)
      apply pt_reduces_Nec_inv in Hb. destruct Hb as [p2_ [Eq' Hp2]].
      subst b'' q2.
      exists (PT_Nec n (PT_MP p1 p2_)). split.
      * apply pt_reduces_R_star.
        apply PTR_Nec. exact (PTR_MP_right _ _ _ Hp2).
      * apply pt_reduces_R_star.
        exact (PTR_BoxK_Nec n phi psi p1 p2_).
    + (* PTR_K: shape mismatch. *)
      discriminate Eq1.
    + (* PTR_BoxK_Nec twice: same shape, q2 = q1. *)
      inversion Eq1; subst.
      inversion Eq2; subst.
      exists (PT_Nec n' (PT_MP p1' p2')). split; apply R_star_refl.
Qed.


(** Confluence (Church-Rosser) of [pt_reduces]: from local confluence
    plus well-foundedness via Newman's lemma. *)

Theorem pt_reduces_church_rosser :
  forall p q1 q2,
    R_star _ pt_reduces p q1 -> R_star _ pt_reduces p q2 ->
    exists r, R_star _ pt_reduces q1 r /\ R_star _ pt_reduces q2 r.
Proof.
  apply newman_for_pt_reduces.
  exact pt_reduces_local_confluence.
Qed.


(******************************************************************************)
(* Strong normalisation of [pt_reduces_full] on the S-free subset.            *)
(*                                                                            *)
(* The full pt_reduces_full system includes PTRF_S, which duplicates the     *)
(* third argument [x] and so does not strictly decrease [proof_term_size]    *)
(* in general.  Howard-style ordinal measures handle this for typed         *)
(* combinatory logic but are research-level for the present untyped         *)
(* polymodal calculus.                                                        *)
(*                                                                            *)
(* On the S-free subset (terms with no [PT_S] occurrence anywhere), [PTRF_S] *)
(* never fires.  All remaining rules strictly decrease [proof_term_size],   *)
(* hence well-foundedness holds via the size measure.                       *)
(******************************************************************************)

(** Note: [pt_S_count] does NOT decrease monotonically under
    [pt_reduces_full] in general — PTRF_S duplicates [x] and can
    therefore increase the count when [x] contains multiple [PT_S]
    occurrences.  However, [pt_S_count = 0] (S-free) IS preserved:
    no rule introduces a [PT_S] from nothing, and PTRF_S cannot fire
    when the LHS is S-free. *)

Lemma pt_S_count_pt_reduces_le : forall p p',
  pt_reduces p p' -> pt_S_count p' <= pt_S_count p.
Proof.
  intros p p' H. induction H; cbn; lia.
Qed.


Lemma pt_S_free_preserved : forall p p',
  pt_S_count p = 0 ->
  pt_reduces_full p p' ->
  pt_S_count p' = 0.
Proof.
  intros p p' Hp H. revert Hp.
  induction H; intro Hp; cbn in *.
  - (* PTRF_orig: pt_reduces; uses pt_S_count_pt_reduces_le. *)
    pose proof (pt_S_count_pt_reduces_le _ _ H). lia.
  - (* PTRF_MP_left *)
    assert (pt_S_count p1 = 0) by lia.
    pose proof (IHpt_reduces_full H0). lia.
  - (* PTRF_MP_right *)
    assert (pt_S_count p2 = 0) by lia.
    pose proof (IHpt_reduces_full H0). lia.
  - (* PTRF_Nec *)
    pose proof (IHpt_reduces_full Hp). lia.
  - (* PTRF_S: PT_S in LHS contradicts Hp = 0. *)
    discriminate Hp.
  - (* PTRF_DN_K *)
    lia.
Qed.


(** Strict size decrease under [pt_reduces_full] when [pt_S_count = 0].
    On S-free terms, PTRF_S cannot fire, and the remaining rules each
    strictly decrease [proof_term_size]. *)

Lemma pt_reduces_full_decreases_size_S_free : forall p p',
  pt_S_count p = 0 ->
  pt_reduces_full p p' ->
  proof_term_size p' < proof_term_size p.
Proof.
  intros p p' Hp H. revert Hp.
  induction H; intro Hp; cbn in *.
  - apply pt_reduces_decreases_size. exact H.
  - lia.
  - lia.
  - lia.
  - (* PTRF_S: but pt_S_count of LHS includes the PT_S, so ≥ 1, contradicting Hp. *)
    cbn in Hp. discriminate Hp.
  - (* PTRF_DN_K *) lia.
Qed.


(** Strong normalisation: on the S-free subset, [pt_reduces_full] is
    well-founded (descending chains terminate). *)

Theorem pt_reduces_full_SN_S_free : forall p,
  pt_S_count p = 0 ->
  Acc (fun y x => pt_S_count x = 0 /\ pt_reduces_full x y) p.
Proof.
  intro p.
  induction p as [p IH] using
    (well_founded_induction
       (Wf_nat.well_founded_lt_compat _ proof_term_size _ (fun x y H => H))).
  intros Hp. apply Acc_intro. intros y [_ Hred].
  apply IH.
  - exact (pt_reduces_full_decreases_size_S_free p y Hp Hred).
  - exact (pt_S_free_preserved p y Hp Hred).
Qed.


(** Useful corollary: every S-free proof term has only finitely many
    reducts under pt_reduces_full's transitive closure. *)

Theorem pt_reduces_full_S_free_terminates :
  well_founded (fun y x => pt_S_count x = 0 /\ pt_reduces_full x y).
Proof.
  intro p.
  destruct (Nat.eq_dec (pt_S_count p) 0) as [Hp|Hnp].
  - exact (pt_reduces_full_SN_S_free p Hp).
  - apply Acc_intro. intros y [Hy _]. exfalso. apply Hnp. exact Hy.
Qed.


(** [proof_term_ordinal] of an atomic proof term is [OZero]. *)

Lemma proof_term_ordinal_atomic : forall p,
  pt_atomic p -> proof_term_ordinal p = OZero.
Proof.
  intros p H. destruct p; cbn; try reflexivity; contradiction.
Qed.


(** [proof_term_ordinal] of [PT_K phi psi] (an atom) is [OZero]. *)

Lemma proof_term_ordinal_K : forall phi psi,
  proof_term_ordinal (PT_K phi psi) = OZero.
Proof. intros. cbn. reflexivity. Qed.


(** [proof_term_ordinal] of [PT_BoxK n phi psi]: also OZero (atom). *)

Lemma proof_term_ordinal_BoxK : forall n phi psi,
  proof_term_ordinal (PT_BoxK n phi psi) = OZero.
Proof. intros. cbn. reflexivity. Qed.


(** Subterm bound: every subterm's ordinal is bounded by the whole. *)

Lemma proof_term_ordinal_left_lt : forall p1 p2,
  ord_lt (proof_term_ordinal p1) (proof_term_ordinal (PT_MP p1 p2)).
Proof.
  intros p1 p2. cbn.
  exact (ord_lt_OCons_self (proof_term_ordinal p1) (proof_term_ordinal p2)).
Qed.


Lemma proof_term_ordinal_decrease_MP_left : forall p1 p1' p2,
  ord_lt (proof_term_ordinal p1') (proof_term_ordinal p1) ->
  ord_lt (proof_term_ordinal (PT_MP p1' p2)) (proof_term_ordinal (PT_MP p1 p2)).
Proof.
  intros p1 p1' p2 H. cbn. apply ord_lt_OCons_head. exact H.
Qed.


Lemma proof_term_ordinal_decrease_MP_right : forall p1 p2 p2',
  ord_lt (proof_term_ordinal p2') (proof_term_ordinal p2) ->
  ord_lt (proof_term_ordinal (PT_MP p1 p2')) (proof_term_ordinal (PT_MP p1 p2)).
Proof.
  intros p1 p2 p2' H. cbn. apply ord_lt_OCons_tail. exact H.
Qed.


Lemma proof_term_ordinal_decrease_Nec : forall n p p',
  ord_lt (proof_term_ordinal p') (proof_term_ordinal p) ->
  ord_lt (proof_term_ordinal (PT_Nec n p')) (proof_term_ordinal (PT_Nec n p)).
Proof.
  intros n p p' H. cbn. apply ord_lt_OCons_tail. exact H.
Qed.


Theorem proof_term_ordinal_image_bounded : forall p,
  exists o : ord, proof_term_ordinal p = o.
Proof. intro p. exists (proof_term_ordinal p). reflexivity. Qed.


Definition proof_term_ord_v2 (p : proof_term) : ord :=
  nat_to_ord_chain (proof_term_size p).


Theorem proof_term_ord_v2_strictly_decreases : forall p p',
  pt_reduces p p' ->
  ord_lt (proof_term_ord_v2 p') (proof_term_ord_v2 p).
Proof.
  intros p p' H. unfold proof_term_ord_v2.
  apply nat_to_ord_chain_lt.
  exact (pt_reduces_decreases_size p p' H).
Qed.


Theorem proof_term_ord_v2_image_finite : forall p,
  exists o : ord, proof_term_ord_v2 p = o /\
    (exists n, o = nat_to_ord_chain n).
Proof.
  intro p. unfold proof_term_ord_v2.
  exists (nat_to_ord_chain (proof_term_size p)). split; [reflexivity|].
  exists (proof_term_size p). reflexivity.
Qed.





(** Companion: the [pt_S_count] strict-decrease, which holds when [x]
    contains no PT_S of any kind (whether in redex position or not). *)

Theorem PTRF_S_decreases_S_count_when_x_S_free :
  forall phi psi chi f g x,
    pt_S_count x = 0 ->
    pt_S_count (PT_MP (PT_MP f x) (PT_MP g x))
      < pt_S_count (PT_MP (PT_MP (PT_MP (PT_S phi psi chi) f) g) x).
Proof.
  exact pt_S_count_PTRF_S_decreases_when_x_S_free.
Qed.

