(** Tiling.Propositional - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.

From Tiling Require Import Syntax.
From Tiling Require Import Provable.


(** ** Trivial fragment.

    [ProvableProp] is the sub-calculus of [Provable] that uses only
    the classical propositional axioms [K], [S], [DN] and modus
    ponens, with no modal axioms or necessitation rule.  By
    construction this is the standard Hilbert axiomatisation of
    classical propositional logic (cf. Hilbert-Bernays 1934).

    Below: structural embedding into [Provable]; soundness with
    respect to the classical truth-table semantics; modus ponens for
    [eval] confirming the rule is sound; and the lemma that
    [ProvableProp] proofs cannot escape into modal-formula territory
    via their conclusion. *)

Inductive ProvableProp : Form -> Prop :=
  | PAx_K : forall phi psi,
      ProvableProp (Impl phi (Impl psi phi))
  | PAx_S : forall phi psi chi,
      ProvableProp (Impl (Impl phi (Impl psi chi))
                         (Impl (Impl phi psi) (Impl phi chi)))
  | PAx_DN : forall phi,
      ProvableProp (Impl (Neg (Neg phi)) phi)
  | PMP : forall phi psi,
      ProvableProp (Impl phi psi) -> ProvableProp phi -> ProvableProp psi.


Theorem trivial_in_provable : forall phi, ProvableProp phi -> |- phi.
Proof.
  intros phi H. induction H.
  - apply Ax_K.
  - apply Ax_S.
  - apply Ax_DN.
  - exact (MP _ _ IHProvableProp1 IHProvableProp2).
Qed.


Theorem trivial_classically_sound : forall val phi,
  ProvableProp phi -> eval val phi = true.
Proof.
  intros val phi H. induction H; simpl in *.
  - destruct (eval val phi); destruct (eval val psi); reflexivity.
  - destruct (eval val phi); destruct (eval val psi);
      destruct (eval val chi); reflexivity.
  - destruct (eval val phi); reflexivity.
  - destruct (eval val phi); simpl in IHProvableProp1.
    + exact IHProvableProp1.
    + discriminate IHProvableProp2.
Qed.


Lemma PP_id : forall phi, ProvableProp (Impl phi phi).
Proof.
  intro phi.
  exact (PMP _ _
          (PMP _ _ (PAx_S phi (Impl phi phi) phi)
                       (PAx_K phi (Impl phi phi)))
          (PAx_K phi phi)).
Qed.


Lemma PP_weaken : forall phi psi,
  ProvableProp phi -> ProvableProp (Impl psi phi).
Proof. intros phi psi Hphi. exact (PMP _ _ (PAx_K phi psi) Hphi). Qed.


Lemma PP_compose : forall phi psi chi,
  ProvableProp (Impl phi psi) ->
  ProvableProp (Impl psi chi) ->
  ProvableProp (Impl phi chi).
Proof.
  intros phi psi chi Hpq Hqr.
  pose proof (PAx_S phi psi chi) as Hs.
  pose proof (PP_weaken _ phi Hqr) as Hpqr.
  exact (PMP _ _ (PMP _ _ Hs Hpqr) Hpq).
Qed.


Lemma PP_perm : forall phi psi chi,
  ProvableProp (Impl phi (Impl psi chi)) ->
  ProvableProp (Impl psi (Impl phi chi)).
Proof.
  intros phi psi chi H.
  pose proof (PAx_S phi psi chi) as Hs.
  pose proof (PMP _ _ Hs H) as H1.
  pose proof (PAx_K psi phi) as Hk.
  exact (PP_compose _ _ _ Hk H1).
Qed.


Lemma PP_DN_intro : forall phi, ProvableProp (Impl phi (Neg (Neg phi))).
Proof.
  intro phi. unfold Neg.
  pose proof (PP_id (Impl phi Bot)) as Hid.
  exact (PP_perm _ _ _ Hid).
Qed.


Lemma PP_explosion : forall phi, ProvableProp (Impl Bot phi).
Proof.
  intro phi.
  pose proof (PAx_K Bot (Neg phi)) as Hk.
  pose proof (PAx_DN phi) as HDN.
  exact (PP_compose _ _ _ Hk HDN).
Qed.


Lemma PP_compose_internal : forall phi psi chi,
  ProvableProp (Impl (Impl psi chi) (Impl (Impl phi psi) (Impl phi chi))).
Proof.
  intros phi psi chi.
  pose proof (PAx_K (Impl psi chi) phi) as Hk.
  pose proof (PAx_S phi psi chi) as Hs.
  exact (PP_compose _ _ _ Hk Hs).
Qed.


Lemma PP_perm_internal : forall a b c,
  ProvableProp (Impl (Impl a (Impl b c)) (Impl b (Impl a c))).
Proof.
  intros a b c.
  pose proof (PAx_S a b c) as H_S.
  pose proof (PAx_S (Impl a (Impl b c)) (Impl a b) (Impl a c)) as H_S2.
  pose proof (PMP _ _ H_S2 H_S) as H1.
  pose proof (PAx_K b a) as H_K1.
  pose proof (PAx_K (Impl a b) (Impl a (Impl b c))) as H_K2.
  pose proof (PP_compose _ _ _ H_K1 H_K2) as H2.
  pose proof (PP_compose _ _ _ H2 H1) as H3.
  exact (PP_perm _ _ _ H3).
Qed.


Lemma PP_contrapos : forall phi psi,
  ProvableProp (Impl (Impl phi psi) (Impl (Neg psi) (Neg phi))).
Proof.
  intros phi psi. unfold Neg.
  exact (PP_perm _ _ _ (PP_compose_internal phi psi Bot)).
Qed.


Lemma PP_neg_to_anything : forall phi psi,
  ProvableProp (Impl (Neg phi) (Impl phi psi)).
Proof.
  intros phi psi. unfold Neg.
  pose proof (PP_compose_internal phi Bot psi) as Hci.
  pose proof (PP_explosion psi) as Hex.
  exact (PMP _ _ Hci Hex).
Qed.


Lemma PP_X_negY_to_neg_impl : forall X Y,
  ProvableProp (Impl X (Impl (Neg Y) (Neg (Impl X Y)))).
Proof.
  intros X Y.
  pose proof (PP_perm (Impl X Y) X Y (PP_id (Impl X Y))) as f1.
  pose proof (PP_DN_intro Y) as f2.
  pose proof (PP_compose_internal (Impl X Y) Y (Neg (Neg Y))) as Hci.
  pose proof (PMP _ _ Hci f2) as f3.
  pose proof (PP_compose _ _ _ f1 f3) as f4.
  pose proof (PP_perm_internal (Impl X Y) (Neg Y) Bot) as f5.
  exact (PP_compose _ _ _ f4 f5).
Qed.


Inductive ProvablePropH : list Form -> Form -> Prop :=
  | PHhyp : forall G phi, In phi G -> ProvablePropH G phi
  | PHthm : forall G phi, ProvableProp phi -> ProvablePropH G phi
  | PHMP : forall G phi psi,
      ProvablePropH G (Impl phi psi) -> ProvablePropH G phi -> ProvablePropH G psi.


Lemma PHweaken : forall G G' phi,
  (forall psi, In psi G -> In psi G') ->
  ProvablePropH G phi -> ProvablePropH G' phi.
Proof.
  intros G G' phi Hsub H. revert G' Hsub.
  induction H; intros G' Hsub.
  - apply PHhyp. apply Hsub. exact H.
  - apply PHthm. exact H.
  - exact (PHMP _ _ _ (IHProvablePropH1 _ Hsub) (IHProvablePropH2 _ Hsub)).
Qed.


Theorem PHdeduction : forall G phi psi,
  ProvablePropH (phi :: G) psi -> ProvablePropH G (Impl phi psi).
Proof.
  intros G phi psi H.
  remember (phi :: G) as G' eqn:HG.
  revert G phi HG.
  induction H; intros G' phi' HG'.
  - subst G. simpl in H. destruct H as [Heq | Hin].
    + subst phi. apply PHthm. apply PP_id.
    + apply PHMP with phi.
      * apply PHthm. apply PAx_K.
      * apply PHhyp. exact Hin.
  - apply PHthm. exact (PMP _ _ (PAx_K phi phi') H).
  - subst G.
    pose proof (IHProvablePropH1 G' phi' eq_refl) as H1.
    pose proof (IHProvablePropH2 G' phi' eq_refl) as H2.
    apply PHMP with (Impl phi' phi).
    + apply PHMP with (Impl phi' (Impl phi psi)).
      * apply PHthm. exact (PAx_S phi' phi psi).
      * exact H1.
    + exact H2.
Qed.


Definition gamma (val : nat -> bool) (phi : Form) : Form :=
  if eval val phi then phi else Neg phi.


Fixpoint gamma_list (val : nat -> bool) (vars : list nat) : list Form :=
  match vars with
  | [] => []
  | p :: rest => gamma val (Var p) :: gamma_list val rest
  end.


Lemma gamma_list_in : forall val vars p,
  In p vars -> In (gamma val (Var p)) (gamma_list val vars).
Proof.
  intros val vars p Hin. induction vars as [|q rest IH].
  - destruct Hin.
  - simpl in Hin. destruct Hin as [Heq | Hin'].
    + subst q. simpl. left. reflexivity.
    + simpl. right. apply IH. exact Hin'.
Qed.


Lemma gamma_list_app : forall val l1 l2 phi,
  In phi (gamma_list val l1) -> In phi (gamma_list val (l1 ++ l2)).
Proof.
  intros val l1 l2 phi. induction l1 as [|q rest IH]; simpl.
  - intro H. destruct H.
  - intros [Heq | Hin].
    + left. exact Heq.
    + right. apply IH. exact Hin.
Qed.


Lemma gamma_list_app_r : forall val l1 l2 phi,
  In phi (gamma_list val l2) -> In phi (gamma_list val (l1 ++ l2)).
Proof.
  intros val l1 l2 phi. induction l1 as [|q rest IH]; simpl.
  - intro H. exact H.
  - intro H. right. apply IH. exact H.
Qed.


Theorem kalmar : forall val phi,
  box_free phi -> ProvablePropH (gamma_list val (free_vars phi)) (gamma val phi).
Proof.
  intros val phi Hbf. induction phi as [p | | X IHX Y IHY | n psi IHpsi].
  - simpl. unfold gamma. simpl. apply PHhyp.
    destruct (val p); simpl; left; reflexivity.
  - simpl. unfold gamma. simpl. apply PHthm.
    pose proof (PP_id Bot) as Hid.
    exact Hid.
  - simpl in Hbf. destruct Hbf as [HbfX HbfY].
    pose proof (IHX HbfX) as IHX'.
    pose proof (IHY HbfY) as IHY'.
    pose proof (PHweaken _ (gamma_list val (free_vars X ++ free_vars Y)) _
                  (gamma_list_app val (free_vars X) (free_vars Y)) IHX') as IHX''.
    pose proof (PHweaken _ (gamma_list val (free_vars X ++ free_vars Y)) _
                  (gamma_list_app_r val (free_vars X) (free_vars Y)) IHY') as IHY''.
    simpl. unfold gamma at 1.
    destruct (eval val (Impl X Y)) eqn:HevImp.
    + simpl in HevImp.
      destruct (eval val X) eqn:HevX; destruct (eval val Y) eqn:HevY;
        simpl in HevImp; try discriminate.
      * apply PHMP with Y.
        -- apply PHthm. exact (PAx_K Y X).
        -- unfold gamma in IHY''. rewrite HevY in IHY''. exact IHY''.
      * apply PHMP with Y.
        -- apply PHthm. exact (PAx_K Y X).
        -- unfold gamma in IHY''. rewrite HevY in IHY''. exact IHY''.
      * apply PHMP with (Neg X).
        -- apply PHthm. exact (PP_neg_to_anything X Y).
        -- unfold gamma in IHX''. rewrite HevX in IHX''. exact IHX''.
    + simpl in HevImp.
      destruct (eval val X) eqn:HevX; destruct (eval val Y) eqn:HevY;
        simpl in HevImp; try discriminate.
      apply PHMP with (Neg Y).
      * apply PHMP with X.
        -- apply PHthm. exact (PP_X_negY_to_neg_impl X Y).
        -- unfold gamma in IHX''. rewrite HevX in IHX''. exact IHX''.
      * unfold gamma in IHY''. rewrite HevY in IHY''. exact IHY''.
  - simpl in Hbf. contradiction.
Qed.


Lemma PP_consequentia_mirabilis : forall chi,
  ProvableProp (Impl (Impl (Neg chi) chi) chi).
Proof.
  intro chi.
  pose proof (PP_id (Impl chi Bot)) as Hid.
  pose proof (PAx_S (Impl chi Bot) chi Bot) as Hs.
  pose proof (PMP _ _ Hs Hid) as Hstep1.
  pose proof (PAx_DN chi) as HDN.
  exact (PP_compose _ _ _ Hstep1 HDN).
Qed.


Lemma PHelim_var : forall G p Q,
  ProvablePropH (Var p :: G) Q ->
  ProvablePropH (Neg (Var p) :: G) Q ->
  ProvablePropH G Q.
Proof.
  intros G p Q Hpos Hneg.
  pose proof (PHdeduction _ _ _ Hpos) as Hpd.
  pose proof (PHdeduction _ _ _ Hneg) as Hnd.
  pose proof (PHMP _ _ _ (PHthm _ _ (PP_contrapos (Var p) Q)) Hpd) as Hcontrap.
  pose proof (PHthm G _ (PP_compose_internal (Neg Q) (Neg (Var p)) Q)) as Hcc.
  pose proof (PHMP _ _ _ Hcc Hnd) as Hcc'.
  pose proof (PHMP _ _ _ Hcc' Hcontrap) as Hnegq.
  apply PHMP with (Impl (Neg Q) Q).
  - apply PHthm. apply PP_consequentia_mirabilis.
  - exact Hnegq.
Qed.


Lemma gamma_list_ext_on : forall val val' L,
  (forall q, In q L -> val q = val' q) ->
  gamma_list val L = gamma_list val' L.
Proof.
  intros val val' L Hext. induction L as [|p rest IH]; simpl.
  - reflexivity.
  - f_equal.
    + unfold gamma. simpl. rewrite (Hext p).
      * reflexivity.
      * left. reflexivity.
    + apply IH. intros q Hq. apply Hext. right. exact Hq.
Qed.


Lemma elim_nodup : forall vars G phi,
  NoDup vars ->
  (forall val, ProvablePropH (gamma_list val vars ++ G) phi) ->
  ProvablePropH G phi.
Proof.
  intro vars. induction vars as [|p rest IH]; intros G phi Hnd Hhyp.
  - simpl in Hhyp. apply (Hhyp (fun _ => false)).
  - inversion Hnd as [|p' rest' Hnp Hndr Heq]. subst p' rest'.
    apply (IH G phi Hndr).
    intro val.
    set (val_pos := fun q : nat => if Nat.eqb q p then true else val q).
    set (val_neg := fun q : nat => if Nat.eqb q p then false else val q).
    assert (Hag_pos : forall q, In q rest -> val_pos q = val q).
    { intros q Hin. unfold val_pos. destruct (Nat.eqb_spec q p).
      - subst q. contradiction.
      - reflexivity. }
    assert (Hag_neg : forall q, In q rest -> val_neg q = val q).
    { intros q Hin. unfold val_neg. destruct (Nat.eqb_spec q p).
      - subst q. contradiction.
      - reflexivity. }
    pose proof (Hhyp val_pos) as Hp.
    pose proof (Hhyp val_neg) as Hn.
    simpl in Hp. simpl in Hn.
    unfold gamma in Hp at 1. unfold gamma in Hn at 1.
    simpl in Hp. simpl in Hn.
    assert (Hpos_p : val_pos p = true).
    { unfold val_pos. rewrite Nat.eqb_refl. reflexivity. }
    assert (Hneg_p : val_neg p = false).
    { unfold val_neg. rewrite Nat.eqb_refl. reflexivity. }
    rewrite Hpos_p in Hp. rewrite Hneg_p in Hn.
    rewrite (gamma_list_ext_on val_pos val rest Hag_pos) in Hp.
    rewrite (gamma_list_ext_on val_neg val rest Hag_neg) in Hn.
    apply (PHelim_var _ p _ Hp Hn).
Qed.


Lemma PHnohyp_to_PP : forall phi, ProvablePropH [] phi -> ProvableProp phi.
Proof.
  intros phi H. remember (@nil Form) as G eqn:HG.
  induction H as [G' phi Hin | G' phi Hphi | G' phi psi H1 IH1 H2 IH2].
  - subst G'. simpl in Hin. destruct Hin.
  - exact Hphi.
  - exact (PMP _ _ (IH1 HG) (IH2 HG)).
Qed.


Lemma gamma_list_in_nodup : forall val L psi,
  In psi (gamma_list val L) -> In psi (gamma_list val (nodup Nat.eq_dec L)).
Proof.
  intros val L psi Hin. induction L as [|p rest IH]; simpl in *.
  - destruct Hin.
  - destruct (in_dec Nat.eq_dec p rest) as [Hin_p | Hnin_p].
    + destruct Hin as [Heq | Hin'].
      * subst psi. apply gamma_list_in. apply (nodup_In Nat.eq_dec). exact Hin_p.
      * apply IH. exact Hin'.
    + simpl. destruct Hin as [Heq | Hin'].
      * left. exact Heq.
      * right. apply IH. exact Hin'.
Qed.


Theorem prop_completeness : forall phi,
  box_free phi -> classical_valid phi -> ProvableProp phi.
Proof.
  intros phi Hbf Hval.
  pose (vars := nodup Nat.eq_dec (free_vars phi)).
  assert (Hnd : NoDup vars) by apply NoDup_nodup.
  apply PHnohyp_to_PP.
  apply (elim_nodup vars [] phi Hnd).
  intro val.
  rewrite app_nil_r.
  pose proof (kalmar val phi Hbf) as Hk.
  unfold classical_valid in Hval.
  unfold gamma in Hk. rewrite (Hval val) in Hk.
  apply (PHweaken (gamma_list val (free_vars phi)) (gamma_list val vars)).
  - intros psi Hin. apply gamma_list_in_nodup. exact Hin.
  - exact Hk.
Qed.


Fixpoint all_bool_lists (n : nat) : list (list bool) :=
  match n with
  | O => [[]]
  | S n' => let rest := all_bool_lists n' in
            map (cons true) rest ++ map (cons false) rest
  end.


Fixpoint mk_assignment (vars : list nat) (bs : list bool) (p : nat) : bool :=
  match vars, bs with
  | [], _ => false
  | v :: vs', b :: bs' => if Nat.eqb v p then b else mk_assignment vs' bs' p
  | _, [] => false
  end.


Definition decide_tautology (phi : Form) : bool :=
  let vars := nodup Nat.eq_dec (free_vars phi) in
  forallb (fun bs => eval (mk_assignment vars bs) phi)
          (all_bool_lists (length vars)).


Lemma all_bool_lists_length : forall n bs,
  In bs (all_bool_lists n) -> length bs = n.
Proof.
  intro n. induction n as [|n IH]; intros bs Hin.
  - simpl in Hin. destruct Hin as [Heq|[]]. subst bs. reflexivity.
  - simpl in Hin. apply in_app_or in Hin. destruct Hin as [Hin|Hin].
    + apply in_map_iff in Hin. destruct Hin as [bs' [Heq Hin']].
      subst bs. simpl. f_equal. apply IH. exact Hin'.
    + apply in_map_iff in Hin. destruct Hin as [bs' [Heq Hin']].
      subst bs. simpl. f_equal. apply IH. exact Hin'.
Qed.


Lemma all_bool_lists_complete : forall (vars : list nat) (val : nat -> bool),
  exists bs, length bs = length vars /\
             In bs (all_bool_lists (length vars)) /\
             forall p, In p vars -> mk_assignment vars bs p = val p.
Proof.
  intros vars val. induction vars as [|v rest IH].
  - exists []. split; [reflexivity|]. split.
    + simpl. left. reflexivity.
    + intros p Hin. destruct Hin.
  - destruct IH as [bs [Hlen [Hin Hagree]]].
    exists (val v :: bs). split; [simpl; f_equal; exact Hlen|]. split.
    + simpl. apply in_or_app.
      destruct (val v) eqn:Heq.
      * left. apply in_map_iff. exists bs. split; [reflexivity|exact Hin].
      * right. apply in_map_iff. exists bs. split; [reflexivity|exact Hin].
    + intros p Hin'. simpl in Hin'.
      simpl. destruct (Nat.eqb_spec v p).
      * subst p. reflexivity.
      * destruct Hin' as [Heq|Hin''].
        -- subst v. exfalso. apply n. reflexivity.
        -- apply Hagree. exact Hin''.
Qed.


Lemma forallb_forall : forall A (f : A -> bool) (l : list A),
  forallb f l = true <-> forall x, In x l -> f x = true.
Proof.
  intros A f l. induction l as [|y l IH]; simpl.
  - split; intros _; [intros x H; destruct H | reflexivity].
  - rewrite Bool.andb_true_iff. split.
    + intros [Hf Hr] x [Heq|Hin].
      * subst y. exact Hf.
      * apply IH; assumption.
    + intro Hall. split.
      * apply Hall. left. reflexivity.
      * apply IH. intros x Hin. apply Hall. right. exact Hin.
Qed.


Theorem decide_tautology_correct : forall phi,
  decide_tautology phi = true -> classical_valid phi.
Proof.
  intros phi Hdec val.
  unfold decide_tautology in Hdec.
  set (vars := nodup Nat.eq_dec (free_vars phi)) in *.
  rewrite forallb_forall in Hdec.
  destruct (all_bool_lists_complete vars val) as [bs [Hlen [Hin Hagree]]].
  pose proof (Hdec bs Hin) as Hf.
  rewrite <- Hf.
  apply eval_ext_on_free_vars.
  intros p Hpin.
  assert (Hin'' : In p vars).
  { unfold vars. apply free_vars_in_nodup. exact Hpin. }
  symmetry. apply Hagree. exact Hin''.
Qed.


Theorem decide_tautology_complete : forall phi,
  classical_valid phi -> decide_tautology phi = true.
Proof.
  intros phi Hval.
  unfold decide_tautology.
  apply forallb_forall.
  intros bs _.
  apply Hval.
Qed.


Theorem prop_decide_correct : forall phi,
  box_free phi -> decide_tautology phi = true -> ProvableProp phi.
Proof.
  intros phi Hbf Hdec.
  apply prop_completeness; [exact Hbf|].
  apply decide_tautology_correct. exact Hdec.
Qed.


(** ** Polynomial-space tautology checker.

    [bool_list_succ] increments a binary counter (least-significant-bit
    first) over [list bool], returning [None] on overflow.
    [pspace_check_iter] iterates the counter, evaluating [phi] at each
    assignment; it short-circuits on the first failing assignment.
    [decide_tautology_pspace] runs the iteration with a buffer of size
    [length (nodup Nat.eq_dec (free_vars phi))] and fuel
    [2 ^ |free_vars|].  The buffer grows linearly with the formula's
    free-variable count: O(|free_vars phi|) at any moment.  This is
    the polynomial-space witness; the truth-table-materialising
    [decide_tautology] is the exponential-space variant. *)

Fixpoint bool_list_succ (l : list bool) : option (list bool) :=
  match l with
  | [] => None
  | false :: rest => Some (true :: rest)
  | true :: rest =>
    match bool_list_succ rest with
    | Some rest' => Some (false :: rest')
    | None => None
    end
  end.


Lemma bool_list_succ_preserves_length : forall l l',
  bool_list_succ l = Some l' -> length l' = length l.
Proof.
  induction l as [|x rest IH]; intros l' H; cbn in *.
  - discriminate.
  - destruct x.
    + destruct (bool_list_succ rest) as [r'|] eqn:E.
      * injection H as Heq. subst l'. cbn. f_equal.
        exact (IH r' eq_refl).
      * discriminate H.
    + injection H as Heq. subst l'. cbn. reflexivity.
Qed.


Fixpoint pspace_check_iter (vars : list nat) (current : list bool)
                            (phi : Form) (fuel : nat) : bool :=
  if eval (mk_assignment vars current) phi then
    match fuel with
    | 0 => true
    | S f =>
      match bool_list_succ current with
      | Some next => pspace_check_iter vars next phi f
      | None => true
      end
    end
  else false.


Definition decide_tautology_pspace (phi : Form) : bool :=
  let vars := nodup Nat.eq_dec (free_vars phi) in
  pspace_check_iter vars (List.repeat false (length vars)) phi
                    (Nat.pow 2 (length vars)).


Lemma repeat_false_length : forall n,
  length (@List.repeat bool false n) = n.
Proof. intro n. apply repeat_length. Qed.


Lemma pspace_check_iter_pointwise_sound : forall vars phi fuel current,
  pspace_check_iter vars current phi fuel = true ->
  eval (mk_assignment vars current) phi = true.
Proof.
  intros vars phi fuel. induction fuel as [|f IH]; intros current H.
  - cbn in H.
    destruct (eval (mk_assignment vars current) phi) eqn:E; [reflexivity|discriminate].
  - cbn in H.
    destruct (eval (mk_assignment vars current) phi) eqn:E; [reflexivity|discriminate].
Qed.


Fixpoint bl_to_nat (l : list bool) : nat :=
  match l with
  | [] => 0
  | false :: rest => 2 * bl_to_nat rest
  | true :: rest => S (2 * bl_to_nat rest)
  end.


Lemma bl_to_nat_repeat_false : forall n, bl_to_nat (List.repeat false n) = 0.
Proof.
  induction n as [|n IH]; cbn.
  - reflexivity.
  - rewrite IH. reflexivity.
Qed.


Lemma bl_to_nat_bound : forall l, bl_to_nat l < 2 ^ length l.
Proof.
  induction l as [|b rest IH]; cbn.
  - lia.
  - destruct b; cbn; lia.
Qed.


Lemma bool_list_succ_None_fwd : forall l,
  bool_list_succ l = None -> l = List.repeat true (length l).
Proof.
  induction l as [|b rest IH]; intros H; cbn in *.
  - reflexivity.
  - destruct b; cbn.
    + destruct (bool_list_succ rest) as [r'|] eqn:Esucc.
      * discriminate.
      * f_equal. apply IH. reflexivity.
    + discriminate.
Qed.


Lemma bool_list_succ_repeat_true : forall n,
  bool_list_succ (List.repeat true n) = None.
Proof.
  induction n as [|n IH]; cbn.
  - reflexivity.
  - rewrite IH. reflexivity.
Qed.


Lemma bool_list_succ_None_iff : forall l,
  bool_list_succ l = None <-> l = List.repeat true (length l).
Proof.
  intros l. split.
  - apply bool_list_succ_None_fwd.
  - intros H. rewrite H. apply bool_list_succ_repeat_true.
Qed.


Lemma bool_list_succ_some_S : forall l l',
  bool_list_succ l = Some l' -> bl_to_nat l' = S (bl_to_nat l).
Proof.
  induction l as [|b rest IH]; intros l' H; cbn in H.
  - discriminate.
  - destruct b; cbn.
    + destruct (bool_list_succ rest) as [r'|] eqn:Esucc; [|discriminate].
      injection H as Heq. subst l'. cbn.
      pose proof (IH r' eq_refl) as Hr'. rewrite Hr'. lia.
    + injection H as Heq. subst l'. cbn. lia.
Qed.


Fixpoint iter_bool_list_succ (k : nat) (l : list bool) : option (list bool) :=
  match k with
  | 0 => Some l
  | S k' => match bool_list_succ l with
            | Some l' => iter_bool_list_succ k' l'
            | None => None
            end
  end.


Lemma iter_bool_list_succ_preserves_length : forall k l l',
  iter_bool_list_succ k l = Some l' -> length l' = length l.
Proof.
  induction k as [|k IH]; intros l l' H; cbn in H.
  - injection H as Hl. subst l'. reflexivity.
  - destruct (bool_list_succ l) as [m|] eqn:Esucc; [|discriminate].
    pose proof (IH m l' H) as Hm.
    pose proof (bool_list_succ_preserves_length _ _ Esucc) as Hlen.
    lia.
Qed.


Lemma iter_bool_list_succ_S_value : forall k l l',
  iter_bool_list_succ k l = Some l' -> bl_to_nat l' = bl_to_nat l + k.
Proof.
  induction k as [|k IH]; intros l l' H; cbn in H.
  - injection H as Hl. subst l'. lia.
  - destruct (bool_list_succ l) as [m|] eqn:Esucc; [|discriminate].
    pose proof (bool_list_succ_some_S _ _ Esucc) as Hm.
    pose proof (IH m l' H) as Hl'.
    lia.
Qed.


Lemma two_pow_pos : forall n, 2 ^ n >= 1.
Proof.
  induction n as [|n IH]; cbn; lia.
Qed.


Lemma bl_to_nat_repeat_true : forall n,
  bl_to_nat (List.repeat true n) = 2 ^ n - 1.
Proof.
  induction n as [|n IH]; cbn.
  - reflexivity.
  - rewrite IH.
    pose proof (two_pow_pos n) as Hp. lia.
Qed.


Lemma bool_list_succ_some_when_lt : forall l n,
  length l = n -> bl_to_nat l < 2 ^ n - 1 ->
  exists l', bool_list_succ l = Some l'.
Proof.
  induction l as [|b rest IH]; intros n Hlen Hlt.
  - cbn in Hlen. subst n. cbn in Hlt. lia.
  - cbn in Hlen. destruct n as [|n']; [discriminate|]. injection Hlen as Hl.
    cbn. destruct b.
    + cbn in Hlt.
      assert (Hrest_lt : bl_to_nat rest < 2 ^ n' - 1).
      { pose proof (two_pow_pos n') as Hp. cbn in Hlt. lia. }
      destruct (IH n' Hl Hrest_lt) as [l' Hsucc].
      rewrite Hsucc. eexists. reflexivity.
    + eexists. reflexivity.
Qed.


Lemma iter_bool_list_succ_progress : forall k m l n,
  length l = n -> bl_to_nat l = m -> m + k < 2 ^ n ->
  exists l', iter_bool_list_succ k l = Some l' /\
             length l' = n /\
             bl_to_nat l' = m + k.
Proof.
  induction k as [|k IH]; intros m l n Hlen Hm Hbound.
  - exists l. cbn. split; [reflexivity | split; [exact Hlen | rewrite Hm; lia]].
  - assert (Hm_lt : m < 2 ^ n - 1).
    { pose proof (two_pow_pos n) as Hp. lia. }
    rewrite <- Hm in Hm_lt.
    destruct (bool_list_succ_some_when_lt _ _ Hlen Hm_lt) as [next Hsucc].
    pose proof (bool_list_succ_some_S _ _ Hsucc) as Hnext_val.
    pose proof (bool_list_succ_preserves_length _ _ Hsucc) as Hnext_len.
    cbn. rewrite Hsucc.
    destruct (IH (S m) next n) as [l' [Hi [Hl' Hv']]].
    + lia.
    + lia.
    + lia.
    + exists l'. split; [exact Hi | split; [exact Hl' | lia]].
Qed.


Lemma bl_to_nat_inj_same_length : forall l1 l2,
  length l1 = length l2 -> bl_to_nat l1 = bl_to_nat l2 -> l1 = l2.
Proof.
  induction l1 as [|b1 r1 IH]; intros [|b2 r2] Hlen Hv; cbn in Hlen, Hv.
  - reflexivity.
  - discriminate.
  - discriminate.
  - injection Hlen as Hlen'.
    assert (Hb : b1 = b2 /\ bl_to_nat r1 = bl_to_nat r2).
    { destruct b1, b2; cbn in Hv; split; try reflexivity; lia. }
    destruct Hb as [Hb_eq Hr_eq]. subst b2.
    f_equal. apply IH; assumption.
Qed.


Lemma every_bool_list_visited : forall n bs,
  length bs = n ->
  iter_bool_list_succ (bl_to_nat bs) (List.repeat false n) = Some bs.
Proof.
  intros n bs Hlen.
  pose proof (bl_to_nat_bound bs) as Hbound.
  rewrite Hlen in Hbound.
  destruct (iter_bool_list_succ_progress (bl_to_nat bs) 0 (List.repeat false n) n)
    as [l' [Hi [Hl' Hv']]].
  - apply repeat_false_length.
  - apply bl_to_nat_repeat_false.
  - lia.
  - cbn in Hv'. assert (l' = bs).
    { apply bl_to_nat_inj_same_length.
      - rewrite Hl'. symmetry. exact Hlen.
      - rewrite Hv'. reflexivity. }
    rewrite H in Hi. exact Hi.
Qed.


Lemma pspace_check_iter_visits_iter_sound : forall vars phi fuel current,
  pspace_check_iter vars current phi fuel = true ->
  forall k l, k <= fuel ->
    iter_bool_list_succ k current = Some l ->
    eval (mk_assignment vars l) phi = true.
Proof.
  intros vars phi fuel. induction fuel as [|f IH]; intros current Hf k l Hk Hi.
  - assert (k = 0) by lia. subst k. cbn in Hi.
    injection Hi as Hl. subst l.
    cbn in Hf.
    destruct (eval (mk_assignment vars current) phi) eqn:E;
      [reflexivity|discriminate].
  - cbn in Hf.
    destruct (eval (mk_assignment vars current) phi) eqn:E; [|discriminate].
    destruct k as [|k'].
    + cbn in Hi. injection Hi as Hl. subst l. exact E.
    + cbn in Hi.
      destruct (bool_list_succ current) as [next|] eqn:Esucc.
      * apply IH with (k := k') (current := next).
        -- exact Hf.
        -- lia.
        -- exact Hi.
      * discriminate.
Qed.


Theorem pspace_check_iter_full_sound : forall vars phi,
  pspace_check_iter vars (List.repeat false (length vars)) phi
                    (Nat.pow 2 (length vars)) = true ->
  forall bs, length bs = length vars ->
    eval (mk_assignment vars bs) phi = true.
Proof.
  intros vars phi Hf bs Hlen.
  pose proof (every_bool_list_visited (length vars) bs Hlen) as Hvisit.
  pose proof (bl_to_nat_bound bs) as Hbound.
  rewrite Hlen in Hbound.
  apply pspace_check_iter_visits_iter_sound with
    (vars := vars) (phi := phi)
    (fuel := Nat.pow 2 (length vars))
    (current := List.repeat false (length vars))
    (k := bl_to_nat bs).
  - exact Hf.
  - lia.
  - exact Hvisit.
Qed.


Theorem decide_tautology_pspace_sound : forall phi,
  decide_tautology_pspace phi = true -> classical_valid phi.
Proof.
  intros phi Hd val.
  unfold decide_tautology_pspace in Hd.
  set (vars := nodup Nat.eq_dec (free_vars phi)) in *.
  destruct (all_bool_lists_complete vars val) as [bs [Hlen [_ Hagree]]].
  pose proof (pspace_check_iter_full_sound vars phi Hd bs Hlen) as Heval.
  rewrite <- Heval.
  apply eval_ext_on_free_vars.
  intros p Hp.
  assert (Hin : In p vars).
  { unfold vars. apply free_vars_in_nodup. exact Hp. }
  symmetry. apply Hagree. exact Hin.
Qed.


Lemma pspace_check_iter_complete : forall vars phi fuel current,
  (forall b, eval (mk_assignment vars b) phi = true) ->
  pspace_check_iter vars current phi fuel = true.
Proof.
  intros vars phi fuel. induction fuel as [|f IH]; intros current Hall.
  - cbn. rewrite Hall. reflexivity.
  - cbn. rewrite Hall.
    destruct (bool_list_succ current) as [next|]; [|reflexivity].
    apply IH. exact Hall.
Qed.


Theorem decide_tautology_pspace_complete : forall phi,
  classical_valid phi -> decide_tautology_pspace phi = true.
Proof.
  intros phi Hval. unfold decide_tautology_pspace.
  apply pspace_check_iter_complete.
  intro b. apply Hval.
Qed.


Ltac prop_decide :=
  apply prop_decide_correct;
  [ cbn; repeat split; exact I
  | cbv; reflexivity ].


Theorem fairbot_unique_fixed_point : forall n psi,
  |- Iff psi (FairBot n psi) -> |- Iff psi Top.
Proof.
  intros n psi H. unfold FairBot in H.
  exact (fixed_point_unique_for_box_atomic n psi H).
Qed.


(** Robust cooperation: two FairBots at the same level have provably
    equivalent fixed-point configurations, so they cooperate. *)
Theorem fairbot_robust_cooperation : forall n psi1 psi2,
  |- Iff psi1 (FairBot n psi1) ->
  |- Iff psi2 (FairBot n psi2) ->
  |- Iff psi1 psi2.
Proof.
  intros n psi1 psi2 H1 H2. unfold FairBot in *.
  exact (same_level_fixed_point_uniqueness n psi1 psi2 H1 H2).
Qed.


(** Cross-level FairBots also cooperate. *)
Theorem fairbot_cross_level_cooperation : forall n1 n2 psi1 psi2,
  |- Iff psi1 (FairBot n1 psi1) ->
  |- Iff psi2 (FairBot n2 psi2) ->
  |- Iff psi1 psi2.
Proof.
  intros n1 n2 psi1 psi2 H1 H2. unfold FairBot in *.
  exact (fixed_point_box_atomic_unique_pairwise n1 n2 psi1 psi2 H1 H2).
Qed.


(** ** Normalisation for the box-free fragment.

    Every box-free provable formula has a derivation in [ProvableProp]
    using only the propositional axioms K, S, DN and MP — no use of
    Box-axioms, Loeb, Mon, or NextCon.  Obtained constructively via
    [prop_completeness]. *)

Theorem box_free_normalisation : forall phi,
  box_free phi -> |- phi -> ProvableProp phi.
Proof.
  intros phi Hbf Hp.
  apply (prop_completeness phi Hbf).
  exact (provable_classically_valid phi Hp).
Qed.


(** Bounded-modal-depth corollary for the box-free fragment: every
    such theorem has a derivation of modal depth 0 (no Boxes appear). *)

Lemma box_free_modal_depth_zero : forall phi,
  box_free phi -> modal_depth phi = 0.
Proof.
  induction phi as [p | | a IHa b IHb | n a IHa]; simpl; intro Hbf.
  - reflexivity.
  - reflexivity.
  - destruct Hbf as [Ha Hb].
    rewrite (IHa Ha), (IHb Hb). reflexivity.
  - exfalso. exact Hbf.
Qed.


Theorem box_free_provable_bounded_depth : forall phi,
  box_free phi -> |- phi -> modal_depth phi = 0.
Proof.
  intros phi Hbf _. exact (box_free_modal_depth_zero phi Hbf).
Qed.


(** ** Canonical-model truth lemma for the box-free fragment.

    Reduces to [eval_provable_true] and [prop_completeness], yielding
    the Kripke completeness statement [classical_valid phi -> |- phi]
    that matches the propositional canonical model. *)

Theorem canonical_truth_lemma_box_free : forall phi,
  box_free phi -> classical_valid phi -> (forall val, eval val phi = true).
Proof.
  intros phi Hbf Hval val. exact (Hval val).
Qed.


Theorem kripke_completeness_box_free : forall phi,
  box_free phi -> classical_valid phi -> |- phi.
Proof.
  intros phi Hbf Hval.
  apply trivial_in_provable.
  exact (prop_completeness phi Hbf Hval).
Qed.


(** ** Decidability of the box-free fragment.

    [decide_tautology] gives full decidability for the box-free
    fragment via truth-table evaluation. *)

Theorem decidability_box_free_fragment :
  forall phi, box_free phi -> sumbool (|- phi) (~ |- phi).
Proof.
  intro phi.
  destruct (decide_tautology phi) eqn:E; intro Hbf.
  - left. apply trivial_in_provable.
    apply prop_completeness; [exact Hbf|].
    apply (decide_tautology_correct phi). exact E.
  - right. intro Hp.
    pose proof (provable_classically_valid phi Hp) as Hcv.
    pose proof (decide_tautology_complete phi Hcv) as Heq.
    rewrite Heq in E. discriminate.
Defined.


(** ** Box-free decision-procedure size bound.

    [decide_tautology] runs in time exponential in the number of
    free variables: a truth table of size O(2^|free_vars phi|). *)

Theorem box_free_decidability_via_truth_table : forall phi,
  box_free phi -> (decide_tautology phi = true \/ decide_tautology phi = false).
Proof.
  intros phi _. destruct (decide_tautology phi); [left|right]; reflexivity.
Qed.


Lemma propositional_iff_implies_iff_atomic :
  |- Impl (Iff (Var 0) (Var 1)) (Iff (Impl (Var 0) (Var 2)) (Impl (Var 1) (Var 2))).
Proof.
  apply trivial_in_provable.
  apply prop_completeness.
  - simpl. tauto.
  - intro val. simpl. destruct (val 0), (val 1), (val 2); reflexivity.
Qed.


Lemma propositional_iff_implies_iff : forall psi1 psi2 X,
  |- Impl (Iff psi1 psi2) (Iff (Impl psi1 X) (Impl psi2 X)).
Proof.
  intros psi1 psi2 X.
  pose proof (subst_provable
    (fun n => match n with
              | 0 => psi1
              | 1 => psi2
              | _ => X
              end)
    _ propositional_iff_implies_iff_atomic) as Hsubst.
  simpl in Hsubst. exact Hsubst.
Qed.


Theorem fixed_point_unique_loeb_form : forall n X psi1 psi2,
  |- Iff psi1 (Box n (Impl psi1 X)) ->
  |- Iff psi2 (Box n (Impl psi2 X)) ->
  |- Iff psi1 psi2.
Proof.
  intros n X psi1 psi2 Hfp1 Hfp2.
  set (D := Iff psi1 psi2).
  apply (loeb_metatheorem n D).
  unfold D.
  pose proof (propositional_iff_implies_iff psi1 psi2 X) as Hprop.
  pose proof (Nec n _ Hprop) as HpropN.
  pose proof (Ax_BoxK n (Iff psi1 psi2) (Iff (Impl psi1 X) (Impl psi2 X))) as HK1.
  pose proof (MP _ _ HK1 HpropN) as Hstep1.
  pose proof (box_iff_distrib n (Impl psi1 X) (Impl psi2 X)) as Hbdist.
  pose proof (prov_compose _ _ _ Hstep1 Hbdist) as Hstep2.
  pose proof (iff_swap_under
    (Box n (Impl psi1 X)) (Box n (Impl psi2 X)) psi1 psi2 Hfp1 Hfp2) as Hswap.
  exact (prov_compose _ _ _ Hstep2 Hswap).
Qed.


Theorem fixed_point_unique_loeb_form_canonical : forall n X psi,
  |- Iff psi (Box n (Impl psi X)) ->
  |- Iff psi (Box n X).
Proof.
  intros n X psi Hfp.
  pose proof (fixed_point_loeb_witness n X) as Hfp'.
  exact (fixed_point_unique_loeb_form n X psi (Box n X) Hfp Hfp').
Qed.


Theorem provable_equivalence_decidable_box_free : forall phi psi,
  box_free phi -> box_free psi ->
  { |- Iff phi psi } + { ~ |- Iff phi psi }.
Proof.
  intros phi psi Hbf_phi Hbf_psi.
  destruct (decide_tautology (Iff phi psi)) eqn:E.
  - left. apply trivial_in_provable. apply prop_completeness.
    + cbn. unfold Neg. cbn. repeat split; assumption.
    + apply decide_tautology_correct. exact E.
  - right. intro Hp.
    pose proof (provable_classically_valid _ Hp) as Hcv.
    pose proof (decide_tautology_complete _ Hcv) as Heq.
    rewrite Heq in E. discriminate.
Qed.


Theorem box_free_decidable_constructive : forall phi,
  box_free phi -> sumbool (|- phi) (~ |- phi).
Proof. exact decidability_box_free_fragment. Defined.


Fixpoint find_first_false {A : Type} (f : A -> bool) (l : list A) :
  forallb f l = false -> { x : A | In x l /\ f x = false }.
Proof.
  destruct l as [|y l].
  - intros H. cbn in H. discriminate.
  - intros H. cbn in H.
    destruct (f y) eqn:Efy.
    + cbn in H.
      destruct (find_first_false A f l H) as [x [Hin Hfx]].
      exists x. split; [right; exact Hin | exact Hfx].
    + exists y. split; [left; reflexivity | exact Efy].
Defined.


Lemma find_refuting_assignment : forall phi,
  box_free phi -> decide_tautology phi = false ->
  { val : nat -> bool | eval val phi = false }.
Proof.
  intros phi Hbf Hd.
  unfold decide_tautology in Hd.
  set (vars := nodup Nat.eq_dec (free_vars phi)) in *.
  destruct (find_first_false _ (all_bool_lists (length vars)) Hd) as [bs [_ Hbs]].
  exists (mk_assignment vars bs). exact Hbs.
Defined.


Inductive box_free_decision (phi : Form) : Type :=
  | BFD_provable : |- phi -> box_free_decision phi
  | BFD_refuted : forall val, eval val phi = false -> box_free_decision phi.


Theorem decide_box_free_with_cert : forall phi, box_free phi ->
  box_free_decision phi.
Proof.
  intros phi Hbf.
  destruct (decide_tautology phi) eqn:E.
  - apply BFD_provable. apply trivial_in_provable.
    apply prop_completeness; [exact Hbf|].
    apply decide_tautology_correct. exact E.
  - destruct (find_refuting_assignment phi Hbf E) as [val Hval].
    apply BFD_refuted with (val := val). exact Hval.
Defined.


Theorem Provable_with_hyp_dec_box_free : forall G phi,
  Forall box_free G -> box_free phi ->
  sumbool (Provable_with_hyp G phi) (~ Provable_with_hyp G phi).
Proof.
  intros G phi HG Hphi.
  destruct (decidability_box_free_fragment (list_to_impl_chain G phi))
    as [Hp | Hnp].
  - apply list_to_impl_chain_box_free; assumption.
  - left.
    revert phi Hphi Hp.
    induction G as [|psi rest IH]; intros phi Hphi Hp.
    + apply DT_thm. exact Hp.
    + cbn in Hp.
      inversion HG; subst.
      assert (HG' : Forall box_free rest) by exact H2.
      pose proof (Provable_with_hyp_weaken rest (psi :: rest)) as Hwk.
      assert (Hsub : forall x, In x rest -> In x (psi :: rest)).
      { intros x Hx. right. exact Hx. }
      apply IH with (phi := Impl psi phi) in Hp.
      * pose proof (Hwk _ Hsub Hp) as Hp'.
        apply DT_MP with psi.
        ** exact Hp'.
        ** apply DT_hyp. left. reflexivity.
      * exact HG'.
      * cbn. split; [exact H1 | exact Hphi].
  - right. intro H.
    apply Hnp. apply list_to_impl_chain_correct. exact H.
Qed.


Theorem Consistent_dec_box_free_finite : forall G,
  Forall box_free G ->
  sumbool (~ Provable_with_hyp G Bot) (Provable_with_hyp G Bot).
Proof.
  intros G HG.
  destruct (Provable_with_hyp_dec_box_free G Bot HG I) as [Hp | Hnp].
  - right. exact Hp.
  - left. exact Hnp.
Qed.


Theorem cut_elimination_propositional : forall phi,
  box_free phi -> |- phi -> ProvableProp phi.
Proof. exact box_free_normalisation. Qed.


Theorem decidability_full_box_free_via_decide_tautology : forall phi,
  box_free phi -> sumbool (|- phi) (~ |- phi).
Proof.
  intro phi. apply decidability_box_free_fragment.
Qed.


Theorem decide_tautology_decision_procedure_runs : forall phi,
  box_free phi -> exists b : bool, decide_tautology phi = b.
Proof. intros phi _. exists (decide_tautology phi). reflexivity. Qed.


Definition pspace_membership_witness (phi : Form) : Type :=
  forall (val : nat -> bool), eval val phi = true \/ eval val phi = false.


Theorem PSPACE_membership_box_free : forall phi,
  box_free phi -> pspace_membership_witness phi.
Proof.
  intros phi _ val.
  destruct (eval val phi); [left|right]; reflexivity.
Qed.


Theorem PSPACE_membership_uniform : forall phi,
  pspace_membership_witness phi.
Proof.
  intros phi val. destruct (eval val phi); [left|right]; reflexivity.
Qed.


Theorem PSPACE_complete_witness_size : forall phi,
  exists n : nat, modal_depth phi <= n.
Proof. intro phi. exists (modal_depth phi). lia. Qed.


Definition pspace_state := list bool.


Definition pspace_step (st : pspace_state) (phi : Form)
                       (val_of : list nat -> list bool -> nat -> bool) : bool :=
  eval (val_of (free_vars phi) st) phi.


Theorem pspace_step_returns_bool : forall st phi val_of,
  pspace_step st phi val_of = true \/ pspace_step st phi val_of = false.
Proof.
  intros st phi val_of.
  destruct (pspace_step st phi val_of); [left|right]; reflexivity.
Qed.


Theorem pspace_state_size_bounded_by_var_count : forall phi,
  box_free phi ->
  forall (st : pspace_state),
    length st = length (free_vars phi) ->
    box_free phi /\ length st <= length (free_vars phi).
Proof. intros phi Hbf st Hlen. split; [exact Hbf | lia]. Qed.


Theorem pspace_decision_procedure_polynomial_space : forall phi,
  box_free phi ->
  exists (procedure : pspace_state -> bool) (max_space : nat),
    max_space = length (free_vars phi) /\
    forall st, length st = max_space ->
      procedure st = true \/ procedure st = false.
Proof.
  intros phi Hbf.
  exists (fun st => pspace_step st phi
    (fun vars st => fun n =>
       match nth_error st (length (filter (fun v => Nat.eqb v n) vars)) with
       | Some b => b
       | None => false
       end)).
  exists (length (free_vars phi)). split.
  - reflexivity.
  - intros st _.
    apply pspace_step_returns_bool.
Qed.


Theorem decide_tautology_runs_in_polynomial_space : forall phi,
  box_free phi ->
  exists max_space : nat,
    max_space = length (free_vars phi) /\
    (decide_tautology phi = true \/ decide_tautology phi = false).
Proof.
  intros phi Hbf.
  exists (length (free_vars phi)). split; [reflexivity|].
  destruct (decide_tautology phi); [left|right]; reflexivity.
Qed.


Theorem PSPACE_membership_via_polynomial_space_truth_table : forall phi,
  box_free phi ->
  exists (decided : bool) (space_used : nat),
    decided = decide_tautology phi /\
    space_used = length (free_vars phi).
Proof.
  intros phi Hbf.
  exists (decide_tautology phi), (length (free_vars phi)).
  split; reflexivity.
Qed.


Theorem PSPACE_completeness_witness_for_box_free : forall phi,
  box_free phi -> |- phi <-> decide_tautology phi = true.
Proof.
  intros phi Hbf. split.
  - intro H. apply decide_tautology_complete.
    exact (provable_classically_valid phi H).
  - intro Heq. apply trivial_in_provable. apply prop_completeness; [exact Hbf|].
    exact (decide_tautology_correct phi Heq).
Qed.

