(** Tiling.Provable - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.

From Tiling Require Import Syntax.


(** GLP* is the Hilbert-style polymodal proof system used throughout.
    Its axioms are:

    - Classical propositional axioms (K, S, double-negation elimination).
    - For each level n: K and Loeb for [Box n].
    - Monotonicity across levels: [Box n phi -> Box (S n) phi].
    - NextCon: [Box (S n) (Neg (Box n Bot))], i.e., level (S n) proves
      that level n is consistent.

    Inference rules are modus ponens and necessitation at every level.
    Propositional consequence and modal-K give the standard "K-valid"
    derivable consequence; the Loeb axiom gives Goedel-Loeb provability
    behaviour at every level; monotonicity and NextCon give the tower
    structure required by Yudkowsky-Herreshoff 2013.

    Axiom 4 ([Box n phi -> Box n (Box n phi)]) is included primitively
    below as [Ax_Box4].  It is provably redundant: [nb4_axiom4] derives
    it from K and Loeb in [Provable_no_B4] via the standard A ∧ Box A
    substitution argument, and [provable_iff_no_b4] shows the two
    calculi coincide. *)

Inductive Provable : Form -> Prop :=
  (* Classical propositional axioms. *)
  | Ax_K   : forall phi psi,
      Provable (Impl phi (Impl psi phi))
  | Ax_S   : forall phi psi chi,
      Provable (Impl (Impl phi (Impl psi chi))
                     (Impl (Impl phi psi) (Impl phi chi)))
  | Ax_DN  : forall phi,
      Provable (Impl (Neg (Neg phi)) phi)
  (* Modal K and Loeb at every level. *)
  | Ax_BoxK : forall n phi psi,
      Provable (Impl (Box n (Impl phi psi))
                     (Impl (Box n phi) (Box n psi)))
  | Ax_Loeb : forall n phi,
      Provable (Impl (Box n (Impl (Box n phi) phi)) (Box n phi))
  | Ax_Box4 : forall n phi,
      Provable (Impl (Box n phi) (Box n (Box n phi)))
  (* Polymodal axioms. *)
  | Ax_Mon  : forall n phi,
      Provable (Impl (Box n phi) (Box (S n) phi))
  | Ax_NextCon : forall n,
      Provable (Box (S n) (Neg (Box n Bot)))
  (* Inference rules. *)
  | MP : forall phi psi,
      Provable (Impl phi psi) -> Provable phi -> Provable psi
  | Nec : forall n phi,
      Provable phi -> Provable (Box n phi).


Notation "|- f" := (Provable f) (at level 75, no associativity).


(** A small library of derived propositional facts.  We proceed in
    Hilbert style: every theorem is a chain of axioms and modus
    ponens.  These lemmas are reused throughout the development. *)

(** ** [phi -> phi] (reflexivity of implication) *)
Lemma prov_id : forall phi, |- Impl phi phi.
Proof.
  intro phi.
  (* Standard Hilbert proof: K, S, K, MP, MP. *)
  pose proof (Ax_S phi (Impl phi phi) phi) as Hs.
  pose proof (Ax_K phi (Impl phi phi)) as Hk1.
  pose proof (Ax_K phi phi) as Hk2.
  exact (MP _ _ (MP _ _ Hs Hk1) Hk2).
Qed.


(** ** Weakening: from [phi] derive [psi -> phi]. *)
Lemma prov_weaken : forall phi psi, |- phi -> |- Impl psi phi.
Proof.
  intros phi psi Hphi.
  exact (MP _ _ (Ax_K phi psi) Hphi).
Qed.


(** ** Composition / syllogism: from [phi -> psi] and [psi -> chi]
    derive [phi -> chi]. *)
Lemma prov_compose : forall phi psi chi,
  |- Impl phi psi -> |- Impl psi chi -> |- Impl phi chi.
Proof.
  intros phi psi chi Hpq Hqr.
  (* Use S applied to (Ax_K (psi -> chi) phi) to get
     (phi -> psi -> chi) -> (phi -> psi) -> (phi -> chi). *)
  pose proof (Ax_S phi psi chi) as Hs.
  pose proof (prov_weaken _ phi Hqr) as Hpqr.
  exact (MP _ _ (MP _ _ Hs Hpqr) Hpq).
Qed.


(** ** Permutation of antecedents. *)
Lemma prov_perm : forall phi psi chi,
  |- Impl phi (Impl psi chi) -> |- Impl psi (Impl phi chi).
Proof.
  intros phi psi chi H.
  pose proof (Ax_S phi psi chi) as Hs.
  pose proof (MP _ _ Hs H) as H1. (* (phi -> psi) -> (phi -> chi) *)
  pose proof (Ax_K psi phi) as Hk.   (* psi -> (phi -> psi) *)
  pose proof (prov_compose _ _ _ Hk H1) as H2. (* psi -> (phi -> chi) *)
  exact H2.
Qed.


(** ** Three-place modus ponens / chained MP. *)
Lemma prov_mp2 : forall phi psi chi,
  |- Impl phi (Impl psi chi) -> |- phi -> |- psi -> |- chi.
Proof.
  intros phi psi chi H Hphi Hpsi.
  exact (MP _ _ (MP _ _ H Hphi) Hpsi).
Qed.


(** ** Double negation introduction: [phi -> ~~phi]. *)
Lemma prov_DN_intro : forall phi, |- Impl phi (Neg (Neg phi)).
Proof.
  intro phi.
  unfold Neg.
  (* Goal: |- Impl phi (Impl (Impl phi Bot) Bot). *)
  (* First derive: |- Impl (Impl phi Bot) (Impl phi Bot)  (= prov_id). *)
  pose proof (prov_id (Impl phi Bot)) as Hid.
  (* Permute antecedents: (phi -> Bot) -> (phi -> Bot)  =>  phi -> ((phi -> Bot) -> Bot). *)
  exact (prov_perm _ _ _ Hid).
Qed.


(** ** Ex falso: [Bot -> phi]. *)
Lemma prov_explosion : forall phi, |- Impl Bot phi.
Proof.
  intro phi.
  (* Bot -> Bot is just prov_id. *)
  pose proof (prov_id Bot) as HBB.
  (* Bot -> ((phi -> Bot) -> Bot)  by Ax_K applied to HBB twice: actually
     we want Bot -> phi, not via DN.  Use Ax_DN: ~~phi -> phi.
     We need: Bot -> ~~phi -> phi via Ax_K then composition. *)
  pose proof (Ax_K Bot (Neg phi)) as Hk. (* Bot -> ((phi -> Bot) -> Bot) *)
  (* Goal: Bot -> phi.
     We have Bot -> ~~phi (= Bot -> ((phi -> Bot) -> Bot)) since (Neg phi = phi -> Bot)
     and Ax_DN: ~~phi -> phi. *)
  pose proof (Ax_DN phi) as HDN.
  exact (prov_compose _ _ _ Hk HDN).
Qed.


(** ** Internal composition: [(psi -> chi) -> (phi -> psi) -> (phi -> chi)]. *)
Lemma prov_compose_internal : forall phi psi chi,
  |- Impl (Impl psi chi) (Impl (Impl phi psi) (Impl phi chi)).
Proof.
  intros phi psi chi.
  pose proof (Ax_K (Impl psi chi) phi) as Hk.
  pose proof (Ax_S phi psi chi) as Hs.
  exact (prov_compose _ _ _ Hk Hs).
Qed.


(** ** Internal permutation: [(a -> b -> c) -> (b -> a -> c)] as a
    single provable formula.

    The metatheorem [prov_perm] swaps antecedents at the proof level;
    this lemma is its internal Hilbert form, derivable from the
    propositional axioms K and S without any modal axioms. *)

Lemma prov_perm_internal : forall a b c,
  |- Impl (Impl a (Impl b c)) (Impl b (Impl a c)).
Proof.
  intros a b c.
  (* Step 1: Ax_S a b c = (a -> b -> c) -> ((a -> b) -> (a -> c)). *)
  pose proof (Ax_S a b c) as H_S.
  (* Step 2: Ax_S over (a -> b -> c) -> ((a -> b) -> (a -> c)) feeding
     the result through. *)
  pose proof (Ax_S (Impl a (Impl b c)) (Impl a b) (Impl a c)) as H_S2.
  (* H1 : ((a -> b -> c) -> (a -> b)) -> ((a -> b -> c) -> (a -> c)). *)
  pose proof (MP _ _ H_S2 H_S) as H1.
  (* Step 3: from b derive (a -> b) (Ax_K), and weaken to "(a -> b -> c) -> (a -> b)". *)
  pose proof (Ax_K b a) as H_K1.
  pose proof (Ax_K (Impl a b) (Impl a (Impl b c))) as H_K2.
  pose proof (prov_compose _ _ _ H_K1 H_K2) as H2.
  (* H2 : b -> ((a -> b -> c) -> (a -> b)). *)
  (* H3 : b -> ((a -> b -> c) -> (a -> c)) by composing H2 and H1. *)
  pose proof (prov_compose _ _ _ H2 H1) as H3.
  (* Goal: (a -> b -> c) -> (b -> (a -> c)).  Permute H3. *)
  exact (prov_perm _ _ _ H3).
Qed.


(** ** And-introduction: [|- phi -> psi -> phi /\ psi].

    Unfolds via [And phi psi := Neg (Impl phi (Neg psi))] to
    [|- phi -> psi -> (phi -> psi -> Bot) -> Bot].  The proof is a
    chain: start with [prov_id (phi -> psi -> Bot)], permute the
    outermost antecedent into position 3 using [prov_perm] then
    [prov_perm_internal] under one layer. *)

Lemma prov_and_intro : forall phi psi,
  |- Impl phi (Impl psi (And phi psi)).
Proof.
  intros phi psi.
  unfold And, Neg.
  (* Goal: |- Impl phi (Impl psi (Impl (Impl phi (Impl psi Bot)) Bot)). *)
  pose proof (prov_id (Impl phi (Impl psi Bot))) as Hid.
  pose proof (prov_perm _ _ _ Hid) as Hperm.
  pose proof (prov_perm_internal (Impl phi (Impl psi Bot)) psi Bot) as Hpi.
  exact (prov_compose _ _ _ Hperm Hpi).
Qed.


(** ** And-introduction in metatheorem form: from [|- phi] and [|- psi]
    derive [|- And phi psi].  Two MPs against [prov_and_intro]. *)

Lemma prov_and_intro_meta : forall phi psi,
  |- phi -> |- psi -> |- And phi psi.
Proof.
  intros phi psi Hphi Hpsi.
  exact (MP _ _ (MP _ _ (prov_and_intro phi psi) Hphi) Hpsi).
Qed.


(** ** From a negation derive any implication landing in a negation:
    [Neg phi -> (phi -> Neg psi)].

    Internal form of "if [phi] is impossible, then any consequence
    landing in a negation also follows."  Used in [prov_and_elim_l]. *)

Lemma prov_neg_imp_ng : forall phi psi,
  |- Impl (Neg phi) (Impl phi (Neg psi)).
Proof.
  intros phi psi.
  unfold Neg.
  pose proof (prov_compose_internal phi Bot (Impl psi Bot)) as Hci.
  pose proof (prov_explosion (Impl psi Bot)) as Hex.
  exact (MP _ _ Hci Hex).
Qed.


(** ** And-elimination (left): [|- (phi /\ psi) -> phi].

    Unfolded: [|- ((phi -> Neg psi) -> Bot) -> phi].
    Proof via classical double-negation: from [(phi -> Neg psi) -> Bot]
    derive [Neg phi -> Bot] (i.e. [Neg (Neg phi)]) by feeding a [Neg phi]
    through [prov_neg_imp_ng], then apply [Ax_DN]. *)

Lemma prov_and_elim_l : forall phi psi,
  |- Impl (And phi psi) phi.
Proof.
  intros phi psi.
  unfold And, Neg.
  (* Goal: |- Impl (Impl (Impl phi (Impl psi Bot)) Bot) phi. *)
  pose proof (prov_neg_imp_ng phi psi) as H1.
  (* H1 : |- Impl (Impl phi Bot) (Impl phi (Impl psi Bot)). *)
  pose proof (prov_compose_internal
                (Impl phi Bot)
                (Impl phi (Impl psi Bot))
                Bot) as H2.
  (* H2 : |- Impl (Impl (Impl phi (Impl psi Bot)) Bot)
                  (Impl (Impl (Impl phi Bot) (Impl phi (Impl psi Bot)))
                        (Impl (Impl phi Bot) Bot)). *)
  pose proof (prov_perm _ _ _ H2) as H2_perm.
  pose proof (MP _ _ H2_perm H1) as Hstep1.
  (* Hstep1 : |- Impl (Impl (Impl phi (Impl psi Bot)) Bot)
                      (Impl (Impl phi Bot) Bot). *)
  pose proof (Ax_DN phi) as HDN.
  (* HDN: |- Impl (Impl (Impl phi Bot) Bot) phi. *)
  exact (prov_compose _ _ _ Hstep1 HDN).
Qed.


(** ** And-elimination (right): [|- (phi /\ psi) -> psi].

    Symmetric to [prov_and_elim_l] but extracts the right component.
    From [psi -> (phi -> psi)] (Ax_K) and the [(phi -> Neg psi) -> Bot]
    hypothesis, double-negation elimination delivers [psi]. *)

Lemma prov_and_elim_r : forall phi psi,
  |- Impl (And phi psi) psi.
Proof.
  intros phi psi.
  unfold And, Neg.
  pose proof (Ax_K (Impl psi Bot) phi) as H1.
  pose proof (prov_compose_internal
                (Impl psi Bot)
                (Impl phi (Impl psi Bot))
                Bot) as H2.
  pose proof (prov_perm _ _ _ H2) as H2_perm.
  pose proof (MP _ _ H2_perm H1) as Hstep1.
  pose proof (Ax_DN psi) as HDN.
  exact (prov_compose _ _ _ Hstep1 HDN).
Qed.


(** ** And-elimination metatheorem (left): from [|- And phi psi]
    derive [|- phi]. *)

Lemma prov_and_elim_l_meta : forall phi psi,
  |- And phi psi -> |- phi.
Proof.
  intros phi psi Hand.
  exact (MP _ _ (prov_and_elim_l phi psi) Hand).
Qed.


(** ** And-elimination metatheorem (right). *)

Lemma prov_and_elim_r_meta : forall phi psi,
  |- And phi psi -> |- psi.
Proof.
  intros phi psi Hand.
  exact (MP _ _ (prov_and_elim_r phi psi) Hand).
Qed.


(** ** Box-And-elimination (left): [|- Box n (phi /\ psi) -> Box n phi].

    Pure K-distribution: necessitate [prov_and_elim_l] and feed
    through [Ax_BoxK]. *)

Lemma prov_box_and_elim_l : forall n phi psi,
  |- Impl (Box n (And phi psi)) (Box n phi).
Proof.
  intros n phi psi.
  pose proof (prov_and_elim_l phi psi) as Hand.
  pose proof (Nec n _ Hand) as Hnec.
  pose proof (Ax_BoxK n (And phi psi) phi) as HBK.
  exact (MP _ _ HBK Hnec).
Qed.


(** ** Box-And-elimination (right): [|- Box n (phi /\ psi) -> Box n psi].

    Symmetric counterpart of [prov_box_and_elim_l]. *)

Lemma prov_box_and_elim_r : forall n phi psi,
  |- Impl (Box n (And phi psi)) (Box n psi).
Proof.
  intros n phi psi.
  pose proof (prov_and_elim_r phi psi) as Hand.
  pose proof (Nec n _ Hand) as Hnec.
  pose proof (Ax_BoxK n (And phi psi) psi) as HBK.
  exact (MP _ _ HBK Hnec).
Qed.


(** ** Box-And introduction.

    If level [n] proves [phi] and proves [psi], then level [n] proves
    their conjunction.  The "easy" direction of K-distribution over And. *)

Lemma prov_box_and_intro : forall n phi psi,
  |- Impl (Box n phi) (Impl (Box n psi) (Box n (And phi psi))).
Proof.
  intros n phi psi.
  pose proof (prov_and_intro phi psi) as Hand.
  pose proof (Nec n _ Hand) as Hnec.
  pose proof (Ax_BoxK n phi (Impl psi (And phi psi))) as HBK1.
  pose proof (MP _ _ HBK1 Hnec) as Hstep1.
  pose proof (Ax_BoxK n psi (And phi psi)) as HBK2.
  exact (prov_compose _ _ _ Hstep1 HBK2).
Qed.


(** ** Box-And full distribution.

    The converse of [prov_box_and_intro]:
    [|- Box n (And phi psi) -> And (Box n phi) (Box n psi)].
    Combined with [prov_box_and_intro] (in metatheorem MP-form) this
    gives the full K-distribution-over-And biconditional. *)

Lemma prov_box_and_distrib_fwd : forall n phi psi,
  |- Impl (Box n (And phi psi)) (And (Box n phi) (Box n psi)).
Proof.
  intros n phi psi.
  pose proof (prov_box_and_elim_l n phi psi) as HL.
  pose proof (prov_box_and_elim_r n phi psi) as HR.
  pose proof (prov_and_intro (Box n phi) (Box n psi)) as Hand.
  (* Hand : |- Box n phi -> Box n psi -> And (Box n phi) (Box n psi). *)
  pose proof (prov_compose_internal
                (Box n (And phi psi))
                (Box n phi)
                (Impl (Box n psi) (And (Box n phi) (Box n psi)))) as Hci.
  pose proof (MP _ _ Hci Hand) as Hstep1.
  pose proof (MP _ _ Hstep1 HL) as Hstep2.
  (* Hstep2 : |- Box n (And phi psi) ->
                  (Box n psi -> And (Box n phi) (Box n psi)). *)
  pose proof (Ax_S
                (Box n (And phi psi))
                (Box n psi)
                (And (Box n phi) (Box n psi))) as Hs.
  pose proof (MP _ _ Hs Hstep2) as Hstep3.
  (* Hstep3 : |- (Box n (And phi psi) -> Box n psi) ->
                 (Box n (And phi psi) -> And (Box n phi) (Box n psi)). *)
  exact (MP _ _ Hstep3 HR).
Qed.


(** ** Contraposition (one direction): [(phi -> psi) -> (~psi -> ~phi)]. *)
Lemma prov_contrapos : forall phi psi,
  |- Impl (Impl phi psi) (Impl (Neg psi) (Neg phi)).
Proof.
  intros phi psi.
  unfold Neg.
  (* prov_compose_internal phi psi Bot gives
     (psi -> Bot) -> ((phi -> psi) -> (phi -> Bot)),
     and we need the perm of that. *)
  exact (prov_perm _ _ _ (prov_compose_internal phi psi Bot)).
Qed.


(** ** Contraposition (converse direction): [(~psi -> ~phi) -> (phi -> psi)].

    Together with [prov_contrapos] this gives the full classical
    contrapositive equivalence.  The proof uses double-negation
    elimination: from [(psi -> Bot) -> (phi -> Bot)] and [phi],
    derive [(psi -> Bot) -> Bot] (i.e., [Neg (Neg psi)]), then apply
    [Ax_DN]. *)

Lemma prov_contrapos_converse : forall phi psi,
  |- Impl (Impl (Neg psi) (Neg phi)) (Impl phi psi).
Proof.
  intros phi psi.
  unfold Neg.
  (* H_perm : ((psi -> Bot) -> (phi -> Bot)) -> (phi -> ((psi -> Bot) -> Bot)). *)
  pose proof (prov_perm_internal (Impl psi Bot) phi Bot) as H_perm.
  (* HDN : ((psi -> Bot) -> Bot) -> psi. *)
  pose proof (Ax_DN psi) as HDN.
  (* Hci : (((psi -> Bot) -> Bot) -> psi) ->
           ((phi -> ((psi -> Bot) -> Bot)) -> (phi -> psi)). *)
  pose proof (prov_compose_internal phi
                (Impl (Impl psi Bot) Bot) psi) as Hci.
  pose proof (MP _ _ Hci HDN) as Hstep.
  exact (prov_compose _ _ _ H_perm Hstep).
Qed.


(** ** Consequentia mirabilis: [(Neg chi -> chi) -> chi].

    A classical principle equivalent to double-negation elimination
    in the presence of [Ax_DN].  Used in the Or-elimination proof
    below. *)

Lemma prov_consequentia_mirabilis : forall chi,
  |- Impl (Impl (Neg chi) chi) chi.
Proof.
  intro chi.
  unfold Neg.
  (* From prov_id (Impl chi Bot) and Ax_S, derive
     (Impl (Impl chi Bot) chi) -> (Impl (Impl chi Bot) Bot),
     i.e., (Neg chi -> chi) -> Neg (Neg chi).  Then apply Ax_DN. *)
  pose proof (prov_id (Impl chi Bot)) as Hid.
  pose proof (Ax_S (Impl chi Bot) chi Bot) as Hs.
  pose proof (MP _ _ Hs Hid) as Hstep1.
  pose proof (Ax_DN chi) as HDN.
  exact (prov_compose _ _ _ Hstep1 HDN).
Qed.


(** ** Or-introduction (left): [|- phi -> Or phi psi].

    Unfolds to [|- phi -> (Neg phi -> psi)].  Classical: from [phi]
    and [Neg phi] derive [Bot] then anything. *)

Lemma prov_or_intro_l : forall phi psi,
  |- Impl phi (Or phi psi).
Proof.
  intros phi psi.
  unfold Or.
  pose proof (prov_explosion psi) as Hexp.
  pose proof (prov_compose_internal (Neg phi) Bot psi) as Hci.
  pose proof (MP _ _ Hci Hexp) as HX.
  (* HX : |- (Neg phi -> Bot) -> (Neg phi -> psi). *)
  pose proof (prov_DN_intro phi) as HDN.
  (* HDN : |- phi -> (Neg phi -> Bot). *)
  exact (prov_compose _ _ _ HDN HX).
Qed.


(** ** Or-introduction (right): [|- psi -> Or phi psi].

    Trivial via [Ax_K]: [psi] implies [Neg phi -> psi]. *)

Lemma prov_or_intro_r : forall phi psi,
  |- Impl psi (Or phi psi).
Proof.
  intros phi psi.
  unfold Or.
  exact (Ax_K psi (Neg phi)).
Qed.


(** ** Apply-two-under-outer-impl.

    From [|- A -> (B -> (C -> R))], [|- B], and [|- C], derive
    [|- A -> R].  Used to plug constant arguments into a multi-arg
    Hilbert formula while leaving an outer antecedent open. *)

Lemma prov_apply2 : forall A B C R,
  |- Impl A (Impl B (Impl C R)) -> |- B -> |- C -> |- Impl A R.
Proof.
  intros A B C R Hf Hb Hc.
  pose proof (Ax_S A B (Impl C R)) as Hs1.
  pose proof (MP _ _ Hs1 Hf) as Hstep1.
  pose proof (Ax_K B A) as HK_b.
  pose proof (MP _ _ HK_b Hb) as HAB.
  pose proof (MP _ _ Hstep1 HAB) as Hstep2.
  pose proof (Ax_S A C R) as Hs2.
  pose proof (MP _ _ Hs2 Hstep2) as Hstep3.
  pose proof (Ax_K C A) as HK_c.
  pose proof (MP _ _ HK_c Hc) as HAC.
  exact (MP _ _ Hstep3 HAC).
Qed.


(** ** Compose-under-shared-antecedent.

    From [|- A -> (B -> C)] and [|- D -> B] derive [|- A -> (D -> C)].
    Pre-composes with [g] under a shared outer antecedent [A]. *)

Lemma prov_compose_under : forall A B C D,
  |- Impl A (Impl B C) -> |- Impl D B -> |- Impl A (Impl D C).
Proof.
  intros A B C D Hf Hg.
  pose proof (prov_compose_internal D B C) as HCI.
  pose proof (prov_perm _ _ _ HCI) as HCI_perm.
  (* HCI_perm : |- (D -> B) -> ((B -> C) -> (D -> C)). *)
  pose proof (MP _ _ HCI_perm Hg) as HX.
  (* HX : |- (B -> C) -> (D -> C). *)
  exact (prov_compose _ _ _ Hf HX).
Qed.


(** ** Two-place forward chaining combinator.

    From [A -> B -> C] and [C -> D], derive [A -> B -> D].
    Equivalently as a single Hilbert formula:
    [(A -> B -> C) -> (C -> D) -> (A -> B -> D)]. *)

Lemma prov_chain_2 : forall A B C D,
  |- Impl (Impl A (Impl B C))
          (Impl (Impl C D) (Impl A (Impl B D))).
Proof.
  intros A B C D.
  pose proof (prov_compose_internal B C D) as H1.
  pose proof (prov_compose_internal A (Impl B C) (Impl B D)) as H2.
  pose proof (prov_compose _ _ _ H1 H2) as H3.
  exact (prov_perm _ _ _ H3).
Qed.


(** ** Or-elimination.

    Classical disjunction elimination: from [Or phi psi], [phi -> chi],
    and [psi -> chi], derive [chi].  In our system, [Or phi psi]
    unfolds to [Neg phi -> psi], so the goal is

      |- (Neg phi -> psi) -> (phi -> chi) -> (psi -> chi) -> chi.

    Proof chain: from [phi -> chi] derive [Neg chi -> Neg phi] by
    contrapos; compose with [Neg phi -> psi] to get [Neg chi -> psi];
    compose with [psi -> chi] to get [Neg chi -> chi]; apply
    consequentia mirabilis to get [chi]. *)

Lemma prov_or_elim : forall phi psi chi,
  |- Impl (Or phi psi)
       (Impl (Impl phi chi) (Impl (Impl psi chi) chi)).
Proof.
  intros phi psi chi.
  unfold Or.
  pose proof (prov_contrapos phi chi) as HCP.
  pose proof (prov_compose_internal (Neg chi) (Neg phi) psi) as HCI1.
  pose proof (prov_compose_internal (Neg chi) psi chi) as HCI2.
  pose proof (prov_consequentia_mirabilis chi) as HCM.
  (* HA : (Neg phi -> psi) -> ((phi -> chi) -> (Neg chi -> psi)). *)
  pose proof (prov_compose_under
                (Impl (Neg phi) psi)
                (Impl (Neg chi) (Neg phi))
                (Impl (Neg chi) psi)
                (Impl phi chi)
                HCI1 HCP) as HA.
  (* HCH : combine HCI2 and HCM via prov_chain_2 to derive
     (psi -> chi) -> ((Neg chi -> psi) -> chi). *)
  pose proof (prov_chain_2
                (Impl psi chi)
                (Impl (Neg chi) psi)
                (Impl (Neg chi) chi)
                chi) as HCH.
  pose proof (MP _ _ HCH HCI2) as HCH1.
  pose proof (MP _ _ HCH1 HCM) as HB.
  (* HB : (psi -> chi) -> ((Neg chi -> psi) -> chi). *)
  pose proof (prov_perm _ _ _ HB) as HB_perm.
  (* HB_perm : (Neg chi -> psi) -> ((psi -> chi) -> chi). *)
  pose proof (prov_chain_2
                (Impl (Neg phi) psi)
                (Impl phi chi)
                (Impl (Neg chi) psi)
                (Impl (Impl psi chi) chi)) as HCH2.
  pose proof (MP _ _ HCH2 HA) as HCH2_1.
  exact (MP _ _ HCH2_1 HB_perm).
Qed.


(** ** K-distribution over Or: [|- Or (Box n phi) (Box n psi) -> Box n (Or phi psi)].

    Standard K-modal-logic theorem: from a (classical) disjunction
    of boxed claims at level n, derive a box of the disjunction.
    Proof by classical Or-elim with the two Box-friendly directions. *)

Lemma prov_box_or_intro : forall n phi psi,
  |- Impl (Or (Box n phi) (Box n psi)) (Box n (Or phi psi)).
Proof.
  intros n phi psi.
  pose proof (prov_or_intro_l phi psi) as Holil.
  pose proof (Nec n _ Holil) as HNl.
  pose proof (Ax_BoxK n phi (Or phi psi)) as HBKl.
  pose proof (MP _ _ HBKl HNl) as Hbol.
  pose proof (prov_or_intro_r phi psi) as Holir.
  pose proof (Nec n _ Holir) as HNr.
  pose proof (Ax_BoxK n psi (Or phi psi)) as HBKr.
  pose proof (MP _ _ HBKr HNr) as Hbor.
  pose proof (prov_or_elim (Box n phi) (Box n psi) (Box n (Or phi psi))) as Hoe.
  exact (prov_apply2 _ _ _ _ Hoe Hbol Hbor).
Qed.


(** ** Modus tollens (derived form): [phi -> psi] and [~psi] yield [~phi]. *)
Lemma prov_mt : forall phi psi,
  |- Impl phi psi -> |- Neg psi -> |- Neg phi.
Proof.
  intros phi psi Himp Hnpsi.
  exact (MP _ _ (MP _ _ (prov_contrapos phi psi) Himp) Hnpsi).
Qed.


(** ** From [phi] and [~phi] derive [psi] (ex contradictione quodlibet). *)
Lemma prov_explode : forall phi psi,
  |- phi -> |- Neg phi -> |- psi.
Proof.
  intros phi psi Hphi Hnp.
  (* Apply Hnp (= phi -> Bot) to Hphi to get Bot, then apply prov_explosion. *)
  pose proof (MP _ _ Hnp Hphi) as Hbot.
  exact (MP _ _ (prov_explosion psi) Hbot).
Qed.


(** All [Box n] satisfy axiom K and the necessitation rule.  We derive
    their working forms here. *)

(** ** Internal modus ponens at level n. *)
Lemma prov_box_mp : forall n phi psi,
  |- Box n (Impl phi psi) -> |- Box n phi -> |- Box n psi.
Proof.
  intros n phi psi Himp Hphi.
  exact (MP _ _ (MP _ _ (Ax_BoxK n phi psi) Himp) Hphi).
Qed.


(** ** Necessitation lifts an implication. *)
Lemma prov_box_imp : forall n phi psi,
  |- Impl phi psi -> |- Impl (Box n phi) (Box n psi).
Proof.
  intros n phi psi H.
  exact (MP _ _ (Ax_BoxK n phi psi) (Nec n _ H)).
Qed.


(** ** Composition through Box. *)
Lemma prov_box_compose : forall n phi psi chi,
  |- Impl phi psi -> |- Impl psi chi ->
  |- Impl (Box n phi) (Box n chi).
Proof.
  intros n phi psi chi H1 H2.
  exact (prov_box_imp n _ _ (prov_compose _ _ _ H1 H2)).
Qed.


(** ** Two-step internal MP at level n. *)
Lemma prov_box_mp2 : forall n phi psi chi,
  |- Box n (Impl phi (Impl psi chi)) ->
  |- Box n phi -> |- Box n psi -> |- Box n chi.
Proof.
  intros n phi psi chi Himp Hphi Hpsi.
  exact (prov_box_mp n _ _ (prov_box_mp n _ _ Himp Hphi) Hpsi).
Qed.


(** ** [Box n] of an axiom is provable.  Just Nec + the axiom. *)
Lemma prov_box_K_inst : forall n phi psi,
  |- Box n (Impl phi (Impl psi phi)).
Proof.
  intros n phi psi; exact (Nec n _ (Ax_K phi psi)).
Qed.


(** ** Box-modus-tollens.

    If [Box n] proves [phi -> psi] and [Box n] proves [Neg psi], then
    [Box n] proves [Neg phi].  Internalized contraposition at level
    [n], useful for forward proofs about consistency. *)

Lemma prov_box_mt : forall n phi psi,
  |- Impl (Box n (Impl phi psi))
          (Impl (Box n (Neg psi)) (Box n (Neg phi))).
Proof.
  intros n phi psi.
  pose proof (prov_contrapos phi psi) as Hcp.
  pose proof (Nec n _ Hcp) as Hnec.
  pose proof (Ax_BoxK n (Impl phi psi) (Impl (Neg psi) (Neg phi))) as HBK1.
  pose proof (MP _ _ HBK1 Hnec) as Hstep1.
  pose proof (Ax_BoxK n (Neg psi) (Neg phi)) as HBK2.
  exact (prov_compose _ _ _ Hstep1 HBK2).
Qed.


(** ** Box-Diamond duality (definitional).

    By the very definition of [Diamond n phi := Neg (Box n (Neg phi))],
    the iff holds by [prov_id] in both directions. *)

Lemma prov_diamond_def : forall n phi,
  |- Iff (Diamond n phi) (Neg (Box n (Neg phi))).
Proof.
  intros n phi.
  unfold Iff, Diamond.
  apply prov_and_intro_meta.
  - exact (prov_id (Neg (Box n (Neg phi)))).
  - exact (prov_id (Neg (Box n (Neg phi)))).
Qed.


(** ** Box-Diamond duality (DN form): [|- Iff (Box n phi) (Neg (Diamond n (Neg phi)))].

    Standard classical-modal duality.  Both directions go through
    classical double-negation lifted under [Box] via [prov_box_imp]. *)

Lemma prov_box_neg_diamond : forall n phi,
  |- Iff (Box n phi) (Neg (Diamond n (Neg phi))).
Proof.
  intros n phi.
  unfold Iff, Diamond.
  (* Direction 1: Box n phi -> Neg (Neg (Box n (Neg (Neg phi)))). *)
  pose proof (prov_DN_intro phi) as Hdn1.
  pose proof (prov_box_imp n _ _ Hdn1) as Hb1.
  pose proof (prov_DN_intro (Box n (Neg (Neg phi)))) as Hdn2.
  pose proof (prov_compose _ _ _ Hb1 Hdn2) as HD1.
  (* Direction 2: Neg (Neg (Box n (Neg (Neg phi)))) -> Box n phi. *)
  pose proof (Ax_DN (Box n (Neg (Neg phi)))) as Hdn3.
  pose proof (Ax_DN phi) as Hdn4.
  pose proof (prov_box_imp n _ _ Hdn4) as Hb2.
  pose proof (prov_compose _ _ _ Hdn3 Hb2) as HD2.
  exact (prov_and_intro_meta _ _ HD1 HD2).
Qed.


(** Loeb's metatheorem.  This is the central derived rule of GL: if
    [Box n phi -> phi] is provable, so is [phi].  In Goedel-Loeb's
    arithmetic interpretation (where [Box] is the formal provability
    predicate of PA), this corresponds to: from [PA proves "Bew(phi)
    -> phi"], conclude [PA proves phi].

    The proof uses only the Loeb axiom, necessitation, and modus
    ponens; in particular it does not need axiom 4. *)

Theorem loeb_metatheorem : forall n phi,
  |- Impl (Box n phi) phi -> |- phi.
Proof.
  intros n phi Hsound.
  (* Nec gives: |- Box n (Box n phi -> phi). *)
  pose proof (Nec n _ Hsound) as Hnec.
  (* Loeb axiom: |- Box n (Box n phi -> phi) -> Box n phi. *)
  pose proof (Ax_Loeb n phi) as HLoeb.
  (* MP gives: |- Box n phi. *)
  pose proof (MP _ _ HLoeb Hnec) as Hbox.
  (* Combined with Hsound by MP: |- phi. *)
  exact (MP _ _ Hsound Hbox).
Qed.



(** The Loebian obstacle in Yudkowsky-Herreshoff 2013 is the assertion
    that a single fixed theory cannot prove its own soundness without
    becoming inconsistent.  In Goedel-Loeb form: any [Box]-modality
    that satisfies [Box phi -> phi] uniformly over [phi] is the
    modality of an inconsistent theory.

    The proof is a one-line corollary of the Loeb metatheorem,
    instantiated at [phi := Bot].  This is the obstacle that the
    parametric [T_kappa] construction in Section 9 will bypass. *)

Theorem loebian_obstacle : forall n,
  (forall phi, |- Impl (Box n phi) phi) -> |- Bot.
Proof.
  intros n Hsound.
  exact (loeb_metatheorem n Bot (Hsound Bot)).
Qed.


(** At a single level [n], if both [phi] and its negation are
    internally provable, then so is [Bot] — i.e., level [n] is
    inconsistent.  This is the K-internalization of the propositional
    fact that [phi] and [Neg phi] together imply [Bot]. *)

Lemma prov_box_n_contradiction : forall n phi,
  |- Impl (Box n phi) (Impl (Box n (Neg phi)) (Box n Bot)).
Proof.
  intros n phi.
  (* Step 1: |- Impl phi (Impl (Neg phi) Bot)  is just prov_DN_intro. *)
  pose proof (prov_DN_intro phi) as Hpnnp.
  (* Step 2: Necessitate at level n. *)
  pose proof (Nec n _ Hpnnp) as Hnec.
  (* Step 3: Ax_BoxK to peel off the outer Box. *)
  pose proof (Ax_BoxK n phi (Impl (Neg phi) Bot)) as HBK1.
  pose proof (MP _ _ HBK1 Hnec) as Hstep1.
  (* Hstep1 : |- Impl (Box n phi) (Box n (Impl (Neg phi) Bot)). *)
  (* Step 4: Ax_BoxK to peel off the inner Box from (Neg phi -> Bot). *)
  pose proof (Ax_BoxK n (Neg phi) Bot) as HBK2.
  (* HBK2 : |- Impl (Box n (Impl (Neg phi) Bot))
                    (Impl (Box n (Neg phi)) (Box n Bot)). *)
  (* Compose Hstep1 and HBK2. *)
  exact (prov_compose _ _ _ Hstep1 HBK2).
Qed.


(** The central positive result: at level [S n], the modality proves
    that level-[n] provability of [phi] excludes level-[n] provability
    of [Neg phi].

    This is the "consistency tiling" property of YH 2013 in modal
    abstraction: the theory at the strictly higher level [S n] verifies
    the consistency-of-phi-at-level-n property internally.  It is
    provable from the tower axioms (NextCon and Ax_BoxK) alone, no
    arithmetisation required.

    The Loebian obstacle (Section 6) ruled out the same statement at
    level n inside [Box n] itself; the tiling theorem here recovers
    the property by promoting it one level up. *)

Theorem tiling_consistency : forall n phi,
  |- Box (S n) (Impl (Box n phi) (Neg (Box n (Neg phi)))).
Proof.
  intros n phi.
  (* H1 : |- Impl (Box n phi) (Impl (Box n (Neg phi)) (Box n Bot)). *)
  pose proof (prov_box_n_contradiction n phi) as H1.
  (* H1n : |- Box (S n) (Impl (Box n phi) (Impl (Box n (Neg phi)) (Box n Bot))). *)
  pose proof (Nec (S n) _ H1) as H1n.
  (* H2 : |- Box (S n) (Neg (Box n Bot))
         = |- Box (S n) (Impl (Box n Bot) Bot). *)
  pose proof (Ax_NextCon n) as H2.
  (* H3 : the propositional chain combinator at A,B,C,D := Box n phi,
     Box n (Neg phi), Box n Bot, Bot. *)
  pose proof (prov_chain_2 (Box n phi) (Box n (Neg phi)) (Box n Bot) Bot) as H3.
  (* H3n : the chain combinator necessitated at level (S n). *)
  pose proof (Nec (S n) _ H3) as H3n.
  (* Apply prov_box_mp twice: first feed H1n into H3n, then feed H2. *)
  pose proof (prov_box_mp (S n) _ _ H3n H1n) as H4.
  pose proof (prov_box_mp (S n) _ _ H4 H2) as H5.
  exact H5.
Qed.


(** YH 2013 indexes a sequence of theories [T_0, T_1, T_2, ...] where
    each [T_{k+1}] strictly extends [T_k] with the consistency of
    [T_k].  Our polymodal axioms encode exactly this:

    - [Ax_Mon n phi] = [T_n |- phi] implies [T_{n+1} |- phi]:
      higher-indexed theories prove at least everything lower ones do.
    - [Ax_NextCon n] = [T_{n+1}] proves [Con(T_n)]:
      the strictly higher theory verifies consistency of the strictly
      lower one.

    Applying these axioms at multiple levels yields the chain
    [T_k |- Con(T_n)] for every [k > n], which we prove formally below. *)

(** ** Iterated monotonicity.

    The single-step monotonicity axiom [Box n phi -> Box (S n) phi]
    extends to an arbitrary jump [Box n phi -> Box m phi] whenever
    [n <= m].  Proof is by induction on the order proof. *)

Lemma prov_box_mon_le : forall n m phi,
  n <= m -> |- Impl (Box n phi) (Box m phi).
Proof.
  intros n m phi Hle.
  induction Hle as [| m' Hle' IH].
  - exact (prov_id (Box n phi)).
  - exact (prov_compose _ _ _ IH (Ax_Mon m' phi)).
Qed.


(** ** The consistency chain.

    For any two levels [n < k], the level-[k] theory proves the
    consistency of the level-[n] theory.  This is the FS2014-style
    "all levels above n agree on n's consistency" claim.

    Proof: NextCon gives the immediate-successor case [Box (S n)
    (Neg (Box n Bot))]; iterated monotonicity lifts it to any [Box k]
    for [k >= S n], i.e., for [k > n]. *)

Theorem consistency_chain : forall n k,
  n < k -> |- Box k (Neg (Box n Bot)).
Proof.
  intros n k Hlt.
  pose proof (Ax_NextCon n) as Hnext.
  pose proof (prov_box_mon_le (S n) k (Neg (Box n Bot)) Hlt) as Hmon.
  exact (MP _ _ Hmon Hnext).
Qed.


(** ** Tiling at any strictly higher level.

    The single-step tiling theorem ([tiling_consistency]) is lifted to
    arbitrary higher levels by monotonicity: if level [S n] verifies
    the consistency tiling at level [n], so does any level [k >= S n]
    (i.e., any [k > n]).

    Read in agent terms: every supervising agent strictly above the
    licensing level can verify that the licensor's claims do not
    contradict each other, regardless of the supervisory gap. *)

Theorem tiling_chain : forall n k phi,
  n < k -> |- Box k (Impl (Box n phi) (Neg (Box n (Neg phi)))).
Proof.
  intros n k phi Hlt.
  pose proof (tiling_consistency n phi) as Htil.
  pose proof (prov_box_mon_le (S n) k
                (Impl (Box n phi) (Neg (Box n (Neg phi)))) Hlt) as Hmon.
  exact (MP _ _ Hmon Htil).
Qed.


(** ** [|- Box n Top]. *)

Lemma prov_box_top : forall n, |- Box n Top.
Proof.
  intro n.
  unfold Top.
  exact (Nec n _ (prov_id Bot)).
Qed.


(** ** Box-And-list intro: each entry boxed implies the conjunction boxed. *)

Lemma prov_box_and_list_intro : forall n l,
  Forall (fun phi => |- Box n phi) l ->
  |- Box n (And_list l).
Proof.
  intros n l. induction l as [|phi rest IH]; intro H.
  - simpl. exact (prov_box_top n).
  - simpl.
    pose proof (Forall_inv H) as Hphi.
    pose proof (Forall_inv_tail H) as Hrest.
    pose proof (IH Hrest) as IHrest.
    pose proof (prov_box_and_intro n phi (And_list rest)) as Hbai.
    exact (MP _ _ (MP _ _ Hbai Hphi) IHrest).
Qed.


(** ** Meta-level consistency translation.

    If level [n] is meta-consistent (i.e., we cannot Coq-derive
    [|- Box n Bot]), then no formula and its negation are both
    licensed at that level.

    The assumption [~(|- Box n Bot)] is the meta-consistency of
    level [n]'s theory.  We do not prove it for any specific [n] —
    that requires either semantic methods (Kripke models for GL) or
    a cut-elimination argument (Gore et al.).  But conditional on
    that assumption, level-internal contradiction collapses to
    inconsistency by [prov_box_n_contradiction]. *)

Theorem meta_consistency_no_contradiction : forall n,
  ~ (|- Box n Bot) ->
  forall phi, ~ (|- Box n phi /\ |- Box n (Neg phi)).
Proof.
  intros n Hcons phi [Hphi Hnphi].
  pose proof (prov_box_n_contradiction n phi) as Hcontra.
  pose proof (MP _ _ Hcontra Hphi) as Hstep.
  pose proof (MP _ _ Hstep Hnphi) as Hbot.
  exact (Hcons Hbot).
Qed.


(** The companion result to the Loebian obstacle: if level [n] proves
    its own consistency, then level [n] is inconsistent.

    [Box n (Neg (Box n Bot))] reads as "level n proves: level n
    doesn't prove Bot."  Goedel's second incompleteness theorem says
    this implies [Box n Bot] (level n is inconsistent).

    Concretely the proof is a one-step instance of the Loeb axiom at
    [phi := Bot]: [Box n (Box n Bot -> Bot) -> Box n Bot] under the
    notation unfolding [Neg X = Impl X Bot]. *)

Theorem godel_second : forall n,
  |- Impl (Box n (Neg (Box n Bot))) (Box n Bot).
Proof.
  intro n.
  exact (Ax_Loeb n Bot).
Qed.


(** ** Self-licensed consistency collapses.

    If level [n] internally licenses its own consistency
    ([|- Box n (Neg (Box n Bot))]), then level [n] is inconsistent
    ([|- Box n Bot]).  Read in YH terms: an agent that internally
    asserts its own consistency triggers the Loebian collapse and
    becomes inconsistent.  This is the agent-level reason a tower
    must reach for the next level up rather than self-trusting. *)

Theorem self_consistency_inconsistent : forall n,
  |- Box n (Neg (Box n Bot)) ->
  |- Box n Bot.
Proof.
  intros n Hself.
  exact (MP _ _ (godel_second n) Hself).
Qed.


(** ** Inconsistency propagates upward in the tower.

    If a lower level proves [Bot], every higher level does too, by
    monotonicity.  An inconsistent agent at any rung of the YH ladder
    therefore taints every supervisor above it. *)

Theorem inconsistency_propagates : forall n m,
  n <= m -> |- Box n Bot -> |- Box m Bot.
Proof.
  intros n m Hle Hbot.
  pose proof (prov_box_mon_le n m Bot Hle) as Hmon.
  exact (MP _ _ Hmon Hbot).
Qed.


(** ** Consistency propagates downward in the tower.

    Contrapositive of [inconsistency_propagates]: if a higher level
    is meta-consistent, then every lower level is too.  In tower
    terms, the consistency of any single supervisor at a level [m]
    certifies the consistency of every agent below it in the chain. *)

Theorem consistency_propagates_down : forall n m,
  n <= m -> ~ (|- Box m Bot) -> ~ (|- Box n Bot).
Proof.
  intros n m Hle Hcons_m Hbot_n.
  exact (Hcons_m (inconsistency_propagates n m Hle Hbot_n)).
Qed.


(** [Diamond n phi] is by definition [Neg (Box n (Neg phi))], i.e., the
    consistency of [phi] in the level-[n] theory.  The tiling theorem
    therefore reads, at level [S n], "if level n proves [phi], then
    [phi] is consistent in level n." *)

Corollary tiling_diamond : forall n phi,
  |- Box (S n) (Impl (Box n phi) (Diamond n phi)).
Proof.
  intros n phi.
  unfold Diamond.
  exact (tiling_consistency n phi).
Qed.


(** ** Diamond tiling at any strictly higher level.

    Same lift as [tiling_chain] for the [Neg-Box-Neg] form, restated
    using [Diamond] for symmetry with classical modal-logic notation. *)

Corollary tiling_diamond_chain : forall n k phi,
  n < k -> |- Box k (Impl (Box n phi) (Diamond n phi)).
Proof.
  intros n k phi Hlt.
  unfold Diamond.
  exact (tiling_chain n k phi Hlt).
Qed.


(** The Yudkowsky-Herreshoff bypass packages three facts:

    1. The single-level soundness schema is incompatible with
       consistency: any [Box n] satisfying [Box n phi -> phi]
       uniformly is the modality of an inconsistent theory.
       (Loebian obstacle.)

    2. At the strictly higher level [S n], the consistency tiling
       is provable: [Box (S n)] verifies that [Box n] cannot
       license both [phi] and [Neg phi].
       (Tiling theorem.)

    3. Higher levels provably acknowledge consistency of strictly
       lower levels: every [Box k] with [k > n] proves [Neg (Box n Bot)].
       (Consistency chain.)

    Together, these three facts isolate exactly the YH 2013
    construction: the parametric tower [T_0 subseteq T_1 subseteq ...]
    achieves cross-level consistency verification at every step,
    even though no single level can verify its own soundness. *)

Theorem yh_bypass_summary : forall n : nat,
  ((forall phi, |- Impl (Box n phi) phi) -> |- Bot) /\
  (forall phi, |- Box (S n) (Impl (Box n phi) (Neg (Box n (Neg phi))))) /\
  (forall k, n < k -> |- Box k (Neg (Box n Bot))).
Proof.
  intro n.
  split; [|split].
  - exact (loebian_obstacle n).
  - exact (tiling_consistency n).
  - exact (consistency_chain n).
Qed.


(** ** Internal YH bypass.

    A single Form witnessing the bypass content at a single level:
    the conjunction of consistency tiling for [phi] and consistency
    of level [n] itself.  Provable at level [S n] inside the calculus,
    not just at the meta-level. *)

Definition yh_bypass_summary_internal (n : nat) (phi : Form) : Form :=
  And (Impl (Box n phi) (Neg (Box n (Neg phi)))) (Neg (Box n Bot)).


Theorem yh_bypass_internal : forall n phi,
  |- Box (S n) (yh_bypass_summary_internal n phi).
Proof.
  intros n phi.
  unfold yh_bypass_summary_internal.
  pose proof (tiling_consistency n phi) as Htil.
  pose proof (Ax_NextCon n) as Hncon.
  pose proof (prov_box_and_intro (S n)
                (Impl (Box n phi) (Neg (Box n (Neg phi))))
                (Neg (Box n Bot))) as Hbai.
  exact (MP _ _ (MP _ _ Hbai Htil) Hncon).
Qed.


(** ** Uniform bypass schema.

    [tiling_consistency] as a uniform derivation, exposed as a single
    proof term parameterised by [n] and [phi].  The Coq type itself
    encodes the schematic nature: a single dependent term inhabits
    [forall n phi, |- ...], so each [tiling_consistency n phi]
    instance is obtained by parameter substitution into a fixed
    derivation tree. *)

Definition tiling_schema : forall n phi,
  |- Box (S n) (Impl (Box n phi) (Neg (Box n (Neg phi))))
  := tiling_consistency.


Lemma eval_provable_true : forall val phi, |- phi -> eval val phi = true.
Proof.
  intros val phi H.
  induction H; simpl in *.
  - destruct (eval val phi); destruct (eval val psi); reflexivity.
  - destruct (eval val phi); destruct (eval val psi); destruct (eval val chi);
      reflexivity.
  - destruct (eval val phi); reflexivity.
  - reflexivity.
  - reflexivity.
  - reflexivity.
  - reflexivity.
  - reflexivity.
  - destruct (eval val phi); simpl in IHProvable1.
    + exact IHProvable1.
    + discriminate IHProvable2.
  - reflexivity.
Qed.


Theorem meta_consistency_system : ~ (|- Bot).
Proof.
  intro H.
  pose proof (eval_provable_true (fun _ => true) Bot H) as Heval.
  simpl in Heval.
  discriminate.
Qed.


(** ** [Top] is a fixed point of [phi(p) := Box n p].

    A concrete fixed point: [|- Iff Top (Box n Top)].  Both [Top]
    and [Box n Top] are theorems individually, so the iff follows by
    [prov_weaken] in each direction. *)

Theorem fixedpoint_top_box : forall n,
  |- Iff Top (Box n Top).
Proof.
  intro n.
  unfold Iff.
  apply prov_and_intro_meta.
  - exact (prov_weaken _ Top (prov_box_top n)).
  - unfold Top.
    exact (prov_weaken _ (Box n (Impl Bot Bot)) (prov_id Bot)).
Qed.


(** ** Provability with hypotheses.

    [Provable_with_hyp Gamma phi] holds when [phi] is derivable from
    the hypotheses in [Gamma] using axioms, theorems, and modus
    ponens.  Necessitation is deliberately omitted: in modal logic,
    [Nec] only applies to closed proofs, not to derivations under
    open assumptions, since [phi] in the modal-K sense is
    [|- phi -> |- Box n phi] — a metatheorem, not a Hilbert rule on
    hypotheses.  This restriction is what makes the deduction
    theorem hold. *)

Inductive Provable_with_hyp : list Form -> Form -> Prop :=
  | DT_hyp : forall Gamma alpha,
      In alpha Gamma -> Provable_with_hyp Gamma alpha
  | DT_thm : forall Gamma alpha,
      |- alpha -> Provable_with_hyp Gamma alpha
  | DT_MP : forall Gamma alpha beta,
      Provable_with_hyp Gamma (Impl alpha beta) ->
      Provable_with_hyp Gamma alpha ->
      Provable_with_hyp Gamma beta.


(** ** The deduction theorem.

    If [phi] discharges to [psi] under hypotheses [Gamma], then
    [phi -> psi] is derivable from [Gamma] alone.  Standard Hilbert-
    calculus result, valid here because [Provable_with_hyp] omits
    [Nec]. *)

Theorem deduction_theorem : forall Gamma phi psi,
  Provable_with_hyp (phi :: Gamma) psi ->
  Provable_with_hyp Gamma (Impl phi psi).
Proof.
  intros Gamma phi psi H.
  remember (phi :: Gamma) as G eqn:HG.
  generalize dependent Gamma. generalize dependent phi.
  induction H as [G' alpha Hin | G' alpha Hthm
                   | G' alpha beta Himp IHimp Halpha IHalpha];
    intros phi Gamma HG.
  - (* DT_hyp: alpha is in G = phi :: Gamma. *)
    subst G'. simpl in Hin. destruct Hin as [Heq | Hin'].
    + subst alpha. apply DT_thm. apply prov_id.
    + apply DT_MP with (alpha := alpha).
      * apply DT_thm. apply Ax_K.
      * apply DT_hyp. exact Hin'.
  - (* DT_thm: alpha is a closed theorem; weaken via Ax_K. *)
    apply DT_thm. exact (MP _ _ (Ax_K alpha phi) Hthm).
  - (* DT_MP: chain via Ax_S. *)
    subst G'.
    pose proof (IHimp phi Gamma eq_refl) as HI1.
    pose proof (IHalpha phi Gamma eq_refl) as HI2.
    apply DT_MP with (alpha := Impl phi alpha).
    + apply DT_MP with (alpha := Impl phi (Impl alpha beta)).
      * apply DT_thm. exact (Ax_S phi alpha beta).
      * exact HI1.
    + exact HI2.
Qed.


(** ** Reflexivity, intro, symmetry for Iff. *)

Lemma prov_iff_refl : forall phi, |- Iff phi phi.
Proof.
  intro phi. unfold Iff.
  exact (prov_and_intro_meta _ _ (prov_id phi) (prov_id phi)).
Qed.


Lemma prov_iff_intro : forall phi psi,
  |- Impl phi psi -> |- Impl psi phi -> |- Iff phi psi.
Proof.
  intros phi psi H1 H2. unfold Iff.
  exact (prov_and_intro_meta _ _ H1 H2).
Qed.


Lemma prov_iff_sym : forall phi psi,
  |- Iff phi psi -> |- Iff psi phi.
Proof.
  intros phi psi H. unfold Iff in *.
  pose proof (prov_and_elim_l_meta _ _ H) as H1.
  pose proof (prov_and_elim_r_meta _ _ H) as H2.
  exact (prov_and_intro_meta _ _ H2 H1).
Qed.


(** ** Diamond cross-level monotonicity.

    [Diamond (S n) phi -> Diamond n phi] by contraposition of
    [Ax_Mon] applied to [Neg phi]. *)

Lemma prov_diamond_mon : forall n phi,
  |- Impl (Diamond (S n) phi) (Diamond n phi).
Proof.
  intros n phi. unfold Diamond.
  pose proof (Ax_Mon n (Neg phi)) as Hmon.
  pose proof (prov_contrapos (Box n (Neg phi)) (Box (S n) (Neg phi))) as Hcon.
  exact (MP _ _ Hcon Hmon).
Qed.


(** ** Diamond modus ponens.

    From [|- Box n (phi -> psi)] and [|- Diamond n phi] derive
    [|- Diamond n psi]. *)

Lemma prov_diamond_mp : forall n phi psi,
  |- Box n (Impl phi psi) -> |- Diamond n phi -> |- Diamond n psi.
Proof.
  intros n phi psi Himp Hdia. unfold Diamond in *.
  pose proof (prov_contrapos phi psi) as Hcon.
  pose proof (Nec n _ Hcon) as Hncon.
  pose proof (Ax_BoxK n (Impl phi psi)
                       (Impl (Neg psi) (Neg phi))) as HBK1.
  pose proof (MP _ _ HBK1 Hncon) as Hstep1.
  pose proof (MP _ _ Hstep1 Himp) as Hbcontra.
  pose proof (Ax_BoxK n (Neg psi) (Neg phi)) as HBK2.
  pose proof (MP _ _ HBK2 Hbcontra) as Himpneg.
  exact (prov_compose _ _ _ Himpneg Hdia).
Qed.


(** ** Lindenbaum-Tarski algebra of GLP*.

    The provable-equivalence relation [prov_equiv] partitions [Form]
    into equivalence classes; the quotient is the Lindenbaum-Tarski
    algebra of the calculus.  We establish the algebra's structural
    properties directly: [prov_equiv] is reflexive, symmetric, and
    transitive; it is a congruence for [Impl] and [Box n]; and the
    algebra is non-degenerate ([Top] and [Bot] are not in the same
    class).  The non-degeneracy proof routes through Kripke soundness
    against the [F0] frame, giving an independent witness of
    [~(|- Bot)] that does not invoke the trivial-truth-assignment
    used in [meta_consistency_system]. *)

Definition prov_equiv (phi psi : Form) : Prop := |- Iff phi psi.


Lemma prov_equiv_refl : forall phi, prov_equiv phi phi.
Proof. intro phi. unfold prov_equiv. apply prov_iff_refl. Qed.


Lemma prov_equiv_sym : forall phi psi,
  prov_equiv phi psi -> prov_equiv psi phi.
Proof.
  intros phi psi H. unfold prov_equiv in *.
  apply prov_iff_sym. exact H.
Qed.


Lemma prov_equiv_trans : forall phi psi chi,
  prov_equiv phi psi -> prov_equiv psi chi -> prov_equiv phi chi.
Proof.
  intros phi psi chi Hpq Hqr.
  unfold prov_equiv, Iff in *.
  pose proof (prov_and_elim_l_meta _ _ Hpq) as Hpq_f.
  pose proof (prov_and_elim_r_meta _ _ Hpq) as Hpq_b.
  pose proof (prov_and_elim_l_meta _ _ Hqr) as Hqr_f.
  pose proof (prov_and_elim_r_meta _ _ Hqr) as Hqr_b.
  apply prov_and_intro_meta.
  - exact (prov_compose _ _ _ Hpq_f Hqr_f).
  - exact (prov_compose _ _ _ Hqr_b Hpq_b).
Qed.


Lemma prov_equiv_impl_cong : forall phi1 phi2 psi1 psi2,
  prov_equiv phi1 phi2 -> prov_equiv psi1 psi2 ->
  prov_equiv (Impl phi1 psi1) (Impl phi2 psi2).
Proof.
  intros phi1 phi2 psi1 psi2 H1 H2.
  unfold prov_equiv, Iff in *.
  pose proof (prov_and_elim_l_meta _ _ H1) as H1f.
  pose proof (prov_and_elim_r_meta _ _ H1) as H1b.
  pose proof (prov_and_elim_l_meta _ _ H2) as H2f.
  pose proof (prov_and_elim_r_meta _ _ H2) as H2b.
  apply prov_and_intro_meta.
  - pose proof (prov_compose_internal phi2 phi1 psi1) as Hci1.
    pose proof (MP _ _ (prov_perm _ _ _ Hci1) H1b) as Hstep1.
    pose proof (prov_compose_internal phi2 psi1 psi2) as Hci2.
    pose proof (MP _ _ Hci2 H2f) as Hstep2.
    exact (prov_compose _ _ _ Hstep1 Hstep2).
  - pose proof (prov_compose_internal phi1 phi2 psi2) as Hci1.
    pose proof (MP _ _ (prov_perm _ _ _ Hci1) H1f) as Hstep1.
    pose proof (prov_compose_internal phi1 psi2 psi1) as Hci2.
    pose proof (MP _ _ Hci2 H2b) as Hstep2.
    exact (prov_compose _ _ _ Hstep1 Hstep2).
Qed.


Lemma prov_equiv_box_cong : forall n phi psi,
  prov_equiv phi psi -> prov_equiv (Box n phi) (Box n psi).
Proof.
  intros n phi psi H. unfold prov_equiv, Iff in *.
  pose proof (prov_and_elim_l_meta _ _ H) as Hf.
  pose proof (prov_and_elim_r_meta _ _ H) as Hb.
  apply prov_and_intro_meta.
  - exact (prov_box_imp n _ _ Hf).
  - exact (prov_box_imp n _ _ Hb).
Qed.


(** ** Substitution theorem.

    Define [Subst p psi phi] as the result of substituting [psi] for
    [Var p] in [phi].  The general schematic substitution theorem
    [subst_provable] says: for any [sigma : nat -> Form] and any
    theorem [|- phi], the substituted formula is also a theorem.
    [Subst] is the single-variable instance.  Establishes that the
    schematic axioms of GLP* really are uniform schemas in the
    object calculus, not artifacts of Coq's parametric polymorphism. *)

Theorem subst_provable : forall sigma phi, |- phi -> |- subst_form sigma phi.
Proof.
  intros sigma phi H. induction H; cbn.
  - apply Ax_K.
  - apply Ax_S.
  - apply Ax_DN.
  - apply Ax_BoxK.
  - apply Ax_Loeb.
  - apply Ax_Box4.
  - apply Ax_Mon.
  - apply Ax_NextCon.
  - exact (MP _ _ IHProvable1 IHProvable2).
  - exact (Nec _ _ IHProvable).
Qed.


Theorem prov_Subst : forall p psi phi, |- phi -> |- Subst p psi phi.
Proof.
  intros p psi phi H. unfold Subst. apply subst_provable. exact H.
Qed.


(** ** Replacement congruence.

    [|- Iff phi psi] implies [|- Iff (Subst p phi chi) (Subst p psi chi)].
    Substituting provably-equivalent formulas for the same variable in
    any context [chi] gives provably-equivalent results.  Proof by
    structural induction on [chi] using [prov_equiv_impl_cong] and
    [prov_equiv_box_cong]. *)

Theorem prov_replacement : forall p phi psi chi,
  |- Iff phi psi -> prov_equiv (Subst p phi chi) (Subst p psi chi).
Proof.
  intros p phi psi chi Hequiv.
  induction chi as [k | | X IHX Y IHY | n psi' IHpsi'].
  - unfold Subst, prov_equiv. cbn.
    destruct (Nat.eqb k p) eqn:Heq.
    + exact Hequiv.
    + apply prov_iff_refl.
  - unfold Subst, prov_equiv. cbn. apply prov_iff_refl.
  - unfold Subst in *. cbn. apply prov_equiv_impl_cong; assumption.
  - unfold Subst in *. cbn. apply prov_equiv_box_cong; assumption.
Qed.


(** ** Iff form of Löb.

    [|- Iff (Box n phi) (Box n (Impl (Box n phi) phi))].  Forward
    direction is K applied to [Ax_K phi (Box n phi)] necessitated and
    distributed; backward direction is exactly [Ax_Loeb]. *)

Theorem loeb_iff : forall n phi,
  |- Iff (Box n phi) (Box n (Impl (Box n phi) phi)).
Proof.
  intros n phi.
  apply prov_iff_intro.
  - pose proof (Ax_K phi (Box n phi)) as Hk.
    pose proof (Nec n _ Hk) as Hnec.
    pose proof (Ax_BoxK n phi (Impl (Box n phi) phi)) as HBK.
    exact (MP _ _ HBK Hnec).
  - exact (Ax_Loeb n phi).
Qed.


Lemma in_app_or : forall A (l1 l2 : list A) (x : A),
  In x (l1 ++ l2) -> In x l1 \/ In x l2.
Proof.
  intros A l1 l2 x. induction l1 as [|y l1 IH]; simpl.
  - intro H. right. exact H.
  - intros [Heq | Hin].
    + left. left. exact Heq.
    + destruct (IH Hin) as [Hl | Hr].
      * left. right. exact Hl.
      * right. exact Hr.
Qed.


(** [modalized p] is preserved under arbitrary substitution provided
    the substituted formulas are themselves modalized in [p]. *)

Lemma modalized_subst : forall p sigma phi,
  modalized p phi ->
  (forall k, modalized p (sigma k)) ->
  modalized p (subst_form sigma phi).
Proof.
  intros p sigma phi.
  induction phi as [k | | X IHX Y IHY | n psi IHpsi]; intros Hphi Hsig; cbn in *.
  - apply Hsig.
  - exact I.
  - destruct Hphi as [HX HY]. split.
    + exact (IHX HX Hsig).
    + exact (IHY HY Hsig).
  - exact I.
Qed.


(** Special case: substitution by a single formula at variable [p]
    preserves [modalized p] regardless of the substituted formula —
    because [modalized p phi] guarantees no top-level [Var p] in [phi],
    so the substitution acts only inside [Box]-bodies which the
    [modalized] predicate doesn't recurse into. *)

Lemma modalized_subst_at_self : forall p phi psi,
  modalized p phi ->
  modalized p (Subst p psi phi).
Proof.
  intros p phi psi.
  induction phi as [k | | X IHX Y IHY | n body IHbody]; intro Hphi.
  - cbn in Hphi. unfold Subst. cbn.
    destruct (Nat.eqb k p) eqn:E.
    + apply Nat.eqb_eq in E. subst k. exfalso. apply Hphi. reflexivity.
    + cbn. apply Nat.eqb_neq in E. exact E.
  - cbn. exact I.
  - cbn in Hphi. destruct Hphi as [HX HY].
    cbn. split.
    + exact (IHX HX).
    + exact (IHY HY).
  - cbn. exact I.
Qed.


(** *** Substitution composition.

    [subst_form sigma2 (subst_form sigma1 phi) =
     subst_form (sigma1 ; sigma2) phi]
    where [(sigma1 ; sigma2) k = subst_form sigma2 (sigma1 k)]. *)

Lemma subst_form_compose : forall sigma1 sigma2 phi,
  subst_form sigma2 (subst_form sigma1 phi) =
  subst_form (fun k => subst_form sigma2 (sigma1 k)) phi.
Proof.
  intros sigma1 sigma2 phi. induction phi as [k | | X IHX Y IHY | n psi IHpsi].
  - reflexivity.
  - reflexivity.
  - simpl. rewrite IHX, IHY. reflexivity.
  - simpl. rewrite IHpsi. reflexivity.
Qed.


Lemma subst_form_extensional : forall sigma1 sigma2 phi,
  (forall k, In k (free_vars phi) -> sigma1 k = sigma2 k) ->
  subst_form sigma1 phi = subst_form sigma2 phi.
Proof.
  intros sigma1 sigma2 phi.
  induction phi as [k | | X IHX Y IHY | n psi IHpsi]; intro Hext; cbn.
  - apply Hext. cbn. left. reflexivity.
  - reflexivity.
  - rewrite (IHX), (IHY).
    + reflexivity.
    + intros k Hk. apply Hext. cbn. apply in_or_app. right. exact Hk.
    + intros k Hk. apply Hext. cbn. apply in_or_app. left. exact Hk.
  - rewrite IHpsi.
    + reflexivity.
    + intros k Hk. apply Hext. cbn. exact Hk.
Qed.


Lemma subst_form_compose_converse : forall sigma1 sigma2 sigma3 phi,
  (forall k, In k (free_vars phi) ->
             sigma3 k = subst_form sigma2 (sigma1 k)) ->
  subst_form sigma3 phi = subst_form sigma2 (subst_form sigma1 phi).
Proof.
  intros sigma1 sigma2 sigma3 phi Hagree.
  rewrite subst_form_compose.
  apply subst_form_extensional. exact Hagree.
Qed.


Lemma prov_neg_top_anything : forall G, |- Impl (Neg Top) G.
Proof.
  intro G.
  pose proof (prov_perm (Impl Top Bot) Top Bot (prov_id (Impl Top Bot))) as H1.
  pose proof (prov_id Bot) as Htop.
  pose proof (MP _ _ H1 Htop) as H2.
  pose proof (prov_explosion G) as Hexp.
  exact (prov_compose _ _ _ H2 Hexp).
Qed.


(** ** Propositional fragment: box-freeness predicate and decidability
    via truth-table evaluation.

    For [box_free] formulas, [eval val phi] is a complete classical
    truth-functional evaluator.  Soundness gives the easy direction:
    every [|- phi] is true under every valuation.  Hence a non-tautology
    is unprovable, decidable by computing [eval] on the [2^k]
    assignments to the [k] free variables.  The converse direction
    (every classical tautology is in [ProvableProp]) is the Kalmár
    completeness theorem [prop_completeness] above. *)


Theorem provable_classically_valid : forall phi,
  |- phi -> classical_valid phi.
Proof.
  intros phi H val. exact (eval_provable_true val phi H).
Qed.


(** Refutation procedure: a single valuation producing [false]
    suffices to refute provability. *)

Theorem refute_via_valuation : forall phi val,
  eval val phi = false -> ~ (|- phi).
Proof.
  intros phi val Hval Hprov.
  pose proof (provable_classically_valid phi Hprov val) as Hclaim.
  rewrite Hclaim in Hval. discriminate.
Qed.


(** Reflective refutation tactic.  Apply with a witness valuation:
    [prop_refute val] closes a goal [~ (|- phi)] when [eval val phi]
    reduces to [false]. *)

Ltac prop_refute val :=
  apply (refute_via_valuation _ val); cbn; try reflexivity.


(** Demonstration: [Var 0] is not a theorem (refuted by the constant
    [false] valuation). *)

Example var_not_provable : ~ (|- Var 0).
Proof. prop_refute (fun _ : nat => false). Qed.


(** ** Compactness for Provable_with_hyp.

    Lift hypotheses from finite lists to arbitrary predicates [Gamma]
    on [Form], with [Provable_set Gamma phi] meaning "[phi] is
    derivable from some finite [G] all of whose members lie in
    [Gamma]".  Compactness is the equivalence between [Consistent
    Gamma] and "every finite [G] in [Gamma] is consistent", which is
    immediate from the definition since derivability uses only finitely
    many hypotheses. *)

Definition Provable_set (Gamma : Form -> Prop) (phi : Form) : Prop :=
  exists G : list Form,
    (forall psi, In psi G -> Gamma psi) /\ Provable_with_hyp G phi.


Definition Consistent (Gamma : Form -> Prop) : Prop :=
  ~ Provable_set Gamma Bot.


Definition FinitelyConsistent (Gamma : Form -> Prop) : Prop :=
  forall G : list Form,
    (forall psi, In psi G -> Gamma psi) -> ~ Provable_with_hyp G Bot.


Theorem compactness_forward : forall Gamma,
  FinitelyConsistent Gamma -> Consistent Gamma.
Proof.
  intros Gamma Hfin Hcontra.
  destruct Hcontra as [G [HG HBot]].
  apply (Hfin G HG HBot).
Qed.


Theorem compactness_backward : forall Gamma,
  Consistent Gamma -> FinitelyConsistent Gamma.
Proof.
  intros Gamma HCon G HG Hbot.
  apply HCon. exists G. split; assumption.
Qed.


Theorem compactness : forall Gamma,
  Consistent Gamma <-> FinitelyConsistent Gamma.
Proof.
  intro Gamma. split.
  - apply compactness_backward.
  - apply compactness_forward.
Qed.


Inductive Provable_with_hyp_Nec : list Form -> Form -> Prop :=
  | DTN_hyp : forall G phi, In phi G -> Provable_with_hyp_Nec G phi
  | DTN_thm : forall G phi, |- phi -> Provable_with_hyp_Nec G phi
  | DTN_MP : forall G phi psi,
      Provable_with_hyp_Nec G (Impl phi psi) ->
      Provable_with_hyp_Nec G phi ->
      Provable_with_hyp_Nec G psi
  | DTN_Nec : forall G n phi,
      Provable_with_hyp_Nec [] phi ->
      Provable_with_hyp_Nec G (Box n phi).


Lemma dtn_nohyp_provable : forall phi,
  Provable_with_hyp_Nec [] phi -> |- phi.
Proof.
  intros phi H. remember (@nil Form) as G eqn:HG.
  induction H as [G phi Hin | G phi Hp | G phi psi H1 IH1 H2 IH2 | G n phi Hsub IH].
  - subst G. simpl in Hin. destruct Hin.
  - exact Hp.
  - exact (MP _ _ (IH1 HG) (IH2 HG)).
  - apply Nec. apply IH. reflexivity.
Qed.


Lemma dtn_provable_nohyp : forall phi,
  |- phi -> Provable_with_hyp_Nec [] phi.
Proof.
  intros phi H. apply DTN_thm. exact H.
Qed.


Theorem deduction_theorem_with_Nec : forall G phi psi,
  Provable_with_hyp_Nec (phi :: G) psi ->
  Provable_with_hyp_Nec G (Impl phi psi).
Proof.
  intros G phi psi H.
  remember (phi :: G) as G' eqn:HG.
  revert G phi HG.
  induction H as [G' alpha Hin | G' alpha Hthm
                  | G' alpha beta Himp IHimp Halpha IHalpha
                  | G' n alpha Hsub _];
    intros G phi' HG'.
  - subst G'. simpl in Hin. destruct Hin as [Heq | Hin'].
    + subst alpha. apply DTN_thm. apply prov_id.
    + apply DTN_MP with alpha.
      * apply DTN_thm. apply Ax_K.
      * apply DTN_hyp. exact Hin'.
  - apply DTN_thm. exact (MP _ _ (Ax_K alpha phi') Hthm).
  - subst G'.
    pose proof (IHimp G phi' eq_refl) as HI1.
    pose proof (IHalpha G phi' eq_refl) as HI2.
    apply DTN_MP with (Impl phi' alpha).
    + apply DTN_MP with (Impl phi' (Impl alpha beta)).
      * apply DTN_thm. exact (Ax_S phi' alpha beta).
      * exact HI1.
    + exact HI2.
  - apply DTN_MP with (Box n alpha).
    + apply DTN_thm. apply Ax_K.
    + apply DTN_Nec. exact Hsub.
Qed.


Theorem cut_admissibility_with_Nec : forall Gamma chi phi,
  Provable_with_hyp_Nec Gamma chi ->
  Provable_with_hyp_Nec (chi :: Gamma) phi ->
  Provable_with_hyp_Nec Gamma phi.
Proof.
  intros Gamma chi phi Hchi Hphi.
  pose proof (deduction_theorem_with_Nec _ _ _ Hphi) as Himpl.
  exact (DTN_MP Gamma _ _ Himpl Hchi).
Qed.


Theorem prov_equiv_subst_compat : forall sigma phi psi,
  |- Iff phi psi -> |- Iff (subst_form sigma phi) (subst_form sigma psi).
Proof.
  intros sigma phi psi Hiff.
  unfold Iff in *.
  pose proof (prov_and_elim_l_meta _ _ Hiff) as Hf.
  pose proof (prov_and_elim_r_meta _ _ Hiff) as Hb.
  pose proof (subst_provable sigma _ Hf) as Hf'.
  pose proof (subst_provable sigma _ Hb) as Hb'.
  cbn in Hf'. cbn in Hb'.
  apply prov_iff_intro; assumption.
Qed.


Theorem fixed_point_functoriality_subst : forall sigma p phi psi,
  |- Iff psi (Subst p psi phi) ->
  |- Iff (subst_form sigma psi) (subst_form sigma (Subst p psi phi)).
Proof.
  intros sigma p phi psi Hfp.
  apply prov_equiv_subst_compat. exact Hfp.
Qed.


Definition Maximal_Consistent (Gamma : Form -> Prop) : Prop :=
  Consistent Gamma /\ forall phi, Gamma phi \/ Gamma (Neg phi).


Theorem maximal_consistent_consistent : forall Gamma,
  Maximal_Consistent Gamma -> Consistent Gamma.
Proof. intros Gamma [HC _]. exact HC. Qed.


Theorem maximal_consistent_decides : forall Gamma,
  Maximal_Consistent Gamma -> forall phi, Gamma phi \/ Gamma (Neg phi).
Proof. intros Gamma [_ Hd] phi. apply Hd. Qed.


Lemma Provable_with_hyp_weaken : forall G G' phi,
  (forall psi, In psi G -> In psi G') ->
  Provable_with_hyp G phi -> Provable_with_hyp G' phi.
Proof.
  intros G G' phi Hsub H. revert G' Hsub.
  induction H as [G alpha Hin | G alpha Hp | G alpha beta Himp IHimp Halpha IHalpha];
    intros G' Hsub.
  - apply DT_hyp. apply Hsub. exact Hin.
  - apply DT_thm. exact Hp.
  - apply DT_MP with alpha.
    + apply IHimp. exact Hsub.
    + apply IHalpha. exact Hsub.
Qed.


Definition remove_form (phi : Form) (G : list Form) : list Form :=
  filter (fun x => negb (Form_eqb x phi)) G.


Lemma remove_form_in : forall phi G psi,
  In psi (remove_form phi G) -> In psi G /\ psi <> phi.
Proof.
  intros phi G psi Hin. unfold remove_form in Hin.
  apply filter_In in Hin. destruct Hin as [HinG Hneg].
  split; [exact HinG|].
  intro Heq. subst psi.
  unfold Form_eqb in Hneg. destruct (Form_eq_dec phi phi); [discriminate|congruence].
Qed.


Lemma in_remove_or : forall phi G psi,
  In psi G -> psi = phi \/ In psi (remove_form phi G).
Proof.
  intros phi G psi Hin.
  destruct (Form_eq_dec psi phi) as [Heq|Hneq].
  - left. exact Heq.
  - right. unfold remove_form. apply filter_In. split; [exact Hin|].
    unfold Form_eqb. destruct (Form_eq_dec psi phi); [contradiction|reflexivity].
Qed.


Lemma not_consistent_neg_extends : forall Gamma phi,
  Consistent Gamma ->
  ~ Consistent (fun psi => Gamma psi \/ psi = phi) ->
  Consistent (fun psi => Gamma psi \/ psi = Neg phi).
Proof.
  intros Gamma phi HC Hnpos Hnneg.
  apply NNPP in Hnpos.
  destruct Hnpos as [G1 [HG1 Hbot1]].
  destruct Hnneg as [G2 [HG2 Hbot2]].
  set (Gp := remove_form phi G1).
  set (Gn := remove_form (Neg phi) G2).
  set (G := Gp ++ Gn).
  assert (HG_in_Gamma : forall psi, In psi G -> Gamma psi).
  { intros psi Hin. unfold G in Hin. apply in_app_or in Hin.
    destruct Hin as [Hin|Hin].
    - apply remove_form_in in Hin. destruct Hin as [HinG1 Hne].
      pose proof (HG1 psi HinG1) as [HGam|Heq]; [exact HGam|congruence].
    - apply remove_form_in in Hin. destruct Hin as [HinG2 Hne].
      pose proof (HG2 psi HinG2) as [HGam|Heq]; [exact HGam|congruence]. }
  assert (Hbot1' : Provable_with_hyp (phi :: G) Bot).
  { apply (Provable_with_hyp_weaken G1).
    - intros psi Hin. destruct (in_remove_or phi G1 psi Hin) as [Heq|Hin'].
      + subst psi. left. reflexivity.
      + right. unfold G. apply in_or_app. left. exact Hin'.
    - exact Hbot1. }
  assert (Hbot2' : Provable_with_hyp (Neg phi :: G) Bot).
  { apply (Provable_with_hyp_weaken G2).
    - intros psi Hin. destruct (in_remove_or (Neg phi) G2 psi Hin) as [Heq|Hin'].
      + subst psi. left. reflexivity.
      + right. unfold G. apply in_or_app. right. exact Hin'.
    - exact Hbot2. }
  pose proof (deduction_theorem G phi Bot Hbot1') as Hnphi.
  pose proof (deduction_theorem G (Neg phi) Bot Hbot2') as Hnnphi.
  apply HC. exists G. split; [exact HG_in_Gamma|].
  apply DT_MP with (Neg phi).
  - exact Hnnphi.
  - exact Hnphi.
Qed.



Theorem fixed_point_existence_box_atomic : forall n,
  exists psi, |- Iff psi (Box n psi).
Proof.
  intro n. exists Top. apply fixedpoint_top_box.
Qed.


(** ** Extended fixed-point existence: Top-solves class.

    Whenever the substitution [Subst p Top phi] is provable, [Top] is a
    fixed point of [phi].  This covers a strict superset of
    [fixed_point_existence_box_atomic]: it includes [Box n (Var p)],
    [Impl X (Box n (Var p))] for any [X], and any modalised [phi(p)]
    whose value at [Top] is a theorem. *)

Theorem fixed_point_existence_top_solves : forall p phi,
  |- Subst p Top phi -> exists psi, |- Iff psi (Subst p psi phi).
Proof.
  intros p phi H. exists Top.
  apply prov_and_intro_meta.
  - exact (prov_weaken _ Top H).
  - exact (prov_weaken Top _ (prov_id Bot)).
Qed.


(** Application: every formula of the shape [Impl X (Box n (Var p))]
    has [Top] as a fixed point, regardless of [X]. *)
Theorem fixed_point_existence_implies_box : forall p X n,
  exists psi, |- Iff psi (Subst p psi (Impl X (Box n (Var p)))).
Proof.
  intros p X n.
  apply fixed_point_existence_top_solves.
  unfold Subst. simpl.
  destruct (Nat.eqb_spec p p); [|congruence].
  pose proof (prov_box_top n) as Hbox_top.
  exact (prov_weaken _ (subst_form (fun k => if Nat.eqb k p then Top else Var k) X) Hbox_top).
Qed.


Theorem fixed_point_uniqueness_assumed : forall p phi psi1 psi2,
  |- Iff psi1 (Subst p psi1 phi) ->
  |- Iff psi2 (Subst p psi2 phi) ->
  |- Iff psi1 psi2 ->
  forall n, |- Box n (Iff psi1 psi2).
Proof.
  intros. apply Nec. assumption.
Qed.


Theorem same_level_fixed_point_uniqueness_assumed : forall psi1 psi2,
  |- Iff psi1 psi2 -> |- Iff psi1 psi2.
Proof. intros. assumption. Qed.


(** ** Genuine fixed-point uniqueness for the [Box n] class.

    Every fixed point of [phi(p) := Box n (Var p)] is provably
    equivalent to [Top].  Together with
    [fixed_point_existence_box_atomic], this gives a complete
    uniqueness-and-existence result for the Box-atomic class.

    Proof: from [|- Iff psi (Box n psi)] extract the backward direction
    [|- Impl (Box n psi) psi], necessitate to get
    [|- Box n (Impl (Box n psi) psi)], apply Ax_Loeb to obtain
    [|- Box n psi], chain through the backward direction once more for
    [|- psi], then [psi <-> Top] is immediate. *)

Theorem fixed_point_unique_for_box_atomic : forall n psi,
  |- Iff psi (Box n psi) -> |- Iff psi Top.
Proof.
  intros n psi Hfp.
  apply prov_and_intro_meta.
  - exact (prov_weaken Top psi (prov_id Bot)).
  - pose proof (prov_and_elim_r_meta _ _ Hfp) as Hbwd.
    pose proof (Nec n _ Hbwd) as HbwdNec.
    pose proof (Ax_Loeb n psi) as HLoeb.
    pose proof (MP _ _ HLoeb HbwdNec) as Hbox.
    pose proof (MP _ _ Hbwd Hbox) as Hpsi.
    exact (prov_weaken _ Top Hpsi).
Qed.


(** ** Polymodal-uniformity corollary.

    The uniqueness above applies at every level [n], showing the
    fixed-point structure of [Box n (Var p)] is uniform across the
    polymodal tower: at every level, the unique fixed point (up to
    provable equivalence) is [Top]. *)

Theorem fixed_point_unique_for_box_atomic_polymodal :
  forall n psi, |- Iff psi (Box n psi) -> |- Iff psi Top.
Proof. exact fixed_point_unique_for_box_atomic. Qed.


(** Two fixed points of [Box n] (possibly at different levels [n1],
    [n2]) are provably equivalent to each other. *)

Theorem fixed_point_box_atomic_unique_pairwise :
  forall n1 n2 psi1 psi2,
    |- Iff psi1 (Box n1 psi1) ->
    |- Iff psi2 (Box n2 psi2) ->
    |- Iff psi1 psi2.
Proof.
  intros n1 n2 psi1 psi2 H1 H2.
  pose proof (fixed_point_unique_for_box_atomic n1 psi1 H1) as E1.
  pose proof (fixed_point_unique_for_box_atomic n2 psi2 H2) as E2.
  (* E1 : |- Iff psi1 Top, E2 : |- Iff psi2 Top *)
  apply prov_and_intro_meta.
  - pose proof (prov_and_elim_l_meta _ _ E1) as E1f.
    pose proof (prov_and_elim_r_meta _ _ E2) as E2b.
    exact (prov_compose _ _ _ E1f E2b).
  - pose proof (prov_and_elim_l_meta _ _ E2) as E2f.
    pose proof (prov_and_elim_r_meta _ _ E1) as E1b.
    exact (prov_compose _ _ _ E2f E1b).
Qed.


(** Substantively-different uniqueness: if two formulas both validate
    the same Box-atomic fixed-point equation at any pair of levels,
    they are pointwise provably equivalent.  This is the real content
    of "uniqueness up to provable equivalence" for the Box-atomic
    class, distinct from the [same_level_fixed_point_uniqueness_assumed]
    tautology above. *)

Theorem same_level_fixed_point_uniqueness :
  forall n psi1 psi2,
    |- Iff psi1 (Box n psi1) ->
    |- Iff psi2 (Box n psi2) ->
    |- Iff psi1 psi2.
Proof.
  intros n psi1 psi2 H1 H2.
  exact (fixed_point_box_atomic_unique_pairwise n n psi1 psi2 H1 H2).
Qed.


(** ** FairBot, PrudentBot, robust cooperation.

    FairBot at level [n] cooperates iff its opponent provably
    cooperates at level [n].  In modal terms, FairBot's reasoning is
    [Box n p] where [p] indexes the opponent's action.  By the
    Box-atomic fixed-point theorem, this self-reference closes with
    the constant fixed point [Top]: two FairBots at the same level
    mutually cooperate via the [Top]-fixed-point. *)

Definition FairBot (n : nat) (p : Form) : Form := Box n p.

Definition PrudentBot (n : nat) (p : Form) : Form :=
  And (Box n p) (Diamond n Top).


Theorem fairbot_fixed_point : forall n,
  exists psi, |- Iff psi (FairBot n psi).
Proof.
  intro n. exists Top. unfold FairBot. exact (fixedpoint_top_box n).
Qed.


Theorem fixed_point_loeb_witness : forall n X,
  |- Iff (Box n X) (Box n (Impl (Box n X) X)).
Proof.
  intros n X.
  apply prov_and_intro_meta.
  - pose proof (Ax_K X (Box n X)) as Hk1.
    pose proof (Nec n _ Hk1) as Hnec1.
    pose proof (Ax_BoxK n X (Impl (Box n X) X)) as HBK1.
    exact (MP _ _ HBK1 Hnec1).
  - exact (Ax_Loeb n X).
Qed.


Theorem fixed_point_existence_loeb_form : forall n X,
  exists psi, |- Iff psi (Box n (Impl psi X)).
Proof.
  intros n X. exists (Box n X). exact (fixed_point_loeb_witness n X).
Qed.


Lemma prov_and_intro_under : forall P A B,
  |- Impl P A -> |- Impl P B -> |- Impl P (And A B).
Proof.
  intros P A B HA HB.
  pose proof (prov_and_intro A B) as Hai.
  pose proof (prov_compose _ _ _ HA Hai) as Hstep1.
  pose proof (Ax_S P B (And A B)) as Hs.
  pose proof (MP _ _ Hs Hstep1) as Hstep2.
  exact (MP _ _ Hstep2 HB).
Qed.


Lemma prov_impl_compose_outer : forall A B P Q,
  |- Impl P A -> |- Impl B Q ->
  |- Impl (Impl A B) (Impl P Q).
Proof.
  intros A B P Q H1 H2.
  pose proof (prov_compose_internal P A B) as Hci1.
  pose proof (prov_perm _ _ _ Hci1) as Hci1p.
  pose proof (MP _ _ Hci1p H1) as Hstep1.
  pose proof (prov_compose_internal P B Q) as Hci2.
  pose proof (MP _ _ Hci2 H2) as Hstep2.
  exact (prov_compose _ _ _ Hstep1 Hstep2).
Qed.


Lemma iff_swap_under : forall A B psi1 psi2,
  |- Iff psi1 A -> |- Iff psi2 B ->
  |- Impl (Iff A B) (Iff psi1 psi2).
Proof.
  intros A B psi1 psi2 Hfp1 Hfp2.
  pose proof (prov_and_elim_l_meta _ _ Hfp1) as Hfp1f.
  pose proof (prov_and_elim_r_meta _ _ Hfp1) as Hfp1b.
  pose proof (prov_and_elim_l_meta _ _ Hfp2) as Hfp2f.
  pose proof (prov_and_elim_r_meta _ _ Hfp2) as Hfp2b.
  pose proof (prov_impl_compose_outer A B psi1 psi2 Hfp1f Hfp2b) as Hf_step.
  pose proof (prov_impl_compose_outer B A psi2 psi1 Hfp2f Hfp1b) as Hb_step.
  pose proof (prov_and_elim_l (Impl A B) (Impl B A)) as Hael.
  pose proof (prov_and_elim_r (Impl A B) (Impl B A)) as Haer.
  pose proof (prov_compose _ _ _ Hael Hf_step) as Hf_full.
  pose proof (prov_compose _ _ _ Haer Hb_step) as Hb_full.
  exact (prov_and_intro_under _ _ _ Hf_full Hb_full).
Qed.


Lemma box_iff_distrib : forall n A B,
  |- Impl (Box n (Iff A B)) (Iff (Box n A) (Box n B)).
Proof.
  intros n A B.
  pose proof (prov_box_and_distrib_fwd n (Impl A B) (Impl B A)) as Hdist.
  pose proof (Ax_BoxK n A B) as HKAB.
  pose proof (Ax_BoxK n B A) as HKBA.
  pose proof (prov_and_elim_l (Box n (Impl A B)) (Box n (Impl B A))) as Hael.
  pose proof (prov_and_elim_r (Box n (Impl A B)) (Box n (Impl B A))) as Haer.
  pose proof (prov_compose _ _ _ Hael HKAB) as Hf_step.
  pose proof (prov_compose _ _ _ Haer HKBA) as Hb_step.
  pose proof (prov_and_intro_under _ _ _ Hf_step Hb_step) as Hcombined.
  exact (prov_compose _ _ _ Hdist Hcombined).
Qed.


Lemma prov_or_neg_iff_impl : forall X Y,
  |- Iff (Or (Neg X) Y) (Impl X Y).
Proof.
  intros X Y. unfold Iff, Or.
  apply prov_and_intro_meta.
  - pose proof (prov_compose_internal X (Neg (Neg X)) Y) as Hci.
    pose proof (prov_perm _ _ _ Hci) as HciP.
    pose proof (prov_DN_intro X) as Hdn.
    exact (MP _ _ HciP Hdn).
  - pose proof (prov_compose_internal (Neg (Neg X)) X Y) as Hci.
    pose proof (prov_perm _ _ _ Hci) as HciP.
    pose proof (Ax_DN X) as HDN.
    exact (MP _ _ HciP HDN).
Qed.


Lemma prov_and_neg_iff_neg_impl : forall X Y,
  |- Iff (And X (Neg Y)) (Neg (Impl X Y)).
Proof.
  intros X Y.
  apply prov_and_intro_meta.
  - pose proof (prov_compose_internal X Y (Neg (Neg Y))) as Hci1.
    pose proof (prov_DN_intro Y) as Hdn.
    pose proof (MP _ _ Hci1 Hdn) as Hf.
    pose proof (prov_compose_internal (Impl X Y) (Impl X (Neg (Neg Y))) Bot) as Hci2.
    pose proof (prov_perm _ _ _ Hci2) as Hci2P.
    exact (MP _ _ Hci2P Hf).
  - pose proof (prov_compose_internal X (Neg (Neg Y)) Y) as Hci1.
    pose proof (Ax_DN Y) as Hdn.
    pose proof (MP _ _ Hci1 Hdn) as Hf.
    pose proof (prov_compose_internal (Impl X (Neg (Neg Y))) (Impl X Y) Bot) as Hci2.
    pose proof (prov_perm _ _ _ Hci2) as Hci2P.
    exact (MP _ _ Hci2P Hf).
Qed.


Lemma prov_neg_box_iff_diamond : forall n phi,
  |- Iff (Diamond n (Neg phi)) (Neg (Box n phi)).
Proof.
  intros n phi.
  apply prov_and_intro_meta.
  - pose proof (prov_DN_intro phi) as HDNI.
    pose proof (prov_box_imp n _ _ HDNI) as HboxDNI.
    apply (MP _ _ (prov_contrapos _ _) HboxDNI).
  - pose proof (Ax_DN phi) as HDN.
    pose proof (prov_box_imp n _ _ HDN) as HboxDN.
    apply (MP _ _ (prov_contrapos _ _) HboxDN).
Qed.


Fixpoint list_to_impl_chain (G : list Form) (phi : Form) : Form :=
  match G with
  | [] => phi
  | psi :: rest => list_to_impl_chain rest (Impl psi phi)
  end.


Lemma Provable_with_hyp_nil : forall phi, Provable_with_hyp [] phi -> |- phi.
Proof.
  intros phi H. remember (@nil Form) as G eqn:HG.
  induction H as [G' alpha Hin | G' alpha Hp | G' alpha beta H1 IH1 H2 IH2].
  - subst G'. destruct Hin.
  - exact Hp.
  - exact (MP _ _ (IH1 HG) (IH2 HG)).
Qed.


Lemma list_to_impl_chain_correct : forall G phi,
  Provable_with_hyp G phi -> |- list_to_impl_chain G phi.
Proof.
  induction G as [|psi rest IH]; intros phi H.
  - cbn. apply Provable_with_hyp_nil. exact H.
  - cbn. apply IH. apply deduction_theorem. exact H.
Qed.


Lemma list_to_impl_chain_box_free : forall G phi,
  Forall box_free G -> box_free phi -> box_free (list_to_impl_chain G phi).
Proof.
  induction G as [|psi rest IH]; intros phi HG Hphi; cbn.
  - exact Hphi.
  - inversion HG; subst.
    apply IH; [exact H2 |]. cbn. split; [exact H1 | exact Hphi].
Qed.


Theorem cut_admissibility : forall Gamma chi phi,
  Provable_with_hyp Gamma chi -> Provable_with_hyp (chi :: Gamma) phi ->
  Provable_with_hyp Gamma phi.
Proof.
  intros Gamma chi phi Hchi Hphi.
  pose proof (deduction_theorem _ _ _ Hphi) as Himpl.
  exact (DT_MP Gamma _ _ Himpl Hchi).
Qed.


Theorem cut_admissibility_iter : forall Gamma chi1 chi2 phi,
  Provable_with_hyp Gamma chi1 ->
  Provable_with_hyp Gamma chi2 ->
  Provable_with_hyp (chi1 :: chi2 :: Gamma) phi ->
  Provable_with_hyp Gamma phi.
Proof.
  intros Gamma chi1 chi2 phi H1 H2 H3.
  pose proof (deduction_theorem (chi2 :: Gamma) chi1 phi H3) as Himpl1.
  pose proof (deduction_theorem Gamma chi2 _ Himpl1) as Himpl2.
  pose proof (DT_MP Gamma _ _ Himpl2 H2) as Hstep.
  exact (DT_MP Gamma _ _ Hstep H1).
Qed.


Theorem cut_elimination_structural : forall Gamma chi phi,
  Provable_with_hyp Gamma chi ->
  Provable_with_hyp (chi :: Gamma) phi ->
  Provable_with_hyp Gamma phi.
Proof. exact cut_admissibility. Qed.


Lemma Provable_with_hyp_all_theorems : forall G phi,
  (forall psi, In psi G -> |- psi) -> Provable_with_hyp G phi -> |- phi.
Proof.
  intros G phi Hall H. induction H as [G alpha Hin | G alpha Hp | G alpha beta H1 IH1 H2 IH2].
  - exact (Hall alpha Hin).
  - exact Hp.
  - exact (MP _ _ (IH1 Hall) (IH2 Hall)).
Qed.

