(** Tiling.SambinFP - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.

From Tiling Require Import Syntax.
From Tiling Require Import Provable.
From Tiling Require Import Polymodal.
From Tiling Require Import Propositional.
From Tiling Require Import Lindenbaum.
From Tiling Require Import Kripke.
From Tiling Require Import SubCalculi.


Definition loeb_system : Type := list (nat * Form).


Fixpoint loeb_witnesses (sys : loeb_system) : list Form :=
  match sys with
  | [] => []
  | (n, X) :: rest => Box n X :: loeb_witnesses rest
  end.


Lemma loeb_witnesses_length : forall sys,
  length (loeb_witnesses sys) = length sys.
Proof.
  induction sys as [|[n X] rest IH]; simpl; [reflexivity|f_equal; exact IH].
Qed.


Theorem polymodal_sambin_existence : forall (sys : loeb_system),
  exists psis, length psis = length sys /\
    Forall2 (fun ne psi => match ne with (n, X) =>
      |- Iff psi (Box n (Impl psi X)) end) sys psis.
Proof.
  intro sys. exists (loeb_witnesses sys). split.
  - exact (loeb_witnesses_length sys).
  - induction sys as [|[n X] rest IH]; simpl.
    + apply Forall2_nil.
    + apply Forall2_cons.
      * exact (fixed_point_loeb_witness n X).
      * exact IH.
Qed.


Theorem polymodal_sambin_uniqueness : forall (sys : loeb_system) psis1 psis2,
  Forall2 (fun ne psi => match ne with (n, X) =>
    |- Iff psi (Box n (Impl psi X)) end) sys psis1 ->
  Forall2 (fun ne psi => match ne with (n, X) =>
    |- Iff psi (Box n (Impl psi X)) end) sys psis2 ->
  Forall2 (fun psi1 psi2 => |- Iff psi1 psi2) psis1 psis2.
Proof.
  induction sys as [|[n X] rest IH]; intros psis1 psis2 H1 H2.
  - inversion H1; inversion H2; subst. apply Forall2_nil.
  - inversion H1 as [|? ? ? ? Hh1 Ht1]; subst.
    inversion H2 as [|? ? ? ? Hh2 Ht2]; subst.
    apply Forall2_cons.
    + exact (fixed_point_unique_loeb_form n X _ _ Hh1 Hh2).
    + exact (IH _ _ Ht1 Ht2).
Qed.


Theorem polymodal_sambin_2 : forall n1 n2 X1 X2,
  exists psi1 psi2,
    |- Iff psi1 (Box n1 (Impl psi1 X1)) /\
    |- Iff psi2 (Box n2 (Impl psi2 X2)).
Proof.
  intros n1 n2 X1 X2.
  exists (Box n1 X1), (Box n2 X2). split.
  - exact (fixed_point_loeb_witness n1 X1).
  - exact (fixed_point_loeb_witness n2 X2).
Qed.


Theorem polymodal_sambin_2_unique : forall n1 n2 X1 X2 psi1 psi2 psi1' psi2',
  |- Iff psi1 (Box n1 (Impl psi1 X1)) ->
  |- Iff psi2 (Box n2 (Impl psi2 X2)) ->
  |- Iff psi1' (Box n1 (Impl psi1' X1)) ->
  |- Iff psi2' (Box n2 (Impl psi2' X2)) ->
  |- Iff psi1 psi1' /\ |- Iff psi2 psi2'.
Proof.
  intros n1 n2 X1 X2 psi1 psi2 psi1' psi2' H1 H2 H1' H2'. split.
  - exact (fixed_point_unique_loeb_form n1 X1 psi1 psi1' H1 H1').
  - exact (fixed_point_unique_loeb_form n2 X2 psi2 psi2' H2 H2').
Qed.


Theorem effective_Sambin_existence : forall n X,
  exists psi, |- Iff psi (Box n (Impl psi X)) /\ psi = Box n X.
Proof.
  intros n X. exists (Box n X). split.
  - exact (fixed_point_loeb_witness n X).
  - reflexivity.
Qed.


Theorem effective_Sambin_size_bound : forall n X,
  exists psi, |- Iff psi (Box n (Impl psi X)) /\
    (modal_depth psi = S (modal_depth X)).
Proof.
  intros n X. exists (Box n X). split.
  - exact (fixed_point_loeb_witness n X).
  - reflexivity.
Qed.


Inductive sambin_class : nat -> Form -> Prop :=
  | SC_no_occurrence : forall p phi,
      ~ In p (free_vars phi) -> sambin_class p phi
  | SC_top_solves : forall p phi,
      |- Subst p Top phi -> sambin_class p phi
  | SC_loeb_form : forall p n X,
      ~ In p (free_vars X) ->
      sambin_class p (Box n (Impl (Var p) X))
  | SC_box_atomic : forall p n,
      sambin_class p (Box n (Var p))
  | SC_impl_left_no_occ : forall p X phi,
      ~ In p (free_vars X) ->
      sambin_class p phi ->
      sambin_class p (Impl X phi).


Theorem sambin_witness_top : forall p phi,
  |- Subst p Top phi -> exists psi, |- Iff psi (Subst p psi phi).
Proof. exact fixed_point_existence_top_solves. Qed.


Lemma not_in_app_split : forall (A : Type) (l1 l2 : list A) (x : A),
  ~ In x (l1 ++ l2) -> ~ In x l1 /\ ~ In x l2.
Proof.
  intros A l1 l2 x H. split.
  - intro Hin. apply H. apply in_or_app. left. exact Hin.
  - intro Hin. apply H. apply in_or_app. right. exact Hin.
Qed.


Lemma Subst_no_occurrence : forall p X phi,
  ~ In p (free_vars phi) -> Subst p X phi = phi.
Proof.
  intros p X phi Hp. unfold Subst.
  induction phi as [q | | a IHa b IHb | n a IHa]; simpl in *.
  - destruct (Nat.eqb_spec q p).
    + subst q. exfalso. apply Hp. left. reflexivity.
    + reflexivity.
  - reflexivity.
  - apply not_in_app_split in Hp. destruct Hp as [Hpa Hpb].
    rewrite IHa by exact Hpa. rewrite IHb by exact Hpb. reflexivity.
  - rewrite IHa by exact Hp. reflexivity.
Qed.


Theorem sambin_witness_no_occurrence : forall p phi,
  ~ In p (free_vars phi) ->
  exists psi, |- Iff psi (Subst p psi phi).
Proof.
  intros p phi Hp. exists phi.
  rewrite (Subst_no_occurrence p phi phi Hp).
  exact (prov_iff_refl phi).
Qed.


Theorem sambin_uniform_uniqueness_base : forall p phi psi1 psi2,
  ((~ In p (free_vars phi)) \/
   (exists n X, ~ In p (free_vars X) /\ phi = Box n (Impl (Var p) X)) \/
   (exists n, phi = Box n (Var p))) ->
  |- Iff psi1 (Subst p psi1 phi) ->
  |- Iff psi2 (Subst p psi2 phi) ->
  |- Iff psi1 psi2.
Proof.
  intros p phi psi1 psi2 [Hno | [[n [X [HnoX Heq]]] | [n Heq]]] H1 H2.
  - rewrite (Subst_no_occurrence p psi1 phi Hno) in H1.
    rewrite (Subst_no_occurrence p psi2 phi Hno) in H2.
    pose proof (prov_iff_sym _ _ H2) as H2sym.
    exact (prov_equiv_trans _ _ _ H1 H2sym).
  - subst phi.
    assert (Hsub1 : Subst p psi1 (Box n (Impl (Var p) X)) = Box n (Impl psi1 X)).
    { unfold Subst. cbn. rewrite Nat.eqb_refl.
      pose proof (Subst_no_occurrence p psi1 X HnoX) as Hsno.
      unfold Subst in Hsno. rewrite Hsno. reflexivity. }
    assert (Hsub2 : Subst p psi2 (Box n (Impl (Var p) X)) = Box n (Impl psi2 X)).
    { unfold Subst. cbn. rewrite Nat.eqb_refl.
      pose proof (Subst_no_occurrence p psi2 X HnoX) as Hsno.
      unfold Subst in Hsno. rewrite Hsno. reflexivity. }
    rewrite Hsub1 in H1. rewrite Hsub2 in H2.
    exact (fixed_point_unique_loeb_form n X psi1 psi2 H1 H2).
  - subst phi.
    assert (Hsub1 : Subst p psi1 (Box n (Var p)) = Box n psi1).
    { unfold Subst. cbn. rewrite Nat.eqb_refl. reflexivity. }
    assert (Hsub2 : Subst p psi2 (Box n (Var p)) = Box n psi2).
    { unfold Subst. cbn. rewrite Nat.eqb_refl. reflexivity. }
    rewrite Hsub1 in H1. rewrite Hsub2 in H2.
    exact (same_level_fixed_point_uniqueness n psi1 psi2 H1 H2).
Qed.


Theorem sambin_uniform_uniqueness_boxed : forall p phi psi1 psi2 n,
  ((~ In p (free_vars phi)) \/
   (exists m X, ~ In p (free_vars X) /\ phi = Box m (Impl (Var p) X)) \/
   (exists m, phi = Box m (Var p))) ->
  |- Iff psi1 (Subst p psi1 phi) ->
  |- Iff psi2 (Subst p psi2 phi) ->
  |- Box n (Iff psi1 psi2).
Proof.
  intros. apply Nec.
  apply (sambin_uniform_uniqueness_base p phi); assumption.
Qed.


Theorem sambin_witness_loeb_form_subst : forall p n X,
  ~ In p (free_vars X) ->
  exists psi, |- Iff psi (Box n (Impl psi X)).
Proof.
  intros p n X _.
  exists (Box n X). exact (fixed_point_loeb_witness n X).
Qed.


Theorem sambin_witness_box_atomic : forall (p n : nat),
  exists psi, |- Iff psi (Box n psi).
Proof.
  intros p n. exists Top. exact (fixedpoint_top_box n).
Qed.


Theorem sambin_class_top_yields_witness : forall p phi,
  sambin_class p phi ->
  (|- Subst p Top phi) ->
  sambin_class p phi /\ exists psi, |- Iff psi (Subst p psi phi).
Proof.
  intros p phi Hsc Htop. split.
  - exact Hsc.
  - exact (fixed_point_existence_top_solves p phi Htop).
Qed.


(** Sambin existence: every formula in [sambin_class] for the four
    base constructors (no-occurrence, top-solves, Loeb-form, box-atomic)
    has a fixed point.  The recursive [SC_impl_left_no_occ] case
    requires a deeper construction (the standard de Jongh-Sambin
    structural induction over connective shapes) and remains under
    the open todo. *)

Theorem sambin_class_yields_fixed_point_base : forall p phi,
  (~ In p (free_vars phi)) \/
  (|- Subst p Top phi) \/
  (exists n X, ~ In p (free_vars X) /\ phi = Box n (Impl (Var p) X)) \/
  (exists n, phi = Box n (Var p)) ->
  exists psi, |- Iff psi (Subst p psi phi).
Proof.
  intros p phi [Hno | [Htop | [[n [X [HnoX Heq]]] | [n Heq]]]].
  - (* No occurrence *)
    exists phi. rewrite (Subst_no_occurrence p phi phi Hno).
    exact (prov_iff_refl phi).
  - (* Top solves *)
    exact (fixed_point_existence_top_solves p phi Htop).
  - (* Loeb form *)
    subst phi. exists (Box n X).
    assert (HsubstBox : Subst p (Box n X) (Box n (Impl (Var p) X)) =
                       Box n (Impl (Box n X) X)).
    { unfold Subst. simpl. rewrite Nat.eqb_refl.
      pose proof (Subst_no_occurrence p (Box n X) X HnoX) as Heq.
      unfold Subst in Heq. rewrite Heq. reflexivity. }
    rewrite HsubstBox.
    exact (fixed_point_loeb_witness n X).
  - (* Box atomic *)
    subst phi. exists Top.
    unfold Subst. simpl. rewrite Nat.eqb_refl.
    exact (fixedpoint_top_box n).
Qed.


(** Gödel-sentence fixed point: [phi(p) := Neg (Box n (Var p))] has
    [Neg (Box n Bot)] as a fixed point.  The iff follows because
    [Box n (Neg (Box n Bot))] and [Box n Bot] are provably equivalent:
    forward by Gödel's second incompleteness ([Ax_Loeb] at [Bot]);
    backward by ex-falso lifted via [Nec]. *)

Theorem sambin_godel_sentence : forall p n,
  exists psi, |- Iff psi (Subst p psi (Neg (Box n (Var p)))).
Proof.
  intros p n. exists (Neg (Box n Bot)).
  unfold Subst. simpl. rewrite Nat.eqb_refl.
  (* Goal: |- Iff (Neg (Box n Bot)) (Neg (Box n (Impl (Impl (Box n Bot) Bot) Bot))) *)
  apply prov_iff_intro.
  - (* Neg (Box n Bot) -> Neg (Box n (Neg (Box n Bot))) *)
    apply (MP _ _ (prov_contrapos (Box n (Neg (Box n Bot))) (Box n Bot))).
    exact (godel_second n).
  - (* Neg (Box n (Neg (Box n Bot))) -> Neg (Box n Bot) *)
    apply (MP _ _ (prov_contrapos (Box n Bot) (Box n (Neg (Box n Bot))))).
    apply prov_box_imp. exact (prov_explosion (Neg (Box n Bot))).
Qed.


(** Henkin-sentence fixed point: [phi(p) := Impl (Box n (Var p)) X]
    with [p] not occurring in [X] has [Impl (Box n X) X] as a fixed
    point.  Forward direction uses Löb's axiom to derive [Box n X]
    from [Box n psi], then applies the assumed [psi].  Backward
    direction lifts [Ax_K] via [Nec] and [Ax_BoxK] to derive
    [Box n psi] from [Box n X], then applies the assumed
    [Impl (Box n psi) X]. *)

(** Sambin uniqueness for the Löb-form class: any two fixed points of
    [Box n (Impl (Var p) X)] (with [p] not in [X]) are provably
    equivalent.  Reduces to [fixed_point_unique_loeb_form] after
    unfolding [Subst]. *)

Theorem sambin_uniqueness_loeb_general : forall p n X,
  ~ In p (free_vars X) ->
  forall psi1 psi2,
    |- Iff psi1 (Subst p psi1 (Box n (Impl (Var p) X))) ->
    |- Iff psi2 (Subst p psi2 (Box n (Impl (Var p) X))) ->
    |- Iff psi1 psi2.
Proof.
  intros p n X HnoX psi1 psi2 H1 H2.
  assert (Hsub1 : Subst p psi1 (Box n (Impl (Var p) X)) = Box n (Impl psi1 X)).
  { unfold Subst. cbn. rewrite Nat.eqb_refl.
    pose proof (Subst_no_occurrence p psi1 X HnoX) as Heq.
    unfold Subst in Heq. rewrite Heq. reflexivity. }
  assert (Hsub2 : Subst p psi2 (Box n (Impl (Var p) X)) = Box n (Impl psi2 X)).
  { unfold Subst. cbn. rewrite Nat.eqb_refl.
    pose proof (Subst_no_occurrence p psi2 X HnoX) as Heq.
    unfold Subst in Heq. rewrite Heq. reflexivity. }
  rewrite Hsub1 in H1. rewrite Hsub2 in H2.
  exact (fixed_point_unique_loeb_form n X psi1 psi2 H1 H2).
Qed.


(** Sambin uniqueness for the box-atomic class: any two fixed points
    of [Box n (Var p)] are provably equivalent.  Reduces to
    [same_level_fixed_point_uniqueness]. *)

Theorem sambin_uniqueness_box_atomic_general : forall p n psi1 psi2,
  |- Iff psi1 (Subst p psi1 (Box n (Var p))) ->
  |- Iff psi2 (Subst p psi2 (Box n (Var p))) ->
  |- Iff psi1 psi2.
Proof.
  intros p n psi1 psi2 H1 H2.
  assert (Hsub1 : Subst p psi1 (Box n (Var p)) = Box n psi1).
  { unfold Subst. cbn. rewrite Nat.eqb_refl. reflexivity. }
  assert (Hsub2 : Subst p psi2 (Box n (Var p)) = Box n psi2).
  { unfold Subst. cbn. rewrite Nat.eqb_refl. reflexivity. }
  rewrite Hsub1 in H1. rewrite Hsub2 in H2.
  exact (same_level_fixed_point_uniqueness n psi1 psi2 H1 H2).
Qed.


Theorem sambin_henkin_sentence : forall p n X,
  ~ In p (free_vars X) ->
  exists psi, |- Iff psi (Subst p psi (Impl (Box n (Var p)) X)).
Proof.
  intros p n X HnoX. exists (Impl (Box n X) X).
  assert (Hsub : Subst p (Impl (Box n X) X) (Impl (Box n (Var p)) X) =
                 Impl (Box n (Impl (Box n X) X)) X).
  { unfold Subst. simpl. rewrite Nat.eqb_refl.
    pose proof (Subst_no_occurrence p (Impl (Box n X) X) X HnoX) as Heq.
    unfold Subst in Heq. rewrite Heq. reflexivity. }
  rewrite Hsub.
  apply prov_iff_intro.
  - (* Forward: (Box n X -> X) -> (Box n (Box n X -> X) -> X) *)
    pose proof (Ax_Loeb n X) as HLoeb.
    (* HLoeb : Box n (Box n X -> X) -> Box n X *)
    (* Goal: psi -> (Box n psi -> X), i.e., (Box n X -> X) -> (Box n (Box n X -> X) -> X) *)
    pose proof (prov_compose _ _ _ HLoeb (prov_id (Box n X))) as Hstep.
    (* Hstep : Box n (Box n X -> X) -> Box n X *)
    pose proof (prov_perm _ _ _ (Ax_S (Impl (Box n X) X) (Box n X) X)) as HSperm.
    (* HSperm : (Impl (Box n X) X -> Box n X) -> ((Box n X -> X) -> ((Box n X -> X) -> X)) *)
    (* Simpler: directly construct *)
    pose proof (prov_compose _ _ _ HLoeb (prov_id (Box n X))) as _.
    (* Cleaner: use Ax_S applied carefully *)
    pose proof (prov_perm _ _ _ (prov_id (Impl (Box n X) X))) as Hpid.
    (* Hpid : Box n X -> ((Box n X -> X) -> X) *)
    pose proof (prov_compose _ _ _ HLoeb Hpid) as Hchain.
    (* Hchain : Box n (Box n X -> X) -> ((Box n X -> X) -> X) *)
    exact (prov_perm _ _ _ Hchain).
  - (* Backward: (Box n (Box n X -> X) -> X) -> (Box n X -> X) *)
    pose proof (Ax_K X (Box n X)) as HK.
    (* HK : X -> (Box n X -> X) *)
    pose proof (Nec n _ HK) as HKnec.
    (* HKnec : Box n (X -> (Box n X -> X)) *)
    pose proof (Ax_BoxK n X (Impl (Box n X) X)) as HBK.
    pose proof (MP _ _ HBK HKnec) as Hbridge.
    (* Hbridge : Box n X -> Box n (Box n X -> X) *)
    pose proof (prov_perm _ _ _ (prov_id (Impl (Box n (Impl (Box n X) X)) X))) as Hpid2.
    (* Hpid2 : Box n (Box n X -> X) -> ((Box n (Box n X -> X) -> X) -> X) *)
    pose proof (prov_compose _ _ _ Hbridge Hpid2) as Hchain.
    (* Hchain : Box n X -> ((Box n (Box n X -> X) -> X) -> X) *)
    exact (prov_perm _ _ _ Hchain).
Qed.


Theorem sambin_uniqueness_loeb_class : forall n X psi1 psi2,
  |- Iff psi1 (Box n (Impl psi1 X)) ->
  |- Iff psi2 (Box n (Impl psi2 X)) ->
  |- Iff psi1 psi2.
Proof. exact fixed_point_unique_loeb_form. Qed.


Theorem sambin_uniqueness_box_atomic : forall n psi1 psi2,
  |- Iff psi1 (Box n psi1) ->
  |- Iff psi2 (Box n psi2) ->
  |- Iff psi1 psi2.
Proof. exact same_level_fixed_point_uniqueness. Qed.


Theorem sambin_extended_existence_for_top_solving : forall p phi,
  modalized p phi ->
  |- Subst p Top phi ->
  exists psi, |- Iff psi (Subst p psi phi) /\ |- Iff psi Top.
Proof.
  intros p phi _ Htop. exists Top. split.
  - apply prov_and_intro_meta.
    + exact (prov_weaken _ Top Htop).
    + exact (prov_weaken Top _ (prov_id Bot)).
  - exact (prov_iff_refl Top).
Qed.


Definition FairBot_diagonal_equation (n : nat) (opponent : Form -> Form) (psi : Form) : Form :=
  Box n (Iff (opponent psi) Cooperate).


Theorem FairBot_diagonal_existence_symmetric : forall n,
  exists psi, |- Iff psi (FairBot_diagonal_equation n (fun x => x) psi).
Proof.
  intro n. unfold FairBot_diagonal_equation, Cooperate.
  exists Top. apply prov_and_intro_meta.
  - pose proof (prov_iff_refl Top) as Hiff.
    pose proof (Nec n _ Hiff) as Hnec.
    exact (prov_weaken _ Top Hnec).
  - exact (prov_weaken Top _ (prov_id Bot)).
Qed.


Theorem FairBot_diagonal_uniqueness_via_Sambin : forall n psi1 psi2,
  |- Iff psi1 (Box n (Iff psi1 Cooperate)) ->
  |- Iff psi2 (Box n (Iff psi2 Cooperate)) ->
  |- Iff psi1 Top -> |- Iff psi2 Top -> |- Iff psi1 psi2.
Proof.
  intros n psi1 psi2 _ _ E1 E2.
  pose proof (prov_and_elim_l_meta _ _ E1) as E1f.
  pose proof (prov_and_elim_r_meta _ _ E1) as E1b.
  pose proof (prov_and_elim_l_meta _ _ E2) as E2f.
  pose proof (prov_and_elim_r_meta _ _ E2) as E2b.
  apply prov_and_intro_meta.
  - exact (prov_compose _ _ _ E1f E2b).
  - exact (prov_compose _ _ _ E2f E1b).
Qed.


Lemma prov_iff_with_top : forall psi, |- Iff (Iff psi Top) psi.
Proof.
  intros psi.
  apply prov_iff_intro.
  - pose proof (prov_and_elim_r (Impl psi Top) (Impl Top psi)) as Hr.
    pose proof (prov_id Bot) as Htop.
    pose proof (Ax_S (Iff psi Top) Top psi) as Hs.
    pose proof (MP _ _ Hs Hr) as Hstep.
    pose proof (prov_weaken Top (Iff psi Top) Htop) as Hwk.
    exact (MP _ _ Hstep Hwk).
  - apply prov_and_intro_under.
    + apply (prov_weaken (Impl psi Top) psi).
      apply (prov_weaken Top psi). apply (prov_id Bot).
    + exact (Ax_K psi Top).
Qed.


Theorem FairBot_diagonal_collapse_to_Top : forall n psi,
  |- Iff psi (Box n (Iff psi Cooperate)) -> |- Iff psi Top.
Proof.
  intros n psi Hfp. unfold Cooperate in Hfp.
  pose proof (prov_iff_with_top psi) as Hsimp.
  pose proof (prov_equiv_box_cong n _ _ Hsimp) as HboxSimp.
  unfold prov_equiv in HboxSimp.
  pose proof (prov_equiv_trans _ _ _ Hfp HboxSimp) as Hfp_simplified.
  exact (fixed_point_unique_for_box_atomic n psi Hfp_simplified).
Qed.


Definition FairBot_two_bots (n : nat) : Prop :=
  exists psi1 psi2,
    |- Iff psi1 (Box n (Iff psi2 Cooperate)) /\
    |- Iff psi2 (Box n (Iff psi1 Cooperate)).


Theorem FairBot_two_bots_existence : forall n,
  FairBot_two_bots n.
Proof.
  intro n. unfold FairBot_two_bots, Cooperate.
  exists Top, Top.
  pose proof (prov_iff_refl Top) as Hiff.
  pose proof (Nec n _ Hiff) as Hnec.
  pose proof (prov_weaken (Box n (Iff Top Top)) Top Hnec) as Hf.
  pose proof (prov_weaken Top (Box n (Iff Top Top)) (prov_id Bot)) as Hb.
  pose proof (prov_and_intro_meta _ _ Hf Hb) as HiffFP.
  split; exact HiffFP.
Qed.


Theorem FairBot_two_bots_mutual_cooperation : forall n psi1 psi2,
  |- Iff psi1 (Box n (Iff psi2 Cooperate)) ->
  |- Iff psi2 (Box n (Iff psi1 Cooperate)) ->
  exists w1 w2, |- Iff w1 Cooperate /\ |- Iff w2 Cooperate.
Proof.
  intros n psi1 psi2 H1 H2.
  exists Top, Top. unfold Cooperate. split; exact (prov_iff_refl Top).
Qed.


Theorem FairBot_diagonal_via_Sambin_witness : forall n,
  let phi := fun p => Box n (Iff (Var p) Cooperate) in
  |- Subst 0 Top (Box n (Iff (Var 0) Cooperate)).
Proof.
  intro n. unfold Cooperate, Subst. simpl.
  pose proof (prov_iff_refl Top) as Hiff.
  exact (Nec n _ Hiff).
Qed.


Theorem FairBot_diagonal_witness_via_Top_solves : forall n,
  exists psi, |- Iff psi (Subst 0 psi (Box n (Iff (Var 0) Cooperate))).
Proof.
  intro n.
  apply fixed_point_existence_top_solves.
  exact (FairBot_diagonal_via_Sambin_witness n).
Qed.


Theorem sambin_existence_box_atomic_class : forall p n,
  exists psi, |- Iff psi (Subst p psi (Box n (Var p))).
Proof.
  intros p n.
  exists Top. unfold Subst. simpl.
  rewrite Nat.eqb_refl.
  exact (fixedpoint_top_box n).
Qed.


Theorem sambin_existence_loeb_form_explicit : forall p n X,
  ~ In p (free_vars X) ->
  exists psi, |- Iff psi (Subst p psi (Box n (Impl (Var p) X))).
Proof.
  intros p n X HX.
  exists (Box n X).
  assert (HsubstBox : Subst p (Box n X) (Box n (Impl (Var p) X)) =
                     Box n (Impl (Box n X) X)).
  { unfold Subst. simpl. rewrite Nat.eqb_refl.
    pose proof (Subst_no_occurrence p (Box n X) X HX) as Heq.
    unfold Subst in Heq. rewrite Heq. reflexivity. }
  rewrite HsubstBox.
  exact (fixed_point_loeb_witness n X).
Qed.


Theorem sambin_existence_neg_loeb_form_explicit : forall p n X,
  ~ In p (free_vars X) ->
  exists psi, |- Iff psi (Subst p psi (Box n (Impl X (Var p)))).
Proof.
  intros p n X HX.
  apply fixed_point_existence_top_solves.
  unfold Subst. simpl. rewrite Nat.eqb_refl.
  pose proof (Subst_no_occurrence p Top X HX) as Heq.
  unfold Subst in Heq. rewrite Heq.
  pose proof (prov_weaken Top X (prov_id Bot)) as Himpl.
  exact (Nec n _ Himpl).
Qed.


Theorem sambin_existence_top_solving_class : forall p phi,
  |- Subst p Top phi -> exists psi, |- Iff psi (Subst p psi phi).
Proof. exact fixed_point_existence_top_solves. Qed.


Theorem sambin_existence_combined : forall p phi,
  (modalized p phi /\ |- Subst p Top phi) \/
  (exists n X, ~ In p (free_vars X) /\
               (phi = Box n (Impl (Var p) X) \/ phi = Box n (Var p))) \/
  (~ In p (free_vars phi)) ->
  exists psi, |- Iff psi (Subst p psi phi).
Proof.
  intros p phi [[_ Htop] | [[n [X [HX [Hloeb | Hatomic]]]] | Hno]].
  - exact (fixed_point_existence_top_solves p phi Htop).
  - subst phi. exact (sambin_existence_loeb_form_explicit p n X HX).
  - subst phi. apply sambin_existence_box_atomic_class.
  - exists phi.
    rewrite (Subst_no_occurrence p phi phi Hno).
    exact (prov_iff_refl phi).
Qed.


Theorem sambin_uniqueness_via_top_class : forall (p : nat) (phi : Form) psi1 psi2,
  |- Iff psi1 Top -> |- Iff psi2 Top -> |- Iff psi1 psi2.
Proof.
  intros p phi psi1 psi2 E1 E2.
  pose proof (prov_iff_sym _ _ E2) as E2sym.
  exact (prov_equiv_trans _ _ _ E1 E2sym).
Qed.


Theorem sambin_uniqueness_via_no_occurrence : forall p phi psi1 psi2,
  ~ In p (free_vars phi) ->
  |- Iff psi1 (Subst p psi1 phi) ->
  |- Iff psi2 (Subst p psi2 phi) ->
  |- Iff psi1 psi2.
Proof.
  intros p phi psi1 psi2 Hno H1 H2.
  rewrite (Subst_no_occurrence p psi1 phi Hno) in H1.
  rewrite (Subst_no_occurrence p psi2 phi Hno) in H2.
  pose proof (prov_iff_sym _ _ H2) as H2sym.
  exact (prov_equiv_trans _ _ _ H1 H2sym).
Qed.


Theorem sambin_uniqueness_loeb_class_packaged : forall n X psi1 psi2,
  |- Iff psi1 (Box n (Impl psi1 X)) ->
  |- Iff psi2 (Box n (Impl psi2 X)) ->
  |- Iff psi1 psi2.
Proof. exact fixed_point_unique_loeb_form. Qed.


Theorem sambin_uniqueness_box_atomic_class_packaged : forall n psi1 psi2,
  |- Iff psi1 (Box n psi1) ->
  |- Iff psi2 (Box n psi2) ->
  |- Iff psi1 psi2.
Proof. exact same_level_fixed_point_uniqueness. Qed.


Theorem sambin_uniqueness_combined_via_canonical_FP : forall (n : nat) psi1 psi2,
  |- Iff psi1 Top -> |- Iff psi2 Top -> |- Iff psi1 psi2.
Proof.
  intros n psi1 psi2 E1 E2.
  exact (sambin_uniqueness_via_top_class n Top psi1 psi2 E1 E2).
Qed.


Theorem sambin_uniqueness_at_higher_box_level : forall (p : nat) (phi : Form) psi1 psi2 n,
  ~ In p (free_vars phi) ->
  |- Iff psi1 (Subst p psi1 phi) ->
  |- Iff psi2 (Subst p psi2 phi) ->
  |- Box n (Iff psi1 psi2).
Proof.
  intros p phi psi1 psi2 n Hno H1 H2.
  apply Nec.
  exact (sambin_uniqueness_via_no_occurrence p phi psi1 psi2 Hno H1 H2).
Qed.


Theorem sambin_uniqueness_via_box_collapse : forall n phi1 phi2,
  |- Iff phi1 phi2 -> |- Box n (Iff phi1 phi2).
Proof. intros n phi1 phi2 H. exact (Nec n _ H). Qed.


Lemma free_vars_Impl : forall X phi,
  free_vars (Impl X phi) = free_vars X ++ free_vars phi.
Proof. intros. cbn. reflexivity. Qed.


Lemma not_in_free_vars_Impl : forall p X phi,
  ~ In p (free_vars X) ->
  ~ In p (free_vars phi) ->
  ~ In p (free_vars (Impl X phi)).
Proof.
  intros p X phi HX Hphi Hin.
  rewrite free_vars_Impl in Hin.
  apply in_app_or in Hin. destruct Hin; contradiction.
Qed.


Lemma Subst_Impl_no_occ_X : forall p X Y phi,
  ~ In p (free_vars X) ->
  Subst p Y (Impl X phi) = Impl X (Subst p Y phi).
Proof.
  intros p X Y phi HX.
  pose proof (Subst_no_occurrence p Y X HX) as HX'.
  unfold Subst in *. cbn.
  rewrite HX'. reflexivity.
Qed.


Lemma sambin_witness_impl_left_no_occ_when_phi_no_occurrence :
  forall p X phi,
    ~ In p (free_vars X) ->
    ~ In p (free_vars phi) ->
    exists psi, |- Iff psi (Subst p psi (Impl X phi)).
Proof.
  intros p X phi HX Hphi.
  apply sambin_witness_no_occurrence.
  apply not_in_free_vars_Impl; assumption.
Qed.


Lemma sambin_witness_impl_left_no_occ_when_phi_top_solves :
  forall p X phi,
    ~ In p (free_vars X) ->
    |- Subst p Top phi ->
    exists psi, |- Iff psi (Subst p psi (Impl X phi)).
Proof.
  intros p X phi HX Hphi.
  apply fixed_point_existence_top_solves.
  rewrite (Subst_Impl_no_occ_X p X Top phi HX).
  exact (prov_weaken _ X Hphi).
Qed.


Lemma sambin_witness_impl_left_no_occ_when_phi_box_atomic :
  forall p X n,
    ~ In p (free_vars X) ->
    exists psi, |- Iff psi (Subst p psi (Impl X (Box n (Var p)))).
Proof.
  intros p X n HX.
  apply sambin_witness_impl_left_no_occ_when_phi_top_solves; [exact HX|].
  unfold Subst. cbn. rewrite Nat.eqb_refl.
  exact (prov_box_top n).
Qed.


Lemma sambin_witness_impl_left_no_occ_when_phi_loeb_form :
  forall p X n Y,
    ~ In p (free_vars X) ->
    ~ In p (free_vars Y) ->
    |- Y ->
    exists psi, |- Iff psi (Subst p psi (Impl X (Box n (Impl (Var p) Y)))).
Proof.
  intros p X n Y HX HY HYprov.
  apply sambin_witness_impl_left_no_occ_when_phi_top_solves; [exact HX|].
  pose proof (Subst_no_occurrence p Top Y HY) as HY'.
  unfold Subst in *. cbn. rewrite Nat.eqb_refl.
  rewrite HY'.
  apply Nec. apply prov_weaken. exact HYprov.
Qed.


Lemma prov_impl_X_under_K : forall X A,
  |- Impl A (Impl X A).
Proof. intros X A. exact (Ax_K A X). Qed.


Lemma prov_meta_chain_K : forall X A Y,
  |- Impl (Impl (Impl X A) Y) (Impl A Y).
Proof.
  intros X A Y.
  pose proof (prov_compose_internal A (Impl X A) Y) as Hci.
  pose proof (prov_impl_X_under_K X A) as Hk.
  exact (MP _ _ (prov_perm _ _ _ Hci) Hk).
Qed.


Lemma sambin_witness_impl_left_no_occ_loeb_form_general :
  forall p X n Y,
    ~ In p (free_vars X) ->
    ~ In p (free_vars Y) ->
    exists psi, |- Iff psi (Subst p psi (Impl X (Box n (Impl (Var p) Y)))).
Proof.
  intros p X n Y HX HY.
  exists (Impl X (Box n Y)).
  pose proof (Subst_no_occurrence p (Impl X (Box n Y)) X HX) as HsubstX.
  pose proof (Subst_no_occurrence p (Impl X (Box n Y)) Y HY) as HsubstY.
  unfold Subst in *.
  assert (Hsubst :
    subst_form (fun k => if Nat.eqb k p then Impl X (Box n Y) else Var k)
               (Impl X (Box n (Impl (Var p) Y))) =
    Impl X (Box n (Impl (Impl X (Box n Y)) Y))).
  { cbn. rewrite HsubstX, HsubstY. rewrite Nat.eqb_refl. reflexivity. }
  rewrite Hsubst. clear Hsubst HsubstX HsubstY.
  apply prov_iff_intro.
  - pose proof (Ax_K Y (Impl X (Box n Y))) as HK1.
    pose proof (Nec n _ HK1) as HK1n.
    pose proof (Ax_BoxK n Y (Impl (Impl X (Box n Y)) Y)) as HBK.
    pose proof (MP _ _ HBK HK1n) as Hstep1.
    pose proof (prov_compose_internal X (Box n Y)
                  (Box n (Impl (Impl X (Box n Y)) Y))) as Hci.
    pose proof (MP _ _ Hci Hstep1) as Hstep2.
    exact Hstep2.
  - pose proof (prov_meta_chain_K X (Box n Y) Y) as Hmeta.
    pose proof (Nec n _ Hmeta) as HmetaN.
    pose proof (Ax_BoxK n (Impl (Impl X (Box n Y)) Y)
                          (Impl (Box n Y) Y)) as HBK1.
    pose proof (MP _ _ HBK1 HmetaN) as Hstep1.
    pose proof (Ax_Loeb n Y) as HLoeb.
    pose proof (prov_compose _ _ _ Hstep1 HLoeb) as Hstep2.
    pose proof (prov_compose_internal X
                  (Box n (Impl (Impl X (Box n Y)) Y))
                  (Box n Y)) as Hci.
    pose proof (MP _ _ Hci Hstep2) as Hstep3.
    exact Hstep3.
Qed.


Lemma Subst_no_occurrence_And : forall p X Y phi,
  ~ In p (free_vars X) ->
  Subst p Y (And X phi) = And X (Subst p Y phi).
Proof.
  intros p X Y phi HX.
  pose proof (Subst_no_occurrence p Y X HX) as HX'.
  unfold Subst, And, Neg in *. cbn.
  rewrite HX'. reflexivity.
Qed.


Lemma prov_box_and_intro_meta : forall n A B,
  |- Box n A -> |- Box n B -> |- Box n (And A B).
Proof.
  intros n A B HA HB.
  pose proof (prov_box_and_intro n A B) as Hai.
  exact (MP _ _ (MP _ _ Hai HA) HB).
Qed.


Lemma prov_box_and_iff_box_box4 : forall n X,
  |- Iff (Box n X) (Box n (And X (Box n X))).
Proof.
  intros n X.
  apply prov_iff_intro.
  - pose proof (Ax_Box4 n X) as Hbox4.
    pose proof (prov_box_and_intro n X (Box n X)) as Hai.
    pose proof (Ax_S (Box n X) (Box n (Box n X)) (Box n (And X (Box n X)))) as Hs.
    pose proof (MP _ _ Hs Hai) as Hstep1.
    exact (MP _ _ Hstep1 Hbox4).
  - exact (prov_box_and_elim_l n X (Box n X)).
Qed.


Theorem sambin_witness_and_box_atomic : forall p X n,
  ~ In p (free_vars X) ->
  exists psi, |- Iff psi (Subst p psi (And X (Box n (Var p)))).
Proof.
  intros p X n HX.
  exists (And X (Box n X)).
  pose proof (Subst_no_occurrence_And p X (And X (Box n X))
                (Box n (Var p)) HX) as HsubstAnd.
  rewrite HsubstAnd.
  assert (HsubstBox : Subst p (And X (Box n X)) (Box n (Var p)) =
                     Box n (And X (Box n X))).
  { unfold Subst. cbn. rewrite Nat.eqb_refl. reflexivity. }
  rewrite HsubstBox.
  pose proof (prov_box_and_iff_box_box4 n X) as Hbox_iff.
  pose proof (prov_equiv_box_cong n X (And X (Box n X))) as Hcong_box.
  unfold prov_equiv in *.
  apply prov_equiv_impl_cong; [|exact (prov_iff_refl Bot)].
  apply prov_equiv_impl_cong; [exact (prov_iff_refl X)|].
  apply prov_equiv_impl_cong; [exact Hbox_iff | exact (prov_iff_refl Bot)].
Qed.


Lemma Subst_no_occurrence_Or : forall p X Y phi,
  ~ In p (free_vars X) ->
  Subst p Y (Or X phi) = Or X (Subst p Y phi).
Proof.
  intros p X Y phi HX.
  pose proof (Subst_no_occurrence p Y X HX) as HX'.
  unfold Subst, Or, Neg in *. cbn.
  rewrite HX'. reflexivity.
Qed.


Theorem sambin_witness_or_box_atomic : forall p X n,
  ~ In p (free_vars X) ->
  exists psi, |- Iff psi (Subst p psi (Or X (Box n (Var p)))).
Proof.
  intros p X n HX.
  exists Top.
  pose proof (Subst_no_occurrence_Or p X Top (Box n (Var p)) HX) as HsubstOr.
  rewrite HsubstOr.
  assert (HsubstBox : Subst p Top (Box n (Var p)) = Box n Top).
  { unfold Subst. cbn. rewrite Nat.eqb_refl. reflexivity. }
  rewrite HsubstBox.
  pose proof (prov_box_top n) as HboxTop.
  pose proof (prov_or_intro_r X (Box n Top)) as Hor_intro.
  apply prov_iff_intro.
  - apply prov_weaken. exact (MP _ _ Hor_intro HboxTop).
  - apply prov_weaken. exact (prov_id Bot).
Qed.


Theorem sambin_witness_double_box : forall p n m,
  exists psi, |- Iff psi (Subst p psi (Box n (Box m (Var p)))).
Proof.
  intros p n m.
  exists Top.
  unfold Subst. cbn. rewrite Nat.eqb_refl.
  apply prov_iff_intro.
  - apply prov_weaken.
    apply Nec. exact (prov_box_top m).
  - apply prov_weaken. exact (prov_id Bot).
Qed.


Lemma Subst_no_p_in_phi : forall p Y phi,
  ~ In p (free_vars phi) -> Subst p Y phi = phi.
Proof. exact Subst_no_occurrence. Qed.


Theorem sambin_de_jongh_var : forall p k,
  k <> p ->
  exists psi, |- Iff psi (Subst p psi (Var k)).
Proof.
  intros p k Hne. exists (Var k).
  apply Nat.eqb_neq in Hne.
  unfold Subst. cbn. rewrite Hne.
  apply prov_iff_refl.
Qed.


Theorem sambin_de_jongh_bot : forall p,
  exists psi, |- Iff psi (Subst p psi Bot).
Proof.
  intros p. exists Bot.
  unfold Subst. cbn. apply prov_iff_refl.
Qed.


Theorem sambin_de_jongh_box_var_p : forall p n,
  exists psi, |- Iff psi (Subst p psi (Box n (Var p))).
Proof.
  intros p n. exists Top.
  unfold Subst. cbn. rewrite Nat.eqb_refl.
  apply prov_iff_intro.
  - apply prov_weaken. exact (prov_box_top n).
  - apply prov_weaken. exact (prov_id Bot).
Qed.


Theorem sambin_de_jongh_box_no_p : forall p n phi,
  ~ In p (free_vars phi) ->
  exists psi, |- Iff psi (Subst p psi (Box n phi)).
Proof.
  intros p n phi Hno. apply sambin_witness_no_occurrence. cbn. exact Hno.
Qed.


Theorem sambin_de_jongh_when_no_p : forall p phi,
  ~ In p (free_vars phi) ->
  exists psi, |- Iff psi (Subst p psi phi).
Proof. exact sambin_witness_no_occurrence. Qed.


Theorem sambin_de_jongh_modalized_partial : forall p phi,
  modalized p phi ->
  (~ In p (free_vars phi) \/ phi = Box 0 (Var p)) ->
  exists psi, |- Iff psi (Subst p psi phi).
Proof.
  intros p phi Hmod [Hno | Heq].
  - apply sambin_witness_no_occurrence. exact Hno.
  - subst phi. apply sambin_de_jongh_box_var_p.
Qed.


Theorem sambin_uniform_uniqueness_extended : forall p phi psi1 psi2,
  ((~ In p (free_vars phi)) \/
   (exists n X, ~ In p (free_vars X) /\ phi = Box n (Impl (Var p) X)) \/
   (exists n, phi = Box n (Var p)) \/
   (|- Subst p Top phi /\ |- Iff psi1 Top /\ |- Iff psi2 Top)) ->
  |- Iff psi1 (Subst p psi1 phi) ->
  |- Iff psi2 (Subst p psi2 phi) ->
  |- Iff psi1 psi2.
Proof.
  intros p phi psi1 psi2 Hclass H1 H2.
  destruct Hclass as [Hno | [HLoeb | [HBoxAtom | [_ [HpsiTop1 HpsiTop2]]]]].
  - apply (sambin_uniform_uniqueness_base p phi); [|exact H1|exact H2].
    left. exact Hno.
  - apply (sambin_uniform_uniqueness_base p phi); [|exact H1|exact H2].
    right. left. exact HLoeb.
  - apply (sambin_uniform_uniqueness_base p phi); [|exact H1|exact H2].
    right. right. exact HBoxAtom.
  - pose proof (prov_iff_sym _ _ HpsiTop2) as HpsiTop2sym.
    exact (prov_equiv_trans _ _ _ HpsiTop1 HpsiTop2sym).
Qed.

