(** Tiling.SubCalculi - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.

From Tiling Require Import Syntax.
From Tiling Require Import Provable.
From Tiling Require Import Kripke.
From Tiling Require Import Polymodal.
From Tiling Require Import Propositional.
From Tiling Require Import Ordinals.
From Tiling Require Import Bew.
From Tiling Require Import ProofTerms.


(** ** GLP* without NextCon.

    [Provable_no_NC] is the calculus with every GLP* axiom except
    [Ax_NextCon].  Used below to show that consistency_chain at the
    level-0/1 boundary is unprovable without [NextCon], exhibiting
    the relative-consistency content of [NextCon]. *)

Inductive Provable_no_NC : Form -> Prop :=
  | NC_Ax_K : forall phi psi,
      Provable_no_NC (Impl phi (Impl psi phi))
  | NC_Ax_S : forall phi psi chi,
      Provable_no_NC (Impl (Impl phi (Impl psi chi))
                           (Impl (Impl phi psi) (Impl phi chi)))
  | NC_Ax_DN : forall phi,
      Provable_no_NC (Impl (Neg (Neg phi)) phi)
  | NC_Ax_BoxK : forall n phi psi,
      Provable_no_NC (Impl (Box n (Impl phi psi))
                           (Impl (Box n phi) (Box n psi)))
  | NC_Ax_Loeb : forall n phi,
      Provable_no_NC (Impl (Box n (Impl (Box n phi) phi)) (Box n phi))
  | NC_Ax_Box4 : forall n phi,
      Provable_no_NC (Impl (Box n phi) (Box n (Box n phi)))
  | NC_Ax_Mon : forall n phi,
      Provable_no_NC (Impl (Box n phi) (Box (S n) phi))
  | NC_MP : forall phi psi,
      Provable_no_NC (Impl phi psi) -> Provable_no_NC phi -> Provable_no_NC psi
  | NC_Nec : forall n phi,
      Provable_no_NC phi -> Provable_no_NC (Box n phi).


Notation "|-no_nc f" := (Provable_no_NC f) (at level 75, no associativity).


Fixpoint forces_nc (F : Frame_no_NC) (V : fW_nc F -> nat -> bool)
                   (w : fW_nc F) (phi : Form) : Prop :=
  match phi with
  | Var p => V w p = true
  | Bot => False
  | Impl X Y => forces_nc F V w X -> forces_nc F V w Y
  | Box n psi => forall v, fR_nc F n w v -> forces_nc F V v psi
  end.


Theorem soundness_no_NC : forall phi, |-no_nc phi ->
  forall F V w, forces_nc F V w phi.
Proof.
  intros phi H. induction H.
  - intros F V w. simpl. intros Hphi _. exact Hphi.
  - intros F V w. simpl. intros Hf Hg Hphi.
    apply Hf; [exact Hphi | apply Hg; exact Hphi].
  - intros F V w. simpl. intro Hnnp. apply NNPP. exact Hnnp.
  - intros F V w. simpl. intros Himp Hphi v Hwv.
    apply (Himp v Hwv). apply (Hphi v Hwv).
  - intros F V w. simpl. intros Hbox v Hwv.
    pose proof (fR_nc_wf F n) as Hwf.
    set (P := fun u => fR_nc F n w u -> forces_nc F V u phi).
    cut (P v); [intro Hpv; exact (Hpv Hwv) |].
    apply (well_founded_ind Hwf P).
    intros u IH. unfold P. intro Hwu.
    apply (Hbox u Hwu).
    intros u' Huu'.
    apply (IH u' Huu' (fR_nc_trans F n w u u' Hwu Huu')).
  - intros F V w. simpl. intros Hphi v Hwv u Hvu.
    apply Hphi. apply (fR_nc_trans F n w v u Hwv Hvu).
  - intros F V w. simpl. intros Hphi v Hwv.
    apply Hphi. apply (fR_nc_mon F n w v Hwv).
  - intros F V w. apply (IHProvable_no_NC1 F V w).
    apply (IHProvable_no_NC2 F V w).
  - intros F V w. simpl. intros v _.
    apply (IHProvable_no_NC F V v).
Qed.


(** ** A frame violating NextCon at the 0/1 boundary.

    Two worlds, with [R 0 = R 1 = {(true, false)}] and higher [R n]
    empty.  Transitivity, well-foundedness, and monotonicity all hold
    trivially.  [NextCon] fails: [false] has no [R 0]-successor while
    being [R 1]-reachable from [true]. *)

Definition F_no_NC_R (n : nat) (w v : bool) : Prop :=
  match n with
  | 0 => w = true /\ v = false
  | 1 => w = true /\ v = false
  | _ => False
  end.


Lemma F_no_NC_R_trans : forall n w v u,
  F_no_NC_R n w v -> F_no_NC_R n v u -> F_no_NC_R n w u.
Proof.
  intros n w v u H1 H2.
  destruct n as [|[|n']]; simpl in *.
  - destruct H1 as [_ Hvf]. destruct H2 as [Hvt _]. subst v. discriminate.
  - destruct H1 as [_ Hvf]. destruct H2 as [Hvt _]. subst v. discriminate.
  - destruct H1.
Qed.


Lemma F_no_NC_R_wf : forall n, well_founded (fun u v => F_no_NC_R n v u).
Proof.
  intros n.
  destruct n as [|[|n']]; intros w; destruct w; apply Acc_intro;
    intros y Hy; simpl in Hy.
  - destruct Hy as [_ Hyf]. subst y.
    apply Acc_intro. intros z [Heq _]. discriminate.
  - destruct Hy as [Heq _]. discriminate.
  - destruct Hy as [_ Hyf]. subst y.
    apply Acc_intro. intros z [Heq _]. discriminate.
  - destruct Hy as [Heq _]. discriminate.
  - destruct Hy.
  - destruct Hy.
Qed.


Lemma F_no_NC_R_mon : forall n w v,
  F_no_NC_R (S n) w v -> F_no_NC_R n w v.
Proof.
  intros [|n] w v H; simpl in *.
  - exact H.
  - destruct n; simpl; auto. destruct H.
Qed.


Definition F_no_NC : Frame_no_NC :=
  mkFrame_no_NC bool F_no_NC_R F_no_NC_R_trans F_no_NC_R_wf F_no_NC_R_mon.


(** ** Consistency-chain at level 0 requires NextCon.

    [|- Box 1 (Neg (Box 0 Bot))] (which holds in full GLP* via
    [Ax_NextCon]) is not derivable in [Provable_no_NC]: in [F_no_NC],
    [false] has no [R 0]-successor, so [Box 0 Bot] is vacuously
    forced at [false], making [Neg (Box 0 Bot)] fail there, and the
    [Box 1] at [true] reaches [false]. *)

Theorem consistency_chain_needs_NC :
  ~ (|-no_nc Box 1 (Neg (Box 0 Bot))).
Proof.
  intro H.
  pose proof (soundness_no_NC _ H F_no_NC (fun _ _ => true) true) as Hf.
  simpl in Hf.
  specialize (Hf false).
  assert (HR : F_no_NC_R 1 true false) by (simpl; split; reflexivity).
  specialize (Hf HR).
  apply Hf.
  intros u Hfu. simpl in Hfu.
  destruct Hfu as [Heq _]. discriminate.
Qed.


(** ** Loeb metatheorem in the no-NextCon calculus.

    The Loeb metatheorem and Loebian obstacle do not depend on
    [Ax_NextCon]: they are preserved under dropping NextCon. *)

Theorem loeb_metatheorem_no_NC : forall n phi,
  (|-no_nc Impl (Box n phi) phi) -> |-no_nc phi.
Proof.
  intros n phi Hsound.
  pose proof (NC_Nec n _ Hsound) as Hnec.
  pose proof (NC_Ax_Loeb n phi) as HLoeb.
  pose proof (NC_MP _ _ HLoeb Hnec) as Hbox.
  exact (NC_MP _ _ Hsound Hbox).
Qed.


Theorem loebian_obstacle_no_NC : forall n,
  (forall phi, |-no_nc Impl (Box n phi) phi) -> |-no_nc Bot.
Proof.
  intros n Hsound.
  exact (loeb_metatheorem_no_NC n Bot (Hsound Bot)).
Qed.


(** ** Cross-level monotonicity is preserved.

    [Ax_Mon] is a constructor of [Provable_no_NC], so monotonicity
    survives the perturbation. *)

Theorem parametric_reflection_succeeds_no_NC : forall n phi,
  |-no_nc Impl (Box n phi) (Box (S n) phi).
Proof.
  intros n phi.
  exact (NC_Ax_Mon n phi).
Qed.


Definition AxK_carrier : Form :=
  Impl (Var 0) (Impl (Var 1) (Var 0)).

Definition AxS_carrier : Form :=
  Impl (Impl (Var 0) (Impl (Var 1) (Var 2)))
       (Impl (Impl (Var 0) (Var 1)) (Impl (Var 0) (Var 2))).

Definition AxDN_carrier : Form :=
  Impl (Neg (Neg (Var 0))) (Var 0).

Definition AxBoxK_carrier (n : nat) : Form :=
  Impl (Box n (Impl (Var 0) (Var 1)))
       (Impl (Box n (Var 0)) (Box n (Var 1))).

Definition AxLoeb_carrier (n : nat) : Form :=
  Impl (Box n (Impl (Box n (Var 0)) (Var 0))) (Box n (Var 0)).

Definition AxBox4_carrier (n : nat) : Form :=
  Impl (Box n (Var 0)) (Box n (Box n (Var 0))).

Definition AxMon_carrier (n : nat) : Form :=
  Impl (Box n (Var 0)) (Box (S n) (Var 0)).

Definition AxNextCon_carrier (n : nat) : Form :=
  Box (S n) (Neg (Box n Bot)).


Inductive FAxProvable : Form -> Prop :=
  | FAx_K_inst : forall sigma,
      FAxProvable (subst_form sigma AxK_carrier)
  | FAx_S_inst : forall sigma,
      FAxProvable (subst_form sigma AxS_carrier)
  | FAx_DN_inst : forall sigma,
      FAxProvable (subst_form sigma AxDN_carrier)
  | FAx_BoxK_inst : forall n sigma,
      FAxProvable (subst_form sigma (AxBoxK_carrier n))
  | FAx_Loeb_inst : forall n sigma,
      FAxProvable (subst_form sigma (AxLoeb_carrier n))
  | FAx_Box4_inst : forall n sigma,
      FAxProvable (subst_form sigma (AxBox4_carrier n))
  | FAx_Mon_inst : forall n sigma,
      FAxProvable (subst_form sigma (AxMon_carrier n))
  | FAx_NextCon_inst : forall n,
      FAxProvable (AxNextCon_carrier n)
  | FMP : forall phi psi,
      FAxProvable (Impl phi psi) -> FAxProvable phi -> FAxProvable psi
  | FNec : forall n phi,
      FAxProvable phi -> FAxProvable (Box n phi).


Definition sub1 (phi : Form) : nat -> Form := fun _ => phi.

Definition sub2 (phi psi : Form) : nat -> Form :=
  fun k => match k with 0 => phi | _ => psi end.

Definition sub3 (phi psi chi : Form) : nat -> Form :=
  fun k => match k with 0 => phi | 1 => psi | _ => chi end.


Theorem fax_provable_sound : forall phi, FAxProvable phi -> |- phi.
Proof.
  intros phi H. induction H; cbn.
  - apply Ax_K.
  - apply Ax_S.
  - apply Ax_DN.
  - apply Ax_BoxK.
  - apply Ax_Loeb.
  - apply Ax_Box4.
  - apply Ax_Mon.
  - apply Ax_NextCon.
  - exact (MP _ _ IHFAxProvable1 IHFAxProvable2).
  - exact (Nec _ _ IHFAxProvable).
Qed.


Theorem fax_provable_complete : forall phi, |- phi -> FAxProvable phi.
Proof.
  intros phi H. induction H.
  - exact (FAx_K_inst (sub2 phi psi)).
  - exact (FAx_S_inst (sub3 phi psi chi)).
  - exact (FAx_DN_inst (sub1 phi)).
  - exact (FAx_BoxK_inst n (sub2 phi psi)).
  - exact (FAx_Loeb_inst n (sub1 phi)).
  - exact (FAx_Box4_inst n (sub1 phi)).
  - exact (FAx_Mon_inst n (sub1 phi)).
  - exact (FAx_NextCon_inst n).
  - exact (FMP _ _ IHProvable1 IHProvable2).
  - exact (FNec _ _ IHProvable).
Qed.


Theorem finite_axiomatisation : forall phi, FAxProvable phi <-> |- phi.
Proof.
  intro phi. split.
  - apply fax_provable_sound.
  - apply fax_provable_complete.
Qed.


Fixpoint level_lift (k : nat) (phi : Form) : Form :=
  match phi with
  | Var p => Var p
  | Bot => Bot
  | Impl X Y => Impl (level_lift k X) (level_lift k Y)
  | Box n psi => Box (n + k) (level_lift k psi)
  end.


Definition AxBoxK_carrier_base : Form :=
  Impl (Box 0 (Impl (Var 0) (Var 1)))
       (Impl (Box 0 (Var 0)) (Box 0 (Var 1))).

Definition AxLoeb_carrier_base : Form :=
  Impl (Box 0 (Impl (Box 0 (Var 0)) (Var 0))) (Box 0 (Var 0)).

Definition AxBox4_carrier_base : Form :=
  Impl (Box 0 (Var 0)) (Box 0 (Box 0 (Var 0))).

Definition AxMon_carrier_base : Form :=
  Impl (Box 0 (Var 0)) (Box 1 (Var 0)).

Definition AxNextCon_carrier_base : Form :=
  Box 1 (Neg (Box 0 Bot)).


Inductive FAx2Provable : Form -> Prop :=
  | F2_AxK_inst : forall sigma k,
      FAx2Provable (subst_form sigma (level_lift k AxK_carrier))
  | F2_AxS_inst : forall sigma k,
      FAx2Provable (subst_form sigma (level_lift k AxS_carrier))
  | F2_AxDN_inst : forall sigma k,
      FAx2Provable (subst_form sigma (level_lift k AxDN_carrier))
  | F2_AxBoxK_inst : forall sigma k,
      FAx2Provable (subst_form sigma (level_lift k AxBoxK_carrier_base))
  | F2_AxLoeb_inst : forall sigma k,
      FAx2Provable (subst_form sigma (level_lift k AxLoeb_carrier_base))
  | F2_AxBox4_inst : forall sigma k,
      FAx2Provable (subst_form sigma (level_lift k AxBox4_carrier_base))
  | F2_AxMon_inst : forall sigma k,
      FAx2Provable (subst_form sigma (level_lift k AxMon_carrier_base))
  | F2_AxNextCon_inst : forall k,
      FAx2Provable (level_lift k AxNextCon_carrier_base)
  | F2_MP : forall phi psi,
      FAx2Provable (Impl phi psi) -> FAx2Provable phi -> FAx2Provable psi
  | F2_Nec : forall n phi,
      FAx2Provable phi -> FAx2Provable (Box n phi).


Theorem fax2_to_provable : forall phi, FAx2Provable phi -> |- phi.
Proof.
  intros phi H. induction H; cbn in *.
  - apply Ax_K.
  - apply Ax_S.
  - apply Ax_DN.
  - apply Ax_BoxK.
  - apply Ax_Loeb.
  - apply Ax_Box4.
  - apply Ax_Mon.
  - apply Ax_NextCon.
  - exact (MP _ _ IHFAx2Provable1 IHFAx2Provable2).
  - exact (Nec _ _ IHFAx2Provable).
Qed.


Theorem provable_to_fax2 : forall phi, |- phi -> FAx2Provable phi.
Proof.
  intros phi H. induction H.
  - exact (F2_AxK_inst (sub2 phi psi) 0).
  - exact (F2_AxS_inst (sub3 phi psi chi) 0).
  - exact (F2_AxDN_inst (sub1 phi) 0).
  - exact (F2_AxBoxK_inst (sub2 phi psi) n).
  - exact (F2_AxLoeb_inst (sub1 phi) n).
  - exact (F2_AxBox4_inst (sub1 phi) n).
  - exact (F2_AxMon_inst (sub1 phi) n).
  - exact (F2_AxNextCon_inst n).
  - exact (F2_MP _ _ IHProvable1 IHProvable2).
  - exact (F2_Nec _ _ IHProvable).
Qed.


Theorem finite_axiomatisation_levelsubst : forall phi, FAx2Provable phi <-> |- phi.
Proof.
  intro phi. split; [apply fax2_to_provable | apply provable_to_fax2].
Qed.


(** ** Independence of Ax_Mon.

    [Provable_no_Mon] is GLP* with [Ax_Mon] removed.  A frame
    satisfying transitivity, converse-well-foundedness, and NextCon-
    successor (but not the monotone-inclusion condition) gives a
    counter-model.  Specifically [|- Impl (Box 0 (Var 0)) (Box 1
    (Var 0))], a direct instance of [Ax_Mon], is not derivable in
    [Provable_no_Mon].  Parallels [consistency_chain_needs_NC]. *)

Inductive Provable_no_Mon : Form -> Prop :=
  | NM_Ax_K : forall phi psi,
      Provable_no_Mon (Impl phi (Impl psi phi))
  | NM_Ax_S : forall phi psi chi,
      Provable_no_Mon (Impl (Impl phi (Impl psi chi))
                            (Impl (Impl phi psi) (Impl phi chi)))
  | NM_Ax_DN : forall phi,
      Provable_no_Mon (Impl (Neg (Neg phi)) phi)
  | NM_Ax_BoxK : forall n phi psi,
      Provable_no_Mon (Impl (Box n (Impl phi psi))
                            (Impl (Box n phi) (Box n psi)))
  | NM_Ax_Loeb : forall n phi,
      Provable_no_Mon (Impl (Box n (Impl (Box n phi) phi)) (Box n phi))
  | NM_Ax_Box4 : forall n phi,
      Provable_no_Mon (Impl (Box n phi) (Box n (Box n phi)))
  | NM_Ax_NextCon : forall n,
      Provable_no_Mon (Box (S n) (Neg (Box n Bot)))
  | NM_MP : forall phi psi,
      Provable_no_Mon (Impl phi psi) -> Provable_no_Mon phi -> Provable_no_Mon psi
  | NM_Nec : forall n phi,
      Provable_no_Mon phi -> Provable_no_Mon (Box n phi).


Notation "|-no_mon f" := (Provable_no_Mon f) (at level 75, no associativity).


Fixpoint forces_nm (F : Frame_no_Mon) (V : fW_nm F -> nat -> bool)
                   (w : fW_nm F) (phi : Form) : Prop :=
  match phi with
  | Var p => V w p = true
  | Bot => False
  | Impl X Y => forces_nm F V w X -> forces_nm F V w Y
  | Box n psi => forall v, fR_nm F n w v -> forces_nm F V v psi
  end.


Theorem soundness_no_Mon : forall phi, |-no_mon phi ->
  forall F V w, forces_nm F V w phi.
Proof.
  intros phi H. induction H.
  - intros F V w. simpl. intros Hphi _. exact Hphi.
  - intros F V w. simpl. intros Hf Hg Hphi.
    apply Hf; [exact Hphi | apply Hg; exact Hphi].
  - intros F V w. simpl. intro Hnnp. apply NNPP. exact Hnnp.
  - intros F V w. simpl. intros Himp Hphi v Hwv.
    apply (Himp v Hwv). apply (Hphi v Hwv).
  - intros F V w. simpl. intros Hbox v Hwv.
    pose proof (fR_nm_wf F n) as Hwf.
    set (P := fun u => fR_nm F n w u -> forces_nm F V u phi).
    cut (P v); [intro Hpv; exact (Hpv Hwv) |].
    apply (well_founded_ind Hwf P).
    intros u IH. unfold P. intro Hwu.
    apply (Hbox u Hwu).
    intros u' Huu'.
    apply (IH u' Huu' (fR_nm_trans F n w u u' Hwu Huu')).
  - intros F V w. simpl. intros Hphi v Hwv u Hvu.
    apply Hphi. apply (fR_nm_trans F n w v u Hwv Hvu).
  - intros F V w. simpl. intros v Hwv Hbox.
    destruct (fR_nm_nextcon F n w v Hwv) as [u Hvu].
    exact (Hbox u Hvu).
  - intros F V w. apply (IHProvable_no_Mon1 F V w).
    apply (IHProvable_no_Mon2 F V w).
  - intros F V w. simpl. intros v _.
    apply (IHProvable_no_Mon F V v).
Qed.


Definition F_no_Mon : Frame_no_Mon :=
  mkFrame_no_Mon nat R_break_mon
    R_break_mon_trans R_break_mon_wf R_break_mon_nextcon.


Theorem mon_axiom_needs_Mon :
  ~ (|-no_mon Impl (Box 0 (Var 0)) (Box 1 (Var 0))).
Proof.
  intro H.
  pose proof (soundness_no_Mon _ H F_no_Mon (fun w _ => negb (Nat.eqb w 1)) 0)
    as Hf.
  simpl in Hf.
  assert (HBox0 : forall v : nat, R_break_mon 0 0 v -> negb (Nat.eqb v 1) = true).
  { intros v Hv. simpl in Hv. destruct Hv as [Hv _]. discriminate. }
  pose proof (Hf HBox0) as HBox1.
  assert (HR : R_break_mon 1 0 1) by (simpl; split; reflexivity).
  pose proof (HBox1 1 HR) as Hcontra.
  simpl in Hcontra. discriminate.
Qed.


(** ** Box4 as a derived theorem of K + Löb (without Ax_Box4).

    The standard derivation (folklore, attributed to substitution
    [A ∧ □A] for the variable in Löb's axiom): apply Löb's axiom at
    the formula [A ∧ □A], derive the antecedent [□(□(A ∧ □A) → A ∧ □A)]
    from [□A] using K + propositional reasoning, and conclude
    [□(A ∧ □A)], from which K + and-elim yields [□□A].  No fixed-point
    machinery beyond Löb's axiom itself is needed.

    [Provable_no_B4] is GLP* with [Ax_Box4] removed.  Showing axiom 4
    is derivable in [Provable_no_B4] establishes it as redundant. *)

Inductive Provable_no_B4 : Form -> Prop :=
  | NB4_Ax_K : forall phi psi,
      Provable_no_B4 (Impl phi (Impl psi phi))
  | NB4_Ax_S : forall phi psi chi,
      Provable_no_B4 (Impl (Impl phi (Impl psi chi))
                           (Impl (Impl phi psi) (Impl phi chi)))
  | NB4_Ax_DN : forall phi,
      Provable_no_B4 (Impl (Neg (Neg phi)) phi)
  | NB4_Ax_BoxK : forall n phi psi,
      Provable_no_B4 (Impl (Box n (Impl phi psi))
                           (Impl (Box n phi) (Box n psi)))
  | NB4_Ax_Loeb : forall n phi,
      Provable_no_B4 (Impl (Box n (Impl (Box n phi) phi)) (Box n phi))
  | NB4_Ax_Mon : forall n phi,
      Provable_no_B4 (Impl (Box n phi) (Box (S n) phi))
  | NB4_Ax_NextCon : forall n,
      Provable_no_B4 (Box (S n) (Neg (Box n Bot)))
  | NB4_MP : forall phi psi,
      Provable_no_B4 (Impl phi psi) -> Provable_no_B4 phi -> Provable_no_B4 psi
  | NB4_Nec : forall n phi,
      Provable_no_B4 phi -> Provable_no_B4 (Box n phi).


Notation "|-no_b4 f" := (Provable_no_B4 f) (at level 75, no associativity).


(** Basic propositional helpers in [Provable_no_B4]. *)

Lemma nb4_prov_id : forall phi, |-no_b4 Impl phi phi.
Proof.
  intro phi.
  exact (NB4_MP _ _
          (NB4_MP _ _ (NB4_Ax_S phi (Impl phi phi) phi)
                       (NB4_Ax_K phi (Impl phi phi)))
          (NB4_Ax_K phi phi)).
Qed.


Lemma nb4_prov_weaken : forall phi psi, |-no_b4 phi -> |-no_b4 Impl psi phi.
Proof. intros phi psi Hphi. exact (NB4_MP _ _ (NB4_Ax_K phi psi) Hphi). Qed.


Lemma nb4_prov_compose : forall phi psi chi,
  |-no_b4 Impl phi psi -> |-no_b4 Impl psi chi -> |-no_b4 Impl phi chi.
Proof.
  intros phi psi chi Hpq Hqr.
  pose proof (NB4_Ax_S phi psi chi) as Hs.
  pose proof (nb4_prov_weaken _ phi Hqr) as Hpqr.
  exact (NB4_MP _ _ (NB4_MP _ _ Hs Hpqr) Hpq).
Qed.


Lemma nb4_prov_box_imp : forall n phi psi,
  |-no_b4 Impl phi psi -> |-no_b4 Impl (Box n phi) (Box n psi).
Proof.
  intros n phi psi Himp.
  pose proof (NB4_Nec n _ Himp) as Hnec.
  pose proof (NB4_Ax_BoxK n phi psi) as HBK.
  exact (NB4_MP _ _ HBK Hnec).
Qed.


Lemma nb4_prov_perm : forall phi psi chi,
  |-no_b4 Impl phi (Impl psi chi) -> |-no_b4 Impl psi (Impl phi chi).
Proof.
  intros phi psi chi H.
  pose proof (NB4_Ax_S phi psi chi) as Hs.
  pose proof (NB4_MP _ _ Hs H) as H1.
  pose proof (NB4_Ax_K psi phi) as Hk.
  exact (nb4_prov_compose _ _ _ Hk H1).
Qed.


Lemma nb4_prov_DN_intro : forall phi, |-no_b4 Impl phi (Neg (Neg phi)).
Proof.
  intro phi. unfold Neg.
  pose proof (nb4_prov_id (Impl phi Bot)) as Hid.
  exact (nb4_prov_perm _ _ _ Hid).
Qed.


Lemma nb4_prov_explosion : forall phi, |-no_b4 Impl Bot phi.
Proof.
  intro phi.
  pose proof (NB4_Ax_K Bot (Neg phi)) as Hk.
  pose proof (NB4_Ax_DN phi) as HDN.
  exact (nb4_prov_compose _ _ _ Hk HDN).
Qed.


Lemma nb4_prov_compose_internal : forall phi psi chi,
  |-no_b4 Impl (Impl psi chi) (Impl (Impl phi psi) (Impl phi chi)).
Proof.
  intros phi psi chi.
  pose proof (NB4_Ax_K (Impl psi chi) phi) as Hk.
  pose proof (NB4_Ax_S phi psi chi) as Hs.
  exact (nb4_prov_compose _ _ _ Hk Hs).
Qed.


Lemma nb4_prov_perm_internal : forall a b c,
  |-no_b4 Impl (Impl a (Impl b c)) (Impl b (Impl a c)).
Proof.
  intros a b c.
  pose proof (NB4_Ax_S a b c) as H_S.
  pose proof (NB4_Ax_S (Impl a (Impl b c)) (Impl a b) (Impl a c)) as H_S2.
  pose proof (NB4_MP _ _ H_S2 H_S) as H1.
  pose proof (NB4_Ax_K b a) as H_K1.
  pose proof (NB4_Ax_K (Impl a b) (Impl a (Impl b c))) as H_K2.
  pose proof (nb4_prov_compose _ _ _ H_K1 H_K2) as H2.
  pose proof (nb4_prov_compose _ _ _ H2 H1) as H3.
  exact (nb4_prov_perm _ _ _ H3).
Qed.


Lemma nb4_prov_and_intro : forall phi psi,
  |-no_b4 Impl phi (Impl psi (And phi psi)).
Proof.
  intros phi psi.
  unfold And, Neg.
  pose proof (nb4_prov_id (Impl phi (Impl psi Bot))) as Hid.
  pose proof (nb4_prov_perm _ _ _ Hid) as Hperm.
  pose proof (nb4_prov_perm_internal (Impl phi (Impl psi Bot)) psi Bot) as Hpi.
  exact (nb4_prov_compose _ _ _ Hperm Hpi).
Qed.


Lemma nb4_prov_and_intro_meta : forall phi psi,
  |-no_b4 phi -> |-no_b4 psi -> |-no_b4 And phi psi.
Proof.
  intros phi psi Hphi Hpsi.
  exact (NB4_MP _ _ (NB4_MP _ _ (nb4_prov_and_intro phi psi) Hphi) Hpsi).
Qed.


Lemma nb4_prov_neg_imp_ng : forall phi psi,
  |-no_b4 Impl (Neg phi) (Impl phi (Neg psi)).
Proof.
  intros phi psi. unfold Neg.
  pose proof (nb4_prov_compose_internal phi Bot (Impl psi Bot)) as Hci.
  pose proof (nb4_prov_explosion (Impl psi Bot)) as Hex.
  exact (NB4_MP _ _ Hci Hex).
Qed.


Lemma nb4_prov_and_elim_l : forall phi psi,
  |-no_b4 Impl (And phi psi) phi.
Proof.
  intros phi psi. unfold And, Neg.
  pose proof (nb4_prov_neg_imp_ng phi psi) as H1.
  pose proof (nb4_prov_compose_internal
                (Impl phi Bot)
                (Impl phi (Impl psi Bot))
                Bot) as H2.
  pose proof (nb4_prov_perm _ _ _ H2) as H2_perm.
  pose proof (NB4_MP _ _ H2_perm H1) as Hstep1.
  pose proof (NB4_Ax_DN phi) as HDN.
  exact (nb4_prov_compose _ _ _ Hstep1 HDN).
Qed.


Lemma nb4_prov_and_elim_r : forall phi psi,
  |-no_b4 Impl (And phi psi) psi.
Proof.
  intros phi psi. unfold And, Neg.
  pose proof (NB4_Ax_K (Impl psi Bot) phi) as H1.
  pose proof (nb4_prov_compose_internal
                (Impl psi Bot)
                (Impl phi (Impl psi Bot))
                Bot) as H2.
  pose proof (nb4_prov_perm _ _ _ H2) as H2_perm.
  pose proof (NB4_MP _ _ H2_perm H1) as Hstep1.
  pose proof (NB4_Ax_DN psi) as HDN.
  exact (nb4_prov_compose _ _ _ Hstep1 HDN).
Qed.


Lemma nb4_prov_and_elim_l_meta : forall phi psi,
  |-no_b4 And phi psi -> |-no_b4 phi.
Proof.
  intros phi psi Hand.
  exact (NB4_MP _ _ (nb4_prov_and_elim_l phi psi) Hand).
Qed.


Lemma nb4_prov_and_elim_r_meta : forall phi psi,
  |-no_b4 And phi psi -> |-no_b4 psi.
Proof.
  intros phi psi Hand.
  exact (NB4_MP _ _ (nb4_prov_and_elim_r phi psi) Hand).
Qed.


(** Uncurry [And] into chained implication. *)

Lemma nb4_prov_uncurry : forall A B C,
  |-no_b4 Impl (And A B) C -> |-no_b4 Impl A (Impl B C).
Proof.
  intros A B C Hf.
  pose proof (nb4_prov_and_intro A B) as Handi.
  pose proof (nb4_prov_compose_internal B (And A B) C) as Hci.
  pose proof (NB4_MP _ _ Hci Hf) as Hstep1.
  exact (nb4_prov_compose _ _ _ Handi Hstep1).
Qed.


(** Axiom 4 as a derived theorem of Provable_no_B4 (i.e., GLP* without
    primitive [Ax_Box4]).  The standard substitution argument: apply
    Löb's axiom at the formula [A ∧ Box n A], derive the Löb-axiom
    antecedent from [Box n A] using K and propositional reasoning, and
    conclude [Box n (A ∧ Box n A)]; from this, K + and-elim yields
    [Box n (Box n A)]. *)

Theorem nb4_axiom4 : forall n A,
  |-no_b4 Impl (Box n A) (Box n (Box n A)).
Proof.
  intros n A.
  set (B := Box n A).
  set (X := And A (Box n (And A B))).
  pose proof (nb4_prov_and_elim_l A B) as H1.
  pose proof (nb4_prov_box_imp n _ _ H1) as H2.
  pose proof (nb4_prov_and_elim_l A (Box n (And A B))) as H3.
  pose proof (nb4_prov_and_elim_r A (Box n (And A B))) as H4pre.
  pose proof (nb4_prov_compose _ _ _ H4pre H2) as H4.
  pose proof (nb4_prov_and_intro A B) as Handi.
  pose proof (nb4_prov_compose _ _ _ H3 Handi) as Hcomp1.
  pose proof (NB4_Ax_S X B (And A B)) as Hs.
  pose proof (NB4_MP _ _ Hs Hcomp1) as Hstep1.
  pose proof (NB4_MP _ _ Hstep1 H4) as H5.
  pose proof (nb4_prov_uncurry _ _ _ H5) as H6.
  pose proof (nb4_prov_box_imp n _ _ H6) as H7.
  pose proof (NB4_Ax_Loeb n (And A B)) as H8.
  pose proof (nb4_prov_compose _ _ _ H7 H8) as H9.
  pose proof (nb4_prov_and_elim_r A B) as H10pre.
  pose proof (nb4_prov_box_imp n _ _ H10pre) as H11.
  exact (nb4_prov_compose _ _ _ H9 H11).
Qed.


Theorem provable_to_no_b4 : forall phi, |- phi -> |-no_b4 phi.
Proof.
  intros phi H. induction H.
  - apply NB4_Ax_K.
  - apply NB4_Ax_S.
  - apply NB4_Ax_DN.
  - apply NB4_Ax_BoxK.
  - apply NB4_Ax_Loeb.
  - apply nb4_axiom4.
  - apply NB4_Ax_Mon.
  - apply NB4_Ax_NextCon.
  - exact (NB4_MP _ _ IHProvable1 IHProvable2).
  - exact (NB4_Nec _ _ IHProvable).
Qed.


Theorem no_b4_to_provable : forall phi, |-no_b4 phi -> |- phi.
Proof.
  intros phi H. induction H as [| | | | | | | phi psi _ IH1 _ IH2 | n phi _ IH].
  - apply Ax_K.
  - apply Ax_S.
  - apply Ax_DN.
  - apply Ax_BoxK.
  - apply Ax_Loeb.
  - apply Ax_Mon.
  - apply Ax_NextCon.
  - exact (MP _ _ IH1 IH2).
  - exact (Nec _ _ IH).
Qed.


Theorem provable_iff_no_b4 : forall phi, |- phi <-> |-no_b4 phi.
Proof.
  intro phi. split; [apply provable_to_no_b4 | apply no_b4_to_provable].
Qed.


Definition F_no_NC_m_R (m : nat) (k : nat) (w v : bool) : Prop :=
  k <= m /\ w = true /\ v = false.


Lemma F_no_NC_m_R_trans : forall m k w v u,
  F_no_NC_m_R m k w v -> F_no_NC_m_R m k v u -> F_no_NC_m_R m k w u.
Proof.
  intros m k w v u [_ [_ Hvf]] [_ [Hvt _]]. subst v. discriminate.
Qed.


Lemma F_no_NC_m_R_wf : forall m k,
  well_founded (fun u v => F_no_NC_m_R m k v u).
Proof.
  intros m k x.
  apply Acc_intro. intros y [_ [_ Hyf]]. subst y.
  apply Acc_intro. intros z [_ [Hzt _]]. discriminate.
Qed.


Lemma F_no_NC_m_R_mon : forall m k w v,
  F_no_NC_m_R m (S k) w v -> F_no_NC_m_R m k w v.
Proof.
  intros m k w v [Hle [Hw Hv]]. split; [lia | split; assumption].
Qed.


Definition F_no_NC_m (m : nat) : Frame_no_NC :=
  mkFrame_no_NC bool (F_no_NC_m_R m)
    (F_no_NC_m_R_trans m) (F_no_NC_m_R_wf m) (F_no_NC_m_R_mon m).


Lemma provable_higher_NC : forall n,
  1 <= n -> |- Box n (Neg (Box 0 Bot)).
Proof.
  intros n Hn.
  destruct n as [|n']; [lia|].
  pose proof (Ax_NextCon 0) as H1.
  pose proof (prov_box_mon_le 1 (S n') (Neg (Box 0 Bot)) Hn) as Hmon.
  exact (MP _ _ Hmon H1).
Qed.


Theorem separation_NC_at : forall n, 1 <= n ->
  (|- Box n (Neg (Box 0 Bot))) /\
  ~ (|-no_nc Box n (Neg (Box 0 Bot))).
Proof.
  intros n Hn.
  split.
  - apply provable_higher_NC. exact Hn.
  - intro Habs.
    pose proof (soundness_no_NC _ Habs (F_no_NC_m n) (fun _ _ => true) true) as Hf.
    simpl in Hf.
    assert (Hwit : F_no_NC_m_R n n true false).
    { unfold F_no_NC_m_R. split; [lia | split; reflexivity]. }
    pose proof (Hf false Hwit) as Hnegbox.
    apply Hnegbox.
    intros u Hu.
    unfold F_no_NC_m_R in Hu.
    destruct Hu as [_ [Hbad _]]. discriminate.
Qed.


Definition F_no_Mon_n_R (k : nat) (w v : nat) : Prop :=
  w = k + 1 /\ v = k.


Lemma F_no_Mon_n_R_trans : forall k w v u,
  F_no_Mon_n_R k w v -> F_no_Mon_n_R k v u -> F_no_Mon_n_R k w u.
Proof.
  intros k w v u [_ Hv] [Hv' _]. subst v. lia.
Qed.


Lemma F_no_Mon_n_R_wf : forall k,
  well_founded (fun u v => F_no_Mon_n_R k v u).
Proof.
  intros k x.
  apply Acc_intro. intros y [_ Hy]. subst y.
  apply Acc_intro. intros z [Hz _]. lia.
Qed.


Lemma F_no_Mon_n_R_nextcon : forall k w v,
  F_no_Mon_n_R (S k) w v -> exists u, F_no_Mon_n_R k v u.
Proof.
  intros k w v [Hw Hv]. exists k.
  unfold F_no_Mon_n_R. split; lia.
Qed.


Definition F_no_Mon_n : Frame_no_Mon :=
  mkFrame_no_Mon nat F_no_Mon_n_R
    F_no_Mon_n_R_trans F_no_Mon_n_R_wf F_no_Mon_n_R_nextcon.


Theorem separation_Mon_at : forall n,
  (|- Impl (Box n (Var 0)) (Box (S n) (Var 0))) /\
  ~ (|-no_mon Impl (Box n (Var 0)) (Box (S n) (Var 0))).
Proof.
  intro n.
  split.
  - exact (Ax_Mon n (Var 0)).
  - intro Habs.
    pose proof (soundness_no_Mon _ Habs F_no_Mon_n
      (fun w _ => negb (Nat.eqb w (S n))) (n + 2)) as Hf.
    simpl in Hf.
    assert (HBoxN : forall v, F_no_Mon_n_R n (n+2) v -> negb (Nat.eqb v (S n)) = true).
    { intros v [Hw _]. exfalso. lia. }
    pose proof (Hf HBoxN) as HBoxSn.
    assert (HR : F_no_Mon_n_R (S n) (n+2) (S n)).
    { unfold F_no_Mon_n_R. split; lia. }
    pose proof (HBoxSn (S n) HR) as Hcontra.
    rewrite Nat.eqb_refl in Hcontra. simpl in Hcontra. discriminate.
Qed.


Theorem yh_bypass_robust_no_b4 : forall n,
  ((forall phi, |-no_b4 Impl (Box n phi) phi) -> |-no_b4 Bot) /\
  (forall phi, |-no_b4 Box (S n) (Impl (Box n phi) (Neg (Box n (Neg phi))))) /\
  (forall k, n < k -> |-no_b4 Box k (Neg (Box n Bot))).
Proof.
  intro n. split; [|split].
  - intros Hsch.
    apply provable_to_no_b4.
    apply (loebian_obstacle n).
    intro phi.
    apply no_b4_to_provable. apply Hsch.
  - intro phi.
    apply provable_to_no_b4. exact (tiling_consistency n phi).
  - intros k Hlt.
    apply provable_to_no_b4. exact (consistency_chain n k Hlt).
Qed.


Theorem yh_bypass_robust_summary :
  forall n, (forall phi, |- Box n phi <-> |-no_b4 Box n phi).
Proof.
  intros n phi. exact (provable_iff_no_b4 (Box n phi)).
Qed.


Theorem minimal_viable_bypass_mon : forall n,
  ~ (forall phi, |-no_mon Impl (Box n phi) (Box (S n) phi)).
Proof.
  intros n Hsch.
  pose proof (separation_Mon_at n) as [_ Hsep].
  apply Hsep. apply (Hsch (Var 0)).
Qed.


Theorem minimal_viable_bypass_nc : forall n, 1 <= n ->
  ~ (|-no_nc Box n (Neg (Box 0 Bot))).
Proof.
  intros n Hn.
  pose proof (separation_NC_at n Hn) as [_ Hsep]. exact Hsep.
Qed.


(** ** Independence of Ax_Loeb.

    [Provable_no_Loeb] is GLP* with [Ax_Loeb] removed.  Loeb is sound
    in any converse-well-founded frame; in [R_break_wf] (the strict
    [<] relation on nat, which is transitive, monotone, and NextCon-
    successor closed but not converse-WF) Löb fails.  A specific
    instance of Löb at [Bot] is unprovable in [Provable_no_Loeb]. *)

Inductive Provable_no_Loeb : Form -> Prop :=
  | NL_Ax_K : forall phi psi,
      Provable_no_Loeb (Impl phi (Impl psi phi))
  | NL_Ax_S : forall phi psi chi,
      Provable_no_Loeb (Impl (Impl phi (Impl psi chi))
                             (Impl (Impl phi psi) (Impl phi chi)))
  | NL_Ax_DN : forall phi,
      Provable_no_Loeb (Impl (Neg (Neg phi)) phi)
  | NL_Ax_BoxK : forall n phi psi,
      Provable_no_Loeb (Impl (Box n (Impl phi psi))
                             (Impl (Box n phi) (Box n psi)))
  | NL_Ax_Box4 : forall n phi,
      Provable_no_Loeb (Impl (Box n phi) (Box n (Box n phi)))
  | NL_Ax_Mon : forall n phi,
      Provable_no_Loeb (Impl (Box n phi) (Box (S n) phi))
  | NL_Ax_NextCon : forall n,
      Provable_no_Loeb (Box (S n) (Neg (Box n Bot)))
  | NL_MP : forall phi psi,
      Provable_no_Loeb (Impl phi psi) -> Provable_no_Loeb phi -> Provable_no_Loeb psi
  | NL_Nec : forall n phi,
      Provable_no_Loeb phi -> Provable_no_Loeb (Box n phi).


Notation "|-no_loeb f" := (Provable_no_Loeb f) (at level 75, no associativity).


Fixpoint forces_nl (F : Frame_no_Loeb) (V : fW_nl F -> nat -> bool)
                   (w : fW_nl F) (phi : Form) : Prop :=
  match phi with
  | Var p => V w p = true
  | Bot => False
  | Impl X Y => forces_nl F V w X -> forces_nl F V w Y
  | Box n psi => forall v, fR_nl F n w v -> forces_nl F V v psi
  end.


Theorem soundness_no_Loeb : forall phi, |-no_loeb phi ->
  forall F V w, forces_nl F V w phi.
Proof.
  intros phi H. induction H.
  - intros F V w. simpl. intros Hphi _. exact Hphi.
  - intros F V w. simpl. intros Hf Hg Hphi.
    apply Hf; [exact Hphi | apply Hg; exact Hphi].
  - intros F V w. simpl. intro Hnnp. apply NNPP. exact Hnnp.
  - intros F V w. simpl. intros Himp Hphi v Hwv.
    apply (Himp v Hwv). apply (Hphi v Hwv).
  - intros F V w. simpl. intros Hphi v Hwv u Hvu.
    apply Hphi. apply (fR_nl_trans F n w v u Hwv Hvu).
  - intros F V w. simpl. intros Hphi v Hwv.
    apply Hphi. apply (fR_nl_mon F n w v Hwv).
  - intros F V w. simpl. intros v Hwv Hbox.
    destruct (fR_nl_nextcon F n w v Hwv) as [u Hvu].
    exact (Hbox u Hvu).
  - intros F V w. apply (IHProvable_no_Loeb1 F V w).
    apply (IHProvable_no_Loeb2 F V w).
  - intros F V w. simpl. intros v _.
    apply (IHProvable_no_Loeb F V v).
Qed.


Definition F_no_Loeb : Frame_no_Loeb :=
  mkFrame_no_Loeb nat R_break_wf
    R_break_wf_trans R_break_wf_mon R_break_wf_nextcon.


Theorem loeb_axiom_needs_Loeb :
  ~ (|-no_loeb Impl (Box 0 (Impl (Box 0 Bot) Bot)) (Box 0 Bot)).
Proof.
  intro H.
  pose proof (soundness_no_Loeb _ H F_no_Loeb (fun _ _ => true) 0) as Hf.
  simpl in Hf.
  assert (HantBox : forall v, R_break_wf 0 0 v ->
                    (forall u, R_break_wf 0 v u -> False) -> False).
  { intros v _ Habs. apply (Habs (S v)). unfold R_break_wf. lia. }
  pose proof (Hf HantBox) as HboxBot.
  apply (HboxBot 1). unfold R_break_wf. lia.
Qed.


(** ** Mutual independence theorem.

    Of the modal axioms {Ax_Loeb, Ax_Mon, Ax_NextCon, Ax_Box4}, the
    first three are mutually independent: removing any one of them
    leaves a strictly weaker calculus.  Ax_Box4 is in fact derivable
    from K + Löb (see [nb4_axiom4]) and so is *not* independent.
    The propositional [Ax_K] axiom is universal under Kripke
    semantics and cannot be refuted by a frame, so its independence
    requires non-Kripke (e.g. neighborhood) semantics not developed
    here. *)

Theorem minimal_viable_bypass_loeb :
  ~ (|-no_loeb Impl (Box 0 (Impl (Box 0 Bot) Bot)) (Box 0 Bot)).
Proof. exact loeb_axiom_needs_Loeb. Qed.



Theorem axioms_mutually_independent :
  (~ (|-no_loeb Impl (Box 0 (Impl (Box 0 Bot) Bot)) (Box 0 Bot))) /\
  (~ (|-no_mon Impl (Box 0 (Var 0)) (Box 1 (Var 0)))) /\
  (~ (|-no_nc Box 1 (Neg (Box 0 Bot)))) /\
  (forall n A, |-no_b4 Impl (Box n A) (Box n (Box n A))).
Proof.
  split; [|split; [|split]].
  - exact loeb_axiom_needs_Loeb.
  - exact mon_axiom_needs_Mon.
  - exact consistency_chain_needs_NC.
  - exact nb4_axiom4.
Qed.


Inductive Provable_GLP : Form -> Prop :=
  | GLP_Ax_K : forall phi psi,
      Provable_GLP (Impl phi (Impl psi phi))
  | GLP_Ax_S : forall phi psi chi,
      Provable_GLP (Impl (Impl phi (Impl psi chi))
                         (Impl (Impl phi psi) (Impl phi chi)))
  | GLP_Ax_DN : forall phi,
      Provable_GLP (Impl (Neg (Neg phi)) phi)
  | GLP_Ax_BoxK : forall n phi psi,
      Provable_GLP (Impl (Box n (Impl phi psi))
                         (Impl (Box n phi) (Box n psi)))
  | GLP_Ax_Loeb : forall n phi,
      Provable_GLP (Impl (Box n (Impl (Box n phi) phi)) (Box n phi))
  | GLP_Ax_Box4 : forall n phi,
      Provable_GLP (Impl (Box n phi) (Box n (Box n phi)))
  | GLP_Ax_Mon : forall n phi,
      Provable_GLP (Impl (Box n phi) (Box (S n) phi))
  | GLP_Ax_Japaridze : forall n phi, Provable_GLP (Japaridze n phi)
  | GLP_MP : forall phi psi,
      Provable_GLP (Impl phi psi) -> Provable_GLP phi -> Provable_GLP psi
  | GLP_Nec : forall n phi,
      Provable_GLP phi -> Provable_GLP (Box n phi).


Theorem provable_GLP_proves_japaridze : forall n phi,
  Provable_GLP (Japaridze n phi).
Proof. intros. apply GLP_Ax_Japaridze. Qed.


Theorem provable_does_not_prove_japaridze :
  ~ |- Japaridze 0 (Var 0).
Proof. exact japaridze_unprovable_at_0. Qed.


Theorem provable_GLP_incomparable_with_provable :
  Provable_GLP (Japaridze 0 (Var 0)) /\ ~ |- Japaridze 0 (Var 0).
Proof.
  split.
  - apply provable_GLP_proves_japaridze.
  - exact provable_does_not_prove_japaridze.
Qed.


Inductive Provable_GL : Form -> Prop :=
  | GL_Ax_K : forall phi psi,
      Provable_GL (Impl phi (Impl psi phi))
  | GL_Ax_S : forall phi psi chi,
      Provable_GL (Impl (Impl phi (Impl psi chi))
                        (Impl (Impl phi psi) (Impl phi chi)))
  | GL_Ax_DN : forall phi,
      Provable_GL (Impl (Neg (Neg phi)) phi)
  | GL_Ax_BoxK : forall phi psi,
      Provable_GL (Impl (Box 0 (Impl phi psi))
                        (Impl (Box 0 phi) (Box 0 psi)))
  | GL_Ax_Loeb : forall phi,
      Provable_GL (Impl (Box 0 (Impl (Box 0 phi) phi)) (Box 0 phi))
  | GL_Ax_Box4 : forall phi,
      Provable_GL (Impl (Box 0 phi) (Box 0 (Box 0 phi)))
  | GL_MP : forall phi psi,
      Provable_GL (Impl phi psi) -> Provable_GL phi -> Provable_GL psi
  | GL_Nec : forall phi,
      Provable_GL phi -> Provable_GL (Box 0 phi).


Theorem GL_in_provable : forall phi, Provable_GL phi -> |- phi.
Proof.
  intros phi H. induction H as [| | | | | | phi psi _ IH1 _ IH2 | phi _ IH].
  - apply Ax_K.
  - apply Ax_S.
  - apply Ax_DN.
  - apply Ax_BoxK.
  - apply Ax_Loeb.
  - apply Ax_Box4.
  - exact (MP _ _ IH1 IH2).
  - exact (Nec _ _ IH).
Qed.


Lemma forget_levels_level_0_only : forall phi,
  level_0_only phi -> forget_levels phi = phi.
Proof.
  induction phi as [p | | a IHa b IHb | n a IHa]; intro Hl; simpl in *.
  - reflexivity.
  - reflexivity.
  - destruct Hl as [Ha Hb]. rewrite IHa by exact Ha. rewrite IHb by exact Hb. reflexivity.
  - destruct Hl as [Hn Ha]. subst n. rewrite IHa by exact Ha. reflexivity.
Qed.


(** Hilbert-style derivability lemmas inside [Provable_GL]. *)

Lemma GL_id : forall phi, Provable_GL (Impl phi phi).
Proof.
  intro phi.
  pose proof (GL_Ax_S phi (Impl phi phi) phi) as Hs.
  pose proof (GL_Ax_K phi (Impl phi phi)) as Hk1.
  pose proof (GL_Ax_K phi phi) as Hk2.
  exact (GL_MP _ _ (GL_MP _ _ Hs Hk1) Hk2).
Qed.


Lemma GL_top : Provable_GL Top.
Proof. exact (GL_id Bot). Qed.


Lemma GL_imply_top : forall phi, Provable_GL (Impl phi Top).
Proof.
  intro phi. exact (GL_MP _ _ (GL_Ax_K Top phi) GL_top).
Qed.


Lemma GL_top_imply_top : Provable_GL (Impl Top Top).
Proof. exact (GL_id Top). Qed.


Lemma GL_top_imply_imp_top : forall X, Provable_GL (Impl X (Impl Top Top)).
Proof.
  intro X.
  exact (GL_MP _ _ (GL_Ax_K (Impl Top Top) X) GL_top_imply_top).
Qed.


(** [forget_levels] of every Provable axiom is a Provable_GL theorem. *)

Lemma forget_AxK : forall phi psi,
  Provable_GL (forget_levels (Impl phi (Impl psi phi))).
Proof. intros phi psi. simpl. apply GL_Ax_K. Qed.


Lemma forget_AxS : forall phi psi chi,
  Provable_GL (forget_levels
    (Impl (Impl phi (Impl psi chi)) (Impl (Impl phi psi) (Impl phi chi)))).
Proof. intros phi psi chi. simpl. apply GL_Ax_S. Qed.


Lemma forget_AxDN : forall phi,
  Provable_GL (forget_levels (Impl (Neg (Neg phi)) phi)).
Proof. intro phi. simpl. apply GL_Ax_DN. Qed.


Lemma forget_AxBoxK : forall n phi psi,
  Provable_GL (forget_levels
    (Impl (Box n (Impl phi psi)) (Impl (Box n phi) (Box n psi)))).
Proof.
  intros n phi psi. simpl. destruct n as [|n'].
  - apply GL_Ax_BoxK.
  - exact (GL_top_imply_imp_top Top).
Qed.


Lemma forget_AxLoeb : forall n phi,
  Provable_GL (forget_levels
    (Impl (Box n (Impl (Box n phi) phi)) (Box n phi))).
Proof.
  intros n phi. simpl. destruct n as [|n'].
  - apply GL_Ax_Loeb.
  - exact (GL_id Top).
Qed.


Lemma forget_AxBox4 : forall n phi,
  Provable_GL (forget_levels (Impl (Box n phi) (Box n (Box n phi)))).
Proof.
  intros n phi. simpl. destruct n as [|n'].
  - apply GL_Ax_Box4.
  - exact (GL_id Top).
Qed.


Lemma forget_AxMon : forall n phi,
  Provable_GL (forget_levels (Impl (Box n phi) (Box (S n) phi))).
Proof.
  intros n phi. simpl.
  destruct n as [|n']; apply GL_imply_top.
Qed.


Lemma forget_AxNextCon : forall n,
  Provable_GL (forget_levels (Box (S n) (Neg (Box n Bot)))).
Proof.
  intro n. simpl. exact GL_top.
Qed.


Theorem provable_to_GL_via_forget : forall phi,
  |- phi -> Provable_GL (forget_levels phi).
Proof.
  intros phi H. induction H.
  - apply forget_AxK.
  - apply forget_AxS.
  - apply forget_AxDN.
  - apply forget_AxBoxK.
  - apply forget_AxLoeb.
  - apply forget_AxBox4.
  - apply forget_AxMon.
  - apply forget_AxNextCon.
  - simpl in IHProvable1. exact (GL_MP _ _ IHProvable1 IHProvable2).
  - simpl. destruct n as [|n'].
    + exact (GL_Nec _ IHProvable).
    + exact GL_top.
Qed.


Theorem level_0_conservativity : forall phi,
  |- phi -> level_0_only phi -> Provable_GL phi.
Proof.
  intros phi Hp Hl.
  pose proof (provable_to_GL_via_forget phi Hp) as HGL.
  rewrite (forget_levels_level_0_only phi Hl) in HGL.
  exact HGL.
Qed.


Theorem level_0_provable_iff_GL : forall phi,
  level_0_only phi -> (|- phi <-> Provable_GL phi).
Proof.
  intros phi Hl. split.
  - intro H. exact (level_0_conservativity phi H Hl).
  - apply GL_in_provable.
Qed.


Theorem reflection_algebra :
  (forall phi, prov_equiv phi phi) /\
  (forall phi psi, prov_equiv phi psi -> prov_equiv psi phi) /\
  (forall phi psi chi,
     prov_equiv phi psi -> prov_equiv psi chi -> prov_equiv phi chi) /\
  (forall phi1 phi2 psi1 psi2,
     prov_equiv phi1 phi2 -> prov_equiv psi1 psi2 ->
     prov_equiv (Impl phi1 psi1) (Impl phi2 psi2)) /\
  (forall n phi psi,
     prov_equiv phi psi -> prov_equiv (Box n phi) (Box n psi)) /\
  ~ prov_equiv Top Bot.
Proof.
  split; [|split; [|split; [|split; [|split]]]].
  - apply prov_equiv_refl.
  - apply prov_equiv_sym.
  - apply prov_equiv_trans.
  - apply prov_equiv_impl_cong.
  - apply prov_equiv_box_cong.
  - apply lindenbaum_tarski_non_degenerate.
Qed.


Theorem reflection_algebra_loeb_law : forall n phi,
  prov_equiv (Box n (Impl (Box n phi) phi)) (Box n phi).
Proof.
  intros n phi. unfold prov_equiv.
  apply prov_iff_sym. apply loeb_iff.
Qed.


Theorem reflection_algebra_box_distrib : forall n phi psi,
  |- Impl (Box n (Impl phi psi)) (Impl (Box n phi) (Box n psi)).
Proof.
  intros n phi psi. apply Ax_BoxK.
Qed.


Theorem reflection_algebra_mon : forall n phi,
  |- Impl (Box n phi) (Box (S n) phi).
Proof.
  intros n phi. apply Ax_Mon.
Qed.


Theorem reflection_algebra_axiom4 : forall n phi,
  |- Impl (Box n phi) (Box n (Box n phi)).
Proof.
  intros n phi. apply Ax_Box4.
Qed.


Theorem solovay_polymodal_box_free_subsumed : forall phi,
  box_free phi -> |- phi <-> classical_valid phi.
Proof.
  intros phi Hbf. split.
  - intro Hp. exact (provable_classically_valid phi Hp).
  - intro Hval. apply trivial_in_provable. exact (prop_completeness phi Hbf Hval).
Qed.


(** Polymodal completeness relative to the Beklemishev hierarchy:
    [Provable] strictly contains [Provable_GLP] at every modal depth. *)

Theorem polymodal_provable_GLP_incomparable :
  Provable_GLP (Japaridze 0 (Var 0)) /\ ~ |- Japaridze 0 (Var 0).
Proof. exact provable_GLP_incomparable_with_provable. Qed.


(** ** Reflection hierarchy.

    [Provable]'s reflection schema is unprovable internally
    ([reflection_schema_unprovable]).  Packaged here as: at every
    level, the reflection schema is meta-unprovable. *)

Theorem reflection_schema_classification : forall n,
  ~ (forall phi, |- Impl (Box n phi) phi).
Proof. exact reflection_schema_unprovable. Qed.


Theorem reflection_principle_hierarchy : forall n,
  ~ (forall phi, |- Impl (Box n phi) phi).
Proof. exact reflection_schema_unprovable. Qed.


Theorem Ax_Box4_derivable : forall n A,
  |- Impl (Box n A) (Box n (Box n A)).
Proof.
  intros n A.
  apply no_b4_to_provable.
  exact (nb4_axiom4 n A).
Qed.


Theorem Ax_Box4_independent_of_Mon_NextCon : forall n A,
  |-no_b4 Impl (Box n A) (Box n (Box n A)).
Proof. exact nb4_axiom4. Qed.


Theorem Box4_derivable_in_Provable_no_B4 : forall n A,
  |-no_b4 Impl (Box n A) (Box n (Box n A)).
Proof. exact nb4_axiom4. Qed.


Definition Provable_full_GLP : Form -> Prop := Provable_GLP.


Theorem Provable_full_GLP_proves_Japaridze : forall n phi,
  Provable_full_GLP (Japaridze n phi).
Proof. exact provable_GLP_proves_japaridze. Qed.


Theorem Provable_full_GLP_incomparable_Provable :
  Provable_full_GLP (Japaridze 0 (Var 0)) /\ ~ |- Japaridze 0 (Var 0).
Proof. exact provable_GLP_incomparable_with_provable. Qed.


Lemma ProvableProp_implies_Provable_GLP : forall phi,
  ProvableProp phi -> Provable_GLP phi.
Proof.
  intros phi H. induction H.
  - apply GLP_Ax_K.
  - apply GLP_Ax_S.
  - apply GLP_Ax_DN.
  - exact (GLP_MP _ _ IHProvableProp1 IHProvableProp2).
Qed.


Lemma eval_provable_GLP : forall val phi, Provable_GLP phi -> eval val phi = true.
Proof.
  intros val phi H. induction H; simpl.
  - destruct (eval val phi), (eval val psi); reflexivity.
  - destruct (eval val phi), (eval val psi), (eval val chi); reflexivity.
  - destruct (eval val phi); reflexivity.
  - reflexivity.
  - reflexivity.
  - reflexivity.
  - reflexivity.
  - reflexivity.
  - simpl in IHProvable_GLP1. rewrite IHProvable_GLP2 in IHProvable_GLP1.
    simpl in IHProvable_GLP1. exact IHProvable_GLP1.
  - reflexivity.
Qed.


Theorem provable_GLP_classically_valid : forall phi,
  Provable_GLP phi -> classical_valid phi.
Proof. intros phi H val. exact (eval_provable_GLP val phi H). Qed.


Theorem box_free_conservativity_GLP_Provable : forall phi,
  box_free phi -> (Provable_full_GLP phi <-> |- phi).
Proof.
  intros phi Hbf. unfold Provable_full_GLP. split.
  - intro Hglp.
    pose proof (provable_GLP_classically_valid phi Hglp) as Hcv.
    apply trivial_in_provable.
    exact (prop_completeness phi Hbf Hcv).
  - intro Hp.
    pose proof (box_free_normalisation phi Hbf Hp) as Hpp.
    exact (ProvableProp_implies_Provable_GLP phi Hpp).
Qed.


Theorem intuitionistic_syntactic_core :
  (forall n phi, |- Impl (Box n phi) (Box n (Box n phi))) /\
  (forall n phi, |- Impl (Box n phi) (Box (S n) phi)) /\
  (forall n, |- Box (S n) (Neg (Box n Bot))) /\
  (forall n phi, |- Impl (Box n (Impl (Box n phi) phi)) (Box n phi)) /\
  (forall n phi psi, |- Impl (Box n (Impl phi psi)) (Impl (Box n phi) (Box n psi))) /\
  (forall phi, FAxProvable phi <-> |- phi) /\
  (forall phi, box_free phi -> |- phi -> ProvableProp phi).
Proof.
  split; [|split; [|split; [|split; [|split; [|split]]]]].
  - exact Ax_Box4.
  - exact Ax_Mon.
  - exact Ax_NextCon.
  - exact Ax_Loeb.
  - exact Ax_BoxK.
  - exact finite_axiomatisation.
  - exact box_free_normalisation.
Qed.


Definition arithmetic_interpretation_GL_valid (phi : Form) : Prop :=
  forall I : Form -> Form, is_arithmetic_interpretation I -> |- I phi.


Theorem GL_arithmetic_soundness : forall phi,
  Provable_GL phi -> arithmetic_interpretation_GL_valid phi.
Proof.
  intros phi HGL I [HI1 _].
  apply HI1. exact (GL_in_provable phi HGL).
Qed.


Theorem GL_arithmetic_completeness_level_0 : forall phi,
  level_0_only phi -> arithmetic_interpretation_GL_valid phi -> Provable_GL phi.
Proof.
  intros phi Hl Harith.
  apply level_0_conservativity; [|exact Hl].
  pose proof (Harith (fun x => x) identity_is_arithmetic_interpretation) as H.
  exact H.
Qed.


Theorem solovay_first_completeness_level_0 : forall phi,
  level_0_only phi -> (Provable_GL phi <-> arithmetic_interpretation_GL_valid phi).
Proof.
  intros phi Hl. split.
  - exact (GL_arithmetic_soundness phi).
  - exact (GL_arithmetic_completeness_level_0 phi Hl).
Qed.


Inductive Provable_S : Form -> Prop :=
  | S_GL_subsumes : forall phi, Provable_GL phi -> Provable_S phi
  | S_reflection : forall phi, classical_valid phi -> Provable_S (Impl (Box 0 phi) phi)
  | S_MP : forall phi psi, Provable_S (Impl phi psi) -> Provable_S phi -> Provable_S psi.


Theorem S_contains_GL : forall phi, Provable_GL phi -> Provable_S phi.
Proof. exact S_GL_subsumes. Qed.


Lemma ProvableProp_to_Provable_GL : forall phi,
  ProvableProp phi -> Provable_GL phi.
Proof.
  intros phi H. induction H.
  - apply GL_Ax_K.
  - apply GL_Ax_S.
  - apply GL_Ax_DN.
  - exact (GL_MP _ _ IHProvableProp1 IHProvableProp2).
Qed.


Theorem S_truth_completeness_box_free : forall phi,
  box_free phi -> classical_valid phi -> Provable_S phi.
Proof.
  intros phi Hbf Hval.
  apply S_GL_subsumes.
  apply ProvableProp_to_Provable_GL.
  exact (prop_completeness phi Hbf Hval).
Qed.


Theorem S_box_to_phi_for_valid : forall phi,
  classical_valid phi -> Provable_S (Impl (Box 0 phi) phi).
Proof. exact S_reflection. Qed.


Theorem S_truth_arithmetic_soundness : forall phi,
  Provable_S phi -> classical_valid phi.
Proof.
  intros phi H. induction H.
  - exact (provable_classically_valid phi (GL_in_provable phi H)).
  - intro val. simpl. exact (H val).
  - intro val. specialize (IHProvable_S1 val). specialize (IHProvable_S2 val).
    simpl in IHProvable_S1. rewrite IHProvable_S2 in IHProvable_S1.
    simpl in IHProvable_S1. exact IHProvable_S1.
Qed.


Theorem solovay_second_completeness_box_free : forall phi,
  box_free phi -> (Provable_S phi <-> classical_valid phi).
Proof.
  intros phi Hbf. split.
  - exact (S_truth_arithmetic_soundness phi).
  - exact (S_truth_completeness_box_free phi Hbf).
Qed.


Definition arithmetic_interpretation_GLP_valid (phi : Form) : Prop :=
  forall I : Form -> Form, is_arithmetic_interpretation I -> Provable_full_GLP (I phi).


Theorem GLP_arithmetic_completeness_box_free : forall phi,
  box_free phi -> classical_valid phi -> Provable_full_GLP phi.
Proof.
  intros phi Hbf Hval. unfold Provable_full_GLP.
  apply ProvableProp_implies_Provable_GLP.
  exact (prop_completeness phi Hbf Hval).
Qed.


Theorem solovay_polymodal_box_free : forall phi,
  box_free phi -> (Provable_full_GLP phi <-> classical_valid phi).
Proof.
  intros phi Hbf. split.
  - exact (provable_GLP_classically_valid phi).
  - exact (GLP_arithmetic_completeness_box_free phi Hbf).
Qed.


Theorem GLP_complete_against_canonical_identity : forall phi,
  box_free phi ->
  (forall I : Form -> Form, is_arithmetic_interpretation I -> classical_valid (I phi)) ->
  Provable_full_GLP phi.
Proof.
  intros phi Hbf Hall.
  pose proof (Hall (fun x => x) identity_is_arithmetic_interpretation) as Hcv.
  exact (GLP_arithmetic_completeness_box_free phi Hbf Hcv).
Qed.


Theorem finite_axiomatisation_modal_substitutional : forall phi, FAxProvable phi <-> |- phi.
Proof. exact finite_axiomatisation. Qed.


Theorem finite_axiomatisation_modal_substitutional_minimal : forall phi,
  FAx2Provable phi <-> |- phi.
Proof. exact finite_axiomatisation_levelsubst. Qed.


(** [Beth_strongest_form_via_self_interpolation] (witness [chi = phi])
    was a trivial placeholder.  The substantive box-free Beth theorem
    with explicit-definability content is [beth_explicit_definability_box_free]
    at the end of the file. *)


Theorem GLP_disjunction_property_via_classical_valuation : forall n m phi psi val,
  eval val (Or (Box n phi) (Box m psi)) = true ->
  eval val (Box n phi) = true \/ eval val (Box m psi) = true.
Proof.
  intros n m phi psi val. simpl. left. reflexivity.
Qed.


Theorem GLP_disjunction_via_box_provable_left : forall n m phi psi,
  |- Box n phi -> |- Or (Box m psi) (Box n phi).
Proof.
  intros n m phi psi H. unfold Or.
  exact (prov_weaken (Box n phi) (Neg (Box m psi)) H).
Qed.


Theorem GLP_disjunction_via_box_provable_right : forall n m phi psi,
  |- Box m psi -> |- Or (Box n phi) (Box m psi).
Proof.
  intros n m phi psi H. unfold Or.
  exact (prov_weaken (Box m psi) (Neg (Box n phi)) H).
Qed.


Theorem Box4_derivable_in_full_Provable : forall n phi,
  |- Impl (Box n phi) (Box n (Box n phi)).
Proof.
  intros n phi. apply no_b4_to_provable. exact (nb4_axiom4 n phi).
Qed.


Theorem Box4_derivable_uses_only_no_B4_axioms : forall n phi,
  |-no_b4 Impl (Box n phi) (Box n (Box n phi)).
Proof. exact nb4_axiom4. Qed.


Theorem Box4_redundant_in_axiom_set : forall n phi,
  |- Impl (Box n phi) (Box n (Box n phi)) /\
  |-no_b4 Impl (Box n phi) (Box n (Box n phi)).
Proof.
  intros n phi. split.
  - exact (Box4_derivable_in_full_Provable n phi).
  - exact (Box4_derivable_uses_only_no_B4_axioms n phi).
Qed.


Theorem Provable_iff_Provable_no_B4 : forall phi,
  |- phi <-> |-no_b4 phi.
Proof. exact provable_iff_no_b4. Qed.


Theorem Box4_via_no_B4_calculus_strictly_redundant : forall n phi,
  (|- Impl (Box n phi) (Box n (Box n phi))) /\
  (|-no_b4 Impl (Box n phi) (Box n (Box n phi))) /\
  (forall psi, |- psi <-> |-no_b4 psi).
Proof.
  intros n phi. split; [|split].
  - exact (Box4_derivable_in_full_Provable n phi).
  - exact (Box4_derivable_uses_only_no_B4_axioms n phi).
  - exact provable_iff_no_b4.
Qed.

