(** Tiling.Syntax - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.



(** Polymodal propositional formulas indexed by a natural-number "level".
    [Box n phi] reads: "phi is provable in the theory at level n."
    The propositional skeleton (Var, Bot, Impl) is classical; modal
    axioms are imposed in [Provable] below. *)

Inductive Form : Type :=
  | Var  : nat -> Form
  | Bot  : Form
  | Impl : Form -> Form -> Form
  | Box  : nat -> Form -> Form.


(** ** Derived connectives.
    We define negation, top, diamond (dual modality), conjunction,
    disjunction, and biconditional in terms of [Impl] and [Bot] in the
    standard classical way. *)

Definition Neg (phi : Form) : Form := Impl phi Bot.

Definition Top : Form := Impl Bot Bot.

Definition Diamond (n : nat) (phi : Form) : Form := Neg (Box n (Neg phi)).

Definition And (phi psi : Form) : Form := Neg (Impl phi (Neg psi)).

Definition Or (phi psi : Form) : Form := Impl (Neg phi) psi.

Definition Iff (phi psi : Form) : Form := And (Impl phi psi) (Impl psi phi).


(** ** Decidable equality on formulas.

    Infrastructure needed for any decision procedure on the calculus.
    Standard structural induction with [decide equality] on the
    [Form] inductive (with [Nat.eq_dec] for the [Var] and [Box]
    payloads). *)

Lemma Form_eq_dec : forall (f g : Form), {f = g} + {f <> g}.
Proof.
  decide equality; apply Nat.eq_dec.
Defined.


(** ** And-list: conjunction over a finite list of formulas. *)

Fixpoint And_list (l : list Form) : Form :=
  match l with
  | nil => Top
  | phi :: rest => And phi (And_list rest)
  end.


(** ** Boolean evaluation that maps every box-formula to [true].

    A simple semantic argument for system-level meta-consistency:
    define [eval] mapping every [Box _ _] to [true] and propositional
    structure to its classical truth-table.  Every axiom of GLP*
    evaluates to [true] under this assignment, hence so does every
    Provable formula.  Since [Bot] evaluates to [false], [Bot] is
    not Provable. *)

Fixpoint eval (val : nat -> bool) (phi : Form) : bool :=
  match phi with
  | Var p => val p
  | Bot => false
  | Impl X Y => orb (negb (eval val X)) (eval val Y)
  | Box _ _ => true
  end.


(** ** Substitution and finite axiom carriers.

    The schemata [Ax_K], [Ax_S], [Ax_DN], [Ax_BoxK n], [Ax_Loeb n],
    [Ax_Box4 n], [Ax_Mon n], [Ax_NextCon n] in [Provable] are
    presented in Coq with universal quantification over their formula
    arguments.  Each schema is generated by a single fixed
    "axiom carrier" formula in the propositional variables [Var 0],
    [Var 1], [Var 2], closed under uniform substitution of arbitrary
    formulas for variables.  The level index [n] remains a metalevel
    nat parameter.

    The result: [Provable] is equivalent to the closure of eight
    carrier formulas under uniform substitution, modus ponens, and
    necessitation. *)

Fixpoint subst_form (sigma : nat -> Form) (phi : Form) : Form :=
  match phi with
  | Var p => sigma p
  | Bot => Bot
  | Impl X Y => Impl (subst_form sigma X) (subst_form sigma Y)
  | Box n psi => Box n (subst_form sigma psi)
  end.


Definition Subst (p : nat) (psi phi : Form) : Form :=
  subst_form (fun k => if Nat.eqb k p then psi else Var k) phi.


Fixpoint box_free (phi : Form) : Prop :=
  match phi with
  | Var _ => True
  | Bot => True
  | Impl X Y => box_free X /\ box_free Y
  | Box _ _ => False
  end.


Definition classical_valid (phi : Form) : Prop :=
  forall val, eval val phi = true.


Fixpoint free_vars (phi : Form) : list nat :=
  match phi with
  | Var p => [p]
  | Bot => []
  | Impl X Y => free_vars X ++ free_vars Y
  | Box _ psi => free_vars psi
  end.


Lemma free_vars_in_nodup : forall phi p,
  In p (free_vars phi) -> In p (nodup Nat.eq_dec (free_vars phi)).
Proof.
  intros phi p Hin. apply nodup_In. exact Hin.
Qed.


Lemma eval_ext_on_free_vars : forall phi val1 val2,
  (forall p, In p (free_vars phi) -> val1 p = val2 p) ->
  eval val1 phi = eval val2 phi.
Proof.
  intro phi. induction phi as [k | | X IHX Y IHY | n psi IHpsi];
    intros val1 val2 Hext; simpl.
  - apply Hext. simpl. left. reflexivity.
  - reflexivity.
  - rewrite (IHX val1 val2), (IHY val1 val2).
    + reflexivity.
    + intros p Hin. apply Hext. simpl. apply in_or_app. right. exact Hin.
    + intros p Hin. apply Hext. simpl. apply in_or_app. left. exact Hin.
  - reflexivity.
Qed.


(** ** Sambin's fixed-point theorem (build-up).

    We work toward Sambin's theorem: every formula [phi(p)] in which
    every occurrence of [Var p] is in the scope of some [Box] admits
    a fixed point [psi] with [|- Iff psi (Subst p psi phi)].
    Boolos's derivation of axiom 4 from K + Löb (Logic of Provability,
    Theorem 11) routes through this theorem.  We build up the
    machinery piece by piece. *)

(** *** [modalized p phi]: every [Var p] in [phi] is under a [Box]. *)

Fixpoint modalized (p : nat) (phi : Form) : Prop :=
  match phi with
  | Var k => k <> p
  | Bot => True
  | Impl X Y => modalized p X /\ modalized p Y
  | Box _ _ => True
  end.


(** *** Modal depth: maximum nesting of [Box]. *)

Fixpoint modal_depth (phi : Form) : nat :=
  match phi with
  | Var _ => 0
  | Bot => 0
  | Impl X Y => Nat.max (modal_depth X) (modal_depth Y)
  | Box _ psi => S (modal_depth psi)
  end.


Lemma modal_depth_neg : forall phi,
  modal_depth (Neg phi) = modal_depth phi.
Proof.
  intro phi. unfold Neg. simpl. rewrite Nat.max_0_r. reflexivity.
Qed.


Fixpoint level_k_only (k : nat) (phi : Form) : Prop :=
  match phi with
  | Var _ => True
  | Bot => True
  | Impl X Y => level_k_only k X /\ level_k_only k Y
  | Box n psi => n = k /\ level_k_only k psi
  end.


(** Box-free formulas have no [Box] sub-formula. *)

Lemma box_free_eval_independent : forall phi,
  box_free phi -> forall val1 val2,
    (forall p, val1 p = val2 p) -> eval val1 phi = eval val2 phi.
Proof.
  intros phi Hbf val1 val2 Hext.
  induction phi as [k | | X IHX Y IHY | n psi IHpsi]; simpl.
  - apply Hext.
  - reflexivity.
  - simpl in Hbf. destruct Hbf as [HX HY].
    rewrite (IHX HX), (IHY HY). reflexivity.
  - simpl in Hbf. contradiction.
Qed.


Fixpoint level_le_k (k : nat) (phi : Form) : Prop :=
  match phi with
  | Var _ => True
  | Bot => True
  | Impl X Y => level_le_k k X /\ level_le_k k Y
  | Box n psi => n <= k /\ level_le_k k psi
  end.


Fixpoint level_0_only (phi : Form) : Prop :=
  match phi with
  | Var _ => True
  | Bot => True
  | Impl X Y => level_0_only X /\ level_0_only Y
  | Box n psi => n = 0 /\ level_0_only psi
  end.


(** ** Level-0 conservativity over GL.

    Every level-0-only [Provable] theorem is a [Provable_GL] theorem.
    Proof technique: define a translation [forget_levels] that collapses
    every [Box n phi] with [n > 0] to [Top], leaving level-0 boxes
    intact.  Each Provable axiom maps to a Provable_GL theorem under
    this translation, and forget_levels is the identity on level-0-only
    formulas. *)

Fixpoint forget_levels (phi : Form) : Form :=
  match phi with
  | Var p => Var p
  | Bot => Bot
  | Impl a b => Impl (forget_levels a) (forget_levels b)
  | Box n a => match n with
               | O => Box 0 (forget_levels a)
               | S _ => Top
               end
  end.


Definition Form_eqb (phi psi : Form) : bool :=
  if Form_eq_dec phi psi then true else false.


Lemma Form_eqb_eq : forall phi psi,
  Form_eqb phi psi = true <-> phi = psi.
Proof.
  intros phi psi. unfold Form_eqb.
  destruct (Form_eq_dec phi psi); split; intros; congruence.
Qed.


Lemma Form_eqb_neq : forall phi psi,
  Form_eqb phi psi = false <-> phi <> psi.
Proof.
  intros phi psi. unfold Form_eqb.
  destruct (Form_eq_dec phi psi); split; intros; congruence.
Qed.


Definition Worm := list nat.


Fixpoint worm_to_form (w : Worm) : Form :=
  match w with
  | [] => Top
  | k :: rest => Box k (worm_to_form rest)
  end.


Definition closed_form (phi : Form) : Prop := free_vars phi = [].


Theorem modal_depth_zero_box_free :
  forall phi, modal_depth phi = 0 -> box_free phi.
Proof.
  intro phi. induction phi as [k | | X IHX Y IHY | n psi IHpsi]; simpl; intro H.
  - exact I.
  - exact I.
  - assert (HX0 : modal_depth X = 0) by lia.
    assert (HY0 : modal_depth Y = 0) by lia.
    split.
    + apply IHX. exact HX0.
    + apply IHY. exact HY0.
  - lia.
Qed.


Definition Sigma1_form (phi : Form) : Prop := box_free phi.


(** ** Modal-Sigma_1 closure.

    [Sigma1_form] above is the box-free fragment.  It is sound for the
    arithmetic Sigma_1 hierarchy in the trivial sense (no provability
    operator appears), but it is strictly smaller than the genuine
    modal Sigma_1 closure where positive [Box n phi] occurrences are
    allowed.  We define [Sigma1_modal] as that genuine closure and
    prove the inclusion is strict. *)

Inductive Sigma1_modal : Form -> Prop :=
  | S1_box_free : forall phi, box_free phi -> Sigma1_modal phi
  | S1_box      : forall n phi, Sigma1_modal (Box n phi)
  | S1_impl_bf  : forall a b, box_free a -> Sigma1_modal b ->
                  Sigma1_modal (Impl a b).


Definition Sigma_alpha (alpha : nat) : Form -> Prop :=
  fun phi => modal_depth phi <= alpha.


(** ** Box-level-aware grading.

    [Sigma_alpha] above grades by modal *nesting depth*; it is blind to
    which Box level [n] appears in a formula like [Box n phi].  A
    Box-level-aware grading uses the largest [n] occurring under a
    [Box]-binder, not the depth.  These two gradings are incomparable
    in general; below we exhibit a witness showing the depth grading is
    strictly coarser than the level grading. *)

Fixpoint max_box_level (phi : Form) : nat :=
  match phi with
  | Var _ => 0
  | Bot => 0
  | Impl a b => Nat.max (max_box_level a) (max_box_level b)
  | Box n a => Nat.max n (max_box_level a)
  end.


Definition Sigma_alpha_levels (alpha : nat) (phi : Form) : Prop :=
  max_box_level phi <= alpha.



(** Outer-Box-level bound for Bew-derivations: the OUTERMOST Box of any
    Bew-n theorem is at a level strictly less than n+? — actually false
    in general because [TAx_BoxK k] introduces axioms over arbitrary
    inner formulas which may carry higher-level Boxes.  We instead use
    a more careful bound keyed to Necessitation steps. *)

Definition outer_box_level (phi : Form) : nat :=
  match phi with
  | Box k _ => S k
  | _ => 0
  end.


Inductive QForm : Type :=
  | QVar : nat -> QForm
  | QBot : QForm
  | QImpl : QForm -> QForm -> QForm
  | QBox : nat -> QForm -> QForm
  | QForall : QForm -> QForm
  | QExists : QForm -> QForm.


Fixpoint q_lift (cutoff : nat) (n : nat) (f : QForm) : QForm :=
  match f with
  | QVar i => if Nat.ltb i cutoff then QVar i else QVar (i + n)
  | QBot => QBot
  | QImpl a b => QImpl (q_lift cutoff n a) (q_lift cutoff n b)
  | QBox m a => QBox m (q_lift cutoff n a)
  | QForall a => QForall (q_lift (S cutoff) n a)
  | QExists a => QExists (q_lift (S cutoff) n a)
  end.


Fixpoint q_subst (k : nat) (s : QForm) (f : QForm) : QForm :=
  match f with
  | QVar i =>
      match Nat.compare i k with
      | Eq => s
      | Lt => QVar i
      | Gt => QVar (i - 1)
      end
  | QBot => QBot
  | QImpl a b => QImpl (q_subst k s a) (q_subst k s b)
  | QBox m a => QBox m (q_subst k s a)
  | QForall a => QForall (q_subst (S k) (q_lift 0 1 s) a)
  | QExists a => QExists (q_subst (S k) (q_lift 0 1 s) a)
  end.


Fixpoint nnf_pos (phi : Form) : Form :=
  match phi with
  | Var p => Var p
  | Bot => Bot
  | Impl X Y => Or (nnf_neg X) (nnf_pos Y)
  | Box n X => Box n (nnf_pos X)
  end
with nnf_neg (phi : Form) : Form :=
  match phi with
  | Var p => Neg (Var p)
  | Bot => Top
  | Impl X Y => And (nnf_pos X) (nnf_neg Y)
  | Box n X => Diamond n (nnf_neg X)
  end.


Lemma QForm_eq_dec : forall (f g : QForm), {f = g} + {f <> g}.
Proof.
  decide equality; apply Nat.eq_dec.
Defined.


Lemma box_free_Neg : forall phi, box_free phi -> box_free (Neg phi).
Proof. intros phi H. cbn. split; [exact H | exact I]. Qed.


Lemma box_free_And_list : forall l, Forall box_free l -> box_free (And_list l).
Proof.
  intros l H. induction l as [|phi rest IH]; cbn.
  - split; exact I.
  - inversion H; subst.
    cbn. split; [|exact I]. split; [exact H2 |].
    cbn. split; [apply IH; exact H3 | exact I].
Qed.


Definition Bew_bounded (k n : nat) : Form -> Form := fun phi => Box k (Box n phi).


Definition no_top_impl (phi : Form) : bool :=
  match phi with
  | Impl _ _ => false
  | _ => true
  end.


Fixpoint NNIL_form (phi : Form) : Prop :=
  match phi with
  | Var _ => True
  | Bot => True
  | Box _ psi => NNIL_form psi
  | Impl phi1 phi2 =>
      no_top_impl phi1 = true /\ NNIL_form phi1 /\ NNIL_form phi2
  end.


(** [Goldblatt_translation] applies the double-negation embedding at
    every propositional variable, leaving [Bot] unchanged and recursing
    structurally through [Impl] and [Box].  Equivalently, it is uniform
    substitution by [sigma p := Neg (Neg (Var p))].  The translation is
    not the identity: [Goldblatt_translation (Var 0) = Neg (Neg (Var 0))].
    Provability is preserved both ways via [Ax_DN] / [prov_DN_intro] and
    the standard congruence rules; faithfulness follows from
    transitivity of [Iff]. *)

Fixpoint Goldblatt_translation (phi : Form) : Form :=
  match phi with
  | Var p => Neg (Neg (Var p))
  | Bot => Bot
  | Impl a b => Impl (Goldblatt_translation a) (Goldblatt_translation b)
  | Box n a => Box n (Goldblatt_translation a)
  end.


Definition closed_fragment_form (phi : Form) : Prop :=
  free_vars phi = [].


(** [closed_fragment_iterated_top_provable]: every closed formula
    obtained by an iterated [Box]-prefix over [Top] is provable.
    Substantive replacement for the deleted
    [closed_fragment_complete_axiomatization_via_constants] (which
    was just [prov_box_top n]).  This generalises the single-level
    fact to arbitrary nestings, which is the actual structural claim
    over the closed Box-prefix sub-fragment. *)

Fixpoint iter_box (ns : list nat) (phi : Form) : Form :=
  match ns with
  | [] => phi
  | n :: rest => Box n (iter_box rest phi)
  end.


(** [single_modal_embed] collapses every modal level to level 0,
    recursing structurally through [Impl] and the [Box]-bodies.  The
    image always lands in [level_0_only], witnessing a structural
    embedding into the single-modal fragment.  Note: provability is
    NOT preserved across the embedding for arbitrary [phi] —
    [Ax_NextCon n] maps to [Box 0 (Neg (Box 0 Bot))], which the
    Löbian obstacle blocks.  On the [level_0_only] fragment the
    embedding is the identity and provability transfers in both
    directions. *)

Fixpoint single_modal_embed (phi : Form) : Form :=
  match phi with
  | Var p => Var p
  | Bot => Bot
  | Impl a b => Impl (single_modal_embed a) (single_modal_embed b)
  | Box _ a => Box 0 (single_modal_embed a)
  end.


Lemma Form_eqb_refl : forall phi, Form_eqb phi phi = true.
Proof.
  intro phi. unfold Form_eqb. destruct (Form_eq_dec phi phi); congruence.
Qed.


Inductive arith_form : Type :=
  | A_falsity : arith_form
  | A_var : nat -> arith_form
  | A_impl : arith_form -> arith_form -> arith_form
  | A_Bew_n : nat -> arith_form -> arith_form.


Definition A_neg (a : arith_form) : arith_form := A_impl a A_falsity.


Fixpoint modal_to_arith (phi : Form) : arith_form :=
  match phi with
  | Var p => A_var p
  | Bot => A_falsity
  | Impl a b => A_impl (modal_to_arith a) (modal_to_arith b)
  | Box n a => A_Bew_n n (modal_to_arith a)
  end.


(******************************************************************************)
(* Substantive Craig interpolation for the box-free fragment via variable     *)
(* elimination.  The classical construction: define                            *)
(*   forget_var p phi := (phi[p:=Top]) ∨ (phi[p:=Bot])                         *)
(* eliminating one private variable; iterate over all variables of phi not    *)
(* occurring in psi.  The resulting interpolant chi has free_vars strictly    *)
(* contained in free_vars phi ∩ free_vars psi.                                 *)
(******************************************************************************)

Lemma eval_subst_box_free : forall val sigma phi,
  box_free phi ->
  eval val (subst_form sigma phi) = eval (fun k => eval val (sigma k)) phi.
Proof.
  intros val sigma phi. revert val sigma.
  induction phi as [k | | a IHa b IHb | n a IHa]; intros val sigma Hbf; cbn in *.
  - reflexivity.
  - reflexivity.
  - destruct Hbf as [Ha Hb]. rewrite (IHa val sigma Ha), (IHb val sigma Hb).
    reflexivity.
  - exfalso; exact Hbf.
Qed.


Definition update_val (val : nat -> bool) (p : nat) (b : bool) (k : nat) : bool :=
  if Nat.eqb k p then b else val k.


Lemma eval_Subst_box_free : forall val p X phi,
  box_free phi ->
  eval val (Subst p X phi) = eval (update_val val p (eval val X)) phi.
Proof.
  intros val p X phi Hbf. unfold Subst.
  rewrite (eval_subst_box_free val _ phi Hbf).
  apply eval_ext_on_free_vars.
  intros q _. cbn beta. unfold update_val.
  destruct (Nat.eqb q p); reflexivity.
Qed.


Lemma eval_Top_true : forall val, eval val Top = true.
Proof. intro val. cbn. reflexivity. Qed.


Lemma eval_Bot_false : forall val, eval val Bot = false.
Proof. intro val. cbn. reflexivity. Qed.


Lemma box_free_Top : box_free Top.
Proof. cbn. split; exact I. Qed.


Lemma box_free_Bot : box_free Bot.
Proof. cbn. exact I. Qed.


Lemma box_free_subst_form : forall sigma phi,
  box_free phi ->
  (forall p, In p (free_vars phi) -> box_free (sigma p)) ->
  box_free (subst_form sigma phi).
Proof.
  intros sigma phi. revert sigma.
  induction phi as [k | | a IHa b IHb | n a IHa]; intros sigma Hbf Hsig; cbn in *.
  - apply Hsig. left. reflexivity.
  - exact I.
  - destruct Hbf as [Ha Hb]. split.
    + apply IHa; [exact Ha|]. intros p Hp. apply Hsig. apply in_or_app. left. exact Hp.
    + apply IHb; [exact Hb|]. intros p Hp. apply Hsig. apply in_or_app. right. exact Hp.
  - exfalso; exact Hbf.
Qed.


Lemma box_free_Subst : forall p X phi,
  box_free phi -> box_free X ->
  box_free (Subst p X phi).
Proof.
  intros p X phi Hbf HX. unfold Subst.
  apply box_free_subst_form; [exact Hbf|].
  intros q _. destruct (Nat.eqb q p) eqn:E.
  - exact HX.
  - cbn. exact I.
Qed.


Lemma eval_Or : forall val A B,
  eval val (Or A B) = orb (eval val A) (eval val B).
Proof.
  intros val A B. unfold Or, Neg. cbn.
  destruct (eval val A); destruct (eval val B); reflexivity.
Qed.


Lemma eval_Impl : forall val A B,
  eval val (Impl A B) = orb (negb (eval val A)) (eval val B).
Proof. intros val A B. cbn. reflexivity. Qed.

