(** Tiling.Vingean - generated by split_tiling.py *)

From Stdlib Require Import Arith.Arith.
From Stdlib Require Import Arith.Wf_nat.
From Stdlib Require Import Lists.List.
From Stdlib Require Import micromega.Lia.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.ClassicalEpsilon.
Import ListNotations.

From Tiling Require Import Syntax.
From Tiling Require Import Provable.
From Tiling Require Import Polymodal.
From Tiling Require Import Bew.
From Tiling Require Import ProofTerms.
From Tiling Require Import Kripke.
From Tiling Require Import Propositional.
From Tiling Require Import SubCalculi.


Section VingeanReflection.


Variable Sigma : Type.

Variable Goal_pred : Sigma -> Prop.

Variable Transition : Sigma -> Form -> Sigma.


Definition agent_safe (a : Sigma -> Form) : Prop :=
  forall s, Goal_pred s -> Goal_pred (Transition s (a s)).


Definition tiling_safety_claim (n : nat) (phi : Form) : Form :=
  Impl (Box n phi) (Neg (Box n (Neg phi))).


Theorem level_higher_proves_tiling_safety : forall n phi,
  |- Box (S n) (tiling_safety_claim n phi).
Proof.
  intros n phi. unfold tiling_safety_claim. exact (tiling_consistency n phi).
Qed.


Theorem level_n_does_not_self_validate : forall n,
  ~ (forall phi, |- Impl (Box n phi) phi).
Proof. exact reflection_schema_unprovable. Qed.


Theorem vingean_reflection_full : forall n phi,
  |- Box (S n) (tiling_safety_claim n phi) /\
  ~ (forall psi, |- Impl (Box n psi) psi).
Proof.
  intros n phi. split.
  - exact (level_higher_proves_tiling_safety n phi).
  - exact (level_n_does_not_self_validate n).
Qed.


Theorem vingean_no_loebian_collapse : forall n phi,
  |- Box (S n) (tiling_safety_claim n phi) ->
  ~ (|- Box n phi /\ |- Box n (Neg phi)).
Proof.
  intros n phi Htil [Hphi Hnphi].
  unfold tiling_safety_claim in Htil.
  pose proof (Nec (S n) _ Hphi) as HphiBox.
  pose proof (prov_box_mp (S n) _ _ Htil HphiBox) as Hneg_box.
  pose proof (Nec (S n) _ Hnphi) as HnphiBox.
  apply (meta_consistency_no_contradiction (S n)
          (meta_consistency_every_level (S n))
          (Box n (Neg phi))).
  exact (conj HnphiBox Hneg_box).
Qed.


End VingeanReflection.


Section ConcreteEnvironment.


Definition Env_State : Type := nat.

Definition Env_Action : Type := nat.

Definition Env_Transition (s : Env_State) (a : Env_Action) : Env_State := s + a.

Definition Env_Goal (target : Env_State) (s : Env_State) : Prop := s <= target.


Definition cautious_agent : Env_State -> Env_Action := fun _ => 0.


Theorem cautious_agent_safe : forall target,
  forall s, Env_Goal target s -> Env_Goal target (Env_Transition s (cautious_agent s)).
Proof.
  intros target s Hg. unfold Env_Goal, Env_Transition, cautious_agent.
  rewrite Nat.add_0_r. exact Hg.
Qed.


Definition T_n_plus_1_licenses (n : nat) (action_witness : Form) : Prop :=
  Bew (S n) action_witness.


Theorem licensure_implies_goal_preservation_for_cautious : forall n target witness,
  T_n_plus_1_licenses n witness ->
  T_consistent n ->
  T_consistent n /\
  Bew (S n) witness /\
  (forall s, Env_Goal target s ->
   Env_Goal target (Env_Transition s (cautious_agent s))).
Proof.
  intros n target witness Hlic Hcon. split; [|split].
  - exact Hcon.
  - exact Hlic.
  - intros s Hg. exact (cautious_agent_safe target s Hg).
Qed.


Theorem licensure_via_NextCon_chain : forall n,
  T_consistent n -> T_consistent n /\ T_consistent (S n).
Proof.
  intros n Hcon. split.
  - exact Hcon.
  - exact (T_consistency_chain (S n)).
Qed.


Theorem T_n_plus_1_safe_successor : forall n target,
  T_consistent n ->
  T_consistent n /\
  (forall s, Env_Goal target s -> Env_Goal target (Env_Transition s (cautious_agent s))).
Proof.
  intros n target Hcon. split.
  - exact Hcon.
  - intros s Hg. exact (cautious_agent_safe target s Hg).
Qed.


End ConcreteEnvironment.


Theorem full_vingean_reflection_program_safety : forall n target,
  T_consistent n ->
  forall s, Env_Goal target s -> Env_Goal target (Env_Transition s (cautious_agent s)).
Proof.
  intros n target Hcon.
  exact (proj2 (T_n_plus_1_safe_successor n target Hcon)).
Qed.


Theorem full_vingean_reflection_program_self_modification : forall n phi,
  |- Box (S n) (Impl (Box n phi) (Neg (Box n (Neg phi)))).
Proof. exact tiling_consistency. Qed.


Theorem full_vingean_reflection_program_no_loebian_collapse :
  ~ |- Bot.
Proof. exact meta_consistency_system. Qed.


Theorem full_vingean_reflection_program_complete :
  (forall n target, T_consistent n ->
   forall s, Env_Goal target s -> Env_Goal target (Env_Transition s (cautious_agent s))) /\
  (forall n phi, |- Box (S n) (Impl (Box n phi) (Neg (Box n (Neg phi))))) /\
  (~ |- Bot).
Proof.
  split; [|split].
  - exact full_vingean_reflection_program_safety.
  - exact full_vingean_reflection_program_self_modification.
  - exact full_vingean_reflection_program_no_loebian_collapse.
Qed.


Section RealAgentArchitecture.


Definition RAA_State : Type := nat.


Definition RAA_Goal (target : RAA_State) (s : RAA_State) : Prop := s <= target.


Inductive RAA_Action : Type :=
  | RAA_Stay : RAA_Action
  | RAA_Step : RAA_Action.


Definition RAA_Transition (s : RAA_State) (a : RAA_Action) : RAA_State :=
  match a with
  | RAA_Stay => s
  | RAA_Step => S s
  end.


Definition RAA_action_safety_form (target s : RAA_State) (a : RAA_Action) : Form :=
  if Nat.leb (RAA_Transition s a) target then Top else Bot.


Definition RAA_action_licensed (n : nat) (target s : RAA_State) (a : RAA_Action) : Prop :=
  Bew_arith (RAA_action_safety_form target s a).


Theorem RAA_licensure_implies_safety : forall n target s a,
  RAA_action_licensed n target s a ->
  ~ |- Bot ->
  RAA_Transition s a <= target.
Proof.
  intros n target s a Hlic Hcon.
  unfold RAA_action_licensed, RAA_action_safety_form in Hlic.
  destruct (Nat.leb (RAA_Transition s a) target) eqn:E.
  - apply Nat.leb_le. exact E.
  - exfalso. apply Hcon.
    pose proof (proj1 (Bew_arith_iff_provable Bot) Hlic). exact H.
Qed.


Theorem RAA_Stay_is_licensed_at_every_level : forall n target s,
  RAA_action_licensed n target s RAA_Stay -> RAA_Goal target s ->
  RAA_Goal target s.
Proof. intros. exact H0. Qed.


Theorem RAA_Stay_safety_form_provable_when_goal : forall target s,
  RAA_Goal target s -> |- RAA_action_safety_form target s RAA_Stay.
Proof.
  intros target s Hg. unfold RAA_action_safety_form, RAA_Transition.
  unfold RAA_Goal in Hg. apply Nat.leb_le in Hg.
  rewrite Hg. exact (prov_id Bot).
Qed.


Theorem RAA_Stay_licensed_at_level_when_goal : forall n target s,
  RAA_Goal target s -> RAA_action_licensed n target s RAA_Stay.
Proof.
  intros n target s Hg. unfold RAA_action_licensed.
  pose proof (RAA_Stay_safety_form_provable_when_goal target s Hg) as Hp.
  pose proof (provable_to_proof_term _ Hp) as [pt Hpt].
  exists pt. exact Hpt.
Qed.


Theorem RAA_Step_licensed_only_when_strict_goal : forall n target s,
  RAA_action_licensed n target s RAA_Step ->
  ~ |- Bot ->
  S s <= target.
Proof.
  intros n target s Hlic Hcon.
  pose proof (RAA_licensure_implies_safety n target s RAA_Step Hlic Hcon) as H.
  unfold RAA_Transition in H. exact H.
Qed.


Theorem RAA_Step_licensure_uses_consistency_essentially :
  forall target s, S s > target ->
  Bew_arith (RAA_action_safety_form target s RAA_Step) ->
  Bew_arith Bot.
Proof.
  intros target s Hgt Hbew.
  unfold RAA_action_safety_form, RAA_Transition in Hbew.
  destruct (Nat.leb (S s) target) eqn:E.
  - apply Nat.leb_le in E. lia.
  - exact Hbew.
Qed.



Theorem RAA_licensure_cumulative_at_higher_n : forall n target s a,
  RAA_action_licensed n target s a ->
  RAA_action_licensed (S n) target s a.
Proof. intros. exact H. Qed.


Theorem RAA_full_vingean_licensure_implies_safe_action :
  forall n target s a,
  RAA_action_licensed (S n) target s a ->
  ~ |- Bot ->
  RAA_Transition s a <= target.
Proof.
  intros n target s a Hlic Hcon.
  exact (RAA_licensure_implies_safety _ _ _ _ Hlic Hcon).
Qed.


End RealAgentArchitecture.

